### ISSUE TITLE
支付签名错误

### ISSUE THREAD

**Issue by xingxiaoyang** [overtrue/wechat#101]
你好，我做JS支付，总是返回getBrandWCPayRequest: fail_invalid signature。第一步UnifiedOrder返回success。支付的时候就返回上面那个错误，我检查了下签名是对的。给腾讯客服发邮件，两天了也没回信。有人之前遇到过相同的问题吗。

**Comment by xingxiaoyang** [comment]
我的框架是Laravel5

**Comment by overtrue** [comment]
@0i

**Comment by overtrue** [comment]
@xingxiaoyang 在群里吗？319502940

**Comment by xingxiaoyang** [comment]
我这就去加群

**Comment by overtrue** [comment]
已在群里解决，请有空把解决方案贴一下，方向！
