### ISSUE TITLE
swoole下无法使用

### ISSUE THREAD

**Issue by hanwenbo** [overtrue/wechat#1017]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：
所有版本
是否使用了框架？框架名称：
Easyswoole
## 问题及现象
在swoole开发环境下 是没有$_GET  $_POST等等这种代码的，
我赋值了 ，不过呢
```
 $this['request'] = function () {
            return Request::createFromGlobals();
        };

```
这句代码只能是加载你的Request，这导致我无法给你的getContent赋值，因为没提供赋值
描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**
Request类里写死了代码：
$request = self::createRequestFromFactory($_GET, $_POST, array(), $_COOKIE, $_FILES, $server);
想传都是不可以的 ，这不符合Prs7的标准

**Comment by hanwenbo** [comment]
已经解决，回头补上教程 - - 继续撸了

**Comment by greedying** [comment]
怎么解决的？莫非是自己弄个$_GET ？

**Comment by hanwenbo** [comment]
自己弄超全局变量也行，继承Request类 重定义Message获取的方法也行
