### ISSUE TITLE
支付新增了企业付款到银行卡接口

### ISSUE THREAD

**Issue by lonestonewy** [overtrue/wechat#1018]
建议跟进支持。

**Comment by lonestonewy** [comment]
基于稳定版我fork了一个实现，需要的朋友可以参考。

https://github.com/lonestonewy/wechat/tree/3.1/src/Payment/MerchantPay
需要注意的是，获取到的微信支付公钥要做下格式转换。

**Comment by overtrue** [comment]
@lonestonewy 👍 不过需要注明一下你的只适用于 Yii

**Comment by overtrue** [comment]
我们里面已经实现了，只不过密钥处理部分还还在设计中

**Comment by zealyes** [comment]
SUCCESS（付款成功）可能会变成 BANK_FAIL（银行退票，订单状态由付款成功流转至退票,退票时付款金额和手续费会自动退还）
