### ISSUE TITLE
[V3] AccessToken.php:243

### ISSUE THREAD

**Issue by ac1982** [overtrue/wechat#1021]
## 我用的环境

PHP 版本：7.1.11
overtrue/wechat 版本：3.3.18
是否使用了框架？框架名称：Laravel

## 问题及现象
Cron每天凌晨会自动composer update.
用户OAuth失败，今天没有操作过代码，发现只有overtrue/wechat自动升级为了3.3.18.
回滚到3.3.17问题解决。
我先Open Issue 晚点会查看下原因。

**Comment by FlappyHeart** [comment]
也遇到这个问题了，Request AccessToken fail. response: false

**Comment by FlappyHeart** [comment]
我所遇到的bug仅在本地出现，服务器竟然没事，不知道是缓存还是什么缘故。
如果有后面来的人遇到我发的那个问题，请修改overtrue/wechat/src/Core/Http.php文件中的267行

`$body = $body->getBody()->getContents(); => $body = $body->getBody();`

**Comment by neatstudio** [comment]
确实是。我也是改成$body=(string)$body->getBody();

建议还是
$body = $body->getBody()->getContents() ?: $body->getBody();

**Comment by overtrue** [comment]
3.3.19 已经还原修改， sorry

**Comment by smalleyes** [comment]
今天刚刚遇到了一直排查问题出现在哪里...😂
