### ISSUE TITLE
默认文件缓存的路径是否可以简单修改?

### ISSUE THREAD

**Issue by birdol** [overtrue/wechat#1023]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：4.0 beta
是否使用了框架？框架名称：原生php

## 问题及现象

有些用户的主机对/tmp/路径没有权限，或者不在open basedir的设置范围内，导致文件缓存玩不下去，在不用其他自定义缓存的条件下，能够通过config直接修改缓存路径吗？

**Comment by overtrue** [comment]
默认缓存是取的 php 函数 [sys_get_temp_dir()](http://php.net/manual/zh/function.sys-get-temp-dir.php) 的路径，如果这个路径不存在，那你的 php 也无法正常工作才对

**Comment by overtrue** [comment]
https://github.com/symfony/cache/blob/5b2fffcad066341f9168513ed08e56cf95d377c6/Traits/FilesystemCommonTrait.php#L29

**Comment by birdol** [comment]
自己写个filecache替换了，有些主机真的是奇葩。。。
