### ISSUE TITLE
公众号模板消息不兼容跳转小程序

### ISSUE THREAD

**Issue by cnny** [overtrue/wechat#1025]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：yii2

## 问题及现象

你好，公众号模板消息更新了接口，支持跳转小程序，但是我看您的源码好像并没有兼容。
![image](https://user-images.githubusercontent.com/17918962/32781763-cf8f3990-c90b-11e7-97e5-714c583066c3.png)

**Comment by mingyoung** [comment]
可以直接这样用：
```php
$miniProgram->template_message->send([
    'touser' => 'xxx',
    'template_id' => 'xxx',
    'miniprogram' => [],
    'appid' => 'xxx',
    'pagepath' => 'xxx',
    // ...
]);
```

**Comment by cnny** [comment]
好的，我试试，谢谢~

2017-11-21 15:10 GMT+08:00 张铭阳 <notifications@github.com>:
