### ISSUE TITLE
开放平台不支持全网发布接入检测（第三方）

### ISSUE THREAD

**Issue by goleden** [overtrue/wechat#1029]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：3.2
是否使用了框架？框架名称：thinkphp

## 问题及现象

![image](https://user-images.githubusercontent.com/9799444/32825995-c83b64e0-ca21-11e7-91b1-9a9b81e3fb22.png)

**Comment by mingyoung** [comment]
这些要自己实现返回
