### ISSUE TITLE
lumen+swoole无法获取request信息。

### ISSUE THREAD

**Issue by elrond-g** [overtrue/wechat#1032]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：master线
是否使用了框架？框架名称：lumen+swoole

## 问题及现象
swoole不存在global了，然而这里获取request的方式还是从"php:\\input"获取。
wechat/src/Kernel/ServiceContainer.php
130      * Register request.
131      *
132      * @return $this
133      */
134     protected function registerRequest()
135     {
136         isset($this['request']) || $this['request'] = function () {
137             return Request::createFromGlobals();
138         };
139 
140         return $this;
141     }
142 

如果以后

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

如果你不提供相关的代码，我不会做任何应答，直接 close，感谢！

**Comment by overtrue** [comment]
抱歉，swoole 环境可能需要你自己去解决这些问题了，毕竟它已经不是 php 的 fpm 模式了，而这种模式下，symfony 目前没有去适配它，我个人也没有打算去适配，感谢你的反馈。

**Comment by hanwenbo** [comment]
希望您把Request的接口暴露出来，我们可以通过外部传过去，根据psr7的标准来传

**Comment by yuchonghua** [comment]
同样的问题，为什么 Request 不能使用传入，而是调用 Request::createFromGlobals();
