### ISSUE TITLE
[V3] ErrorException: count()

### ISSUE THREAD

**Issue by ac1982** [overtrue/wechat#1039]
## 我用的环境

PHP 版本：PHP 7.2 + PHPREDIS 3.1.5RC1
overtrue/wechat 版本：3.3.20
是否使用了框架？框架名称：Laravel

## 问题及现象
oauth fail, with exception.
```
local.ERROR: ErrorException: count(): Parameter must be an array or an object that implements Countable in /home/www/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:67
```

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**
Just upgrade php to 7.2(PHPREDIS 3.1.5RC1), if rollback to 7.1(PHPREDIS 3.1.4) would be right again.
cache function works fine under 7.2, so sounds it would not be the problem with phpredis.

**Comment by overtrue** [comment]
7.2 刚发布，要不再等等吧，等周边工具都跟上兼容

**Comment by ac1982** [comment]
Guzzle upgrade to 6.3.0, the bug was fixed.
