### ISSUE TITLE
关于3.x升级4.x的问题

### ISSUE THREAD

**Issue by edwinfound** [overtrue/wechat#1041]
首先感谢框架给我们带来开发上的便利。
我们的项目使用了 `3.x` 版本的 composer 包，注意到作者已经对 `3.x` 停止了新功能的更新，所以不知道如何在一个项目中如何能够平滑的从 `3.x` 升级到 `4.x`，项目中太多地方使用到了相关 `3.x` 相关代码。
本来计划的是同时安装两个版本，这样可以两个版本同时使用逐步迁移，但是因为包名是相同的应该不太可能实现。
我们的项目是已经在 `PHP7` 下运行的，所以 PHP 版本没有什么问题。
不知道作者有没有什么好的建议。

**Comment by overtrue** [comment]
其实如果项目在 3.x 下稳定运行的话可以考虑等时间宽裕，将需求点列出来一点点改过来，一般 1 个人一天左右就可以改完的（我已经迁移了3个项目的总结），无法平滑升级的，因为 4.0 加入了微信周边其它的功能支持，无法在 3.x 基础上直接改，所以结构层面变化较大，抱歉
