### ISSUE TITLE
filecache.php 文件     createPathIfNeeded(string $path) : bool

### ISSUE THREAD

**Issue by anxiaochuang** [overtrue/wechat#1046]
## 我用的环境

PHP 版本：5.6
overtrue/wechat 版本：3.0
是否使用了框架？框架名称：
NT2.0  自编框架
## 问题及现象

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**
filecache.php 文件     
下载代码出现如下：
    private function createPathIfNeeded(string $path) : bool
    protected function writeFile(string $filename, string $content) : bool
    private function getIterator() : \Iterator
创建自定义菜单报错：
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /Data/code/api.websites.vmp/library/Package/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php on line 192
感谢！

**Comment by overtrue** [comment]
更新版本 到最新，或者更新你的 PHP 版本到 7.0 +
