### ISSUE TITLE
swoole xml处理问题

### ISSUE THREAD

**Issue by a569922982** [overtrue/wechat#1054]
## 我用的环境

PHP 版本：7.0.26
overtrue/wechat 版本：3.1
是否使用了框架？框架名称：laravel + swoole

## 问题及现象

想问下4.0版本是否有适配了swoole的request。主要是xml的问题没办法使用。
3.1的自己改了下，倒是可以使用。
每次更新都改太麻烦了呢。。。
![_20171214153154](https://user-images.githubusercontent.com/11918919/33980458-f549200c-e0e3-11e7-9fdf-96692abd4016.png)
像这样弄个入口也好

**Comment by overtrue** [comment]
sorry, swoole 并不是国际通用的标准，并没有特意的适配。但是建议你可以考虑在框架入口中设置 request 对象: 

```php
$app['request'] = $this->request 
```

**Comment by a569922982** [comment]
好的  谢谢大佬。
