### ISSUE TITLE
企业支付没有相关api文档

### ISSUE THREAD

**Issue by a569922982** [overtrue/wechat#1058]
## 我用的环境

PHP 版本：7.0.26
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：laravel + swoole

## 问题及现象
企业支付怎么使用呢，4.0文档上并没有看到相关的说明。

![default](https://user-images.githubusercontent.com/11918919/33992036-07996488-e10c-11e7-82ca-e69a9008a62a.png)

**Comment by overtrue** [comment]
企业微信还有一点小问题没修复，请等待。

**Comment by windpursuer** [comment]
企业支付修复了吗，3.1会不会有同样问题，不然只能用回3.1了

**Comment by overtrue** [comment]
https://www.easywechat.com/docs/master/zh-CN/payment/transfer
