### ISSUE TITLE
提示错误

### ISSUE THREAD

**Issue by nurexmet** [overtrue/wechat#106]
微信支付系统返回的错误和借口提示的错误怎么会不一样（比如说：系统返回的错误是：编码格式错误。 但是，借口提示的是：系统繁忙，此时请开发者稍候再试）。

**Comment by jaring** [comment]
Exception 中 $code 为：
 '-1'      => '系统繁忙，此时请开发者稍候再试',
在构造方法中public function __construct($message, $code = -1) $code有默认值
而各类中抛出异常并为指定$code ,导致不论什么异常都会显示为“系统繁忙，此时请开发者稍候再试“
注释掉上面的 -1那一行就解决了。。

**Comment by jaring** [comment]
建议安大神修改。。Exception类

**Comment by overtrue** [comment]
https://github.com/overtrue/wechat/releases/tag/2.1.6
