### ISSUE TITLE
JS SDK Cache的TTL时间与Laravel不一致，导致微信端无法正确的分享

### ISSUE THREAD

**Issue by fly-studio** [overtrue/wechat#1065]
## 我用的环境

PHP 版本：7.0
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：laravel 5.5
缓存：Redis

## 问题及现象

`JS SDK` 使用 `buildConfig` 方法，此处在获得getTicket时使用了缓存，但此处缓存的TTL单位与Laravel不一致，Laravel使用的 **分** 为缓存单位，而此处使用的是 **秒**，导致缓存失效时间比实际的要长60倍。

在刚刚获取到Ticket之后的一段时间内，分享无误。

但是因为时间单位的差异，超过了Ticket的在微信服务器有效时间之后，此Cache却任然有效，在微信客户端中，会因为Ticket的验签错误（signature错误），导致分享出现不正确的结果。

最后不得不**频繁**手动更新缓存。

```
// laravel\vendor\overtrue\wechat\src\BasicService\Jssdk\Client.php

public function getTicket(bool $refresh = false, string $type = 'jsapi'): array
    {
        $cacheKey = sprintf('easywechat.basic_service.jssdk.ticket.%s.%s', $type, $this->getAppId());

        if (!$refresh && $this->getCache()->has($cacheKey)) {
            return $this->getCache()->get($cacheKey);
        }

        $result = $this->resolveResponse(
            $this->requestRaw(static::API_GET_TICKET, 'GET', ['query' => ['type' => $type]]),
            'array'
        );

        $this->getCache()->set($cacheKey, $result, $result['expires_in'] - 500);   //此处时间问题

        return $result;
    }
```

**Comment by overtrue** [comment]
1. 这个是 PHP 包，与 laravel 无关，你如果使用 laravel 请正确传递缓存时间
2. 请参考 overtrue/laravel-wechat 使用缓存

**Comment by YingQuan-han** [comment]
@fly-studio 
laravel5.8+ 缓存过期时间使用了秒，overtrue/laravel-wechat 4.0 为了兼容导致储存了两次，第一次传递给Illuminate/Cache/RedisStore.php的put函数是分钟，第二次传递的是秒钟，第二次的值覆盖了第一次，最终个过期时间是6700*60秒

最新版本已经修复了这个问题
` composer update overtrue/laravel-wechat `

**Comment by whycomeing** [comment]
PHP 7.2
overtrue/wechat 5.1
laravel5.7
也遇到了这个问题，怎么解决啊
