### ISSUE TITLE
当用户信息有 " 字符时系统出错 (用户与用户组管理接口)

### ISSUE THREAD

**Issue by enbaby** [overtrue/wechat#107]
$userService->batchGet($openId); 批量获取用户信息

在调用此接口时，如果用户信息中带有 " 则会json解析错误，具体错误信息如下
ErrorException in User.php line 93:
Illegal string offset 'user_info_list'

问题主要是
https://github.com/overtrue/wechat/blob/2.1/src/Wechat/Http.php#L103

此段没有将文本中的"替换

我是直接改成了
$contents = json_decode(substr(str_replace(array('\\\\\\\\\\\\"','\\"', '\\\\\\\\'), array('','"', ''), json_encode($response['data'])), 1, -1), true);

虽然成功了，但是却把 " 删除了，希望有更好的解决方案，望指正！

**Comment by overtrue** [comment]
微信的接口团队真的是吃屎的

**Comment by 5-say** [comment]
同感

**Comment by overtrue** [comment]
已发微博点名批评 :laughing:

**Comment by narutooturan** [comment]
有同样的错误，替换上面的还是会报错 = =

**Comment by overtrue** [comment]
@narutooturan 能不能把返回的json原样取一份发我，用gist

**Comment by narutooturan** [comment]
@overtrue 发到您的邮箱了。

**Comment by enbaby** [comment]
持续关注

**Comment by narutooturan** [comment]
现在的做法是在[User.php line 103](https://github.com/overtrue/wechat/blob/2.1/src/Wechat/User.php#L103)前重新验证下是否为数组，如果不是重新用一下json_decode。这样是没有报错了，但是跑了一会儿之后经常会返回40001错误，不知道为什么 = =

**Comment by xiaohome** [comment]
@overtrue  我记得这个错误 我提交过呀！！！  你也都合并了
