### ISSUE TITLE
卡券BUG

### ISSUE THREAD

**Issue by ThinkMe** [overtrue/wechat#1071]
## 我用的环境
Nginx FPM

PHP 版本：7.1
overtrue/wechat 版本：4.X
框架名称：laravel

## 问题及现象
OfficialAccount/Card/JssdkClient.php 文件
attachExtension方法里

在不传入$nonce的情况下   $nonce还是会参与签名就会出错。
改成下面就没问题了

`
        $ext = array_merge(['timestamp' => $timestamp], ['nonce_str' => $nonce], Arr::only(
            $extension,
            ['code', 'openid', 'outer_id', 'balance', 'fixed_begintimestamp', 'outer_str', 'nonce']
        ));
`

**Comment by overtrue** [comment]
已经在 dev-master 修复
