### ISSUE TITLE
php7.0环境下composer依赖问题

### ISSUE THREAD

**Issue by mrwzq** [overtrue/wechat#1073]
## 我用的环境
CentOS 7.5 64Bit
PHP 版本：
PHP 7.0.22 (cli) (built: Aug 16 2017 11:16:05) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
overtrue/wechat 版本：
4.0.2
是否使用了框架？框架名称：

## 问题及现象

overtrue/wechat 下的composer.json 中"symfony/http-foundation": "^2.7|^3.0|^4.0",  默认检出4.0.2的版本，而symfony/http-foundation的版本对版本的要求 php: ^7.1.3
http-foundation中使用了7.1的新特性 可空类型。导致报错。
如Symfony\Component\HttpFoundation\Response第499行。

public function getCharset(): ?string

**Comment by overtrue** [comment]
```shell
$ composer require overtrue/wechat symfony/http-foundation:~3.0 -vvv
```
