### ISSUE TITLE
4.0.2 无法发送客服消息

### ISSUE THREAD

**Issue by liuyami** [overtrue/wechat#1074]
## 我用的环境

PHP 版本：7.0
overtrue/wechat 版本：4.0.2
是否使用了框架？框架名称： laravel 5.5

## 问题及现象

直接 return 字符串可以收到，但是使用客服发送消息，无法收到，文档中也没有额外提到依赖什么

我是用开放平台账号发送的，开放平台，其他都挺正常的（目前就测试了几个基础功能），就客服消息还没有通过。

**Comment by overtrue** [comment]
提问三要素请了解，再说我 issue 模板已经教了怎么提问。
