### ISSUE TITLE
小程序解密数据方法偶尔会失败

### ISSUE THREAD

**Issue by 96qbhy** [overtrue/wechat#1076]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：Laravel 5.5

## 问题及现象

小程序解密数据方法偶尔会失败，控制器代码如下 
![image](https://user-images.githubusercontent.com/24204533/34285507-16976ebc-e715-11e7-90a1-5a25f2894e2b.png)
异常如下 ：
![image](https://user-images.githubusercontent.com/24204533/34285530-4717feb2-e715-11e7-9056-7205b3ce26c8.png)

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

如果你不提供相关的代码，我不会做任何应答，直接 close，感谢！

**Comment by overtrue** [comment]
@mingyoung 看看？

**Comment by manhere** [comment]
贴出success()部分代码？

**Comment by 96qbhy** [comment]
@HanSon 看看？

**Comment by HanSon** [comment]
@mingyoung 看看？我这边也经常有这种情况

**Comment by overtrue** [comment]
@96qbhy 麻烦把失败时的数据存下来，各种参数

**Comment by overtrue** [comment]
#1080 @96qbhy 是不是一样的原因？

**Comment by 96qbhy** [comment]
@overtrue 是这个问题，知道怎么解决了~
