### ISSUE TITLE
开放平台全网发布失败

### ISSUE THREAD

**Issue by Liangkk** [overtrue/wechat#1077]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：thinkphp 5.0.11

## 问题及现象

[开放平台全网发布失败图片](http://xtkj.oss-cn-shenzhen.aliyuncs.com/error.png)

server端代码如下
`
public function open($appid) {

        config('app_debug', false);
        config('app_trace', false);
        $wechatConfig=config('wechat_openplatform');
        $openPlatform=Factory::openPlatform($wechatConfig);
        $openPlatform['cache']=new RedisCache((new Redis())->handler());
        $officialAccount =$openPlatform->officialAccount($appid);
        $server = $officialAccount->server;
        $server->push(function ($message) {
            switch ($message['MsgType']) {
                case 'event':
                    return $message['Event'] . 'from_callback';
                    break;
                case 'text':
                    if ($message['Content']== 'TESTCOMPONENT_MSG_TYPE_TEXT') {
                        return $message['Content'] . '_callback';
                    }
                    break;
                case 'image':
                    return '收到图片消息';
                    break;
                case 'voice':
                    return '收到语音消息';
                    break;
                case 'video':
                    return '收到视频消息';
                    break;
                case 'location':
                    return $message['Event']. 'from_callback';
                    break;
                case 'link':
                    return '收到链接消息';
                    break;
                default:
                    return '收到其它消息';
                    break;
            }
        });
        $message = $server->getMessage();
        if ($message['MsgType'] == 'text' && strpos($message['Content'], 'QUERY_AUTH_CODE') === 0) {
            echo '';
            $code = substr($message['Content'], 16);
            $authorizerInfo = $openPlatform->handleAuthorize($code)['authorization_info'];
            trace($authorizerInfo, 'authorizerInfo');
            $curOfficialAccount = $openPlatform->officialAccount($authorizerInfo['authorizer_appid'], $authorizerInfo['authorizer_refresh_token']);
            $curOfficialAccount->customer_service->message($code . "_from_api")->to($message['FromUserName'])->send();
        } else {
            $response = $server->serve();
            $response->send();
        }
    }
`

**Comment by mingyoung** [comment]
refresh_token 怎么不传？

**Comment by Liangkk** [comment]
开放平台全网发布的时候,一开始是没有refresh_token的
官方文档是怎么说明的,要到第3步通过code才可以获取refresh_token
https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318611&token=&lang=zh_CN

**Comment by heyuemax** [comment]
@Liangkk 遇到同样的问题，而且我们好像是用的一个框架哈？？？可以留个联系么
