### ISSUE TITLE
企业微信管理多个应用,出现access_token不能使用的BUG

### ISSUE THREAD

**Issue by Ge-Ge** [overtrue/wechat#1079]
## 我用的环境

PHP 版本：7
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：tp3.2

## 问题及现象

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**
$config = [
                'corp_id' => 'xxxxx',
                // 应用列表
                'agents' => [
                    'ceshi2' => [
                        'agent_id' => '1000011',
                        'secret' => 'xxxxxxxxxxxxxxx'
                    ],
                    'ceshi' => [
                        'agent_id' => '1000010',
                        'secret' => 'xxxxxxxxxxxxxxx'
                    ]
                ],
                'response_type' => 'array',
                'log' => [
                    'level' => 'debug',
                    'file' => __DIR__ . '/wechat.log',
                ],
            ];
            $work = Factory::work($config);
            $agents1 = $work->agent->get('1000011');     // 能正常使用
            $agents0 = $work->agent->get('1000010');     // 提示accesstoken不能使用在本应用

如果你不提供相关的代码，我不会做任何应答，直接 close，感谢！

**Comment by Ge-Ge** [comment]
![2017-12-24 16-05-19](https://user-images.githubusercontent.com/22065414/34325153-119d57a8-e8c5-11e7-88ce-2c54df6d08b1.png)

**
type 为view的数组中同时有key和url 。。。
**

**Comment by overtrue** [comment]
@Ge-Ge 企业微信在11月底改了 API , 现已经重构了该模块并发布了 4.0.3 请更新并按最新文档使用

**Comment by Ge-Ge** [comment]
@overtrue  企业微信的异步任务没有在文档里看到

**Comment by overtrue** [comment]
@Ge-Ge 这部分目前没有添加，你可以考虑 PR

**Comment by mouyong** [comment]
> @Ge-Ge 企业微信在11月底改了 API , 现已经重构了该模块并发布了 4.0.3 请更新并按最新文档使用

@overtrue 因为一些原因。不便于将项目中的 wechat 版本号进行升级，在查找问题的时候看到这里。想请问以下：

4.0.3 版本小于 4.0.23 ，请问修复版本号是否为 4.0.30? 因为 fix commit 未关联至此 pr 。看了一遍 https://github.com/overtrue/wechat/compare/4.0.23...4.0.30 之前的改动，未看到相关可能的信息。

谢谢您的耐心查看。

**Comment by overtrue** [comment]
@Ge-Ge 用法完全不一样了，建议升级使用新版，因为 API 的修改是用法的改变，我没办法简单的告诉你怎么从旧版改回来哈。

**Comment by mouyong** [comment]
> @Ge-Ge 用法完全不一样了，建议升级使用新版，因为 API 的修改是用法的改变，我没办法简单的告诉你怎么从旧版改回来哈。

好的，理解了，谢谢超哥。

**Comment by mouyong** [comment]
> 应用的 secret 在企业微信创建完就有了哈，不存在你说的情况。

默认的 config 是将应用 secret 写在 wechat.work.agents.*.secret 中的，而 EasyWeChat\Work\Auth\AccessToken 调用的是 wechat.work.secret

这里导致的报错

**Comment by mouyong** [comment]
![image](https://user-images.githubusercontent.com/10336437/52057558-4094cf00-25a0-11e9-8e88-85043edf087d.png)

做如下更改时可以调用成功。只是这样可能失去了 wechat 原有的意愿。配置 work.agents.*

**Comment by overtrue** [comment]
laravel-wechat 什么版本、

**Comment by mouyong** [comment]
> laravel-wechat 什么版本、

已在 2019年1月31日21:39:51 下午将 `"overtrue/wechat"` 更新至当前最新 `"4.1.7"`

此时项目中的 `"overtrue/laravel-wechat"` 版本号为 `"4.0.10"`

**Comment by overtrue** [comment]
@mouyong 升级 overtrue/laravel-wechat

**Comment by mouyong** [comment]
> @mouyong 升级 overtrue/laravel-wechat

@overtrue 已于2019年1月31日21:49:5升级 `overtrue/laravel-wechat` 至最新版本 `"4.0.22"`，问题任然存在。我看了下版本号比较，未发现可能涉及的相关修复代码。

下面是版本比较链接。
https://github.com/overtrue/laravel-wechat/compare/4.0.10...master

**Comment by overtrue** [comment]
我认真确认了一遍源代码，结论是：企业微信的上次 API 改版，已经将应用完全隔离，也就是说你在使用这个 SDK 的时候，一个应用就是一个 work application, 所以你的配置文件写法错了，应该是：

```php
'work' => [
        'agent1' => [
            'corp_id' => 'xxx',
            'agent_id' => 'xxx',
            'secret' => 'xxx',
            //...
        ],

        'agent2' => [
            'corp_id' => 'xxx2',
            'agent_id' => 'xxx2',
            'secret' => 'xxx2',
            //...
        ],
        //...
    ],
```

单个应用的参考：https://www.easywechat.com/docs/master/wework/index

**Comment by mouyong** [comment]
> 我认真确认了一遍源代码，结论是：企业微信的上次 API 改版，已经将应用完全隔离，也就是说你在使用这个 SDK 的时候，一个应用就是一个 work application, 所以你的配置文件写法错了，应该是：
> 
> ```
> 'work' => [
>         'agent1' => [
>             'corp_id' => 'xxx',
>             'agent_id' => 'xxx',
>             'secret' => 'xxx',
>             //...
>         ],
> 
>         'agent2' => [
>             'corp_id' => 'xxx2',
>             'agent_id' => 'xxx2',
>             'secret' => 'xxx2',
>             //...
>         ],
>         //...
>     ],
> ```
> 
> 单个应用的参考：https://www.easywechat.com/docs/master/wework/index

做如下更改后可以调用成功 

![image](https://user-images.githubusercontent.com/10336437/52059136-f57cbb00-25a3-11e9-85eb-4b8ff58fcfa4.png)

![image](https://user-images.githubusercontent.com/10336437/52059148-00cfe680-25a4-11e9-9172-467dbe7a8be2.png)

若是如此。我觉得以下几个地方的文档与代码调用可能需要优化。

- 文档缺少迁移指引。不知道从旧的包升级到新的包需要对配置文件做更改。可以添加到文档中一下。
- 因 agents 已经被隔离了。也许可以对相关接口进行优化。不用传入指定的 agent_id。从缓存中直接获取配置文件的 agent_id 即可。

这是个人的一点小建议。因为技术水平还没到一定程度。不知道怎么更好的为这个项目做贡献。所以只能口头上提下。

**Comment by overtrue** [comment]
@mouyong 

1. 没有迁移指引这点确实是不足，这块之前没做特别声明的原因是原来的代码应该是一直不可用状态，所以没有人找过来应该是没有人在用，而且截止目前你是第一个找过来的，除了 issue 作者。
2. 这可能是企业微信接口的锅了，`$app->agent` 我如果没记错确实可以传入其它 agent_id 并能正确调用，所以我保留了这个参数。

**Comment by mouyong** [comment]
@overtrue 针对第二点我也还没进行测试是否可行。如果可行，那么参数 agency_id 是非必填的。可以进行优化修改。

第一点因为项目本身存在历史性，今天才修复 bug 。所以之前遇到了也没办法复现原因。希望自己能尽快提升技术。这样就可以开心的 pr 了 :(

**Comment by overtrue** [comment]
OK，那可能是因为我测试的时候刚改版接口的缘故吧，或者就是我记错了。我后面将去掉这个参数。

= - = <notifications@github.com>于2019年1月31日 周四下午10:25写道：
