### ISSUE TITLE
好像没有获取自动回复数据接口

### ISSUE THREAD

**Issue by tinpont** [overtrue/wechat#108]
希望能添加一下，作者辛苦了。

http://mp.weixin.qq.com/wiki/7/7b5789bb1262fb866d01b4b40b0efecb.html

**Comment by liyunfang** [comment]
借用此地。
能不能把缓存的key 放到一个类。

**Comment by overtrue** [comment]
@liyunfang 缓存的access_token 本来就在AccessToken类里

**Comment by overtrue** [comment]
@tinpont 目前没有，你可以提PR
