### ISSUE TITLE
decryptData 解密出错

### ISSUE THREAD

**Issue by imsheng** [overtrue/wechat#1080]
## 我用的环境

PHP 版本：>7.0
overtrue/wechat 版本：>4.0
是否使用了框架？框架名称：symfony

![qq 20171225115427](https://user-images.githubusercontent.com/10435075/34332395-28c87e16-e96b-11e7-8193-1c0cf5164a3c.png)

传的参数没问题。
第一次运行出错，
再运行又可以。

隔几分钟后又出错，再运行又可以。
....

**Comment by imsheng** [comment]
有人吗？很急

**Comment by overtrue** [comment]
@imsheng 程序肯定不会出现 “一会儿OK, 一会儿不OK” 的情况出现，它又不带情绪，出问题肯定是输入不一样才会有不同的结果，作为程度员，你应该尝试去跟一下为啥会有不同的结果出现，而不是这样一直等，这是开源项目，我也要工作的，并不可能有那么多时间来把每个人的问题都去重现一次，还请理解。

**Comment by imsheng** [comment]
但是上图所见，参数也没传错，代码也是固定不变的，每第一次就不行，第二次又行了，
3.0不是这样的，升上4.0就这样的

**Comment by overtrue** [comment]
@imsheng 请提供输入的参数我来试

**Comment by imsheng** [comment]
ok,明天

**Comment by imsheng** [comment]
decryptData('j6odKy8LALRoFfoYpIi6XQ==', 'N/C6Qoga9RUpDA1N2Cs/Ww==', '5DR9Z1MyffiqtLn7TmCMWixnK4Erw851FsK6Um0lXr91T3419bIGS+3bQWg/pzsgiQI92QuYapNZqY7QQX5MhNJXFAbFnXhXtGALpf6LYJkeNS1OVNrnevtVhPJYQN58SFUvdBimms+0H7TWPcO12rf1tLNOJpD0ETXwfagjUqegJ+vzQzlMqnhqbMjKAGo2DiKMV6XNye9MzlMZFNKjUN2UP9lrZPhwYabdXiOOuyJRFpgw7IXcUEgd9Qiafe5LXyGInyTkV+rPM2oXt/rzUn9xMr0YH5cGfn4n3zvk6OozWxmh87PgYTBDkX07pDgg203pmwqKWmnRlYzfPGYpBQLGwEsmUZqhbydCrVDRxhuKfihxwRxflslbrU4JjhCi8Bkewf1WBl/lPmZ6gRnSaXwvUVzxFnLY0R5MKG/UAIeH+C/u7pez+6EhkyEn8rrtf431+mkYE4LUYPRfcZemk6sq+PmC7IzI49CMc6t8hkE9k858c+FHb7vHMzgZMUkI')

@overtrue

**Comment by overtrue** [comment]
@imsheng 麻烦把你的配置也发我邮箱一下(anzhengchao@gmail.com)，否则也无法解密

**Comment by imsheng** [comment]
今天突然又没问题了

**Comment by overtrue** [comment]
这。。。

**Comment by imsheng** [comment]
查到问题了，原来是小程序那边出错了，取的是过期数据。thanks

**Comment by overtrue** [comment]
@imsheng 😆

**Comment by mingyoung** [comment]
是不是 session key 过期？

**Comment by imsheng** [comment]
@mingyoung 不知道，反正现在是先登陆拿到code，然后再授权拿用户信息，再解密，之前是相反的，数据是拿到的，但解不了。
