### ISSUE TITLE
有几个接口调用出错

### ISSUE THREAD

**Issue by jianyan74** [overtrue/wechat#1082]
## 我用的环境

PHP 版本：7.0
overtrue/wechat 版本：4.0.3
是否使用了框架？框架名称：Yii2

### 群发消息

文档说明：群发消息给指定组
$broadcast->send($messageType, $message, $groupId);
使用后提示必须要使用数组，看了代码强制要求的是数组和文档不一样

文档说明：别名方式群发
$broadcast->sendNews($mediaId, $groupId);
使用后提示必须至少两个用户的 openid，必须是数组。 这里是不是和下面的用openid群发搞混了导致直接发送判断出错

### 消息回复
语音回复报错，其他的类型回复正常

**Comment by overtrue** [comment]
已经更新 https://github.com/EasyWeChat/docs/commit/90ad19c3f384af4e2e9895bab01da8efde25026c

**Comment by jianyan74** [comment]
语音回复报错，这个我试了一下4.0.5的还是报错的
