### ISSUE TITLE
希望能支持小程序发送模板消息

### ISSUE THREAD

**Issue by Gaoxin1996** [overtrue/wechat#1084]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：laravel

## 问题及现象
目前尚不支持小程序的模板消息
https://mp.weixin.qq.com/debug/wxadoc/dev/api/notice.html#模版消息管理

**Comment by mingyoung** [comment]
支持的
```php
$miniProgram->template_message->send([...]);
```

**Comment by overtrue** [comment]
@mingyoung 改一下文档吧 😆
