### ISSUE TITLE
模版消息调用一次发送2条，重复

### ISSUE THREAD

**Issue by jiamuc** [overtrue/wechat#1086]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：没有

## 问题及现象

    $app->template_message->send(。。。)
调用一次会发生2条相同的模版消息。

**Comment by overtrue** [comment]
为啥我的不会？

**Comment by jiamuc** [comment]
奇怪，只是某个测试模版会这样，其他模版不会重复，可能是测试账号的问题
