### ISSUE TITLE
请问如何判断用户是否订阅公众号呢？获取用户信息后没有是否订阅的信息

### ISSUE THREAD

**Issue by tangj1992** [overtrue/wechat#1087]
## 我用的环境

PHP 版本：7.027
overtrue/wechat 版本：3.3
是否使用了框架？框架名称：laravel

## 问题及现象
用户信息original中只用如下字段
openid
nickname
sex
language
city
province
country
headimgur
privilege

**Comment by overtrue** [comment]
现在官方已经不提供了，请留意官方公告，谢谢！关注的时候自己记录到数据库，取关的时候修改自己数据库状态。

**Comment by tangj1992** [comment]
谢谢，是我使用方式不对，现在获取到了。之前使用的时网页授权所以没有，拿到授权后再用用户openid获取用户信息即可。
