### ISSUE TITLE
模板消息接口调用：cURL error 35: SSL connect error

### ISSUE THREAD

**Issue by slumzzw** [overtrue/wechat#1090]
## 我用的环境

PHP 版本：7.0.13
overtrue/wechat 版本：3.3.22
是否使用了框架？框架名称：Phalcon

## 问题及现象
开发过程有一个需求是：定时执行脚本，发送微信用户模板消息通知。模板消息发送代码如下：
$result = $app->notice->uses($templateId)->withUrl($url)->andData($data)->andReceiver($id)->send();
调用结果，报错截图如下：

![image](https://user-images.githubusercontent.com/17041347/34607430-861e8164-f24e-11e7-9294-fe93a09d6102.png)

今天在cli模式下这个问题必现；服务器也升级了nss；
望解答，感谢！

**Comment by overtrue** [comment]
升级 curl: https://stackoverflow.com/questions/36787413/curl-35-ssl-connect-error
