### ISSUE TITLE
[bug]这个方法无法获取到文件扩展名

### ISSUE THREAD

**Issue by liqunx** [overtrue/wechat#1095]
https://github.com/overtrue/wechat/blob/8c68bfd14695952fd74708f88423356f5ee49efc/src/Kernel/Http/StreamResponse.php#L55

StreamResponse.php 第55行，原文为：
`$filename .= File::getStreamExt($contents);`
使用此方法无法获取到扩展名，改用`File`类中的另一个方法：`getExtBySignature`则可以获取到；

**Comment by overtrue** [comment]
https://github.com/overtrue/wechat/blob/master/src/Kernel/Support/File.php#L110
