### ISSUE TITLE
企业微信,获取部门员工详细信息接口中.json_decode 遇到昵称中出现Emoji的情况下返回了null

### ISSUE THREAD

**Issue by ghostlitao** [overtrue/wechat#1101]
## 我用的环境

PHP 版本： 7.1
overtrue/wechat 版本：4.0
是否使用了框架？框架名称： Lavavel 5.5
 
## 问题及现象

- 企业号通讯录获取部门员工信息
- 使用 getDetailedDepartmentUsers 函数获取信息,员工列表中有一个人的昵称使用了Emoji,所以在获取的  ResponseCastable.php 45行,调用了 Response.php 的72行附近,json_decode 之后 返回的$array为null,打印了 json_last_error_msg => 'Malformed UTF-8 characters, possibly incorrectly encoded'
- 程序的编码都是utf8.
- 其他部门正常获取,只有这个有Emoji昵称的部门获取的array是null.

使用了
		$array = json_decode(utf8_encode($content), true);

之后,得到的名称都是乱码.

试过网上的其他办法iconv,preg_replace都没有找到合适的解决办法.求大神帮忙.

**Comment by ghostlitao** [comment]
目前修改了 overtrue/wechat/src/Kernel/Http/Response.php 的第72行左右为:

$array = json_decode(mb_convert_encoding($content, 'UTF-8', 'UTF-8'), true);

但是Emoji会变成 ?????? 
求教还有什么好办法吗?

**Comment by zacksleo** [comment]
数据库改用utf8mb4编码格式试试？

**Comment by ghostlitao** [comment]
@zacksleo 不是数据库,是从微信接过来的数据解析的过程中遇到这个问题了.

**Comment by overtrue** [comment]
@ghostlitao 抱歉，我未能重现你的问题：

![image](https://user-images.githubusercontent.com/1472352/35179270-f5d7d5da-fdd1-11e7-9a4b-3e9c68457299.png)

**Comment by ghostlitao** [comment]
@overtrue  可能是 整个用户名都用表情符号的原因? 没在测试了.
