### ISSUE TITLE
支持php-msf,或swoole吗？

### ISSUE THREAD

**Issue by wuchuguang** [overtrue/wechat#1103]
## 我用的环境

PHP 版本：7.1.X
overtrue/wechat 版本：github最新
是否使用了框架？框架名称：php-msf

## 问题及现象

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

如果你不提供相关的代码，我不会做任何应答，直接 close，感谢！

**Comment by overtrue** [comment]
抱歉，只兼容标准 PHP 环境，其它环境你需要自己适配
