### ISSUE TITLE
能把文档做的详细一点吗？

### ISSUE THREAD

**Issue by imsheng** [overtrue/wechat#1106]
rt，多写点实际代码，例如怎样在h5调起支付等等

**Comment by overtrue** [comment]
你确定你认真看过了？ https://www.easywechat.com/docs/master/zh-CN/payment/jssdk

![image](https://user-images.githubusercontent.com/1472352/34927138-fd249274-f9ee-11e7-900e-e126a08a702c.png)
![image](https://user-images.githubusercontent.com/1472352/34927140-0063ab5a-f9ef-11e7-99ed-24d9e2763616.png)

**Comment by imsheng** [comment]
看过，当初还以为这么简单，但实际还要其他

`

    ...
            $prepayId = $result['prepay_id'];
            $jssdk = $payment->jssdk;
            $json = $jssdk->sdkConfig($prepayId);
            $jsSdkConfig = $app->jssdk->buildConfig(array('chooseWXPay'), true);
    ...

    <script>
        wx.config({% autoescape false %}{{ jsSdkConfig }}{% endautoescape %});
        wx.ready(function (res) {
            wx.chooseWXPay({
    .....
        })
    })
`

**Comment by overtrue** [comment]
这本来就是 JSSDK 的使用前提啊，这个在 JSSDK 章节有讲啊，不可能每个部分我都写一个完整的例子吧，那样我不用生活了。

**Comment by overtrue** [comment]
在文档第一页就说了：

![image](https://user-images.githubusercontent.com/1472352/34929113-e518e802-f9fc-11e7-80ec-4c295f85d5a6.png)
