### ISSUE TITLE
composer安装不了，

### ISSUE THREAD

**Issue by wuchuguang** [overtrue/wechat#1111]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：
是否使用了框架？框架名称：

 sudo composer require overtrue/wechat 安装，几种都报这下面的错。
[sudo] xxxx 的密码： 
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^4.0 for overtrue/wechat
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install overtrue/wechat 4.0.13
    - Conclusion: don't install overtrue/wechat 4.0.12
    - Conclusion: don't install overtrue/wechat 4.0.11
    - Conclusion: don't install overtrue/wechat 4.0.10
    - Conclusion: don't install overtrue/wechat 4.0.9
    - Conclusion: don't install overtrue/wechat 4.0.8
    - Conclusion: don't install overtrue/wechat 4.0.7
    - Conclusion: don't install overtrue/wechat 4.0.6
    - Conclusion: don't install overtrue/wechat 4.0.5
    - Conclusion: don't install overtrue/wechat 4.0.4
    - Conclusion: don't install overtrue/wechat 4.0.3
    - Conclusion: don't install overtrue/wechat 4.0.2
    - Conclusion: don't install overtrue/wechat 4.0.1
    - Conclusion: don't install overtrue/wechat 4.0.0
    - Conclusion: don't install overtrue/wechat 4.0.0-beta.4
    - Conclusion: don't install overtrue/wechat 4.0.0-beta.3
    - Conclusion: don't install overtrue/wechat 4.0.0-beta.2
    - Conclusion: don't install overtrue/wechat 4.0.0-beta.1
    - Conclusion: don't install overtrue/wechat 4.0.0-alpha.2
    - Conclusion: remove monolog/monolog 2.0.x-dev
    - Installation request for overtrue/wechat ^4.0 -> satisfiable by overtrue/wechat[4.0.0, 4.0.0-alpha.2, 4.0.0-alpha1, 4.0.0-beta.1, 4.0.0-beta.2, 4.0.0-beta.3, 4.0.0-beta.4, 4.0.1, 4.0.10, 4.0.11, 4.0.12, 4.0.13, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.0.9].
    - Conclusion: don't install monolog/monolog 2.0.x-dev
    - overtrue/wechat 4.0.0-alpha1 requires monolog/monolog ^1.22 -> satisfiable by monolog/monolog[1.22.0, 1.22.1, 1.23.0, 1.x-dev].
    - Can only install one of: monolog/monolog[1.22.0, 2.0.x-dev].
    - Can only install one of: monolog/monolog[1.22.1, 2.0.x-dev].
    - Can only install one of: monolog/monolog[1.23.0, 2.0.x-dev].
    - Can only install one of: monolog/monolog[1.x-dev, 2.0.x-dev].
    - Installation request for monolog/monolog (locked at 2.0.x-dev) -> satisfiable by monolog/monolog[2.0.x-dev].

Installation failed, reverting ./composer.json to its original content.

**Comment by greedying** [comment]
在composer.json里面手动改一下 easywechat的版本，然后composer update

**Comment by overtrue** [comment]
monolog/monolog 2.0 还没发布，你就装了 2.0.x-dev 版本，先移除这个非正式版再装吧
