### ISSUE TITLE
请问 Symfony\Component\Cache\Simple\FilesystemCache 这个类找不到怎么办

### ISSUE THREAD

**Issue by malphitee** [overtrue/wechat#1117]
2天前曾经问过这个问题 #1108 ，问题已经被关闭了，请问有什么解决办法么，现象和 #1108 里的一样，反复更新过包，现在composer update显示  Nothing to Update

**Comment by lyt8384** [comment]
其实你可以试下把`vendor` `composer.lock` 删掉。。然后重新ins下试试。。建议先备份。以前遇到类似的问题大多都是框架或者某个插件已经装了装了这个包。然后还是其他版本的。。。或者删除了文件，手动操作了什么。也有类似的问题。

**Comment by malphitee** [comment]
@lyt8384 试过了，在#1108 里有记载，删除lock文件，clear-cache，删除整个文件夹，最后删除整个项目重新用composer装了一个再安装扩展，都报的是这个错

**Comment by mingyoung** [comment]
你 QQ ？

**Comment by malphitee** [comment]
@mingyoung 317126927

**Comment by malphitee** [comment]
问题已解决，可能是我开发环境的问题，laravel5.1中包依赖有点问题，换成5.5就好了，十分感谢 @mingyoung 的耐心解答！

**Comment by unizhu** [comment]
laravel 5.2下还是有这个问题哦

**Comment by malphitee** [comment]
@unizhu 只能用5.5

**Comment by unizhu** [comment]
@malphitee @mingyoung 那是不是应该README.md里写上，4.x 需要 laravel >= 5.5 ?
