### ISSUE TITLE
3.x版本当$_FILES里的临时文件已经被move走的时候会挂

### ISSUE THREAD

**Issue by amoydavid** [overtrue/wechat#1119]
## 我用的环境

PHP 版本：7
overtrue/wechat 版本：3.x
是否使用了框架？框架名称：Yii2

## 问题及现象

```
move_uploaded_file($_FILES['file']['tmp_name'], $to_path);
//init EasyWechat Application here
```

这时候会报一个类似这样的错误

```
[vendor/symfony/http-foundation/File/File.php:37] The file "/tmp/phpMm8rJe" does not exist
```

原因是 `vendor/overtrue/wechat/src/Foundation/Application.php` 的 233 行这里进去在使用 Request 初始化的时候，使用了 `$_FILES` 变量，但这时候这个临时文件已经被移走了，所以就报错了。

需要处理这种情况下的问题。

**Comment by overtrue** [comment]
为啥会被移走？不是应该解决这个问题么？这个明明是 PHP 基本的上传流程。

**Comment by amoydavid** [comment]
我的意思是，如果在实例化 EasyWechat 之前就把临时文件移走的话，EasyWechat 在实例化的时候会抛异常出来。具体原因就是因为实例化时候用了 $_FILES 变量，但实例化的时候对应的 tmp_name 指向的文件不存在了。
目前我的做法是在 move_uploaded_file 之后把 $_FILES 变量清空。

**Comment by overtrue** [comment]
@amoydavid 我非常好奇的是 “如果在实例化 EasyWechat 之前就把临时文件移走” 是怎么来的？为啥会有这样的操作存在 ？

**Comment by amoydavid** [comment]
我这的场景，上传文件处理完后发一个模版消息通知给管理员。

**Comment by amoydavid** [comment]
文件处理完毕了，再发通知。所以就发现了这个问题。

**Comment by overtrue** [comment]
好吧，那这事儿估计你得反馈给 symfony 了，毕竟这部分不是我写的逻辑

**Comment by overtrue** [comment]
https://github.com/symfony/http-foundation

**Comment by overtrue** [comment]
不过我的建议是在框架入口处去初始化服务实例
