### ISSUE TITLE
建议：完善log，增加环境配置异常相关log。

### ISSUE THREAD

**Issue by clwm01** [overtrue/wechat#1120]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：~4.0
是否使用了框架？框架名称：Yii2.0

## 问题及现象

我照着文档一步步走，从上往下走，走到快速开始的`接受&回复用户消息`[部分](https://www.easywechat.com/docs/master/zh-CN/official-account/tutorial)，（后面的配置还没有看），然后我向我的公众号发送了一条消息，得到了`公众号暂时无法服务`的消息。

根据文档上的提示：
- 日志：有
- 日志权限： 有
- 日志内容：无法说明出了什么问题。

后来，我加了异常处理，记录了异常日志，才知道是什么问题。

虽然是因为我没有配置正确的`app_id`造成的，但还是希望能够将更多的错误信息完善到日志记录中去，完善框架使用体验。

---

我的代码：

```php
use EasyWeChat\Factory;

require(__DIR__ . '/../vendor/autoload.php');
chdir(dirname(__DIR__));

$config = [
    'app_id' => '1111',
    'secret' => '1111',
    'token' => '1111',
    'aes_key' => '11111',
    'response_type' => 'array',
    'log' => [
        'level' => 'debug',
        'file' => getcwd().'/runtime/logs/wechat.log',
    ],
];

try {
    $app = Factory::officialAccount($config);

    $app->server->push(function ($message) {
        return 'Welcome to 111!';
    });

    $response = $app->server->serve();
    $response->send();
} catch (Exception $e) {
    $ch = fopen(getcwd().'/runtime/logs/wechat.log', 'a+');
    fwrite($ch, $e->getMessage());
    fclose($ch);
    $app['logger']->debug('Request received:', $e->getMessage()); // 这一句可能不正确，只是为了测试，没有别的目的，请忽略
}
```

日志截图：

![1516607673145](https://user-images.githubusercontent.com/5001145/35210414-0b2872c0-ff8d-11e7-9acf-21fa905db622.jpg)

后面这个`Invalid appId`是我加了异常日志后，才看到的。

**Comment by overtrue** [comment]
1. 一般的应用都是在框架下使用，因为框架具有完备的错误处理与日志，所以建议你使用框架而不是裸写
2. 在文档中已经列出来了 `app_id` 是需要正确填写的，这种错误我不觉得这个 SDK 有必要去解决，因为就算配置错了，微信那边也走不通，你拿到的 API response 也有报错内容。
3. 像这种组件式的包，一般是要用于其它地方的，如果我把异常 catch 了，很多人会觉得他想通过框架来处理这个异常，无法满足所有人，所以，我个人不打算在模块内去 catch 异常来记日志。

**Comment by clwm01** [comment]
好的，明白了。我是因为觉得框架太繁重，所以才把它单拉出来搞了。
所以，主要问题还是我没有用框架，或者说，这个异常处理应该交由这个包的工作环境处理，这样会比较自由一点。
谢谢。
