### ISSUE TITLE
symfony/cache 与 Laravel5.1 包依赖冲突

### ISSUE THREAD

**Issue by teamen** [overtrue/wechat#1121]
## 我用的环境

PHP 版本：7.1.2
overtrue/wechat 版本：4.0.12
使用的框架名称：Laravel 5.1.46

## 问题及现象
![image](https://user-images.githubusercontent.com/13899144/35214989-e0e1d7b6-ff9d-11e7-86c3-8190ce62f4ef.png)
升级 overtrue/wechat 后获取 access token/signature 报以上的错误，看了 #952 ，尝试升级`symfony/cache`，包冲突问题导致失败。

## 包冲突
![image](https://user-images.githubusercontent.com/13899144/35216040-2d074bdc-ffa1-11e7-862c-55fe39a6fc59.png)

`symfony/cache 3.3.0` 版本与 `symfony/var-dumper: <3.3` 冲突，laravel 5.1 对后者的依赖是 2.7.*，laravel 5.4 版本则是 `symfony/var-dumper: ~3.2`。

请问下有没有更好的解决方案？（除了用回旧版本包之外）

**Comment by mingyoung** [comment]
你可以升级你的 Laravel……

**Comment by teamen** [comment]
laravel5.4 以下都会有包依赖问题。
