### ISSUE TITLE
查看打款到银行卡报签名错误　

### ISSUE THREAD

**Issue by glore** [overtrue/wechat#1123]
## 我用的环境

PHP 版本：PHP 7.1.11 
overtrue/wechat 版本：^４.0
是否使用了框架？框架名称：laravel 

## 问题及现象
企业打款到银行卡成功，介是查询打款情况报签名错误：
 array (
  'return_code' => 'SUCCESS',
  'return_msg' => '签名出错，请根据签名算法进行签名',
  'result_code' => 'FAIL',
  'err_code' => 'SIGNERROR',
  'err_code_des' => '签名出错，请根据签名算法进行签名',
) 
描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**
            $app =\EasyWeChat::payment();
            $result = $app->transfer->queryBankCardOrder($transfer->trade_no);
            Log::debug($result);
			if($result['return_code'] == 'SUCCESS' && $result['result_code'] == 'SUCCESS' && $result['err_code'] == 'SUCCESS'){
                $transfer->status = '3';
            }else{
                $transfer->results .= '|'.$transfer->trade_no.','.$result['return_code'].':'.$result['err_code_des'];
            }

如果你不提供相关的代码，我不会做任何应答，直接 close，感谢！

**Comment by almas1992** [comment]
我也遇到此问题了，付款到银行卡正常，查询付款到零钱订单也正常，可就是查询付款到银行卡报签名错误，不知道楼主有没找到解决方法？

**Comment by almas1992** [comment]
找到问题了，查询付款到零钱时参数中要传appid,而查询付款到银行卡时不需要传appid
https://github.com/overtrue/wechat/blob/master/src/Payment/Transfer/Client.php#L83 @overtrue

**Comment by mingyoung** [comment]
PR #1132
