### ISSUE TITLE
BUG 服务端的消息接收当中,ToUserName 不是文档中所说的 公众号id,是用户的微信id

### ISSUE THREAD

**Issue by aprchen** [overtrue/wechat#1129]
## 我用的环境

PHP 版本：7.1.11
overtrue/wechat 版本：4.0.17
是否使用了框架？框架名称：phalcon

## 问题及现象
服务端的消息接收当中,ToUserName 不是文档中所说的 公众号id,是用户的微信id

  public function index($id){
        $app = $this->wxChat->getApp($id);
        $server = $app->server;
        $method = $this->request->getMethod();
        if($method == Methods::POST){
            try {
                $server->push(EventMessage::class,Message::EVENT);//事件处理
                $server->push(TextMessage::class, Message::TEXT); // 文本消息
            } catch (InvalidArgumentException $e) {
                Log::logger('wechat.log')->info($e->getMessage());
                return 'success';
            }
        }
        return $server->serve();
    }
//EventMessage
  public function handle( $message = [])
    {
        $event = $message['Event'] ?? '';
        $res = '';
        switch ($event) {
            case self::SUB:
                $res = $this->sub($message);
                break;
            case self::UN_SUB:
                $res= $this->unSub($message);
                break;
            case self::SCAN:
                $res= $this->scan($message);
                break;
            case self::CLICK:
                $res = $this->click($message);
                break;
            default:
                break;
        }
        return $res;
    }

   /**
     * 未关注参数二维码事件,订阅事件
     * @param $message
     * @return string
     */
    protected function sub($message)
    {
        $openId = array_key_exists('FromUserName', $message) ? $message['FromUserName'] : ''; //用户opendid
        Log::logger()->debug("message:".json_encode($message));
        $eventKey = array_key_exists('EventKey', $message) ? $message['EventKey'] : '';
//        if ($eventKey) { //参数二维码
//            //todo 参数二维码事件
//        }
        try{
            $op = new OrdinaryUserOperator();
            if (!$op->isRegister($openId)) { //是否注册
                $wxOp = new WechatOperator();
                $accountId = $wxOp->getWechatConfigWithAppId($appId)->id;
                $op->addWxUSer($openId, $accountId);//添加用户
            }
            $op->updateWxUserProfile($openId);//更新用户信息
            $text = "欢迎";
            return $text;
        }catch (ApiException $exception){
            Log::logger()->debug($exception->getMessage());
            return "服务器异常";
        }
    }

![image](https://user-images.githubusercontent.com/13740363/35554075-62985dd8-05d5-11e8-87b4-24b10810f509.png)

![image](https://user-images.githubusercontent.com/13740363/35554044-4bb18d92-05d5-11e8-8245-733e5deaa1f8.png)

**Comment by overtrue** [comment]
@aprchen 抱歉我不晓得你是如何测试的，反正我无论发送什么样的消息，得到的消息 `ToUserName` 都是公众号 id:

```xml
<ToUserName><![CDATA[gh_1763313807e5]]></ToUserName>
```

**Comment by aprchen** [comment]
@overtrue  抱歉,是我使用测试接口填错数据了...
