### ISSUE TITLE
如何才能获取普通的access_token

### ISSUE THREAD

**Issue by codesig** [overtrue/wechat#113]
想要获取全局的access_token, 不是网页授权的access_token，没找到相关接口，请问如何才能获取，谢谢

**Comment by overtrue** [comment]
https://github.com/overtrue/wechat/blob/2.1/src/Wechat/AccessToken.php

**Comment by codesig** [comment]
不好意思，不是很明白，能否给下具体代码，我用laravel的，我看到里面有getToken($appId, $appSecret)方法，但好像这样会重新生成access token而不是之前缓存着的token,如何才能获取到之前全局缓存的token？

**Comment by overtrue** [comment]
类都给你了怎么不会用？你不会PHP？

**Comment by codesig** [comment]
明白了，这样可以
```
with(new AccessToken($appid,$appsecret))->getToken()
```
谢谢啦
