### ISSUE TITLE
appId 和 appSecret不要作为各个类的构造参数

### ISSUE THREAD

**Issue by keepeye** [overtrue/wechat#114]
理由如下：
一旦access_token通过中控服务器管理，就没法玩了。

个人建议：
new Notice($appId,$appSecret)
改为
new Notice(new AccessToken($appId,$appSecret))

解耦。

耦合现象比较多，如果通过di来控制，会不会更好些？当然，这只是我的个人小小的建议。

**Comment by overtrue** [comment]
理解，3.0已经是这样的了
