### ISSUE TITLE
多个程序共用一个access_token

### ISSUE THREAD

**Issue by qq690712575** [overtrue/wechat#1145]
## 我用的环境
php7.1.2(nts)x86
PHP 版本：
overtrue/wechat 版本：
是否使用了框架？框架名称：
thinkphp5.1
## 问题及现象
多个程序共用一个access_token怎么操作呢，现在我想把获取到的token存到了redis，但是easywechat.kernel.access_token.37405cc9bc6f02a52bacf107204c2e4d，这后面的数字+英文组合是怎么计算出来的呢
描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

如果你不提供相关的代码，我不会做任何应答，直接 close，感谢！

**Comment by mingyoung** [comment]
https://github.com/overtrue/wechat/blob/cc87a03fd706ba20abbe4142d513b4228851b1c5/src/Kernel/AccessToken.php#L218-L221

**Comment by qq690712575** [comment]
十分感谢，最后我还是通过实现AccessTokenInterface接口去改写我的程序

- 发送自我的Sony Xperia™智能手机

---- 张铭阳编写 ----


https://github.com/overtrue/wechat/blob/cc87a03fd706ba20abbe4142d513b4228851b1c5/src/Kernel/AccessToken.php#L218-L221
