### ISSUE TITLE
请更新文档

### ISSUE THREAD

**Issue by Dysheng** [overtrue/wechat#1147]
## 我用的环境

PHP 版本：7.0
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：wechat

## 问题及现象
Error

Class 'Overtrue\Wechat\Auth' not found

**应该更新了代码。一直没更新文档。请及时更新文档啊。。。。**
描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

如果你不提供相关的代码，我不会做任何应答，直接 close，感谢！

**Comment by overtrue** [comment]
请提供上下文
