### ISSUE TITLE
ticket接收不到了

### ISSUE THREAD

**Issue by summerNazi** [overtrue/wechat#1148]
在回调里边 有  授权 更新授权  取消授权  获取ticket 四个作用
  
现  要在授权  更新授权  跳转新的地址   获取ticket时 返回success    

再用getMessage无效时  我全部跳转了新的地址   ticket接收不到了

**Comment by mingyoung** [comment]
不懂你的描述，请提供代码截图等

**Comment by summerNazi** [comment]
$server->push(function ($message) {
            Log::info('ticket' . json_encode($message));
        }, Guard::EVENT_COMPONENT_VERIFY_TICKET);

        $msg=$server->getMessage();
        if($msg){
            if(array_key_exists("InfoType",$msg)){
                if($msg['InfoType'] == 'component_verify_ticket'){
                    return $server->serve();
                }else{
                    return header("Location:http://xxx");
                }
            }else{
                return header("Location:http://xxx");
            }
        }else{
            return header("Location:http://xxx");
        }

**Comment by summerNazi** [comment]
现在EVENT_COMPONENT_VERIFY_TICKET 接不到了
