### ISSUE TITLE
获得当前链接时，https判断错误

### ISSUE THREAD

**Issue by mkgsac** [overtrue/wechat#1149]
## 我用的环境 

运行环境: iis8
PHP 版本：5.6
overtrue/wechat 版本：3.3.20

## 问题及现象
在`EasyWeChat\Support::current`方法中，判断是否https用的是

```
if (!empty($_SERVER['HTTPS'])  
     || (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && 'https' === $_SERVER['HTTP_X_FORWARDED_PROTO'])) {  
     $protocol = 'https://';
}
```

我的网站用的是`http`，$_SERVER['HTTPS']的值为`off`，所以最后得到 $protocol = `'https://'`

**Comment by manhere** [comment]
肯定是windows服务器（IIS 上以 ISAPI 方式请求时），可修改下：
`        if (!empty($_SERVER['HTTPS'] && $_SERVER['HTTPS'] !== 'off')
            || (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && 'https' === $_SERVER['HTTP_X_FORWARDED_PROTO'])) {
            $protocol = 'https://';
        }`
