### ISSUE TITLE
关于 Cache

### ISSUE THREAD

**Issue by shoaly** [overtrue/wechat#115]
...
/**
     * 获取缓存文件名
     *
     * @param string $key
     *
     * @return string
     */
    protected function getCacheFile($key)
    {   
        // 如果不区分的话, 命令行执行的时候  缓存文件的拥有者会不是 apache
        // return sys_get_temp_dir().DIRECTORY_SEPARATOR.md5($this->prefix.$key);
        return sys_get_temp_dir().DIRECTORY_SEPARATOR.'by_'.php_sapi_name().'_'.md5($this->prefix.$key);
    }
...

- 出现问题的时候 是这样的  , 通常情况下 都是 web容器, 比如apache  去执行的, 
- 这样 这个缓存文件的拥有者是apache , 但是如果 用户 写了 phpunit, 那么在部署代码的时候 跑phpunit的时候 会将 缓存的文件 拥有者 变成 调用phpunit的那个 linux用户
- 这样 apache那边 就没有权限 访问到这个缓存文件了

**Comment by shoaly** [comment]
这样还不行, 无法保证 缓存的accesstoken 是一致,  需要兼容性更好的解决办法

**Comment by overtrue** [comment]
你在干嘛？phpunit还在生产环境玩了？而且phpunit为啥还有文件系统了？你确定你真的会单元测试？

**Comment by shoaly** [comment]
phpunit 不应该在生产环境跑么,  那用什么方法可以确认 本地跑的代码 在服务器上也正常呢? 通常程序员都喜欢对着线上的bug说"在我本地是好的呢".. 所以我一般也会在 生产环境跑一遍, 确保没有问题

**Comment by overtrue** [comment]
1. 上线前通常打码会提交到代码仓库如gitlab之类的，同时你应该有一个CI（持续集成）服务来对代码质量进行检查，CI检查完毕生成是否可上线的结果
2. 手动使用一些服务或者脚本导出git代码到生产服务器
