### ISSUE TITLE
pic_weixin：弹出微信相册发图器的事件推送

### ISSUE THREAD

**Issue by RealZark** [overtrue/wechat#1155]
## 我用的环境

PHP 版本：7.1.5
overtrue/wechat 版本：^4.0
框架名称：laravel

## 问题及现象

服务端监听 `pic_weixin` 事件，日志记录微信推送的内容为： `pic_weixin: {"ToUserName":"gh_a420188dee56","FromUserName":"oEoAzw_7322OSEBsg96kt0LaTK5Y","CreateTime":"1520215390","MsgType":"event","Event":"pic_weixin","EventKey":"create","SendPicsInfo":{"Count":"0","PicList":null}}`，为什么 `SendPicsInfo` 始终为空的？是微信这个接口有问题还是内容解析问题？还是说微信就这么2，弄个接口给你就是返回空的玩意儿给你！

**Comment by overtrue** [comment]
就算解析有问题， Count 为 0 这个肯定错不了，所以看起来就是扔过来的就是这样哦
