### ISSUE TITLE
请教有没有打算支持 微信群发的推送群发结果回调？

### ISSUE THREAD

**Issue by greedying** [overtrue/wechat#1156]
谢谢~~

我想在群发里面插入 `上一条`这样的按钮，需要获取上一条图文的链接。
发现竟然不是那么容易。唯一可能获取到的地方，是微信有个群发结果推送。

请教这个推送有没有 类似 
```php
$server->mass->handle($callback)
````
这样的回调方式？

**Comment by overtrue** [comment]
推送不就是和平常的事件推送一样吗？在服务端 handler 里处理不就得了？

**Comment by greedying** [comment]
哦~~~这样啊。谢谢。我不知道逻辑是不是一样的～
