### ISSUE TITLE
为什么4.0版本很多方法不返回Collection而返回原生数组

### ISSUE THREAD

**Issue by scplay** [overtrue/wechat#1158]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：Laravel

## 问题及现象

之前使用3.x，后来升级4.0很多接口之前返回类型是 Collection，现在直接返回数组，这样就需要改很多处有Type Hint的参数，这样不兼容的修改是为了提升性能还是为什么呢？

如果你不提供相关的代码，我不会做任何应答，直接 close，感谢！

**Comment by overtrue** [comment]
麻烦熟读文档，这个变化的解释是这样的：

在 3.x 的时候，很多新手同学用的时候不明白为啥返回的是个对象，我被无数人反复问了很多次这个问题。所以，在 4.0 以后，我们重新设计了可定制的返回值类型：`array(default)/collection/object/raw/自定义类名`

默认使用数组格式返回，你只需要在配置中指定以上几种返回类型，即可轻松换到你喜欢的格式，所以你只需要在配置里指定 `response_type` 为 `collection` 即可。甚至，你还可以指定你自己实现的类来作为返回值，不过自定义类要求实现 `EasyWeChat\Kernel\Contracts\Arrayable` 接口。

具体实现请参考：https://github.com/overtrue/wechat/blob/master/src/Kernel/Traits/ResponseCastable.php

**Comment by overtrue** [comment]
配置说明：https://www.easywechat.com/docs/master/zh-CN/official-account/configuration

**Comment by scplay** [comment]
十分感谢，原来是这样
