### ISSUE TITLE
怎么给某个粉丝主动发送微信文本消息呢？

### ISSUE THREAD

**Issue by meiyoufengzhengdexian** [overtrue/wechat#1159]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：
是否使用了框架？框架名称：

## 问题及现象

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

如果你不提供相关的代码，我不会做任何应答，直接 close，感谢！

**Comment by tianyong90** [comment]
1. 使用客服接口
2, 发送模板消息（姑且认为这是你说的文本消息）

**Comment by overtrue** [comment]
请按官方文档的用法来操作。
