### ISSUE TITLE
微信支付问题

### ISSUE THREAD

**Issue by allen-hxn** [overtrue/wechat#1162]
## 我用的环境

PHP 版本：7.0.25
overtrue/wechat 版本：1.0.0
框架名称：laravel5.5

## 问题及现象

最近在开发公司的微信公众号里面的微信支付功能，使用了作者这个微信扩展包，十分方便好用，各种不用解析拼凑xml格式串，省了不少时间。

1.在开发微信公众号支付时，看了微信官方文档中的 公众号支付-》微信内H5调起支付，如下图框内，这里是个object,

![123](https://user-images.githubusercontent.com/16730544/37892784-9532252e-310b-11e8-9b5f-845ad36f8c0e.jpg)

但是看了作者的文档，如下图

![234](https://user-images.githubusercontent.com/16730544/37892832-c4934c30-310b-11e8-93e8-ec9c6ed57127.png)

**这里有疑问的是 到底是json字符串还是json对象？**

2. 按照作者文档中的 统一下单 获取到prepay_id。然后 生成支付 JS 配置 (WeixinJSBridge)，

![345](https://user-images.githubusercontent.com/16730544/37892868-e0fd562c-310b-11e8-8c0b-37a794ae63bb.png)

支付配置json:{"appId":"wxd5*********a7653af","timeStamp":"1522047297","nonceStr":"5ab8994122b29","package":"prepay_id=wx201803261454574909e3614c**********","signType":"MD5","paySign":"D8373DED67FFE5AEE9457070CAD14ABE"}
隐私地方已替换*

结果返回：get_brand_wcpay_request:fail

网上各种查找经验贴，看到官方有个解释是：签名错误，请仔细检查签名。
但是 JS 配置 是按照作者文档来的啊，实在找不出原因了，请教下是什么原因？

**Comment by tianyong90** [comment]
![image](https://user-images.githubusercontent.com/9278461/37894835-226346f2-3112-11e8-95bc-e78bf8594e49.png)
其实只要翻一下源码，就能搞清楚这里到底返回的是 json 字符串还是你说的 json 对象了。

另外，签名错误可能的原因可能有很多，但大部分是自己参数配置得不对。比如你这里的 appId 感觉长度就不够啊，难道是微信出了新花样，弄短 ID 了？

**Comment by allen-hxn** [comment]
@tianyong90 我明白这个bridgeConfig（$prepayId, true）方法返回的是json字符串，bridgeConfig（$prepayId, false）返回的是数组。我不明白的是，在WeixinJSBridge.invoke那里，微信官方文档给的示例是个json对象，但是easywechat文档上是直接用的字符串啊，这是我理解错了还是。。？

另外你说这个appId长度是不够，是因为隐私原因，去掉了后面的。

**Comment by tianyong90** [comment]
可能得了解下 js 对象的字面量赋值以及模板变量替换的原理。大概是没转过弯来吧。
示例里 <?= $json ?> 实际上就是一个对象，字面量赋值形式的， { appId: 'xxxx', .... } 这样……

**Comment by overtrue** [comment]
@allen-hxn PHP 输出的所有内容都是字符串，所以没有对象与字符串的区别，只不过这些字符串 html 在浏览器里才有 js 对象这些区别，对于服务器端来讲，都是字符串。

**Comment by allen-hxn** [comment]
@overtrue 好的。再问下，支付返回get_brand_wcpay_request:fail，一般是啥问题导致的呀？我是按照你的文档来生成JS配置串的。

**Comment by wwwhq199** [comment]
你是现在内网还是外网获取支付参数的呢，如果是内网需要注意下ip地址

**Comment by countrywind** [comment]
使用微信的沙箱，一直卡在 ‘调用支付JSAPI缺少参数:total_fee’，ip 用的 ip.cn 看到的公网ip，微信支付真没有支付宝省心

**Comment by nongzhenli** [comment]
> 使用微信的沙箱，一直卡在 ‘调用支付JSAPI缺少参数:total_fee’，ip 用的 ip.cn 看到的公网ip，微信支付真没有支付宝省心

你好！我目前也遇到这个问题，一直提示：缺少 total_fee  ，可是我已经传了呀。。。。在 unify()方法
