### ISSUE TITLE
jssdk分享时的签名错误问题

### ISSUE THREAD

**Issue by wwwhq199** [overtrue/wechat#1164]
## 我用的环境

PHP 版本：7.0
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：ThinkPHP5.0

## 问题及现象
> 已经在微信的公众平台配置好了js相关的各种域名，但是在使用jssdk分享时仍旧提示签名失败；经过查看源代码我发现是url的问题：
- 错误信息
![image](https://user-images.githubusercontent.com/18180191/38004746-489f633c-3270-11e8-8327-4598f197c10c.png)

- 当前页面的url
![image](https://user-images.githubusercontent.com/18180191/38004785-64d16b54-3270-11e8-8fec-340eb3e88d91.png)

- 参与签名的url 
![image](https://user-images.githubusercontent.com/18180191/38004866-c8eccf66-3270-11e8-984a-1db27aa89200.png)

**我认为是这两个url不一致导致签名**

## 我认为的原因
> 如果我们没有手动设置url，`overture/easywechat` 会自动去获取，获取的方式是:

判断是否手动设置url
```
<?php
namespace EasyWeChat\BasicService\Jssdk;
class Client extends BaseClient
{
  ...

 public function getUrl(): string
    {
        if ($this->url) {
            return $this->url;
        }

        return Support\current_url();
    }
}
```
自动获取url的助手方法
```
<?php
namespace EasyWeChat\Kernel\Support;
function current_url()
{
    $protocol = 'http://';

    if ((!empty($_SERVER['HTTPS']) && 'off' !== $_SERVER['HTTPS']) || ($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? 'http') === 'https') {
        $protocol = 'https://';
    }

    return $protocol.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
}
```
> 我觉得主要问题是 `.$_SERVER['REQUEST_URI']` ； `.$_SERVER['REQUEST_URI']` 获取的是要请求的资源路径（如果请求的接口是 `http://www.baidu.com/api/jssdk`,那么`.$_SERVER['REQUEST_URI']` = ‘api/jssdk’）

#### 我的解决办法是自己设置url
```
$url = $_SERVER['HTTP_REFERER'];
$app->jssdk->setUrl($url);
```
**[微信官网文档说的签名算法](https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421141115)**
![image](https://user-images.githubusercontent.com/18180191/38005600-eea8c57c-3273-11e8-87ad-38124cb6b9c9.png)
事实上通过`$_SERVER['HTTP_REFERER']`来获取整个url（包涵了#）来参与签名是可以的（我目前测试没发现问题）
**以上只是我个人的思路，如有不对的地方请多多包涵**

**Comment by overtrue** [comment]
前后分享当然需要手动设置 URL 的。

**Comment by lyt8384** [comment]
其实很明显。。。你这个是单页名应用配置的肯定。。。那个getWXJSSDKConfig是接口地址来的。。然后没看文档去手动设置签名的URL。。。就签名错误拉~~~
你需要。
1. [看文档](https://www.easywechat.com/docs/master/zh-CN/basic-services/jssdk)
1. 让你家前端把当前路径的URL拼接成参数传回来给你
