### ISSUE TITLE
服务商模式发送红包出现签名错误

### ISSUE THREAD

**Issue by Jasongzj** [overtrue/wechat#1166]
## 我用的环境

PHP 版本：7.0.25
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：tp5

## 问题及现象

使用**服务商模式**发送红包时，按照文档内容传入参数，会报签名错误的问题。
检查发现问题出在 `\overtrue\wechat\src\Payment\Kernel\BaseClient.php` 的 `request` 方法里，默认传递的 `sub_appid` 参数是不需要传的。

![_20180328162010](https://user-images.githubusercontent.com/24838580/38017215-f25948ba-32a3-11e8-8ffd-8851fd41534e.png)

## 目前解决方法

在调用发送普通红包接口传入的参数中，添加 `sub_appid => null` 的值：
```
$redpackData = [
    'sub_appid`    => null,
    'mch_billno'   => 'xy123456',
    'send_name'    => '测试红包',
    're_openid'    => 'oxTWIuGaIt6gTKsQRLau2M0yL16E',
    'total_num'    => 1,  //固定为1，可不传
    'total_amount' => 100,  //单位为分，不小于100
    'wishing'      => '祝福语',
    'client_ip'    => '192.168.0.1',  //可不传，不传则由 SDK 取当前客户端 IP
    'act_name'     => '测试活动',
    'remark'       => '测试备注',
    // ...
];

$result = $redpack->sendNormal($redpackData);
```

**Comment by overtrue** [comment]
@Jasongzj 用户 SDK 原来的代码，实际得到的 sub_appid 的值是多少？不是 null?

**Comment by Jasongzj** [comment]
@overtrue 默认获取的sub_appid为null。但是用的服务商模式，设置以后就会给sub_appid赋值
 ```
$app->setSubMerchant(config('WeChatPay.sub_mch_id'), config('WeChatPay.sub_appid'));
```
后面请求获取到的sub_appid不为null

**Comment by overtrue** [comment]
所以，是在发红包时不需要这个参数嘛

**Comment by Jasongzj** [comment]
@overtrue 是的，传这个参数的话会报签名错误。

**Comment by overtrue** [comment]
@Jasongzj OK，我稍后来更新一下

**Comment by overtrue** [comment]
@tianyong90 @mingyoung 看看这部分，我怕改错了

**Comment by tianyong90** [comment]
仔细查看了普通商户以及服务商支付红包相关文档，里面确实没有 sub_appid 这个参数，对于服务商，只是多了 sub_mch_id 和 msgappid 两个必传参数，这个 msgappid 可以是服务商的 app_id 也可以是公众号自己的 appid 或者子商户的。
![image](https://user-images.githubusercontent.com/9278461/38071420-c8ceb6e6-3353-11e8-9d18-3986da7dec02.png)

**Comment by zhlhuang** [comment]
话说，这个问题在最新版没有解决吧。
