### ISSUE TITLE
多图文消息

### ISSUE THREAD

**Issue by RealZark** [overtrue/wechat#1169]
## 我用的环境

PHP 版本：7.1.5
overtrue/wechat 版本：^4.0
框架名称：laravel

### 代码
```php
$newsMessages = NewsMessage::all();
        $message = [];

        $newsMessages->each(function ($item) use (&$message) {
            $newsItem = new NewsItem([
                'title' => $item->title,
                'description' => $item->description,
                'url' => $item->url,
                'image' => $item->image,
            ]);

            $message[] = $newsItem;
        });

        try {
            $app->customer_service->message($message)->to($openid)->send();
        } catch (\Exception $e) {
            Log::error('延迟图文消息发送失败：' . $e->getMessage());
        }
```

### 错误信息
![image](https://user-images.githubusercontent.com/16811858/38122869-54babc34-340a-11e8-8b90-28a61e7bb1ca.png)

> 我看了下这个源码，`$message` 传数组的话，数组直接调用 `transformForJsonRequest ` 方法了，就报错了！文档写法就是这样的。

![image](https://user-images.githubusercontent.com/16811858/38122931-d3e2e216-340a-11e8-9ff3-ac0278436f49.png)

**Comment by RealZark** [comment]
现在我把 `$message` 传入 `EasyWeChat\Kernel\Messages\News` 实例化之后，再传给 `message` 方法就可以了：

```
use EasyWeChat\Kernel\Messages\News;
$news = new News($message);

$app->customer_service->message($message)->to($openid)->send();
```

这样就可以了！

**Comment by overtrue** [comment]
文档是从3.0改过来的，有问题发现时点击文档页右上角的“纠正”按钮即可。
