### ISSUE TITLE
微信H5支付提示调用支付JSAPI缺少参数：timeStamp

### ISSUE THREAD

**Issue by DarkVisitor** [overtrue/wechat#1172]
![_20180331215625](https://user-images.githubusercontent.com/24539270/38163952-189ebd42-352f-11e8-883c-bb7f01096fcc.jpg)

**Comment by DarkVisitor** [comment]
有使用到微信公众号H5支付赶紧修改
wechat/src/Payment/Jssdk/Client.php 第70、71行 注释

**Comment by tianyong90** [comment]
@DarkVisitor 贴一下你的代码啊。你用的不是 JSSDK 吧？JSSDK 和 WxJsBridge 配置不一样……

**Comment by DarkVisitor** [comment]
@tianyong90  $payment = app("wechat.payment");
        //统一下单
        $unify = $payment->order->unify($params);

        if ($unify["return_code"] != "SUCCESS" || $unify["return_code"] != "SUCCESS"){
            throw new \Exception("微信统一下单失败: ".$unify["return_msg"]);
        }

        //生成jssdk配置
        $config = $payment->jssdk->sdkConfig($unify["prepay_id"]);


![image](https://user-images.githubusercontent.com/24539270/38164796-50aae5b4-353c-11e8-88b6-aec9324f48c1.png)

**Comment by DarkVisitor** [comment]
tianyong90 你有写支付可以自己试一下

**Comment by mingyoung** [comment]
那你调用 `bridgeConfig` 不就行了？为什么要调用 `sdkConfig`

**Comment by DarkVisitor** [comment]
@mingyoung  也是哦

**Comment by mingyoung** [comment]
@DarkVisitor 😂

**Comment by DarkVisitor** [comment]
![image](https://user-images.githubusercontent.com/24539270/38164882-c9a13b52-353d-11e8-9d87-f04cca31b4f8.png)


不明真相的总会出问题的
