### ISSUE TITLE
图文消息报错

### ISSUE THREAD

**Issue by oknixus** [overtrue/wechat#1177]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：dev-master README.md中显示的是4.0.21
框架名称：laravel 5.5

## 问题及现象
发送图文消息时，微信返回如下错误
{"errcode":40008,"errmsg":"invalid message type hint: [ZKJg.A0552ge20]"} 
无论是否嵌入卡券，微信都返回该错误信息

代码
```
$officialAccount = $this->initOfficialAccount(); // 初始化了一个公众号实例：成功
$broadcast       = $officialAccount->broadcasting;

$card_html = $officialAccount->card->getHtml($card->card_id); // 获取卡券嵌入图文的代码：成功
if ($card_html['errcode'] != 0) {
    Log::info('卡券HTML获取失败：', $card_html);
}

$material = $officialAccount->material->get($card->media_id);  // 获取图文信息：成功

// 构建卡券嵌入图文的数组
$item               = $material['news_item'][0];
$item['content']    = $card_html['content'] . $item['content'];

$news = new News([new NewsItem($item)]); // 调用图文接口
$resp = $broadcast->sendMessage($news);  // 发送图文信息
Log::info('发送信息：', $resp);
```

谢谢！

**Comment by overtrue** [comment]
文档中已经写清楚了，回复与客服消息才是 news, 群发与素材中的图文叫 article ，不是一个东西。
> https://www.easywechat.com/docs/master/zh-CN/official-account/messages

![image](https://user-images.githubusercontent.com/1472352/39457196-ae630dae-4d1e-11e8-9fd9-160f38e1b8a9.png)
