### ISSUE TITLE
微信支付下订单报错

### ISSUE THREAD

**Issue by baiban1993** [overtrue/wechat#1178]
## 我用的环境

PHP 版本：PHP Version 7.1.6RC1
cURL版本：7.54.0
overtrue/wechat 版本： "~4.0"
是否使用了框架？框架名称：thinkphp 5.1.6

## 问题及现象

微信支付下订单
$result = $app->order->unify()操作报错

![qq 20180403113802](https://user-images.githubusercontent.com/14030733/38227986-7ee61c20-3733-11e8-98ec-c7ca073813ea.png)

Use of undefined constant CURLOPT_IPRESOLVE - assumed 'CURLOPT_IPRESOLVE' (this will throw an Error in a future version of PHP)

网上搜索结果：
因为php5.6中去掉了这个常量。详见：

http://php.net/manual/en/curl.constants.php

CURLOPT_CLOSEPOLICY (integer)

Removed in PHP 5.6.0.

**Comment by overtrue** [comment]
？`CURLOPT_IPRESOLVE ` / `CURLOPT_CLOSEPOLICY`  不是同一个东西吧

**Comment by overtrue** [comment]
在命令行：
```shell
$ php -r 'var_dump(curl_version());'
```

在 fpm 环境下（控制器里）也 `var_dump(curl_version())` 看看结果

**Comment by overtrue** [comment]
http://php.net/manual/en/function.curl-setopt.php

**Comment by baiban1993** [comment]
不好意思，发现是服务器环境配置出了问题。已经正常了，感谢。
