### ISSUE TITLE
将代码部署到负载均衡上如何管理access token 

### ISSUE THREAD

**Issue by apt-getyou** [overtrue/wechat#118]
将代码布置到负载均衡，如何管理access token。由于存在多个服务器，导致每个服务器都会去请求一个access token，系统不稳定。现在需要一个中控服务器获取access token，其他服务器从这个中控服务器获取access token。
请问这个插件有什么解决方案么？？

**Comment by overtrue** [comment]
请参考自定义缓存一章

**Comment by apt-getyou** [comment]
写到中间件里？

**Comment by overtrue** [comment]
@apt-getyou 运行前，anywhere
