### ISSUE TITLE
doctrine/cache这个依赖由于1.7版本定义了方法的返回值类型，PHP5.6不支持，导致报错语法错误

### ISSUE THREAD

**Issue by rxlisbest** [overtrue/wechat#1180]
## 我用的环境

PHP 版本：5.6
overtrue/wechat 版本：3.x
是否使用了框架？框架名称：tp5

## 问题及现象

![image](https://user-images.githubusercontent.com/4598303/38284273-fc38c52e-37ec-11e8-975f-68b91760f1b3.png)
![image](https://user-images.githubusercontent.com/4598303/38284309-2a92dfa4-37ed-11e8-81d9-6542e1958bfc.png)
![image](https://user-images.githubusercontent.com/4598303/38284344-4780775c-37ed-11e8-9af2-028474b5ede2.png)

**Comment by forapi** [comment]
我也碰到了，解决方法：
1、直接clone，切换到3.X版本。
2、composer.json 里"doctrine/cache": "~1.4"，改为"doctrine/cache": "1.4"
3、composer install

**Comment by overtrue** [comment]
更新 overtrue/wechat 3.3.26 解决。
