### ISSUE TITLE
设备推送的消息没有正确解包的问题

### ISSUE THREAD

**Issue by dengxiufang** [overtrue/wechat#1187]
## 我用的环境

PHP 版本：7.0.27
overtrue/wechat 版本：4.0.22
是否使用了框架？框架名称：Thinkphp5

## 问题及现象

问题: 设备推送消息给微信客户端，再推送到第三方服务器后台时，接受到的数据并没有转化为数组，而还是原来的 XML 数据, 详细如下:
1. 具体代码
![image](https://user-images.githubusercontent.com/24001791/38729265-002b6baa-3f45-11e8-8d8c-780f6b420943.png)
2. 具体代码
![image](https://user-images.githubusercontent.com/24001791/38729062-4d194b18-3f44-11e8-8f46-6aad1a1eae24.png)
3. 报错信息
![image](https://user-images.githubusercontent.com/24001791/38729096-66a59b2c-3f44-11e8-9c22-c73331b7ae0c.png)

**Comment by overtrue** [comment]
dump 一下 $payload

**Comment by dengxiufang** [comment]
我把返回值存到了数据库，上下是正常的返回数据，设备推送上来的数据还是 XML 格式
![image](https://user-images.githubusercontent.com/24001791/38764371-12a82872-3fe0-11e8-93ae-f9d1931826ef.png)

**Comment by dengxiufang** [comment]
我把返回的数据保存到了数据库，上下是正常的返回数据，中间是设备推送上来的数据
![image](https://user-images.githubusercontent.com/24001791/38764419-2c0a5cee-3fe1-11e8-9ce4-d8469b78e0a6.png)

**Comment by overtrue** [comment]
我让你打印 payload 而不是你数据库里的东西
