### ISSUE TITLE
3.3 版本获得小程序码，page参数不能自定义，默认是首页

### ISSUE THREAD

**Issue by jc91715** [overtrue/wechat#1189]
## 我用的环境

PHP 版本：7.0
overtrue/wechat 版本：3.3
框架名称：laravel

## 问题及现象
* 3.3版本获得小程序码，没有page参数
![image](https://user-images.githubusercontent.com/24908449/38763770-542c54c2-3fd5-11e8-9b94-902d53f49a88.png)
* 4.0 版本的可以自自定义传参数
![image](https://user-images.githubusercontent.com/24908449/38763791-c573cc64-3fd5-11e8-8d02-148fe0a94527.png)

* 小程序文档
![image](https://user-images.githubusercontent.com/24908449/38763807-15a8c130-3fd6-11e8-9a98-c1f3aa47ad16.png)

**Comment by mingyoung** [comment]
3.3 的时候小程序官方还不支持 `page` 参数，你可以提个 PR 把 `page` 参数加到最后面

**Comment by mingyoung** [comment]
请使用 `appCodeUnlimit` 方法： https://github.com/overtrue/wechat/commit/39e63860edb4f58eb663521338d923c24832f709
