### ISSUE TITLE
关于Bag

### ISSUE THREAD

**Issue by iam993** [overtrue/wechat#119]
用户验证过后，返回的是一个Bag对象，请问怎么使用这个对象。
另外，在getUser里return new Bag($this->http->get($url));
为什么不直接写为return $this->http->get($url);呢？

**Comment by overtrue** [comment]
https://github.com/overtrue/wechat/wiki/%E7%94%A8%E6%88%B7%E4%B8%8E%E7%94%A8%E6%88%B7%E7%BB%84%E7%AE%A1%E7%90%86 wgbb例子不够明显？
![image](https://cloud.githubusercontent.com/assets/1472352/10480888/85d45cb4-729f-11e5-97a3-533a6da4f0c4.png)

**Comment by iam993** [comment]
应该是说网页授权
$this->http->get($url)返回的就是授权用户的信息，包括昵称等。
但是return new Bag($this->http->get($url));后我就不知道怎么用了。
也就是你给你例子：
if (empty($_SESSION['logged_user'])) {
    $user = $auth->authorize(); // 返回用户 Bag
    $_SESSION['logged_user'] = $user;
    // 跳转到其它授权才能访问的页面
}

$user = $_SESSION['logged_user'] ;
不知道这个$user怎么取数据。

**Comment by overtrue** [comment]
Bag的用法与普通类用法一样。上面已经给了你例子了

**Comment by iam993** [comment]
我用$Bag->all()的时候，老是报类似什么serialize  __autoload_的错误。
而且上面已经use Overtrue\Wechat\Utils\Bag过了。纠结了一下午。

**Comment by overtrue** [comment]
@iam993 请贴错误截图

**Comment by iam993** [comment]
:(
Home\Controller\UserController::Login(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "Overtrue\Wechat\Utils\Bag" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition

--------------------------------------------------------上面是错误，下面是代码
use Think\Controller;
use Overtrue\Wechat\Utils\Bag;
use Overtrue\Wechat\User;

class UserController extends Controller {
    public function Login(){
		if( !isset($_SESSION['user']) ){
			$Auth = new Auth(C('appid'),C('appsecret'));
			$_SESSION['user'] = ($Auth->authorize());
		}else{
			$user = ($_SESSION['user']);
			var_dump(($user->all()));

		}
    }
	
    public function LoginOut(){
		unset($_SESSION["user"]);
		echo 'loginout!';
    }

}

**Comment by overtrue** [comment]
SESSION 不支持对象存储吧？支持数组与标量。所以你直接把 $auth->authorize() 存进去就是错的吧？

```php
$user = ($_SESSION['user']); // 你这里得到的要么是数组要么是标量
var_dump(($user->all())); // 然而你却把它当成Bag对象用，谁教你的呢?
```

**Comment by iam993** [comment]
https://github.com/overtrue/wechat/wiki/%E7%BD%91%E9%A1%B5%E6%8E%88%E6%9D%83

// 请一定要自己存储用户的登录信息，不要每次都授权
if (empty($_SESSION['logged_user'])) {
    $user = $auth->authorize(); // 返回用户 Bag
    $_SESSION['logged_user'] = $user;
    // 跳转到其它授权才能访问的页面
}

var_dump($_SESSION['logged_user']);

我是看了你的例子，我以为可以这样用。那要怎么用呢？就我这里例子。

**Comment by overtrue** [comment]
@iam993 请学习PHP基础

**Comment by iam993** [comment]
懂了，大脑生锈，我把session想成c#的了，才学这个语言，还有点不熟。
谢谢了！代码写的真不错，我这样的新手也能看懂。
另外，有没有想过做公众号第三方的开发？

**Comment by overtrue** [comment]
@iam993 没想过
