### ISSUE TITLE
如何指定 StreamResponse 下载时的文件名

### ISSUE THREAD

**Issue by bestony** [overtrue/wechat#1195]
## 我用的环境

PHP 版本：php 7.1.4 
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：Laravel

## 问题及现象

下载到的二维码文件名为 `__pages_goods_goods_id=53 (1)` ,希望可以不保存到本地，直接下载时也可以自定义文件名。

如果不提供参数，希望为 response 添加 header 方法或 withHeader 方法。

目前调用方法：
```
 $response = $miniProgram->app_code->get($path,$options);
```

希望加入功能：

自定义下载参数，如文件名等。

**Comment by bestony** [comment]
目前我自己的 workaround 如下，供其他有同问题的人参考：

```
header('Content-Disposition: attachment; filename="'.$good->title.'.png"'); 
return $response->getBodyContents();
```

$good->title 是设置文件名的部分。

**Comment by overtrue** [comment]
@bestony 本来就有 `withHeader` 方法

**Comment by overtrue** [comment]
```php
$response->withHeader($header, $value)->getBodyContents()
```

**Comment by bestony** [comment]
好的，我测试一下，之前测试无法使用。
