### ISSUE TITLE
微信支付buildConfig()方法 ，返回404 not found

### ISSUE THREAD

**Issue by zhangzheng7856** [overtrue/wechat#1196]
## 我用的环境

PHP 版本：7.0
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：thinkphp

## 问题及现象
![_20180419225611](https://user-images.githubusercontent.com/31315670/39002673-a051f7c6-442b-11e8-9acd-2b82ede41eb3.png)
![_20180419234552](https://user-images.githubusercontent.com/31315670/39002755-d24d79e4-442b-11e8-9dc0-d6cb803b95e6.png)

**Comment by overtrue** [comment]
@zhangzheng7856 抱歉无法重现

**Comment by mingyoung** [comment]
你应该使用 `Factory::officialAccount(...)->jssdk->buildConfig(['chooseWXPay'])` 来生成 JSSDK 配置
