### ISSUE TITLE
负载均衡下token失效问题

### ISSUE THREAD

**Issue by wang199296** [overtrue/wechat#1197]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：lumen5.4

## 问题及现象

负载均衡，多台服务器下lumen下用easywechat出现了token失效问题，  请问该如何解决呢？
![image](https://user-images.githubusercontent.com/10125974/39029587-20fe3944-448f-11e8-8926-1a11a16db733.png)

这是获取token
![image](https://user-images.githubusercontent.com/10125974/39029601-35026596-448f-11e8-8274-512dd41d59df.png)

**Comment by overtrue** [comment]
> https://www.easywechat.com/docs/master/zh-CN/customize/cache

自定义缓存，将缓存放到一台机器，其它共用。

**Comment by liangshuocj** [comment]
@overtrue  链接失效啦

**Comment by almas1992** [comment]
> @overtrue 链接失效啦

https://www.easywechat.com/docs/4.1/customize/cache
