### ISSUE TITLE
 素材管理 -- 图片下载失败

### ISSUE THREAD

**Issue by lazyou** [overtrue/wechat#12]
<ol>
<li></li><br>
overtrue\wechat\src\Wechat\Media.php 的 download() 方法返回是空。

原因在 overtrue\wechat\src\Wechat\Http.php 的 request() 中 
<p><code>$contents = json_decode($response['data'], true);</code></p>
<code>$response['data']</code>并不是json格式，是图片资源。

<br><br><li></li><br>
download()的返回值  
<p><code>return $filename ? $contents : file_put_contents($filename, $contents);</code></p>

要对换下冒号两边的参数 ：
<p><code>return $filename ? file_put_contents($filename, $contents) : $contents;</code></p>
</ol>

**Comment by overtrue** [comment]
@lazyou OK。多谢，重构的时候没注意

**Comment by lazyou** [comment]
下载图片的时候我出现了另一个错误情况。大致原因是在

D:\xampp\htdocs\xampp\meishenghuo\vendor\overtrue\wechat\src\Wechat\Utils\Http.php的 request() 方法下 ： 
<code>
$responseSplit = preg_split('/((?:\\r?\\n){2})/', $response['response']);
</code>
正则分割 header和 body的时候出现了 body被拆分成两部分的情况。
我把正则内的 \r 后面的 ? 问号去掉就能解决问题（不懂为什么）。
<code>
$responseSplit = preg_split('/((?:\\r\\n){2})/', $response['response']);
</code>
<br/>

**Comment by overtrue** [comment]
是在处理哪个逻辑的时候？

**Comment by lazyou** [comment]
$media->download($mediaId, $filename); 下载临时素材到本地的时候。
下载失败。

**Comment by overtrue** [comment]
今天我改完那个bug之后？

**Comment by lazyou** [comment]
今天改完的还没更新使用。我明天更新下再建个Issues反馈。
