### ISSUE TITLE
Cache存储部件可定制

### ISSUE THREAD

**Issue by raywill** [overtrue/wechat#120]
现在Cache.php中强制使用文件作为token存储，不支持数据库。建议抽象存储层，支持外部传入定制的存储类。

**Comment by viko16** [comment]
@raywill 
wiki 有写 => [自定义缓存](https://github.com/overtrue/wechat/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BC%93%E5%AD%98)

**Comment by raywill** [comment]
谢谢，看到了。准备删掉这个issue没找到地方删TAT。。
