### ISSUE TITLE
客服消息尚不支持小程序卡片

### ISSUE THREAD

**Issue by Gethin2018** [overtrue/wechat#1201]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：~4.0
是否使用了框架？框架名称：laravel

## 问题及现象

小程序已经支持发送小程序卡片消息. ->[官方文档](https://developers.weixin.qq.com/miniprogram/dev/api/custommsg/receive.html#小程序卡片消息)

目前easywechat还不支持该消息类型,如果直接使用的话会报错

`local.ERROR: Undefined index: miniprogrampage {"exception":"[object] (ErrorException(code: 0): Undefined index: miniprogrampage at  *******/vendor/overtrue/wechat/src/Kernel/ServerGuard.php:253)`

**Comment by oknixus** [comment]
测试了下，好像原始消息是不行的

**Comment by Gethin2018** [comment]
@oknixus  还没有修复吗?

**Comment by oknixus** [comment]
@Gethin2018 好像可以放到图文消息中
