### ISSUE TITLE
如何在网页授权的过程中自定义 state 参数？

### ISSUE THREAD

**Issue by BruceFan-FS71** [overtrue/wechat#1202]
## 我用的环境

PHP 版本：7.2.2
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：Laravel 5.5

## 问题及现象

如何在网页授权的过程中自定义 state 参数？

**Comment by overtrue** [comment]
sorry, oauth 协议中的 state 参数不是用来传递数据的，所以没有自定义一说。

**Comment by BruceFan-FS71** [comment]
那在 Laravel 中，是否有办法允许在向回调页面做 redirect() 的时候加入自定义的 Query 参数？

`$app->oauth->redirect();`

**Comment by overtrue** [comment]
$app->oauth->redirect('http://foo.com?a=1&b=2');
