### ISSUE TITLE
开放平台，后台怎么通过code获取移动应用的用户信息？

### ISSUE THREAD

**Issue by stevieyu** [overtrue/wechat#1205]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：laravel

## 问题及现象

微信开放平台的 [移动应用->微信登录功能->第二步：通过code获取access_token](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419317851&token=318c8f5fdb8579555a19182c5e8b2e4df4db059b&lang=zh_CN)

如下图

![image](https://user-images.githubusercontent.com/8325201/39301913-75cb0d5a-4983-11e8-89b3-cc5990721b04.png)
这个接口有没有方法供调用？

**Comment by mingyoung** [comment]
使用这个 https://github.com/overtrue/socialite
