### ISSUE TITLE
新旧版本兼容问题

### ISSUE THREAD

**Issue by imsheng** [overtrue/wechat#1206]
## 我用的环境

是否使用了框架？框架名称： symfony

## 问题及现象

新旧版本代码不能兼容，即使不兼容 一个大网站要升级到新版本很大工程， 能不能把每个版本作为一个新包 这样能使网站同时使用新旧版本，然后旧版本代码慢慢替换

**Comment by imsheng** [comment]
管理类网站规模巨大，用的是旧版本，升级耗时耗力， 但又要用到新功能，唯有这个方法多版本同存，慢慢替换

**Comment by overtrue** [comment]
抱歉，不可能这样做的，也没见过这样的设计，而且就我所知目前就只有你一个人这样提过，之前的都是基本上花了3小时不到就换掉了，如果你的代码设计的模块化，按理来讲不应该会有太多需要替换，比如支付模块一般都是统一在你项目里的一个类里，那么只需要改这一个类就好，发消息或者其它业务，也应该是有固定出口的，不应该会太多分散直接调用 SDK 的代码存在。

**Comment by imsheng** [comment]
这是一个很哲学性的问题，你把微信接口包装起来，而我又把你的库包装起来，说白就是再写多一个中间件，现在只能按你说的那样

**Comment by imsheng** [comment]
其实按标准不一样区分包是可以的，例如 Yii1和Yii2 两者虽然目的是一样，但由上到下已经不一样。
https://github.com/yiisoft

**Comment by imsheng** [comment]
版本概念只是修复bug和新增功能，但新旧版本完完全全不一样的时候，可以想一下要不要区分两包，easywechat1,easywechat2...

**Comment by overtrue** [comment]
谢谢你的建议，不过我不能接受这样的做法。
