### ISSUE TITLE
请问有没有发送给指定用户的方法。我在文档找不到

### ISSUE THREAD

**Issue by sohenk** [overtrue/wechat#1209]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：4
是否使用了框架？框架名称：laravel5.5

## 问题及现象

我的项目需要需要发送消息给指定用户，已经有他的openid，也是在48小时内的用户。请问有没有这个方法呢

**Comment by overtrue** [comment]
官方对这个动作的称呼是什么？
