### ISSUE TITLE
微信开放平台消息推送闭包函数的问题

### ISSUE THREAD

**Issue by galaxyhao** [overtrue/wechat#1211]
## 我用的环境

PHP 版本：7.0.12
overtrue/wechat 版本：4.0.0
是否使用了框架？框架名称：thinkphp

## 问题及现象
我在处理授权更新事件的时候，能正确接收到message中的信息，但是handleAuthorize（）这个方法没有执行，而且好像$openPlatform这个对象没有被传入闭包中

**

        $this->openPlatform = Factory::openPlatform($this->config);

        $server = $this->openPlatform->server;
        $open_platform = $this->openPlatform;

        try {
            // 处理授权成功事件
            $server->push(function ($message) {
            }, Guard::EVENT_AUTHORIZED);

            // 处理授权更新事件
            $server->push(function ($message) use ($open_platform) {
                $auth_code = explode('@@@',$message['AuthorizationCode'])[1];
                $open_platform->handleAuthorize($auth_code);

            }, Guard::EVENT_UPDATE_AUTHORIZED);

            // 处理授权取消事件
            $server->push(function ($message) {
            }, Guard::EVENT_UNAUTHORIZED);

            //服务器主动推送verify_ticket
            $server->push(function ($message){
            },Guard::EVENT_COMPONENT_VERIFY_TICKET);

            return $server->serve();
        } catch (InvalidArgumentException $e) {
            $this->logError($e->getMessage(),'',$e->getTraceAsString());
            return $e->getMessage();
        } catch (BadRequestException $e) {
            $this->logError($e->getMessage(),'',$e->getTraceAsString());
            return $e->getMessage();
        } catch (InvalidConfigException $e) {
            $this->logError($e->getMessage(),'',$e->getTraceAsString());
            return $e->getMessage();
        }

**

**Comment by mingyoung** [comment]
`Guard::EVENT_UPDATE_AUTHORIZED` 需要更新授权才会触发，注意的是只有权限集发生改变，微信才会推送消息过来的

**Comment by galaxyhao** [comment]
@mingyoung 我晓得啊，我正确能够接收到 `Guard::EVENT_UPDATE_AUTHORIZED`权限更新事件，但是我想在接收到授权更新事件之后使用`handleAuthorize（）`这个方法来获取接口调用凭据和授权信息，但是把这个函数写入到回调函数中无法被执行。

**Comment by mingyoung** [comment]
> $auth_code = explode('@@@',$message['AuthorizationCode'])[1];

@galaxyhao 提供下相关报错信息？还有这里不需要 `explode`，直接传 `$message['AuthorizationCode']` 即可。
