### ISSUE TITLE
在服务器响应接口回复Article类型时错误

### ISSUE THREAD

**Issue by wangshantao** [overtrue/wechat#1212]
## 我用的环境

PHP 版本：7.0.10
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：thinkphp

## 问题及现象

在服务器响应接口回复Article类型时错误，另外我在微信的文档里也没看到这个类型。

`$article = new Article([
            'title'   => 'EasyWeChat',
            'author'  => 'overtrue',
            'content' => 'EasyWeChat 是一个开源的微信 SDK，它... ...',
            'digest' => '摘要摘要',
            'source_url' => 'www.baidu.com',
            'show_cover ' => '0',
        ]);
        return $article;`

错误
> [ error ] [0]致命错误: Class 'Mockery\Exception\BadMethodCallException' not found[/work/wwwcgi/yyzs/release/vendor/overtrue/wechat/src/Kernel/Messages/Message.php:200]

异常不存在，不知道是不是我composer安装的包不完全，但是在服务器上不敢轻易更新。不过已经触发异常了，应该还是有点问题吧？

**Comment by overtrue** [comment]
使用前请先仔细阅读文档：

> https://www.easywechat.com/docs/master/zh-CN/official-account/messages
![image](https://user-images.githubusercontent.com/1472352/39905747-82d23a3e-5511-11e8-80f5-307e8fda6cd9.png)

**Comment by wangshantao** [comment]
之前看到这一句没怎么明白，现在大概懂了。
