### ISSUE TITLE
根据标签群发消息时接口地址错误

### ISSUE THREAD

**Issue by zhaojianhui129** [overtrue/wechat#1213]
在通过用户标签发送群发消息时，调用接口依旧是mass/sendall，而不是切换为mass/send，
文件地址：overtrue/wechat/src/OfficialAccount/Broadcasting/Client.php，
第54行，建议改为：
```php
$api = Arr::has($message, 'filter.is_to_all') ? 'cgi-bin/message/mass/sendall' : 'cgi-bin/message/mass/send';
```
这样才能准确的调用微信接口。

**Comment by overtrue** [comment]
?

**Comment by zhaojianhui129** [comment]
composer里面的包没有更新，更新后发现那里没问题了，旧代码存在问题而已。

**Comment by overtrue** [comment]
@zhaojianhui129 好的，之前确实存在过这个问题，已经修复了。
