### ISSUE TITLE
微信服务器不稳定导致sdk使用受限的问题

### ISSUE THREAD

**Issue by tq102412** [overtrue/wechat#1214]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：4
是否使用了框架？框架名称：laravel

## 问题及现象

感谢作者提供那么优雅的sdk！
接下来我说一下我遇见的问题，我注意到我们sdk里面开放平台的使用方法是先要通过`授权方的基本信息`接口获取`authorizer_refresh_token`在进行使用公众号或小程序的方法，但是微信开放平台获取`授权方的基本信息`的接口：`https://api.weixin.qq.com/cgi-bin/component/api_get_authorizer_info?component_access_token=xxxx`之类的接口偶尔会返回如下错误
```
{
“errcode”: -1,
“errmsg”: “system error hint: [0456vr32]"
}
```
我在代码中尝试重试操作进行调用发现同一时间重试三次都是失败的情况，等待一秒后接口可以正常调用.

我已经给微信去邮件进行询问了，但是我们是否应该对这种情况的出现做出相应措施，例如：在通过`authorizer_refresh_token`刷新`access_token`的时候放一个事件，允许自己处理该事件.

**Comment by overtrue** [comment]
你可以自定义返回值类型，它将作为所有 API 返回结果的返回值在所有 API 请求返回时被初始化，所以你就可以在初始化以后根据 API 结果定制你的需求了，详细 demo 可以参考教程：https://www.easywechat.com/lessons/25

**Comment by tq102412** [comment]
感谢作者的回复！我参考视频教程自己实现了一个自定义返回值类型，然而我发现这并不能达到我所想要的结果，因为接口：
```
http请求方式: POST（请使用https协议）
https:// api.weixin.qq.com /cgi-bin/component/api_authorizer_token?component_access_token=xxxxx
```
的返回值：
```
{
"authorizer_access_token": "aaUl5s6kAByLwgV0BhXNuIFFUqfrR8vTATsoSHukcIGqJgrc4KmMJ-JlKoC_-NKCLBvuU1cWPv4vDcLN8Z0pn5I45mpATruU0b51hzeT1f8", 
"expires_in": 7200, 
"authorizer_refresh_token":
"BstnRqgTJBXb9N2aJq6L5hzfJwP406tpfahQeLNxX0w"
}
```
并没有授权公众号的标识，存储的时候并不能对应到相应的公众号上面去。

*** 建议 ***

由于开放平台带公众号实现业务的逻辑中，现在由于所有的`authorizer_refresh_token`都必须通过`获取授权方授权信息`获取，导致所有的接口使用之前都需要调用这个接口来获取`authorizer_refresh_token`，造成不必要的资源浪费，这个地方官方的建议是授权过来的时候用户通过预授权码获取了`authorizer_refresh_token`过后就保存下来然后使用刷新`authorizer_access_token`之后进行替换，因为这个时候`authorizer_refresh_token`才会过期。所以我建议：
- 解决方案1：这个地方能不能在请求接口完成后放一个事件，事件中传入请求的参数和返回的参数，允许开发人员自行解决类似的问题。
- 解决方案2： sdk直接安装官方推荐的直接处理预授权码的时候就缓存下来`authorizer_refresh_token`然后在后续的刷新`authorizer_access_token`操作中自动完成`authorizer_refresh_token`的替换。

[开放平台参考文档](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1453779503&token=&lang=zh_CN)

**Comment by overtrue** [comment]
@mingyoung 帮忙看看？

**Comment by tq102412** [comment]
@mingyoung 帮忙看看？

**Comment by mingyoung** [comment]
@tq102412 你的意思在处理预授权码的时候就把 `authorizer_access_token` 缓存下来？

**Comment by tq102412** [comment]
@mingyoung 不是的，是把`authorizer_refresh_token `缓存下来，因为只有在使用`authorizer_refresh_token`刷新令牌对`authorizer_access_token`刷新的时候`authorizer_refresh_token`才会改变，可以在处理预授权码把他缓存下来然后后面刷新`authorizer_access_token`的时候对`authorizer_refresh_token`更新

**Comment by mingyoung** [comment]
你确定刷新 `authorizer_refresh_token` 的时候 `authorizer_refresh_token` 也会变？

**Comment by tq102412** [comment]
@mingyoung 是的，刷新`authorizer_access_token `的时候同时会返回新的`authorizer_refresh_token `，我建议可以在关键位置放置一些事件，方便开发者自定义处理一些业务逻辑以应对产品千奇百怪的需求。

**Comment by tq102412** [comment]
重新授权会变，刷新的时候也会的

**Comment by mingyoung** [comment]
截图看看

**Comment by tq102412** [comment]
今早特意测试了一次，调用刷新的时候确实没有变，可能是我一直以来的理解是错误的。那这个地方我可以自己处理了，预授权的时候我存下来后面自己取出来传到sdk里面可以了，谢谢。
