### ISSUE TITLE
注册指定类型的消息处理器 怎么传对象参数进来

### ISSUE THREAD

**Issue by everythinggood** [overtrue/wechat#1220]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：当前
是否使用了框架？框架名称：slim3

## 问题及现象
如题：
$this->app->server->push(EventMessageHandler::class,Message::EVENT);

class EventMessageHandler implements EventHandlerInterface
{

    /**
     * @param mixed $payload
     */
    public function handle($payload = null)
    {

        if(array_key_exists('Ticket',$payload)){
            $scene = str_replace('qrscene','',$payload['EventKey']);
            $ticket = $payload['Ticket'];
//我想传app对象进来
$app->customer_server->...

        }

    }

}

**Comment by everythinggood** [comment]
大佬们，能不能改进一下？我不想也写在匿名函数里面，很丑

**Comment by overtrue** [comment]
@everythinggood Handle 的构造函数第一个参数就是 $app
