### ISSUE TITLE
为什么测试环境snsapi_userinfo授权还需要关注公众号

### ISSUE THREAD

**Issue by QuiteTree** [overtrue/wechat#1221]
## 我用的环境

PHP 版本：7.1.17
overtrue/wechat 版本：
是否使用了框架？框架名称：lavarel

web开发者工具 测试环境 必须要关注测试公众号才能 授权登录即使使用snsapi_userinfo授权？

public function handle($request, Closure $next)
    {
        if(!$request->session()->has("wcOpenId")){
            $request->session()->put('originalUrl',$request->getUri());
            $config = [
                'app_id' => env('WECHAT_OFFICIAL_ACCOUNT_APPID'),         // AppID
                'secret' => env('WECHAT_OFFICIAL_ACCOUNT_SECRET'),    // AppSecret
                'token' => env('WECHAT_OFFICIAL_ACCOUNT_TOKEN'),           // Token
                'aes_key' => env('WECHAT_OFFICIAL_ACCOUNT_AES_KEY'),                 // EncodingAESKey
                'response_type' => 'array',
                'log' => [
                    'level' => 'debug',
                    'file' => __DIR__.'/wechat.log',
                ],
                'oauth' => ['snsapi_userinfo']
            ];
            $app = Factory::officialAccount($config);
            $response = $app->oauth->scopes(['snsapi_userinfo'])
                ->redirect('http://127.0.0.1:8000/wechat/callback');
            return $response;
        }
        return $next($request);
    }

**Comment by mingyoung** [comment]
测试号是需要关注的
