### ISSUE TITLE
PhpStorm 出现一坨黄

### ISSUE THREAD

**Issue by hihuangwei** [overtrue/wechat#1222]
## 我用的环境

PHP 版本：7.2.5
overtrue/wechat 版本：4
是否使用了框架？框架名称：Laravel 5.6

## 问题及现象

![_20180520183405](https://user-images.githubusercontent.com/3166799/40278059-aad7db72-5c5c-11e8-9b5b-a819beac7002.png)

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

如果你不提供相关的代码，我不会做任何应答，直接 close，感谢！

**Comment by overtrue** [comment]
你的设置有问题，可以忽略

**Comment by hihuangwei** [comment]
要怎么设置可以消失，work 就没有这样

**Comment by overtrue** [comment]
@hihuangwei 这个我就不清楚了。

**Comment by mingyoung** [comment]
在 PhpStorm 中配置你的 `Unchecked Exceptions`
