### ISSUE TITLE
安装问题：装的SDK和文档不对应？

### ISSUE THREAD

**Issue by LiZheWang** [overtrue/wechat#1223]
## 我用的环境

PHP 版本：7.0.10
overtrue/wechat 版本：不知道是4.x还是3.x
是否使用了框架？框架名称：yii2

## 问题及现象

https://www.easywechat.com/docs/master/zh-CN/installation
composer require overtrue/wechat:~4.0 -vvv  

安装好以后对照最新文档跑步起来 ，按照3.x的文档能跑起来 。
use EasyWeChat\Foundation\Application;  可以使用
use EasyWeChat\Factory;  不可以使用

我应该看哪份文档？

另外官网 讨论  下发帖：
https://www.easywechat.com/discussions/create
提交一直返回 Whoops, looks like something went wrong 。

**Comment by mingyoung** [comment]
`composer info overtrue/wechat` 查看下你安装的是什么版本

**Comment by overtrue** [comment]
我猜你用了某已经不再维护的国内源，建议更换为 Laravel-China 的 packagist 源再试。https://laravel-china.org/composer

**Comment by LiZheWang** [comment]
composer info overtrue/wechat   看到的结果是3.3.26  。

我的composer国内镜像是：https://www.phpcomposer.com  。 （百度他第一啊，菜鸟直接就用了）
composer config -g repo.packagist composer https://packagist.phpcomposer.com  。

我在试一下 Laravel-China 的 packagist 源 。 谢谢大家

**Comment by overtrue** [comment]
所以被我一下子猜中了

**Comment by overtrue** [comment]
他都一年多快两年没更新那个源了

**Comment by LiZheWang** [comment]
好坑啊，那个源还是百度第一。  
最近刚用PHP，一搜索就直接用了，谁知道还有这种事。。
之前用npm maven  什么的 ， 从未遇到过这种问题

**Comment by LiZheWang** [comment]
问题已解决 Laravel-China源可以 。
设置方法：
composer config -g repo.packagist composer https://packagist.laravel-china.org
