### ISSUE TITLE
三方平台的access token缓存没有使用配置中的的缓存.

### ISSUE THREAD

**Issue by symoo** [overtrue/wechat#1226]
## 我用的环境
 
PHP 版本：7.1
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：laravel

## 问题及现象
 #1225 
具体问题描述在在pull request里面, 但是提交之后发现有一个不妥的地方, 如果直接使用laravel缓存的话, 
`$cache->set('key', 'value', 'ttl');` 这里ttl的值sdk传递的是7200秒, 而laravel接受的单位是分钟.
按我的修改方式无法解决这个问题, 会导致access token在缓存中的过期时间是7200分钟.
这里麻烦大佬看一下有没有什么解决方法.

#1188 似乎和我遇到的是一样的问题

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

如果你不提供相关的代码，我不会做任何应答，直接 close，感谢！

**Comment by mingyoung** [comment]
> 如果直接使用laravel缓存的话,
> $cache->set('key', 'value', 'ttl'); 这里ttl的值sdk传递的是7200秒, 而laravel接受的单位是分钟.
> 按我的修改方式无法解决这个问题, 会导致access token在缓存中的过期时间是7200分钟

使用 Laravel 缓存的可以参考一下以下的写法：

https://github.com/overtrue/laravel-wechat/blob/master/src/ServiceProvider.php#L92

https://github.com/overtrue/laravel-wechat/blob/master/src/CacheBridge.php

**Comment by overtrue** [comment]
@symoo 请试用 dev-master 版本
