### ISSUE TITLE
小程序服务端发送客服信息，只能发送文本信息，图文信息发送提示成功，但是手机无接收！

### ISSUE THREAD

**Issue by sincez** [overtrue/wechat#1230]
## 我用的环境

PHP 版本：php5.6
overtrue/wechat 版本：3.3
是否使用了框架？框架名称：thinkphp3.2

## 问题及现象

小程序服务端发送客服信息，只能发送文本信息，图文信息发送提示成功，但是手机无接收！
发送信息代码如下：
`

        $app = new Application($options);
        $this->app = $app;
        $miniProgram = $this->app->mini_program;
        $message = new Raw('{
            "touser": "",
            "msgtype": "link",
            "link": {
                  "title": "点击进入",
                  "description": "描述",
                  "url": "",
                  "thumb_url": ""
            }
        }');
        $miniProgram->staff->message($message)->send();
`
返回信息如下：
{"contents":{"errcode":0,"errmsg":"ok"}}

并无任何报错，手机上无法接收，不知道什么问题，麻烦大神指点一下。

**Comment by overtrue** [comment]
这个你可能需要检查你的输入是否符合官方的要求了，我们也没办法帮你，毕竟 SDK 只是做转发，没对内容做处理，
