### ISSUE TITLE
JSSDK配置获取不到getLocalImgData接口

### ISSUE THREAD

**Issue by 13564112184** [overtrue/wechat#1231]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：$ composer require overtrue/wechat:~3.1 -vvv
是否使用了框架？框架名称：tp5.0

## 问题及现象

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**
权限列表配置了，没有获取到接口权限
![image](https://user-images.githubusercontent.com/37323598/40634730-20b2dca2-6329-11e8-8dd8-1b762a4d953a.png)
![image](https://user-images.githubusercontent.com/37323598/40634741-29ea2410-6329-11e8-8fba-27c4d3491ac9.png)

**Comment by overtrue** [comment]
![image](https://user-images.githubusercontent.com/1472352/40660899-e9dd355e-6384-11e8-9ea5-c08419ab9da3.png)
