### ISSUE TITLE
企业微信发送消息问题

### ISSUE THREAD

**Issue by saybabi** [overtrue/wechat#1238]
## 我用的环境

PHP 版本：7.0
overtrue/wechat 版本：^4.0
是否使用了框架？框架名称：TP

## 问题及现象
企业微信发送消息， 只能发文字类型的吗？ 我想发图文消息那种
#### 正常
~~~
$res = $app->message->message(‘xx’)->toUser()->ofAgent()->send();
~~~

####  应该接口不支持这样的写法
~~~
$res = $app->message->message([
        'msgtype' => 'text',
        'text' => [
        ]
    ])->toUser()->ofAgent()->send();

~~~

感谢 : )

**Comment by saybabi** [comment]
原来这样用的 
~~
$app->message->send([
        'msgtype' => 'text',
        'touser' => ,
        'agentid' => 'agentid',
        'text' => [
            'content' => 'xxx'
        ]
    ]);
~~

**Comment by Fenglin0721** [comment]
完美解决，感谢~

**Comment by ee01** [comment]
->ofAgent() 这个是一定要加的么？我看文档没写，然后根据文档`$messenger->toUser('overtrue')->send('你的请假单（单号：1928373）已经审批通过！');` 报错【No agentid specified.】
