### ISSUE TITLE
更新到最新的master后，$this->miniProgram->media->uploadImage报错tmp文件不存在

### ISSUE THREAD

**Issue by WannaProGrammer** [overtrue/wechat#1241]
## 我用的环境

PHP 版本：7.0
overtrue/wechat 版本：dev-master
是否使用了框架？框架名称：yii1.1

## 问题及现象

原来是4.20的版本，图片上传是好的，更新到最新的master或4.25后 就报错 The file“/tmp/phpXXXX” does not exist。回退到4.20版本就又好了

**Comment by WannaProGrammer** [comment]
![image](https://user-images.githubusercontent.com/22359902/41041068-ae89d622-69d0-11e8-87eb-9c12ca3e308b.png)
![image](https://user-images.githubusercontent.com/22359902/41041095-c10010c8-69d0-11e8-9158-c4d814fdd266.png)

**Comment by overtrue** [comment]
这。。。

**Comment by WannaProGrammer** [comment]
超哥 求解答下

**Comment by overtrue** [comment]
严格来讲这个我也解答不了，你可以一步步跟一下，这个临时文件为啥会不见

WannaProGrammer <notifications@github.com>于2018年6月7日 周四上午9:02写道：

**Comment by WannaProGrammer** [comment]
好的 谢谢超哥
