### ISSUE TITLE
YII2中服务器端验证总是失败..

### ISSUE THREAD

**Issue by LiZheWang** [overtrue/wechat#1245]
## 我用的环境

PHP 版本：7.0.10
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：yii2

## 问题及现象
看了easywechat视频介绍，我单独一个.php文件已经配置好没有问题 ，用laravel也没问题 。
但是放到yii2里面总是验证失败，不知道什么情况...

## 解决方法
这个是yii2的问题，资料非常少，google了差不多一天才找到解决方案，愤怒的记一下吧：
1.在$response->send();前面加上ob_clean();   （验证token的时候用，验证时候为get）
2.加上public $enableCsrfValidation = false;  （验证完以后，发消息的时候是post，需要禁用csrf验证，不然会提示：公众号故障）

以下完整controller：

```
class WeixinController extends Controller
{

    public $enableCsrfValidation = false;

    public function actionIndex()
    {
        //具体配置参考：https://www.easywechat.com/docs/master/zh-CN/official-account/configuration
        $config = [ ];
        $app = Factory::officialAccount($config);

        $app->server->push(function ($message) {
            $keyword = $message["Content"];
            return "调通了";
        });

        $response = $app->server->serve();
        // 将响应输出
        ob_clean();
        $response->send();

    }
}
```

**Comment by overtrue** [comment]
用浏览器打开试试，然后查看源代码，检查是否有多余输出

**Comment by LiZheWang** [comment]
看过了没有多余输出，这是最新预览地址：
http://m7h84u.natappfree.cc/fireball/yii2/wechat/web/weixin?echostr=asdassdds

**Comment by LiZheWang** [comment]
我用单独一个.php文件的时候是能调通的，也是用的内网转发。
就是YII2里面不行.. 现在功能没有调整好，放外网就会影响使用了

**Comment by overtrue** [comment]
抱歉那你只能自己解决了，因为我也不用 Yii, 我用 Laravel, 而且这个输出也正常，还得麻烦你自己再研究研究了。

**Comment by LiZheWang** [comment]
恩好的，感谢超哥！ 我在研究下

**Comment by huijiewei** [comment]
$response->send();
后面加一个 exit; 试试吧

**Comment by peterpan0708** [comment]
@huijiewei 请问为何加上exit，就可以呢？ exit函数的作用是终止脚本执行呀

**Comment by overtrue** [comment]
@peterpan0708 你的框架在结束时加了其它输出，影响了结果，所以这里用 exit 避免了后续的附加内容
