### ISSUE TITLE
php7.2.6版本下不支持三元运算符简写??不支持

### ISSUE THREAD

**Issue by systoms** [overtrue/wechat#1249]
## 我用的环境

PHP 版本：php7.2.6
overtrue/wechat 版本：4.0.30
框架名称：yii2

## 问题及现象

Parse error: syntax error, unexpected '?' in /vendor/overtrue/wechat/src/Kernel/Support/Helpers.php on line 83

Parse error: syntax error, unexpected '?' in /vendor/overtrue/wechat/src/Kernel/Helpers.php on line 29

Parse error: syntax error, unexpected '?' in /vendor/overtrue/wechat/src/Kernel/Helpers.php on line 31

Parse error: syntax error, unexpected '?' in /vendor/overtrue/wechat/src/Kernel/Helpers.php on line 33

```php
#这是其中的一段错误
#php code line 83
/**
 * Return current url.
 *
 * @return string
 */
function current_url()
{
    $protocol = 'http://';

    if ((!empty($_SERVER['HTTPS']) && 'off' !== $_SERVER['HTTPS']) || ($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? 'http') === 'https') {
        $protocol = 'https://';
    }

    return $protocol.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
}
```

**Comment by overtrue** [comment]
怎么可能！你的 fpm 版本绝对小于7

达 <notifications@github.com>于2018年6月9日 周六下午9:38写道：

**Comment by systoms** [comment]
PHP 7.2.6 (cli) (built: Jun  6 2018 19:05:01) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

是docker环境下运行的

**Comment by mingyoung** [comment]
你这是 cli 版本，请检查一下fpm 版本

达 <notifications@github.com>于2018年6月9日 周六下午10:29写道：
