### ISSUE TITLE
scene内有多参数的小程序无法生成

### ISSUE THREAD

**Issue by caingougou** [overtrue/wechat#1258]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：^4.0
是否使用了框架？框架名称：laravel

## 问题及现象

以下代码调用后无法获取小程序码
$response = $wechat->app_code->getUnlimit(http_build_query(['xid' => $device->partner_id, 'cid' => $device->imei]), ['page' => 'pages/index']);
错误内容：
{"errcode":40169,"errmsg":"invalid length for scene, or the data is not json string hint: [0UPT501274526]"}
据查问题在于如果将query中的&符号去掉就能正确生成，然而小程序码文档中说明&符号为合法字符

**Comment by mingyoung** [comment]
`scene` 最长 32 个字符

**Comment by caingougou** [comment]
好的，看了官方文档了解了，谢谢

**Comment by oknixus** [comment]
128个字节，我也是醉了！为什么不直接写32个字符呢，哎，郁闷！
