### ISSUE TITLE
门店小程序接口无法使用

### ISSUE THREAD

**Issue by gychg** [overtrue/wechat#1259]
## 我用的环境

PHP  #[版本：7.1
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：laravel

## 问题及现象
为什么公众号创建门店小程序接口是在小程序里面的? 
公众号目前无法调用，按照文档上的方式也无法调用。门店小程序应该属于公众号接口吧。
门店小程序文档：https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1496904104_cfEfT

![061051fe-e73a-42dc-8b08-9d7cd0350cd6](https://user-images.githubusercontent.com/16475896/41457287-c33c8146-70b5-11e8-9c77-d3254e5c966a.png)

![image](https://user-images.githubusercontent.com/16475896/41457134-437ed724-70b5-11e8-8bb7-9da64f2a2337.png)

**Comment by mingyoung** [comment]
#1351
