### ISSUE TITLE
使用flightphp框架,验证URL的时候,在Apache下接入成功,在Nginx接入失败

### ISSUE THREAD

**Issue by imyip** [overtrue/wechat#126]
我是使用flightphp框架,url重写规则均按照教程写入
然而验证URL的时候,在Apache下接入成功,在Nginx接入失败 
貌似是http类的get方法没有起作用

**Comment by a939638621** [comment]
@imyip 可否粘贴一下代码

**Comment by imyip** [comment]
@a939638621 这是在框架里面的调用
```php
Flight::route('/weixin',function(){
	Overtrue\Wechat\Alias::register();
	$server = new WechatServer("xxxxxxxxxxxx", "xxxxx");
	$server->on('message', 'text', function($message) {
		return WechatMessage::make('text')->content($message->Content);
	});
	$result = $server->serve();
	echo $result;
});

Flight::start();
```
我感觉是nginx的问题

**Comment by a939638621** [comment]
@imyip  [服务器验证](https://github.com/overtrue/wechat/wiki/%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%AA%8C%E8%AF%81) 你看看这个wiki 的内容

**Comment by overtrue** [comment]
你在`echo $result;` 前把 `error_log("result: ".$result);` 写到日志看一下就知道了嘛，如果都没产生日志,那肯定是你的web服务器问题了
