### ISSUE TITLE
开放平台接收component_verify_ticket问题

### ISSUE THREAD

**Issue by orchie** [overtrue/wechat#1260]
## 我用的环境
测试环境 window7 线上centos7 
PHP 版本：
测试环境 7  线上环境 7.1
overtrue/wechat 版本：
4.0 使用composer安装 
composer require overtrue/wechat:~4.0 -vvv
是否使用了框架？框架名称：
TP5.1.16
## 问题及现象

**1.按照文档中写法 接收component_verify_ticket 无法正常返回**
正常情况 应该只输出 success
**2.没有对component_verify_ticket 进行缓存**
这一点是从 调用 wechat 的getPreAuthorizationUrl 方法 提示 
Credential "component_verify_ticket" does not exist in cache. 得知的。
并且查看缓存目录中 也没有任何文件

尝试了3种方法，分别使用了 wechat 和 文档中TP框架推荐的think-wechat

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

相关代码
基类
```
<?php
/**
 * 开放平台基类
 */
namespace app\openwechat\controller;
// use Naixiaoxin\ThinkWechat\Facade;
use EasyWeChat\Factory;

class Common
{
    public function __construct()
    {
        $config = [
            'app_id'  => '',
            'secret'  => '',
            'token'   => '',
            'aes_key' => '',
        ];
        $this->openPlatform = Factory::openPlatform($config);
        // $this->openPlatform = Facade::openPlatform();
    }
}

```
授权类
```
<?php
/**
 * 开放平台授权页
 */
namespace app\openwechat\controller;

class AuthorizerDelegate extends Common
{
    public function __construct()
    {
        parent::__construct();
    }
    /**
     * 授权页
     */
    public function index()
    {
        redirect($this->openPlatform->getPreAuthorizationUrl("https://{$_SERVER['HTTP_HOST']}/AuthorizerDelegate/callback"));
    }
    /**
     * 授权回调
     */
    public function callback()
    {
        $server = $this->openPlatform->server;
        //三种 返回方式
        //wechat文档写法
        //输出 HTTP/1.0 200 OK Cache-Control: no-cache, private Date: Sun, 17 Jun 2018 12:06:08 GMT success
        // return $server->serve();
        
        //安装了 https://github.com/qiqizjl/think-wechat
        //根据说明 尝试的方法
        //输出了 success 后 又尝试输出一个 boolean 被tp类型检测报错
        // $server->serve()->send();
        
        //由上述方法想到的临时解决方法 立即结束脚本
        //可以只输出 success 
        $server->serve()->send();die;
    }
}

```

截图
文档中默认的方法
![qq 20180617200750](https://user-images.githubusercontent.com/29848298/41507803-9d5b0ade-726c-11e8-8e2f-04950d5583c7.png)
使用think-wechat 并从readme中尝试的方法
![qq 20180617200818](https://user-images.githubusercontent.com/29848298/41507808-b4a336d0-726c-11e8-94c8-e3df5a7b5821.png)
接收tickets后 访问授权页  提示没有tickets
![qq 20180617202645](https://user-images.githubusercontent.com/29848298/41507812-c7c9fb68-726c-11e8-9384-3d4a43d71414.png)

如果你不提供相关的代码，我不会做任何应答，直接 close，感谢！

**Comment by mingyoung** [comment]
![image](https://user-images.githubusercontent.com/6228858/41507869-d38ebabe-726d-11e8-8b96-6c3e023e2cd6.png)

接收微信推送消息 `component_verify_ticket` 的代码有写了吗

**Comment by orchie** [comment]
![qq 20180617211454](https://user-images.githubusercontent.com/29848298/41508207-8406deda-7273-11e8-8c85-3287ce8aee8a.png)
如图 这是从easywechat官方文档 https://www.easywechat.com/docs/master/zh-CN/open-platform/server
截的图，
我在调试开放平台的第一步，获取ticket，所以就按照文档所说写入了这两行代码
SDK应该是会自动缓存ticket的

> SDK 默认会处理事件 component_verify_ticket ，并会缓存 verify_ticket

报错的图在上面已经贴上了 :sos: @mingyoung

**Comment by orchie** [comment]
这个 component_verify_ticket 不存在的问题找到了
1.不知道为啥 TP5.1框架下 easywechat 默认使用的 symfony 缓存 不起作用
好我用think-wechat 设置的 使用TP缓存
2.设置以后缓存还是没有的原因是 ： think-wechat 的 配置代码 键名写错了
在代码中使用的是 wechat.default.use_tp_cache
在配置文件中设置的是  wechat.defaults.use_tp_cache
配置文件中的default多了个s
去掉以后就好了
好我滚去think-wechat提issue了 :smile:  @mingyoung

**Comment by akayzhang** [comment]
我也遇到同样的问题，
环境：
php7.1    laravel 5.4
name     : overtrue/wechat
descrip. : 微信SDK
versions : * 4.1.23
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/overtrue/wechat.git 223d79b8f38a3ca93f499e9e80fcfefbfb0ad6d9
dist     : [zip] https://api.github.com/repos/overtrue/wechat/zipball/223d79b8f38a3ca93f499e9e80fcfefbfb0ad6d9 223d79b8f38a3ca93f499e9e80fcfefbfb0ad6d9
代码是这样写的：
`
$authCode = $request->get('code');
$openPlatform = app('wechat.open_platform');
$data = $openPlatform->handleAuthorize($authCode);
`
报错：
(1/1) RuntimeExceptionCredential "component_verify_ticket" does not exist in cache.

**Comment by w0k2y1** [comment]
现在怎么解决呢？有好的解决办法吗？

**Comment by wangschang** [comment]
> 现在怎么解决呢？有好的解决办法吗？

刚才也遇到了这个问题。
排查以下问题
1.是不是回调接口了
2.ticket是不是正常保存
