### ISSUE TITLE
希望发送模板消息能够达到一分钟1万条

### ISSUE THREAD

**Issue by maxwelldu** [overtrue/wechat#1261]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：3.3
是否使用了框架？框架名称：Lumen

## 问题及现象
现在模板消息发送一分钟能够达到3600左右，公司的业务需求是要能够达到一万以上，我们是做电商，有到货提醒，希望延迟小，不然用户来晚了没商品，用户体验非常不好

**Comment by maxwelldu** [comment]
如何设置调用接口的curl使用curl_multi的方式去调用

**Comment by overtrue** [comment]
@maxwelldu 抱歉，这个你需要自己的使用队列来做，SDK 内不会内置这类需求。
