### ISSUE TITLE
能把开放平台的小程序信息设置 接口加上吗

### ISSUE THREAD

**Issue by mygoodidea** [overtrue/wechat#1262]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：4
是否使用了框架？框架名称：无

## 问题及现象

搜了源码，好像这个接口 [小程序信息设置](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=21528465979XX32V&token=&lang=zh_CN) 没加，哪位兄弟给加上

**Comment by makzai** [comment]
设置类目涉及到证书上传好多东西不好搞..

**Comment by mygoodidea** [comment]
@makzai 个人或组织要证书，商业应该不需要吧？没实践过

**Comment by makzai** [comment]
@mygoodidea 现在直接后台操作不同类目都有不同证书要求

**Comment by mygoodidea** [comment]
@makzai 原来如此
