### ISSUE TITLE
使用php composer.phar require overtrue/wechat:~4.0 -vvv安装报错

### ISSUE THREAD

**Issue by linzhihua1989** [overtrue/wechat#1263]
## 我用的环境
nginx
PHP 版本：7.0.1
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：fastadmin

## 问题及现象

使用php composer.phar require overtrue/wechat:~4.0 -vvv安装报错
安装overtrue/wechat:~3.0 -vvv 会成功；

Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - symfony/options-resolver v3.4.11 requires php ^5.5.9|>=7.0.8 -> your PHP v
ersion (7.0.1) does not satisfy that requirement.
    - symfony/options-resolver v3.4.11 requires php ^5.5.9|>=7.0.8 -> your PHP v
ersion (7.0.1) does not satisfy that requirement.
    - symfony/options-resolver v3.4.11 requires php ^5.5.9|>=7.0.8 -> your PHP v
ersion (7.0.1) does not satisfy that requirement.
    - Installation request for symfony/options-resolver (locked at v3.4.11) -> s
atisfiable by symfony/options-resolver[v3.4.11].
Installation failed, reverting ./composer.json to its original content.

**Comment by overtrue** [comment]
报错已经说了，你的 PHP 版本不够：>= 7.0.8

**Comment by linzhihua1989** [comment]
我在一个空文件夹composer就可以下载下来，或者在thinkphp5都可以，就是fastadmin里面不行，是否可以通过修改什么配置来修正这个问题
