### ISSUE TITLE
开放平台的component_veirfy_ticket不能使用自定义缓存

### ISSUE THREAD

**Issue by chaegumi** [overtrue/wechat#1270]
## 我用的环境

PHP 版本：7.0.1
overtrue/wechat 版本：3.1
是否使用了框架？框架名称：laravel5.4

## 问题及现象

我这样配置了缓存之后，但是开放平台的component_veirfy_ticket在缓存中找不到

```php

	$cacheDriver = new RedisCache();

	// 创建 redis 实例
	$redis = new \Redis();
	$redis->connect(env('REDIS_HOST'), env('REDIS_PORT'));
	$redis->auth(env('REDIS_PASSWORD'));

	$cacheDriver->setRedis($redis);
        $this->options = [
            'open_platform' => [
            ],

            'oauth' => [
                'scopes' => ['snsapi_userinfo'],
                'callback'=> '/platformcallback'
            ],
	    'cache' => $cacheDriver
        ];
        $this->app = new Application($this->options);

```

**Comment by mingyoung** [comment]
确定有推送了 `component_verify_ticket` ？

**Comment by chaegumi** [comment]
···php

use Doctrine\Common\Cache\PredisCache;

$predis = app('redis')->connection();// connection($name), $name 默认为 `default`
$cacheDriver = new PredisCache($predis);

$app->cache = $cacheDriver;

```

用了这种方法之后，报别的错误:Doctrine/Common/Cache/PredisCache.php(39): unserialize('\x00\x00\x00\x02\x11\x9D11_NMhbeF...')

是因为有中文编码吗？

**Comment by chaegumi** [comment]
@mingyoung 有的，laravel的log记录到了

**Comment by chaegumi** [comment]
搜索不到答案

```php

[2018-06-23 18:00:39] local.ERROR: ErrorException: unserialize(): Error at offset 0 of 163 bytes in /home/app/apps/xxxx.com/vendor/doctrine/cache/lib/Doctrine/Common/Cache/PredisCache.php:39
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'unserialize(): ...', '/home/app/apps/...', 39, Array)
#1 /home/app/apps/xxxx.com/vendor/doctrine/cache/lib/Doctrine/Common/Cache/PredisCache.php(39): unserialize('\x00\x00\x00\x02\x11\x9D11_NMhbeF...')
#2 /home/app/apps/xxxx.com/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(78): Doctrine\Common\Cache\PredisCache->doFetch('[easywechat.ope...')
#3 /home/app/apps/xxxx.com/vendor/overtrue/wechat/src/Core/AccessToken.php(116): Doctrine\Common\Cache\CacheProvider->fetch('easywechat.open...')
#4 /home/app/apps/xxxx.com/vendor/overtrue/socialite/src/Providers/WeChatOpenPlatformProvider.php(119): EasyWeChat\Core\AccessToken->getToken()
#5 /home/app/apps/xxxx.com/vendor/overtrue/socialite/src/Providers/WeChatOpenPlatformProvider.php(96): Overtrue\Socialite\Providers\WeChatOpenPlatformProvider->componentAccessToken()
#6 /home/app/apps/xxx.com/vendor/overtrue/socialite/src/Providers/WeChatProvider.php(100): Overtrue\Socialite\Providers\WeChatOpenPlatformProvider->getTokenFields('081YNxRj2lScHG0...')
#7 /home/app/apps/xxx.com/vendor/overtrue/socialite/src/Providers/AbstractProvider.php(185): Overtrue\Socialite\Providers\WeChatProvider->getAccessToken('081YNxRj2lScHG0...')
#8 /home/app/apps/xxx.com/app/Http/Controllers/PlatformController.php(227): Overtrue\Socialite\Providers\AbstractProvider->user()

```

**Comment by chaegumi** [comment]
1) "[easywechat.open_platform.component_verify_ticket.wxf7c2dfadf5][1]"
 2) "[easywechat.open_platform.authorizer_refresh_tokenwxcf36268db5041135wxcf36268db5041135][1]"
 3) "[easywechat.open_platform.authorizer_access_tokenwx7b69f4862aae396dwx7b69f4862aae396d][1]"
 4) "[easywechat.open_platform.authorizer_access_tokenwx3f81cf3cbeab5eedwx3f81cf3cbeab5eed][1]"
 5) "[easywechat.open_platform.authorizer_access_tokenwx61693e00b8cd5522wx61693e00b8cd5522][1]"


保存到redis中的怎么是这样的

**Comment by chaegumi** [comment]
redis-cli中看到的是这样的。

GET [easywechat.open_platform.authorizer_refresh_tokenwx5a4a2d60090f8c5dwx5a4a2d60090f8c5d][1]
"\x00\x00\x00\x02\x11:refreshtoken@@@fPbx4rjHkEDJ24EfOMi1Zb7WpA24UN5oDhdD027fwQ8"

**Comment by mingyoung** [comment]
是这样的哦

**Comment by chaegumi** [comment]
好像找到原因了，

var_dump(preg_replace('/[\x00-\x1F\x80-\x9F]/u', '', '\x00\x00\x00\x02\x11_ticket@@@v8j49zgGuPg66m8c0C7r_NelJ9TehHBH56PXR1t3NZNnC7clMwMkgNsS3J7CJau7UoTilKWKNwirYwk19U8PxA'));

这个替换失败

    /**
     * Filter the invalid JSON string.
     *
     * @param \Psr\Http\Message\StreamInterface|string $invalidJSON
     *
     * @return string
     */
    protected function fuckTheWeChatInvalidJSON($invalidJSON)
    {
        return preg_replace('/[\x00-\x1F\x80-\x9F]/u', '', trim($invalidJSON));
    }

**Comment by mingyoung** [comment]
历史遗留问题吧，不要折腾了，用 4.0 版本吧 😅

**Comment by chaegumi** [comment]
@mingyoung 我倒是想愉快的用4.0，但是线上已经在跑的项目，要凌晨1两点才能替换，而且历史数据还要先跑完才能升级。

**Comment by chaegumi** [comment]
我估计得自己实现一些功能了

**Comment by chaegumi** [comment]
@mingyoung 

$cachekey = 'easywechat.open_platform.component_verify_ticket.' . $authorizerAppId .'';
var_dump($cachekey);
            $component_verify_ticket = $app->access_token->getCache()->fetch($cachekey);

这样不能自己获取component_verify_ticket

**Comment by mingyoung** [comment]
试试

```php
$app->open_platform->verify_ticket->getTicket();
```

**Comment by chaegumi** [comment]
我想到一个方案了，自己保存事件推送的ticket，自己用，不用easywechat保存的ticket

**Comment by waney** [comment]
name     : overtrue/wechat
descrip. : 微信SDK
keywords : sdk, wechat, weixin, weixin-sdk
versions : * 4.1.21


4.1.21也是这样啊

**Comment by huiyonghkw** [comment]
仿照：https://github.com/overtrue/laravel-wechat/blob/f8300dac610baae3736fcdeb1ea4ee17e2f1fac9/src/ServiceProvider.php#L93 这里：

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/1323776/180737605-e78ac0d2-0d24-4391-b805-516bc4b52de4.png">

在业务控制器中可以这样使用：
<img width="913" alt="image" src="https://user-images.githubusercontent.com/1323776/180737949-3f483ce2-9112-4cd8-9786-600363a3b633.png">


然后在`.env`中配置`redis`。是可以正常运行的

```php
CACHE_DRIVER=redis
```
