### ISSUE TITLE
是否存在XXE

### ISSUE THREAD

**Issue by ZhangQi77** [overtrue/wechat#1282]
## 问题及现象
微信昨天报出存在XXS,PHP代码中需要设置 libxml_disable_entity_loader(true);我看了源码没有发现这个设置，想问一下是否存在这个风险
详见：https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=23_5&pass_ticket=FFLrP9HSl1pS4zZHOn30Xr6tdp%2FUe387vNtIpcdcUx6HsQxETmP5bgntuta8k00b

**Comment by ZhangQi77** [comment]
不好意思，是XXE

**Comment by overtrue** [comment]
已经按文档修复被攻击可能，虽然新版的 simpleXML 拓展已经默认关掉了。
