### ISSUE TITLE
微信网页扫码支付出现XML解析存在的安全问题

### ISSUE THREAD

**Issue by liyuliang2013** [overtrue/wechat#1286]
## 我用的环境

PHP 版本：7.0.30
overtrue/wechat 版本：3.x
是否使用了框架？框架名称：Symfony2.8

## 问题及现象

https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=23_5

微信支付商户，最近暴露的XML外部实体注入漏洞(XML External Entity Injection，简称 XXE)，该安全问题是由XML组件默认没有禁用外部实体引用导致，非微信支付系统存在漏洞。

如果你在使用支付业务回调通知中，存在以下场景有使用XML解析的情况，请务必检查是否对进行了防范。

场景1：支付成功通知；
场景2：退款成功通知；
场景3：委托代扣签约、解约、扣款通知；
场景4：车主解约通知；

XXE漏洞需要你在代码中进行相应的设置，不同语言设置的内容不同，下面提供了几种主流开发语言的设置指引：
【PHP】
libxml_disable_entity_loader(true);

**Comment by overtrue** [comment]
#1282
