### ISSUE TITLE
多次遇到 accesstoken 无效的问题

### ISSUE THREAD

**Issue by justocean** [overtrue/wechat#129]
[Wechat]获取access_token时AppSecret错误，或者access_token无效。请开发者认真比对AppSecret的正确性，或查看是否正在为恰当的公众号调用接口

近一周使用您的 sdk，多次遇到这个问题。后来我将access_token、api_ticket、jsapi_ticket 的 expire_at 都改成了返回的 expire_in - 200 秒，也就是官方给出的 sdk 中的7000秒

今天又出现了这个问题，比较疑惑。

**Comment by overtrue** [comment]
- 1500吧

**Comment by justocean** [comment]
这里我觉得可能不是这个时间的问题。
我觉得有可能是并发导致写这个保存 accesstoken 的文件引起的。

因为您用的是 file_put_contents 这个函数，我建议是加上参数 LOCK_EX：

if (!file_put_contents($this->getCacheFile($key), serialize($data), LOCK_EX))
            throw new Exception('Access toekn 缓存失败');

同时我也在用 redis 来保存进行测试。

**Comment by overtrue** [comment]
你的并发多大？
