### ISSUE TITLE
粉丝信息返回为空

### ISSUE THREAD

**Issue by joinmm** [overtrue/wechat#1291]
## 我用的环境

PHP 版本：7.2.1
overtrue/wechat 版本：4.0
是否使用了框架？没有

## 问题及现象
 $app->user_tag->get($openid); 函数返回值有时候为空，手动测试是可以的，
```
$response = $client->request('GET', '/cgi-bin/user/info?access_token='.$token.'&openid='.$openid.'&lang=zh_CN');
$statusCode = $response->getStatusCode();
$body = $response->getBody()->getContents();
$body =  preg_replace('/[\x00-\x1F\x80-\x9F]/u', '', trim($body));
var_dump($body);
$user = json_decode($body,true);
```
昵称中存在   [\x00-\x1F\x80-\x9F]  导致 json_decode 出错

**Comment by overtrue** [comment]
@joinmm 昵称里有表情？我的系统里也有很多用户昵称带表情，正常啊

**Comment by joinmm** [comment]
我们的公众号粉丝有17万，批量拉取粉丝信息时总有失败的openid，最后定位到了具体的openid，一共有7个，使用 $app->user_tag->get($openid);  函数获取信息总是空的，自己写代码是可以获取到的，但是json_decode() 时错误代码为 JSON_ERROR_CTRL_CHAR ，使用 $body =  preg_replace('/[\x00-\x1F\x80-\x9F]/u', '', trim($body)); 过滤一下就OK了。
