### ISSUE TITLE
企业微信接收通讯录事件推送数据没有解密

### ISSUE THREAD

**Issue by yugihuang** [overtrue/wechat#1295]
## 我用的环境

PHP 版本：7.1.x
overtrue/wechat 版本：4.0.34
是否使用了框架？框架名称：laravel 5.6

## 问题及现象

企业微信接收通讯录事件推送数据没有解密.
调试后发现, 接收到url中已经不带encrypt_type=aes(不知道tx什么时候改的), 
导致ServerGuard中的方法isSafeMode为false, 不进行解密.

尝试在overtrue/wechat/src/Work/Server/Guard.php中添加
```
protected function isSafeMode(): bool
{
      return true;
}
```
后测试正常.

**Comment by overtrue** [comment]
已发版
