### ISSUE TITLE
微信公众号Token验证失败，laravel5.6环境

### ISSUE THREAD

**Issue by a645588** [overtrue/wechat#1297]
## 我用的环境

PHP 版本：7.2.5
overtrue/wechat 版本：~4.0
是否使用了框架？框架名称：Laravel5.6

## 问题及现象
 今天遇到一个坑，楞是瞎折腾了很久，所有都是按照文档做的，Token校验算法也完全确认并打印了，没有问题，微信就是报Token验证失败。折腾一下午，试了好多方式，发现缺少了**ob_clean()**（确认过了我的文件没有BOM），加上就马上验证通过了。仔细检查结果，抓取验证url到浏览器查看虽然算出的结果是一致的，但是查看浏览器源码就是发现多了一个换行。

```
        $app = app('wechat.official_account');
        $app->server->push(function ($message) {
            switch ($message['MsgType']) {
            //...
            }
        });

        // 在 laravel 中：
        $response = $app->server->serve();
        ob_clean();
        return $response;
```

**Comment by overtrue** [comment]
检查你的 index.php 开始的第一个字符，或者 routes/* 的文件里，开始是否误添加了空白内容
