### ISSUE TITLE
 素材管理 -- 部分图片下载失败

### ISSUE THREAD

**Issue by lazyou** [overtrue/wechat#13]
下载图片出现如下错误 ： 

有的图片能下载，有的图片不能下载的情况。
错误如下：
<code>
[2015-05-04 10:47:47] local.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in /var/www/meishenghuo/web/vendor/overtrue/wechat/src/Wechat/Utils/Http.php:228
<code/>

我的解决方法如下，但是不知道这样做对不（能解决部分图片不能下载问题）。

Wechat\Utils\Http.php的 request() 方法下 ：

 <code>$responseSplit = preg_split('/((?:\r?\n){2})/', $response['response']); </code>

正则分割 header和 body的时候出现了 body被拆分成两部分的情况(本该是 
 <p><code>$responseSplit = array(0=>"header信息"， 1=>"body信息"); </code> </p>
结果变成 
 <p> <code>$responseSplit = array(0=>"header信息", 1=>"body1信息", 2=>"body2信息"); </code>
)。 </p>
我把正则内的 \r 后面的 ? 问号去掉就能解决问题（不懂为什么）。

 <code> $responseSplit = preg_split('/((?:\r\n){2})/', $response['response']); </code>

**Comment by overtrue** [comment]
@lazyou 麻烦加一下QQ: 44294631
