### ISSUE TITLE
未认证公众号回复音乐music不成功

### ISSUE THREAD

**Issue by guoxiangke** [overtrue/wechat#1301]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：
是否使用了框架？框架名称：laravel

## 问题及现象

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

https://www.codecasts.com/discuss/php/easywechat-reply-how-music-news-1280
未认证公众号，没有权限上传（$app->material->uploadImage()）获取不到thumb_media_id for music
我随意写int数值，返回日志可以构造正确，但是“该公众号提供的服务出现故障。。。”
![image](https://user-images.githubusercontent.com/1160703/42692676-091b20ac-86df-11e8-8934-a26b1f2d8f8f.png)

log：
`[2018-07-13 20:58:26] NULL.DEBUG: Server response created: {"content":"<xml><MsgType><![CDATA[music]]></MsgType><Music><Title><![CDATA[歌曲名]]></Title><Description><![CDATA[歌曲描述]]></Description><MusicUrl><![CDATA[http://lywxaudio.*.com/2018/cw/cw180713.mp3?_upt=7664fb131531571455]]></MusicUrl><HQMusicUrl><![CDATA[http://lywxaudio.*.com/2018/cw/cw180713.mp3?_upt=7664fb131531571455]]></HQMusicUrl><ThumbMediaId>1234</ThumbMediaId></Music><ToUserName><![CDATA[o2VsiwQgPqqaRBPUVFsmpq1fNqsc]]></ToUserName><FromUserName><![CDATA[gh_aa9c2e621082]]></FromUserName><CreateTime>1531486706</CreateTime></xml>"}`

**Comment by overtrue** [comment]
随便写的 media_id 当然不行啊，这还用想么？

**Comment by guoxiangke** [comment]
亲，未认证的公众号 以下权限都没有，你是如果获得media_id的？而且据我之前用的东哥的sdk中，media_id是可选项 ，https://github.com/dodgepudding/wechat-php-sdk 
永久素材管理接口 |   | 未获得 |  
临时素材管理接口 |   | 未获得 |  
。最后，我修改Music.php 55行，comment掉，即可。虽然官方文档上写的是必须项，但实际上并不是！
