### ISSUE TITLE
小程序解密The given payload is invalid.

### ISSUE THREAD

**Issue by woann** [overtrue/wechat#1312]
## 我用的环境

PHP 版本：7.1.7
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：

## 问题及现象
微信小程序,解密,偶尔抛出The given payload is invalid.的异常,查看了easywechat的源码,排查后发现时解密出的结果为空字符串,所以抛出异常,这是什么情况?
![image](https://user-images.githubusercontent.com/25681022/43056146-22a7a8f2-8e6d-11e8-8def-117bc0eb3b50.png)

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

如果你不提供相关的代码，我不会做任何应答，直接 close，感谢！

**Comment by mingyoung** [comment]
检查你 session_key 的情况：

![image](https://user-images.githubusercontent.com/6228858/43058388-fb6cbfa4-8e79-11e8-93f2-7df67e006ceb.png)

**Comment by hotalo** [comment]
我也遇到了这个问题 ，我调试了各种情况，只要吧$this->pkcs7Unpad()这个函数去掉，
直接$decrypted = json_decode($decrypted, true);  就可以解析出来 不然json_decode会返回error4  语法错误。我看到小程序官方demo里面没有需要pkcs7。

**Comment by woann** [comment]
你现在去掉$this->pkcs7Unpad()好用了吗?出现问题没

**Comment by woann** [comment]
我好像不是这个问题,因为我这里偶尔解密出来的是空字符串,所以抛出异常
![image](https://user-images.githubusercontent.com/25681022/43114406-861915b4-8f31-11e8-93de-1fa6a48dfff9.png)
@hotalo

**Comment by hotalo** [comment]
@woann
![image](https://user-images.githubusercontent.com/18346591/43114594-66407056-8f32-11e8-9445-5a46c08dc239.png)
我现在是这样的  完美解决

**Comment by hotalo** [comment]
@woann 
![image](https://user-images.githubusercontent.com/18346591/43114637-8b3ce434-8f32-11e8-9b03-b0c45f0457c5.png)
我现在这样就完美解决，

**Comment by overtrue** [comment]
@mingyoung 帮忙看看？

**Comment by mingyoung** [comment]
@woann 基本都是 session_key 的时效性问题，https://github.com/overtrue/wechat/issues/1312#issuecomment-406948992 检查下你的登录逻辑？

**Comment by woann** [comment]
我现在的逻辑是，用户点击授权按钮，然后在回调里就获取到了加密的iv等字段，然后用wx.Login获取code。然后把加密字段和code一起传到后台。后台处理顺序是先用code获取sessionkey，然后用sessionkey和加密信息进行解密@mingyoung

**Comment by zacksleo** [comment]
code,iv, decryptedData 只能使用一次

**Comment by woann** [comment]
不是啊，现在改版是必须点击按钮，点击按钮走回调，回调里能得到加密信息，同时我在回调里调用wx.Login，不然我应该在什么位置调用wx.Login

**Comment by mingyoung** [comment]
onLaunch 调用不行？

woann <notifications@github.com>于2018年7月25日 周三下午10:51写道：

**Comment by forecho** [comment]
@woann 有可能是这个坑，参与 encryptedData 的 code，必须和服务端解密的 code 一致。

![image](https://user-images.githubusercontent.com/1725326/44021061-652a0472-9f16-11e8-8ed7-d5f0f57fe3a0.png)

**Comment by overtrue** [comment]
@woann 前端传递的信息是不可靠的。

**Comment by hglaravel** [comment]
怎么解决这个问题呢？？？

**Comment by hglaravel** [comment]
> 怎么解决这个问题呢？？？

已经解决了~~

**Comment by wskeee** [comment]
我也遇到一样问题！

**Comment by almas1992** [comment]
> 我也遇到一样问题！

以上说的解决方法都试过了？

**Comment by woann** [comment]
@almas1992 换个其他的包试试吧

**Comment by zacksleo** [comment]
session_key 每次都需要重新获取啊，以保证时效性

**Comment by almas1992** [comment]
> @almas1992 换个其他的包试试吧

我换包干哈，用法正确，不会出现这个问题

**Comment by almas1992** [comment]
> session_key 每次都需要重新获取啊，以保证时效性

不用每次都获取session_key，可以检测session_key是否有效，失效了再重新获取，小程序有提供了相关api的

**Comment by sunshinev** [comment]
我也遇到了这个问题，用户重新登录的时候，会把code和加密信息传递给后台进行用户登录注册
`getUserInfo: function(e) {
    wx.login({
      success: res => {
        // 发送 res.code 到后台换取 openId, sessionKey, unionId
        if (res.code) {
          // 上报数据
          wx.request({
            url: 'http://10.72.114.126/account-book/api/wxapp/login',
            data: {
              code: res.code,
              iv: e.detail.iv,
              encryptedData: e.detail.encryptedData
            },
            success: (res, statusCode, header) => {
              app.globalData.skey = res.data.data.skey
              app.globalData.openid = res.data.data.openid

            }
          })
        } else {
          console.log('登录失败！' + res.errMsg)
        }
      }
    })`


但是后台Easywechat偶发性报错
`
 // 通过code获取openid
        $miniProgram = EasyWeChat::miniProgram();
        $loginInfo   = $miniProgram->auth->session($code);


        if (!$loginInfo || !isset($loginInfo['openid']) || !isset($loginInfo['session_key'])) {
            throw new ApiException('小程序code获取登录信息失败' . $loginInfo['errmsg'] ?? '');
        }

        // 获取用户信息
        $data = $miniProgram->encryptor->decryptData($loginInfo['session_key'], $iv, $encryptedData);
`

**Comment by wangke568** [comment]
> @woann 我现在这样就完美解决，
> ![图片](https://user-images.githubusercontent.com/18346591/43114637-8b3ce434-8f32-11e8-9b03-b0c45f0457c5.png)

完美解决

**Comment by qq1059020841** [comment]
额 你们的解答图片我咋看不到 。。

**Comment by zhanghoo** [comment]
> > @woann 我现在这样就完美解决，
> > ![图片](https://user-images.githubusercontent.com/18346591/43114637-8b3ce434-8f32-11e8-9b03-b0c45f0457c5.png)
> 
> 完美解决

这个图片加载不出来, 可以粘贴一下么, 谢谢了.

**Comment by zhanghoo** [comment]
> @woann
> ![image](https://user-images.githubusercontent.com/18346591/43114637-8b3ce434-8f32-11e8-9b03-b0c45f0457c5.png)
> 我现在这样就完美解决，

这个图片加载不出来, 可以粘贴一下么, 谢谢了.

**Comment by overtrue** [comment]
更新版本就好了

**Comment by aoxiaoxi** [comment]
> 更新版本就好了

更新到哪个版本呢

**Comment by jcleng** [comment]
> 
> 
> @woann
> ![image](https://user-images.githubusercontent.com/18346591/43114637-8b3ce434-8f32-11e8-9b03-b0c45f0457c5.png)
> 我现在这样就完美解决，

```
"overtrue/wechat": "~4.1",也是这样,按照这个处理就可以了
```

**Comment by smallk1002** [comment]
> 更新版本就好了

依旧 还是会出现这样的问题

**Comment by Ynwaspectre** [comment]
依旧出现

**Comment by zhumanito** [comment]
依旧出现这个问题解决了吗？有没有解决这个问题的

**Comment by Aroad233** [comment]
> 依旧出现这个问题解决了吗？有没有解决这个问题的
更新到最新的包，然后
请求解密前先检测session_key的有效性，失败请重新获取最新的session，具体详见下方链接
https://developers.weixin.qq.com/miniprogram/dev/api/open-api/login/wx.checkSession.html
