### ISSUE TITLE
授权登录会偶尔出现curl error 35，发送模板消息偶尔出现curl error 28

### ISSUE THREAD

**Issue by sujianbin** [overtrue/wechat#1313]
## 我用的环境

PHP 版本：php7.0
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：thinkphp5.1
服务器环境：windows 2008 R2
## 问题及现象

1、在授权登录会偶尔出现curl35的错误，概率很低，一般都是隔天没访问，再次访问出现问题

代码：
![image](https://user-images.githubusercontent.com/17819634/43114447-b61e937e-8f31-11e8-99b4-20129e3ddf6a.png)
![image](https://user-images.githubusercontent.com/17819634/43114469-d596a5fc-8f31-11e8-9280-a38aa51cbe0b.png)

2、发送模板消息时偶尔出现curl28的错误，在微信端操作基本不出现，目前只发现在PC后台点击发送消息会出现此情况

代码：
                        $template_id = 'oq-ipVrPjsQwapgQq1CNZcAmk7eLv65K5RhuiwIwL_Y';
			$wechatLogic = new WechatLogic;
			$task = Db::name('orders_info')->alias('i')->field('i.staff_id,m.realname as member_name,j.create_time')->join('orders o','i.orders_id = o.id')->join('member m','o.member_id = m.id')->join('staff_orders_join j','j.orders_info_id = i.id')->where('i.id',$task_id)->find();
			$staff = Db::name('staff')->field('openid')->where('id',$task['staff_id'])->find();
			$data = [
				'first'    =>['恭喜您抢单成功','#173177'],
				'keyword1' =>[date('Y-m-d H:i:s',$task['create_time']),'#173177'],
				'keyword2' =>[$task['member_name'],'#173177'],
				'remark'   =>'如有疑问请联系我司客服，感谢您的支持!'
			];
			$url = request()->domain().'/staff.php/member/ordersdetail/id/'.$task_id.'.html';
			$wechatLogic->templateMessage($staff['openid'],$template_id,$data,$url);

              /**
		 * 发送模板消息
		 * @param  [type] $openid      [description]
		 * @param  [type] $template_id [description]
		 * @param  [type] $data        [description]
		 * @param  string $url         [description]
		 * @return [type]              [description]
		 */
		public function templateMessage($openid,$template_id,$data,$url = '')
		{
			$config = $this->getConfig();
	                $app = Factory::officialAccount($config);
			$app->template_message->send([
				'touser'      => $openid,
				'template_id' => $template_id,
				'url'         => $url,
				'data'        => $data
    		        ]);
		}

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

如果你不提供相关的代码，我不会做任何应答，直接 close，感谢！

**Comment by overtrue** [comment]
curl 28 是超时错误，你的服务器网络问题
