### ISSUE TITLE
不知道这算不算是个BUG

### ISSUE THREAD

**Issue by dindom999** [overtrue/wechat#133]
用的框架，无法连接数据库

<?php
class fwh extends CONTROLLER
{
use Overtrue\Wechat\Server;

$appId = 'wx3cf0f39249eb0e60';
$token = "overtrue";

$server = new Server($appId, $token);

$server->on('message', function($message){
$order_id=$message->Content;
$rs=$this->model('system')->fetch_row('orders',"order_id=".$order_id); // <==每次运行到这句就出错
return json_encode($rs);
});

echo $server->serve();
}

**Comment by a939638621** [comment]
.............. 

这个sdk 并不影响其他东西，

**Comment by a939638621** [comment]
另外你拍一下版 
```php

<?php
class fwh extends CONTROLLER
{
use Overtrue\Wechat\Server;

$appId = 'wx3cf0f39249eb0e60';
$token = "overtrue";

$server = new Server($appId, $token);

$server->on('message', function($message){
$order_id=$message->Content;
$rs=$this->model('system')->fetch_row('orders',"order_id=".$order_id); // <==每次运行到这句就出错
return json_encode($rs);
});

echo $server->serve();
}

```

**Comment by dindom999** [comment]
是不是回调函数里的原因

**Comment by a939638621** [comment]
@dindom999 你用sql 查询一下 ，或者用orm 输出一下 sql

**Comment by viko16** [comment]
php 的 Closure 里面使用外部的东西要用 use 喔，

```php
<?php
class fwh extends CONTROLLER
{
	use Overtrue\Wechat\Server;

	$appId = 'wx3cf0f39249eb0e60';
	$token = "overtrue";

	$server = new Server($appId, $token);

	$sysModel = $this->model('system');

	$server->on('message', function($message) use($sysModel){
	$order_id = $message->Content;
	$rs = $sysModel->fetch_row('orders',"order_id=".$order_id);
		return json_encode($rs);
	});

	echo $server->serve();
}
```

要不试下这样？

**Comment by dindom999** [comment]
不是数据的问题，我试过了；抱歉，我不知道怎么排版

**Comment by a939638621** [comment]
你这真叫做面向对象 ，这样都没有报错！！！！

**Comment by dindom999** [comment]
没有帖完整代码，呵呵，它是在一个Fuction里的

**Comment by a939638621** [comment]
[看完这个链接的东西再说话！！！](http://php.net/manual/zh/language.oop5.php)

**Comment by a939638621** [comment]
这个只能是你自己的问题 ，这么多人都没有问题！！！！

**Comment by dindom999** [comment]
这样解决了，谢谢
$sysModel = $this->model('system');

    $server->on('message', function($message) use($sysModel){
