### ISSUE TITLE
试了两次，真的不会用

### ISSUE THREAD

**Issue by shrekmaxi** [overtrue/wechat#134]
感觉这个项目是不是和菜鸟使用的是吧？能否给出更详细的使用指南呢？我跟着WIKI操作不下去......因为好多地方对于我这种新手来说简直是不知所云 ( ▼-▼ )
例如：
![image](https://cloud.githubusercontent.com/assets/5965221/10630757/c7396818-780b-11e5-803e-5f7eddc7f984.png)
zhe'
这里的意思是说要自己复制以上内容到一个新建的php文件里么？如此种种，不一而足....help

**Comment by a939638621** [comment]
你先能看懂 [这个](http://mp.weixin.qq.com/wiki/home/index.html) 之后再说这个sdk 的事情

**Comment by overtrue** [comment]
@shrekmaxi 学会php的用法以及微信开发基础是必须的。
