### ISSUE TITLE
如何获取获取微信授权页url

### ISSUE THREAD

**Issue by soeben** [overtrue/wechat#1341]
## 我用的环境

PHP 版本：7.2
overtrue/wechat 版本：4.0
框架名称：laravel

## 问题及现象
使用vue开发项目时想实现用户输入任意url进入页面时发起网页授权过程，由于vue的页面状态受控于前段路由，因此后端无法得知前端url中#后面的部分，也就无法在发起网页授权后跳回当前页面，现在想得到发起网页授权要调转到微信授权页的那个url但发现相关方法都是受保护的

## 希望得到的
获取微信授权页url

**Comment by makeup1122** [comment]
$app->oauth->redirect()->getTargetUrl();
