### ISSUE TITLE
小程序解密数据报错

### ISSUE THREAD

**Issue by lifeagin** [overtrue/wechat#1346]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：laravel

## 问题及现象
小程序，在使用session_key，iv，encryptedData解密获取用户信息的时候报错，报错位置代码：
overtrue\wechat\src\MiniProgram\Encryptor.php 文件43行
`throw new DecryptException('The given payload is invalid.');`：

`$decrypted = AES::decrypt(
            base64_decode($encrypted, false), base64_decode($sessionKey, false), base64_decode($iv, false)
        );

        $decrypted = json_decode($this->pkcs7Unpad($decrypted), true);

        if (!$decrypted) {
            throw new DecryptException('The given payload is invalid.');
        }

        return $decrypted;`

定位到AES::decrypt方法：
`return openssl_decrypt($cipherText, $method ?: self::getMode($key), $key, $option, $iv);`

我将第二个参数 `$method ?: self::getMode($key)`，改成：`"AES-128-CBC"`，解密成功。

我的参数如下：
`session_key:4bG6wrISgghTjDw+HMJTrA==

code:033ZVz181vZeMS1lwdY717hu181ZVz1S

iv:VP6o4+J71iKUHvAT/xj/ow==

encryptedData:bdgLZJDli2ri8KaearrbLlgvtEH+lNKiuJ1byV97xI4owuMyjitmFaW2/HR4COxx0OVWyMI4VMnG7kF7FnnhKt7vYvWdwd7kfiRk0+lRoYRJexqcjxQtCOtOTGGlNUQUIfREAhT+6asdhNUWu37dVFJFr2qNgFUWVEqzetXz4QmmwtbVkA57mGNod188tG/xpMVIao9elBIPAOuUeNKqMlA4aCToEgGFA1u3BFWceQuIiX2eSdWj+lJxCWLoxNtmh8G5zj4tlmn+b43T01k/MdqrScOaZF9ZqIRPLQN8EIkp4TS5NM8GvHwPdD/KZI69BxqdnujNFRuIktVNj/DAhycfEXNVs8rZvBa1sJ8OPYtxcwtqYOpq8yfo+skgQ4+yQ2U/5DfuasK4bcn+0GBBRwicBX+WWUZ3L2Cs9F15BkDYstcUPRJtWXZAJdZ0fq3Bssiqknp/R2VnzA55IYPBuRW5D/C+UDRLE0UVyj8FxWDd3H6Nkcnh2wofuYFMh+2O3dWAYoH1uTGV2nfWF1kuOw==
`

麻烦overtrue排查

**Comment by woann** [comment]
有效吗？后续正常使用没
