### ISSUE TITLE
备注一个在thinkphp5.0下的小问题

### ISSUE THREAD

**Issue by lanshe** [overtrue/wechat#1347]
文件：/overtrue/socialite/src/Providers/AbstractProvider.php

```
    protected function hasInvalidState()
    {
        if ($this->isStateless()) {
            return false;
        }

        $state = $this->request->getSession()->get('state');

        return !(strlen($state) > 0 && $this->request->get('state') === $state);
    }
```

其中

`        $state = $this->request->getSession()->get('state');`

改为

`      $state = $this->request->get('state');`

**Comment by overtrue** [comment]
> https://github.com/overtrue/socialite/blob/master/src/SocialiteManager.php#L16
> https://github.com/symfony/http-foundation/blob/master/Request.php#L707

**Comment by tyonly** [comment]
我也觉得有必要，在测试的时候，总是提示 get('state') 为null , php 报错

**Comment by tyonly** [comment]
还是不能去掉，改了 有更大的错误
