### ISSUE TITLE
好奇地问个问题，这项目的测试用例放在哪？

### ISSUE THREAD

**Issue by zswang** [overtrue/wechat#135]
难道是私有项目分支?

**Comment by overtrue** [comment]
@zswang 2.0的测试没写，3.0 在新的组织下进行中 https://github.com/easywechat 每个模块的测试都在自己项目下的tests目录，全部在travis-ci中进行测试

**Comment by zswang** [comment]
感谢解答

**Comment by overtrue** [comment]
@zswang :smile:
