### ISSUE TITLE
关于全局access_token获取和保存以及模板消息发送不稳定的疑惑

### ISSUE THREAD

**Issue by peterpan0708** [overtrue/wechat#1353]
## 我用的环境

PHP 版本：7.2.3
overtrue/wechat 版本：4.1
是否使用了框架？框架名称： yii2.0

## 问题及现象

项目有多台服务器，其中一台，用来跑计划任务，把模板消息打入队列中然后发送，但是现在的问题是，在发送模板消息的时候，相同的access_token，有时会出现模板消息发送不成功，报40001的错误码。经过考量，应该不是access_token失效的问题，因为，在模板消息发送失败后，我再次使用相同的access_token，模板消息依然可以发送成功，证明access_token在微信那边应该是可以验证通过的。请问，此种现象是否与多台服务器部署有easywechat服务，easywechat重复请求access_token有关？有什么解决方法吗？

感谢版主！

![image](https://user-images.githubusercontent.com/36805830/45008217-fc72c200-b033-11e8-9500-73c50c2cac9e.png)

**Comment by overtrue** [comment]
你是否有同样的机器在用同一个账号？

**Comment by overtrue** [comment]
多台服务器建议使用共享缓存，比如 redis

peterpan0708 <notifications@github.com>于2018年9月5日 周三上午9:23写道：

**Comment by peterpan0708** [comment]
@overtrue，我看了一下文档，文档中说如果替换默认缓存的话，要设置$app['cache']，那这样岂不是每次实例化app，都要设置一次？如果我自己维护access_token的话，是定时更新app['access_token']的值，还是每次调用实例的时候从redis里拿到access_token，然后执行$app['access_token']->setToken()？请问哪一种是比较可行的实践呢？ 

感谢版主。

**Comment by shjchen** [comment]
@overtrue  我们出现了请求 access_token 不稳定的现象。

情况如下：

1. 我们升级到 4.0 版本前，是没有报过请求 access_token 错误的现象的。
2. 在升级到4.0版本后，我们的服务器陆续出现 Request access_token fail: {"errcode":41002,"errmsg":"appid missing hint: [XXX]"} 。

平时每周三晚我们客户都会进行秒杀活动，推客会通过JSSDK去分享带参的链接，之前是没有问题的，但是从新版本发布后，我们通过 sentry 接收到了以上错误，appid 我们肯定是设置过了的，而且我们也进行了初步的日志记录，appid 和 appsecret 都是正常设置的，同时大量的请求，并不是每次请求都会产生以上错误，偶发性的。

我们也会去查找原因，同时也请帮忙看下，谢谢。

**Comment by peterpan0708** [comment]
感谢版主。 目前解决方法是我这边自己在redis里维护一份access_token。 然后将配置文件的retries设置为0。让easywechat使用我的access_token。

**Comment by peterpan0708** [comment]
有个小坑，大家注意一下。就是注意/tmp目录下，缓存文件夹的权限。如果权限不对应，会造成每发送一次模板消息，easywechat就重新请求一次access_token。

**Comment by overtrue** [comment]
@peterpan0708 客气了，不过一般 /tmp 都是要可写的，不然的话 PHP 跑起来也会有问题，比如上传文件。
