### ISSUE TITLE
PHP Fatal error:  Maximum execution time of 300 seconds exceeded in  CurlMultiHandler

### ISSUE THREAD

**Issue by guoxiangke** [overtrue/wechat#1356]
## 我用的环境

PHP 版本：php 7.2
overtrue/wechat 版本： "overtrue/laravel-wechat": "~4.0",
是否使用了框架？框架名称：laravel5.6

## 问题及现象
不知道怎么回事儿,使用docker部署, 响应简单文字消息正常,回复Music消息报错.
但是在腾讯云服务器上可以正常,
在本地开发+valet share也可以回复Music
但是,部署到aws东京区、新加坡区都不行,把30s改成300s也不行, 5s后,微信就提示公众号故障了.
有没有遇到过的?多谢.
PHP Fatal error:  Maximum execution time of 300 seconds exceeded in /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php on line 108

 
![image](https://user-images.githubusercontent.com/1160703/45273124-b1e5bf80-b4e3-11e8-9328-ba510f6e1808.png)

**Comment by overtrue** [comment]
这个就帮不上忙了，确实就是网络超时导致的，SDK 怎么修改也帮不上忙。

**Comment by guoxiangke** [comment]
多谢,

**Comment by guoxiangke** [comment]
看来腾讯的服务器还有墙啊 我滴娘啊

**Comment by guoxiangke** [comment]
现在我的腾讯服务器也遇到此类情况,我感觉咱们sdk好像有需要改进的地方,多谢🙏
Maximum execution time of 30 seconds exceeded in /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php on line 108
[Tue Oct 23 15:11:47.231414 2018] [php7:error] [pid 300] [client 172.17.0.3:45079] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php on line 108
[Tue Oct 23 15:11:47.875423 2018] [php7:error] [pid 301] [client 172.17.0.3:45085] PHP Fatal error:  Maximum execution time of 30 s

**Comment by guoxiangke** [comment]
好奇怪的现象,今天测试在腾讯云上又可以了,在google云上本来不可以,加上一句调试语句却可以了

**Comment by guoxiangke** [comment]
用return语句替代die都不行.

**Comment by overtrue** [comment]
这个不是 SDK 的问题，你需要自行解决
