### ISSUE TITLE
easywechat 4.0如何扫码支付，文档里只找到扫码支付成功后通知的用法，如何调用扫码支付却没有

### ISSUE THREAD

**Issue by kl521516** [overtrue/wechat#1361]
## 我用的环境

PHP 版本：7
overtrue/wechat 版本：4.0

## 问题及现象
easywechat 4.0如何扫码支付，文档里只找到扫码支付成功后通知的用法，如何调用扫码支付却没有

**Comment by mingyoung** [comment]
统一下单 trade_type = NATIVE

**Comment by overtrue** [comment]
https://www.easywechat.com/docs/master/zh-CN/payment/scan-pay
