### ISSUE TITLE
3.x的文档能修复下吗

### ISSUE THREAD

**Issue by winter-ice** [overtrue/wechat#1370]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：
3.1
是否使用了框架？框架名称：
thinkphp

## 问题及现象

3.x的文档有部分看不到了

**Comment by overtrue** [comment]
@winter-ice 哪部分看不了？

**Comment by winter-ice** [comment]
模板消息

**Comment by overtrue** [comment]
修好了。

**Comment by xiepeixing** [comment]
现在还是看不了3.x文档模板消息
