### ISSUE TITLE
单个接口监听多个商户号通知遇到的问题

### ISSUE THREAD

**Issue by NHZEX** [overtrue/wechat#1374]
## 我用的环境

PHP 版本：7.1.21
overtrue/wechat 版本：4.1.8
是否使用了框架？框架名称：ThinkPHP

##### 需要一个通知接口监听多个商户号的支付通知。
但是当一个通知来时系统并不知道当前通知应当加载哪个 mchid 与 appid 。
当前的想到两个解决方法：
- 调用 EasyWeChat\Kernel\Support\XML::parse() 预处理再实例，但会重复解析两次xml。
- 通过 url 自行传参，目前使用的方法。

希望能提供一个独立的 xml 解析方法与消息注入能力。

想象中的样子
```php
// 获取 xml 内容并解析 array (不进行签名验证)
$message = EasyWeChat\Factory::getNotifyMessage();
// 加载相关环境数据.....
$config = [.....];
// 实例化支付对象
$pay = EasyWeChat\Factory::payment($config);
// 注入消息 ($message 通过验证会传递到 Handler->$message)
$pay->handlePaidNotify($handle,  $message);
```

**Comment by overtrue** [comment]
在 URL 上带上订单ID即可：`http:://abc.com/notify/wechat/payment/1283949422222`

**Comment by NHZEX** [comment]
OK。那就继续URL传参走起

**Comment by overtrue** [comment]
> OK。那就继续URL传参走起

最省事的做法 😄
