### ISSUE TITLE
新文档提示超链接颜色的疑问

### ISSUE THREAD

**Issue by wangshantao** [overtrue/wechat#1376]
## 我用的环境

Chrome64

## 问题及现象

![image](https://user-images.githubusercontent.com/14883268/47066052-87400280-d217-11e8-8493-a1d4cc09902e.png)
感觉这个颜色看起很不舒服也不太容易看清，不知道是不是为了区分普通文本和超链接特地这样做的？

**Comment by overtrue** [comment]
嗯，这是一个开源产品，回头给他提个建议：https://github.com/saleem-hadad/larecipe
