### ISSUE TITLE
如何设置小程充的客服消息自动回复

### ISSUE THREAD

**Issue by kl521516** [overtrue/wechat#1377]
## 我用的环境

PHP 版本：php7
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：thinkphp

## 问题及现象
我已经微信小程序后台设置了消息推送，但是我在客服消息里发送后，没有任何回复，下面是我的代码，麻烦帮我看看是什么问题？

		$config = [
			'app_id' => "123",
			'secret' => "asdf",
			'token' => 'asdf',
			'aes_key' => 'asdf',
			'response_type' => 'array',
		];

		$app = Factory::miniProgram($config);

		$app->server->push(function ($message) {
			return "您好！欢迎使用!";
		});

		$response = $app->server->serve();

		// 将响应输出
		$response->send();
		exit;

**Comment by guider** [comment]
+1同问

**Comment by mingyoung** [comment]
客服消息需要调用接口发送：https://www.easywechat.com/docs/master/official-account/customer_service

自动回复的实现可以监听相应事件然后调用客服消息接口：https://www.easywechat.com/docs/master/official-account/server

**Comment by kl521516** [comment]
不好意思，我还是有如下疑问：

1、小程序的初始化对象应该用如下哪一个？
你们在服务端验证时用的是
$app = Factory::officialAccount($config);
而在小程序入门时又用的是如下方式，消息推送服务器验证这一块没有关于小程序介绍
$app = Factory::miniProgram($config);

2、你们文档里，小程序客服消息只有如下一行代码，我们需要更详细的介绍。
$service = $app->customer_service;

3、你说自动回复的实现可以监听相应事件，然后调用客服消息接口，按理我不监听事件，那就是所有事件都是回复一段文本，可是我用如下代码测试仍然没有任何回复。
		
$app = Factory::miniProgram($config);

$app->server->push(function ($message) {
		return "您好！欢迎使用 kmm!";
});

// 将响应输出
$response->send();
// exit;

4、客服消息要调用的接口，里面的$openid也不知道从哪里获取？

5、你们代码示例里一会儿是原生的，一会儿又是laravel，特别容易弄混

**Comment by longcnn** [comment]
搜遍了issues了，看来是个冷门啊，困扰了我好久，参看官方讨论区的此帖：
https://yike.io/threads/10
