### ISSUE TITLE
获取AcessToken等是否支持代理？

### ISSUE THREAD

**Issue by jiamuc** [overtrue/wechat#1378]
客户网络没有固定IP，想通过花生壳等NAT工具实现web服务，但是框架与微信服务器通信会使用动态分配的IP，加入白名单后，48小时IP就变了，还得重新加入白名单才能获取AcessToken。
设想如果支持代理，可以指定代理去访问微信服务器，代理的IP固定，
这样是否可行？
如果修改框架可以实现代理访问？
谢谢

## 我用的环境

PHP 版本：
overtrue/wechat 版本：
是否使用了框架？框架名称：

## 问题及现象

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

如果你不提供相关的代码，我不会做任何应答，直接 close，感谢！

**Comment by mingyoung** [comment]
看看这个功能能否满足你的需求？
https://github.com/mingyoung/easywechat-composer#server-delegation

**Comment by TheNorthMemory** [comment]
这个项目 [wechat-swagger](https://github.com/TheNorthMemory/wechat-swagger) 可以耍耍。

其中 `src/nginx.conf` /gateway 是个反向代理实现。。。
