### ISSUE TITLE
群发消息接口 send_ignore_reprint 参数，无法设置

### ISSUE THREAD

**Issue by oyrm** [overtrue/wechat#1379]
## 我用的环境

PHP 版本：7.2
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：laravel5.5

## 问题及现象
群发接口 send_ignore_reprint 参数，开发者可以对群发接口的 send_ignore_reprint 参数进行设置，指定待群发的文章被判定为转载时，是否继续群发。

MP群发接口数据格式：
{
   "filter":{
      "is_to_all":false,
      "tag_id":2
   },
   "mpnews":{
      "media_id":"123dsdajkasd231jhksad"
   },
    "msgtype":"mpnews",
    "send_ignore_reprint":0
}

easywechat文档：
$app->broadcasting->sendMessage(Message $message, array | int $to = null);
看代码没有找到传入send_ignore_reprint 或者自定义参数的方法。

不知道是我没找到设置的方法还目前版本没做这个支持，谢谢。

**Comment by overtrue** [comment]
```php
$app->broadcasting->sendMessage($message, $to, $attributes);
```

放到 `$attributes` 里即可。
