### ISSUE TITLE
开放平台监听器

### ISSUE THREAD

**Issue by FlashFeiFei** [overtrue/wechat#1380]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：overtrue/wechat

## 问题及现象

EasyWeChat\OpenPlatform\Server\Guard类
on方法中是event参数是字符串，dispatch方法的event也是字符串，
notify方法中两个字符串按位与，能进入循环体？还是哪里做了处理？
基类EasyWeChat\Kernel\ServerGuard
dispatch方法传递的event参数是经过转化，转化成int的

**Comment by overtrue** [comment]
@FlashFeiFei 字符串与整型都可以正常工作：
![image](https://user-images.githubusercontent.com/1472352/47342221-cbc71480-d6d5-11e8-9b75-efa4871213bc.png)

**Comment by FlashFeiFei** [comment]
哦，好的，明白了，非常感谢
