### ISSUE TITLE
新版文档字体太难看清楚了！

### ISSUE THREAD

**Issue by zxz054321** [overtrue/wechat#1381]
## 环境

- iMac (Retina 4K, 21.5-inch, Late 2015)
- Firefox 62.0.3 (64 位)

## 问题及现象

新版文档页面有这么一条css，将正文字体设置得非常细小，大家看着不觉得很累吗……
https://www.easywechat.com/docs/master/official-account/tutorial

```
font-weight: 300
```

如图：
![](https://ww1.sinaimg.cn/large/005YhI8igy1fwj4qdsxxqj31kw0zjwp6)

**Comment by mingyoung** [comment]
Mac 用户表示还好

![image](https://user-images.githubusercontent.com/6228858/47403547-75f97780-d77c-11e8-9c75-9f4ced818969.png)

**Comment by zxz054321** [comment]
> Mac 用户表示还好
> 
> ![image](https://user-images.githubusercontent.com/6228858/47403547-75f97780-d77c-11e8-9c75-9f4ced818969.png)

iMac+Firefox用户表示眼要瞎……

- iMac (Retina 4K, 21.5-inch, Late 2015)
- Firefox

**Comment by almas1992** [comment]
> Ubuntu 用户表示还好 

![huaban](https://user-images.githubusercontent.com/9382335/47404906-c6270880-d781-11e8-8897-313debff344b.png)

> 浏览器：Version 70.0.3538.67 (Official Build) (64-bit)
系统：Ubuntu 16.04 xenial

**Comment by overtrue** [comment]
🤣 我已经跟作者沟通过让他改掉默认细化的字体。。。

**Comment by zhlhuang** [comment]
还有左边菜单的高亮选中问题，每次点完之后又回到最顶部。
