### ISSUE TITLE
有关『网页授权』用户授权 state 参数的携带

### ISSUE THREAD

**Issue by WonlyCms** [overtrue/wechat#1382]
## 我用的环境
> Windows10 1803 开发机。PHP 7.2.*
PHP 版本：
overtrue/wechat 版本：
是否使用了框架？框架名称：
> **Laravel**
## 问题及现象
通过微信官方文档查阅可得知，当我们使用微信授权接口时，还可以额外添加 `state` 参数，但是我在相关的EaseWechat的相关文档和实践中都未能找到此参数的设置方式，因为有想直接通过统一的授权回调地址，根据此参数的不同来对业务进行不同的分发，所以请问能否实现。
- [微信公众平台](https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140842)
![0060lm7Tly1fwkkslyhtmj30yn08agm8\.jpg \(690×165\)](http://wx2.sinaimg.cn/mw690/0060lm7Tly1fwkkslyhtmj30yn08agm8.jpg)

```php
    public function __invoke()
    {
        $app = $this->getWechatApp();
        dd($app->oauth->scopes([]));
    }
```

**Comment by overtrue** [comment]
state 参数不是用来传递数据的，谢谢！请了解 OAuth 2 协议规范： https://tools.ietf.org/html/rfc6819
