### ISSUE TITLE
Trait '**EasyWeChatComposer\Traits\WithAggregator**' not found

### ISSUE THREAD

**Issue by dushu520** [overtrue/wechat#1384]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：最新版
是否使用了框架？框架名称：tp5

## 问题及现象
我在tp5中 $app = Factory::officialAccount($options);时显示以下错误
我这方面不熟悉，我找了很久都没有发现相关的文件或代码，请问是不是缺少文件了？

[1] ErrorException in ServiceContainer.php line 34
Trait '**EasyWeChatComposer\Traits\WithAggregator**' not found
namespace EasyWeChat\Kernel;

use EasyWeChat\Kernel\Providers\ConfigServiceProvider;
use EasyWeChat\Kernel\Providers\ExtensionServiceProvider;
use EasyWeChat\Kernel\Providers\HttpClientServiceProvider;
use EasyWeChat\Kernel\Providers\LogServiceProvider;
use EasyWeChat\Kernel\Providers\RequestServiceProvider;
**use EasyWeChatComposer\Traits\WithAggregator;**
use Pimple\Container;

/**
 * Class ServiceContainer.
 * 
* @author overtrue <i@overtrue.me>
 *
 * @property \EasyWeChat\Kernel\Config                 $config
 * @property \Symfony\Component\HttpFoundation\Request $request
 * @property \GuzzleHttp\Client                        $http_client
 * @property \Monolog\Logger                           $logger
 */
class ServiceContainer extends Container
{
    use WithAggregator;

**Comment by mingyoung** [comment]
请使用 composer 方式安装
