### ISSUE TITLE
sign的加密方式

### ISSUE THREAD

**Issue by fengyi1117** [overtrue/wechat#1390]
## 我用的环境

PHP 版本：7.2
overtrue/wechat 版本：4.0.22
是否使用了框架？框架名称：Laravel 5.5

## 问题及现象

现在要做一个微信分账的接口，但是接口要求sign的加密方式是HMAC-SHA256，而我在源码里看到的加密方式好像只有MD5，这个是Bug吗？还是需要通过其他的方式？？？
![Uploading image.png…]()

**Comment by overtrue** [comment]
请提供相关详细信息，链接

**Comment by fengyi1117** [comment]
好的！我先试试看！
