### ISSUE TITLE
2.0版本使用问题

### ISSUE THREAD

**Issue by Fackeronline** [overtrue/wechat#14]
2.0的AppSecret跑哪去了？怎么就变成了encodingAESKey？消息加密的密钥是必须的么？我记得AppSecret这个应用密钥是必须要的啊，1.0版本还有，2.0的版本怎么实例的时候就不用传了？现在用你2.0这类，微信老是未服务，我就纳闷那里奇怪，才发现这里好像有问题。求答复。。

**Comment by Fackeronline** [comment]
2.0的AppSecret跑哪去了？怎么就变成了encodingAESKey？消息加密的密钥是必须的么？我记得AppSecret这个应用密钥是必须要的啊，1.0版本还有，2.0的版本怎么实例的时候就不用传了？现在用你2.0这类，微信老是未服务，我就纳闷那里奇怪，才发现这里好像有问题。求答复。。

**Comment by overtrue** [comment]
@Fackeronline 2.0把服务分拆了，不再是一个 Wechat 类统一入口了，请参考 wiki 作对应的修改，服务端不需要 appSecret: [接收消息与回复](https://github.com/overtrue/wechat/wiki/%E6%8E%A5%E6%94%B6%E6%B6%88%E6%81%AF%E4%B8%8E%E5%9B%9E%E5%A4%8D), 其它比如 [自定义菜单](https://github.com/overtrue/wechat/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8F%9C%E5%8D%95) 还有其它服务基本就俩参数：appId, appSecret。
