### ISSUE TITLE
Server消息回复必须以事件方式吗？

### ISSUE THREAD

**Issue by iam993** [overtrue/wechat#140]
看了一下代码，如果要回复消息，必须使用server的on方法来驱动。

有没有一种方法，消息类型，内容等自己判断，然后通过类似
setReplyMessage ( Message::make ( 'text' )->content( 'test' ) );
最后使用echo $server->serve();

或者说直接replyMessage ( Message::make ( 'text' )->content( 'test' ) );

总感觉靠server的事件驱动回复有点过度封装了。

**Comment by overtrue** [comment]
@iam993 你在事件里做啥都行啊，没做啥封装啊。

**Comment by iam993** [comment]
$str = "test";
$server = new Server($this->appId, $this->token, $this->aeskey);
$server->on('message',function(){
	return Message::make('text')->content($str);
});
这样就不行。

那怎么在回调方法内方便的调用方法外的变量呢？

**Comment by overtrue** [comment]
http://php.net/manual/zh/functions.anonymous.php

```php
$foo = 1;
function ($xxx) use ($foo, $bar, ....其它)
```

**Comment by iam993** [comment]
我重构了你server这块，能实现了，但是不那么‘优雅’ ，勉强凑合用吧。
