### ISSUE TITLE
微信JSSDK版本问题

### ISSUE THREAD

**Issue by vancens002** [overtrue/wechat#1402]
## 问题及现象

目前官网的JSSDK使用的是微信1.2版本，而微信官方手册中已经更新了新的JSSDK相关接口

`<script src="http://res.wx.qq.com/open/js/jweixin-1.2.0.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" charset="utf-8">
    wx.config(<?php echo $app->jssdk->buildConfig(array('onMenuShareQQ', 'onMenuShareWeibo'), true) ?>);
</script>`

官方文档说明：

> 请注意，原有的 wx.onMenuShareTimeline、wx.onMenuShareAppMessage、wx.onMenuShareQQ、wx.onMenuShareQZone 接口，即将废弃。请尽快迁移使用客户端6.7.2及JSSDK 1.4.0以上版本支持的 wx.updateAppMessageShareData、updateTimelineShareData 接口。

**Comment by overtrue** [comment]
我的 SDK 里没有封装 JSSDK 的 js 部分代码，无需变更哈

**Comment by vancens002** [comment]
`<script type="text/javascript" charset="utf-8"> wx.config(jssdk->buildConfig(array('onMenuShareQQ', 'onMenuShareWeibo'), true) ?>); </script>``
在传入使用的接口时，新版本的微信，比如updateAppMessageShareData这个接口，wechat似乎不支持

**Comment by mingyoung** [comment]
请给出`似乎不支持`的依据 🧜‍♂️

**Comment by vancens002** [comment]
好的，谢谢回复，我在外面，回去后给你回复
