### ISSUE TITLE
客服消息发送前,怎么判断用户是否达到20条限制了呢?

### ISSUE THREAD

**Issue by guoxiangke** [overtrue/wechat#1426]
微信想用户发送客服消息,20之后就会报错.
![image](https://user-images.githubusercontent.com/1160703/49991465-1d946880-ffbc-11e8-82b9-045885b8f330.png)
我想如何在发送之前判断一下,是否限制了,如果限制了使用消息模版来发.
谢谢,

**Comment by milkmeowo** [comment]
![image](https://user-images.githubusercontent.com/22437128/50070561-6e4cd100-0209-11e9-8be4-e7a06bf85cdb.png)

https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1433747234

这应该是长时间没互动，或者取消关注，导致发送失败。

可以记录上次的活跃时间，也可以处理返回的错误码，做相应处理，例如 45015 就尝试用消息模板发送

**Comment by guoxiangke** [comment]
> ![image](https://user-images.githubusercontent.com/22437128/50070561-6e4cd100-0209-11e9-8be4-e7a06bf85cdb.png)
> 
> https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1433747234
> 
> 这应该是长时间没互动，或者取消关注，导致发送失败。
> 
> 可以记录上次的活跃时间，也可以处理返回的错误码，做相应处理，例如 45015 就尝试用消息模板发送

怎么样获取这个错误代码?我能在日志里看到,不知道程序如何截获,谢谢.

**Comment by milkmeowo** [comment]
> 怎么样去获取错误码，不知道如何去截获

这...我真的不知道怎么回你好了...

你调用方法就有返回，返回的信息里面就有相应的数据

```php
use EasyWeChat\Kernel\Messages\Text;

$message = new Text('Hello world!');

// 开发的时候可以自己尝试一下调试，别人无法告诉你答案，只有你自己去实践才能验证的你的问题。
// 这里获取到的 result 就是微信返回的信息，和你在日志里面看到的是一样的。
$result = $app->customer_service->message($message)->to($openId)->send();

// 敢不敢打印一下 $result 看看内容
var_dump($result);
// {"errcode":45015,"errmsg":"response out of time limit or subscription is canceled hint: [G6cObA05284126]"}
// {"errcode":0,"errmsg":"ok"}

// 看了内容你就可以获取你想要的东西了
$errCode = $result['errcode'];

```
**记住多去大胆尝试，相信你的做法是对的，或者是往对的方向去靠拢的。**
@guoxiangke 问题解决了就关了这个 issues 吧

**Comment by guoxiangke** [comment]
多谢哈
