### ISSUE TITLE
发视频消息总返回 -1

### ISSUE THREAD

**Issue by linb** [overtrue/wechat#143]
微信抽风还是怎么着？

发视频消息有时候返回 -1，10月以前从来没有发生过。现在是时好时坏。

错误：
[29-Oct-2015 18:24:48 Asia/Shanghai] [Wechat][-1] system error hint: [ZpmEGA0343ent1]
[29-Oct-2015 18:25:35 Asia/Shanghai] [Wechat][-1] system error hint: [7_r0390ent2]
[29-Oct-2015 18:26:04 Asia/Shanghai] [Wechat][-1] system error hint: [PYgQJa0419ent3]

代码：

    // 给用户发视频消息
    // 这里 $uploadedMediaId 已经上传视频成功了, 用户 $openId 刚刚给本公众号发过视频消息
    try{
          $userService = new Staff(WECHAT_APPID, WECHAT_SECRET);
          $message = Message::make("video")->media_id($uploadedMediaId)
                //->thumb_media_id($thumbnialMediaId)
                 ->title("视频表情")
                 ->description("人人来原创");
          $userService->send($message)->to($openId);
    }catch(Exception $e){
          $errMsg = $e->getMessage();
    }

**Comment by liyunfang** [comment]
我想问个问题，微信素材能直接上传到第三方存储不？ 比如把微信的临时图片不经过下载到服务器直接上传到七牛。

**Comment by linb** [comment]
想知道发视频消息总返回 -1 是微信的问题还是库的问题？

**Comment by overtrue** [comment]
@linb 微信的问题
