### ISSUE TITLE
laravel5.6+easywechat做open_platform时，生成和调用component_verify_ticket缓存在两个不同缓存系统BUG！

### ISSUE THREAD

**Issue by wiwind** [overtrue/wechat#1431]
## 我用的环境

PHP 版本：7.2
overtrue/wechat 版本：最新版
是否使用了框架？框架名称：laravel

## 问题及现象
wechat.config中开启use_laravel_cache = true 的时候，easywechat默认的路由获取component_verify_ticket用的是laravel的缓存，比如是redis缓存，会写入到redis缓存。
但是在调用默认的$open_platform->handleAuthorize($auth_code)的方法的时候，这个里面的缓存调用的默认的symfony缓存，并不会去调用laravel缓存，导致api消息接受失败，望官方及时修复。

**Comment by mingyoung** [comment]
`composer info overtrue/wechat` 看看

**Comment by wiwind** [comment]
> `composer info overtrue/wechat` 看看

name     : overtrue/wechat
descrip. : 微信SDK
keywords : sdk, wechat, weixin, weixin-sdk
versions : * 4.1.15
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/overtrue/wechat.git 438057687bfd47d75413c7df32a698c72be751c1
dist     : [zip] https://api.github.com/repos/overtrue/wechat/zipball/438057687bfd47d75413c7df32a698c72be751c1 43805768
7bfd47d75413c7df32a698c72be751c1
names    : overtrue/wechat

**Comment by overtrue** [comment]
@mingyoung

**Comment by mingyoung** [comment]
@wiwind 我这边暂时重现不了，请问问题现在解决没？没有的话留个 QQ，我加你看看

**Comment by LiHouse** [comment]
@mingyoung 我也遇到同样的问题望官网解决

**Comment by wiwind** [comment]
@mingyoung 我没用laravel缓存就好使了-。-

**Comment by LiHouse** [comment]
@wiwind wechat.config中开启use_laravel_cache = true 是完全没有的？

**Comment by wiwind** [comment]
@LiHouse 如果你开启了，你会发现$open_platform->handleAuthorize($auth_code) 调用的缓存不会走laravel缓存，导致你获取不到component_verify_ticket缓存，建议暂时关闭。

**Comment by wqj97** [comment]
现在还是有这个问题, laravel5.7
name : overtrue/wechat
descrip. : 微信SDK
keywords : sdk, wechat, weixin, weixin-sdk
versions : * 4.1.15

**Comment by overtrue** [comment]
我觉得有必要贴一下你的代码的写法，如果你不用默认的方式，而是手动实例化肯定不会默认用配置里的缓存方式。

**Comment by keller31** [comment]
也遇到这个问题 database.php 中 redis缓存default 和cache 设置为不同的 database 时会有此问题
@overtrue

**Comment by mingyoung** [comment]
刚从坑里出来……

我的 `.env` 设置了 `CACHE_DRIVER=redis`，HTTP 下请求是读取到 `redis` 的，但是在 `queue:work` 下读取到的是 `file` 而不是 `redis`。
![image](https://user-images.githubusercontent.com/6228858/67285281-dc3ce580-f509-11e9-9af3-65c55228c7be.png)

我的解决方法：`php artisan config:cache`，这样在哪个环境下都可以读取到正确的值了

**-- 因开发环境差异，非最终解决方案。**
