### ISSUE TITLE
Traits\HasHttpRequests::getHandlerStack 调用 HandlerStack::create 支持透传 $handler 参数

### ISSUE THREAD

**Issue by guoxiaod** [overtrue/wechat#1433]
## 我用的环境

PHP 版本： PHP 7.2
overtrue/wechat 版本：最新版本
是否使用了框架？框架名称：没有使用其他的框架

## 问题及现象

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

如果你不提供相关的代码，我不会做任何应答，直接 close，感谢！

EasyWeChat\Kernel\Traits\HasHttpRequests::getHandlerStack() 方法中，如下的代码中

    public function getHandlerStack(): HandlerStack
    {
        if ($this->handlerStack) {
            return $this->handlerStack;
        }

        $this->handlerStack = HandlerStack::create();

        foreach ($this->middlewares as $name => $middleware) {
            $this->handlerStack->push($middleware, $name);
        }

        return $this->handlerStack;
    }

调用 HandlerStack::create() 方法的时候，是否可以修改以支持透传 $handler 给 create 方法。

**Comment by overtrue** [comment]
麻烦提供一下场景。

**Comment by limingxinleo** [comment]
https://github.com/overtrue/wechat/pull/1455

看看这个pr满足你的条件么
