### ISSUE TITLE
使用easyswoole框架,配置公众号,一直报错,token验证失败

### ISSUE THREAD

**Issue by LMFName** [overtrue/wechat#1434]
## 我用的环境

PHP 版本：7.3
overtrue/wechat 版本：4
是否使用了框架？框架名称：easyswoole

## 问题及现象

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

配置公众号,一直报错,token验证失败

代码如下:
`$config = [
            'app_id' => 'xxx',
            'secret' => 'xxx',
            'token' => 'bmit2018',
            'response_type' => 'array',
        ];
        $app = Factory::officialAccount($config);
        $server = $app->server;
        $response =$server->serve();
        $content = $response->send()->getContent();
        return $this->response()->write($content);`
初始配置公众号时候,只会返回success;
后进入调试得知:
在ServerGuard.php 的validate方法里面,request获取的值为空:

` public function validate()
  {
       var_dump($this->app['request']->get('signature'));
       var_dump($this->app['request']->get('timestamp'));
      var_dump($this->app['request']->get('nonce'));
....
`

如果你不提供相关的代码，我不会做任何应答，直接 close，感谢！

**Comment by overtrue** [comment]
请找对方框架咨询，这边不受理任何非 EasyWeChat 自身在 PHP 标准环境下的问题。如果您使用了其它拓展或者二次封装，请找相关人员提问，谢谢！
