### ISSUE TITLE
使用微信开放平台（第三方平台代公众号提供服务）回复消息提示Messages safe mode is enabled

### ISSUE THREAD

**Issue by Jackson-z6** [overtrue/wechat#1437]
## 我用的环境

PHP 版本：7
overtrue/wechat 版本：
是否使用了框架？框架名称：thinkphp5

## 问题及现象
使用微信开放平台（第三方平台代公众号提供服务）回复消息提示Messages safe mode is enabled
打印的日志截图
![image](https://user-images.githubusercontent.com/46042141/50327804-779cad00-052b-11e9-80b9-80930ffd061a.png)
程序代码
![image](https://user-images.githubusercontent.com/46042141/50327850-b03c8680-052b-11e9-90b3-071fa89bfdd1.png)

**Comment by mingyoung** [comment]
有什么问题？

**Comment by Jackson-z6** [comment]
文件位置：src/Kernel/ServerGuard.php
![image](https://user-images.githubusercontent.com/46042141/50328851-c3e9ec00-052f-11e9-9277-1e5622cb0317.png)
![image](https://user-images.githubusercontent.com/46042141/50328870-d532f880-052f-11e9-9c56-f17977afc2df.png)
在微信开放平台中创建第三方应用，使用第三方应用代替公众号接收回复消息会提示Messages safe mode is enabled
