### ISSUE TITLE
微信客服发送单图文消息接口变动了吗?

### ISSUE THREAD

**Issue by guoxiangke** [overtrue/wechat#1443]
前天发送客服单图文样式和今天不一样,
今天变成转发好友的样式了.
有遇到过的吗?腾讯也没有通知.
![image](https://user-images.githubusercontent.com/1160703/50543338-cb388600-0c10-11e9-9d93-88a77bf6e2c2.png)

**Comment by mingyoung** [comment]
与接口无关，可能展示形式变了吧
