### ISSUE TITLE
新发布的 4.1.16 产品环境出错

### ISSUE THREAD

**Issue by bolechen** [overtrue/wechat#1447]
## 我用的环境

PHP 版本：7.2.11
overtrue/wechat 版本：4.1.15
是否使用了框架？框架名称：Laravel 5.5-LTS

## 问题及现象
今天看版本更新了，就把产品环境升级了下，其它代码没动的情况下报错如下，回滚到 4.1.15 后正常

`
[2019-01-06 23:24:39] production.ERROR: Failed to cache jssdk ticket. {"exception":"[object] (EasyWeChat\\Kernel\\Exceptions\\RuntimeException(code: 0): Failed to cache jssdk ticket. at /var/www/releases/77/vendor/overtrue/wechat/src/BasicService/Jssdk/Client.php:105)
[stacktrace]
#0 /var/www/releases/77/vendor/overtrue/wechat/src/BasicService/Jssdk/Client.php(134): EasyWeChat\\BasicService\\Jssdk\\Client->getTicket()
#1 /var/www/releases/77/vendor/overtrue/wechat/src/BasicService/Jssdk/Client.php(55): EasyWeChat\\BasicService\\Jssdk\\Client->configSignature()
#2 /var/www/releases/77/app/Http/Controllers/WeChatController.php(145): EasyWeChat\\BasicService\\Jssdk\\Client->buildConfig(Array, false)
#3 /var/www/releases/77/app/Http/Controllers/ShopController.php(39): App\\Http\\Controllers\\WeChatController->jssdk(Object(App\\Models\\Shop), false)
#4 [internal function]: App\\Http\\Controllers\\ShopController->shop(Object(App\\Models\\Shop), '564c1396-d81f-4...')
#5 /var/www/releases/77/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#6 /var/www/releases/77/vendor/laravel/framework/src
...
`

**Comment by bolechen** [comment]
直接用数组配置来调用的，调用方式如下

```php
    //EasyWechat init
    public function getApp(Shop $shop)
    {
        $config = $shop->getConfig();
        return \EasyWeChat\Factory::officialAccount($config);
    }
```

**Comment by mingyoung** [comment]
这个是缓存写入失败。你检查一下缓存是不是没权限写入？

**Comment by bolechen** [comment]
> 这个是缓存写入失败。你检查一下缓存是不是没权限写入？

问题是啥也没动，回滚到旧版本就好了，我再部署个环境测试一下，感谢回复

**Comment by mrchenzifan** [comment]
@bolechen  请问下你旧版本是什么

**Comment by mingyoung** [comment]
@luozhenyu @hui1943 

检查缓存是否能成功写入吧，这才是问题的根源

**Comment by overtrue** [comment]
@hui1943 @bolechen @luozhenyu 对不住各位，不细心所致。还请更新到 4.1.17

**Comment by mingyoung** [comment]
😅

**Comment by overtrue** [comment]
无回复就关闭了哈

**Comment by bolechen** [comment]
@hui1943 @luozhenyu 你们好了吗？我这里好像还是不行…… 不知道问题在哪，4.1.17 也报错，只有 4.1.15 正常 @overtrue 

![img_2302](https://user-images.githubusercontent.com/195015/51271520-c0e4fd00-1a02-11e9-8565-e7e16e25445a.PNG)

**Comment by luozhenyu** [comment]
更新到最新版之后一切正常了，你测一测缓存能不能写入

**Comment by bolechen** [comment]
改成下面的写法后一切正常，供参考

```php
    /**
     * EasyWechat init
     *
     * @return EasyWeChat
     **/
    public function getApp(Shop $shop)
    {
        $config = $shop->getConfig();
        $app = \EasyWeChat\Factory::officialAccount($config);

        //下面两句加上就正常了
        $cache = new \Symfony\Component\Cache\Simple\FilesystemCache('', 0, storage_path('framework/cache/data'));
        $app->rebind('cache', $cache);

        return $app;
    }
```

**Comment by overtrue** [comment]
所以就是你的 PHP 临时目录写入失败咯？因为默认是 PHP 的临时目录：https://github.com/symfony/symfony/blob/4.2/src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php#L29

**Comment by bolechen** [comment]
> 所以就是你的 PHP 临时目录写入失败咯？因为默认是 PHP 的临时目录：https://github.com/symfony/symfony/blob/4.2/src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php#L29

是的，之前的版本一直是写入失败的，没抛出错误一直发现不了。 :'(

**Comment by overtrue** [comment]
@bolechen 哈哈

**Comment by overtrue** [comment]
@bolechen 这是我的锅
