### ISSUE TITLE
关于accessToken出现Failed to cache access token.的问题

### ISSUE THREAD

**Issue by mikeshoes** [overtrue/wechat#1450]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：4.1.16
是否使用了框架？框架名称：larvarl 5.5.44

第一次获取accessToken缓存throw exception

      $ok = $this->getCache()->set($this->getCacheKey(), [
            $this->tokenKey => $token,
            'expires_in' => $lifetime,
        ], $lifetime - $this->safeSeconds);

        if (!$ok) {
            throw new RuntimeException('Failed to cache access token.');
        }

关于此段代码，查阅larval 源码发现 如果使用larval 自己的缓存 此处是没有返回值得即ok永远是null
然后就抛出异常了，请查阅谢谢。

![image](https://user-images.githubusercontent.com/19601201/50902983-6f170280-1457-11e9-9af9-1254e460898a.png)

**Comment by guoxiangke** [comment]
正要问这个问题呢

**Comment by calchen** [comment]
感谢，刚好遇到这个问题，结果发现一个小时前修复了

**Comment by overtrue** [comment]
@guoxiangke @calchen  抱歉。

**Comment by calchen** [comment]
> @guoxiangke @calchen 抱歉。

感谢提供这么好用的微信组件🙏
