### ISSUE TITLE
指定文件名生成小程序码建议不要自动增加扩展文件名

### ISSUE THREAD

**Issue by chao** [overtrue/wechat#1452]
https://github.com/overtrue/wechat/blob/fc9ad9b3e0cfc7470352e5f7ab4ac333cfe37188/src/Kernel/Http/StreamResponse.php#L79

如果调用`StreamResponse`的`saveAs`方法给的第二个参数`$filename`没有扩展名时会自动增加文件扩展名。这个没什么必要，否则建议在文档中描述一下。

**Comment by overtrue** [comment]
可是，图片一般会指定后缀吧？

**Comment by overtrue** [comment]
您这边是什么场景不加后缀呢？

**Comment by chao** [comment]
是这样的。因为我要把图片保存到S3上去，但是这个`SteamResponse`没有办法返回图片内容（理想的方式是返回一个PSR-7的`StreamInterface`实现），所以我把图片先存在本地的临时文件夹再拷贝到S3。

我通过uniqid 生成了一个随机字符串作为文件名，使用`saveAs`的方法保存成功，但是在读取时候却说找不到这个文件。后来才发现自动增加了扩展名。这个是我没想到的，按理说和一般的saveAs方法也不太一样。

考虑到现在框架使用的人不少，现在改掉这个功能可能存在风险，建议增加第三个参数设置是否自动增加扩展名，或者修改下文档提醒下开发者。

感谢开发的SDK，用了好几年了。设计的还是很好，希望能更上一层楼。

**Comment by overtrue** [comment]
@chao 获取文件内容：`$steam->getBody()->getContents()`

**Comment by overtrue** [comment]
或者 `$steam->getBodyContents()`
