### ISSUE TITLE
composer 要求PHP版本与依赖包不符导致报错

### ISSUE THREAD

**Issue by kousuutetu** [overtrue/wechat#1459]
## 我用的环境

PHP 版本：7.0.x
overtrue/wechat 版本：4.x
是否使用了框架？框架名称：

## 问题及现象

![image](https://user-images.githubusercontent.com/5842445/51656990-ed3de200-1fdd-11e9-8178-e5a7b889d521.png)

![image](https://user-images.githubusercontent.com/5842445/51657005-fa5ad100-1fdd-11e9-8367-0e69e9761360.png)

如果你不提供相关的代码，我不会做任何应答，直接 close，感谢！

**Comment by overtrue** [comment]
```bash
$ composer require symfony/http-foundation:~3.4
```
