### ISSUE TITLE
EasyWeChat\Kernel\Exceptions\Exception: Invalid request XML. in vendor/overtrue/wechat/src/Payment/Notify/Handler.php:141

### ISSUE THREAD

**Issue by talentant** [overtrue/wechat#1473]
## 我用的环境

PHP 版本：7.2.10
overtrue/wechat 版本：4.1.17
是否使用了框架？框架名称：yii2

## 问题及现象

微信支付完成通知，出现上述问题

**Comment by overtrue** [comment]
看一下推送的 xml 原文

**Comment by talentant** [comment]
原文是在`easywechat.log`这个文件里吗？

**Comment by overtrue** [comment]
@talentant 看一下吧，如果没有的话你就在这个异常抛出的地方加一下日志记到文件里然后贴给我，因为你还真是头一个报这个错的。

**Comment by talentant** [comment]
easywechat.log 没有查找到对应的原文，目前暂时只出现两次，等待下次出现这个情况再提交反馈

**Comment by overtrue** [comment]
@talentant 嗯，可以在报错位置加一个日志记录，以便于下次捕捉现场。

**Comment by talentant** [comment]
@overtrue 明白！

**Comment by fenghoer** [comment]
你好，我也碰到了同样的问题，微信回调的数据如下：
<xml><appid><![CDATA[wx7aa788c4d12cf3a8]]><\/appid>\n<attach><![CDATA[{\"order_number\":\"txg15571327012786178\"}]]><\/attach>\n<bank_type><![CDATA[CFT]]><\/bank_type>\n<cash_fee><![CDATA[1]]><\/cash_fee>\n<fee_type><![CDATA[CNY]]><\/fee_type>\n<is_subscribe><![CDATA[Y]]><\/is_subscribe>\n<mch_id><![CDATA[1530741181]]><\/mch_id>\n<nonce_str><![CDATA[5ccff59d44224]]><\/nonce_str>\n<openid><![CDATA[o7J0X1vaHpr3MS87iZU140xpLTdY]]><\/openid>\n<out_trade_no><![CDATA[txg15571327012786178]]><\/out_trade_no>\n<result_code><![CDATA[SUCCESS]]><\/result_code>\n<return_code><![CDATA[SUCCESS]]><\/return_code>\n<sign><![CDATA[561EEF820FC9BE9BDEAD6EACE21B98CC]]><\/sign>\n<time_end><![CDATA[20190506165146]]><\/time_end>\n<total_fee>1<\/total_fee>\n<trade_type><![CDATA[JSAPI]]><\/trade_type>\n<transaction_id><![CDATA[4200000293201905066080264798]]><\/transaction_id>\n<\/xml>

**Comment by fenghoer** [comment]
<xml><appid><![CDATA[wx7aa788c4d12cf3a8]]><\/appid>\n<attach><![CDATA[{\"order_number\":\"txg15571327012786178\"}]]><\/attach>\n<bank_type><![CDATA[CFT]]><\/bank_type>\n<cash_fee><![CDATA[1]]><\/cash_fee>\n<fee_type><![CDATA[CNY]]><\/fee_type>\n<is_subscribe><![CDATA[Y]]><\/is_subscribe>\n<mch_id><![CDATA[1530741181]]><\/mch_id>\n<nonce_str><![CDATA[5ccff59d44224]]><\/nonce_str>\n<openid><![CDATA[o7J0X1vaHpr3MS87iZU140xpLTdY]]><\/openid>\n<out_trade_no><![CDATA[txg15571327012786178]]><\/out_trade_no>\n<result_code><![CDATA[SUCCESS]]><\/result_code>\n<return_code><![CDATA[SUCCESS]]><\/return_code>\n<sign><![CDATA[561EEF820FC9BE9BDEAD6EACE21B98CC]]><\/sign>\n<time_end><![CDATA[20190506165146]]><\/time_end>\n<total_fee>1<\/total_fee>\n<trade_type><![CDATA[JSAPI]]><\/trade_type>\n<transaction_id><![CDATA[4200000293201905066080264798]]><\/transaction_id>\n<\/xml>

**Comment by fenghoer** [comment]
[wxPay] 2019-05-06 17:35:45 [message] {"error":"wxPayCallback: start!","data":"<xml><appid><![CDATA[wx7aa788c4d12cf3a8]]><\/appid>\n<attach><![CDATA[{\"order_number\":\"txg15571332943298494\"}]]><\/attach>\n<bank_type><![CDATA[CFT]]><\/bank_type>\n<cash_fee><![CDATA[1]]><\/cash_fee>\n<fee_type><![CDATA[CNY]]><\/fee_type>\n<is_subscribe><![CDATA[Y]]><\/is_subscribe>\n<mch_id><![CDATA[1530741181]]><\/mch_id>\n<nonce_str><![CDATA[5ccff7ee52be1]]><\/nonce_str>\n<openid><![CDATA[o7J0X1vaHpr3MS87iZU140xpLTdY]]><\/openid>\n<out_trade_no><![CDATA[txg15571332943298494]]><\/out_trade_no>\n<result_code><![CDATA[SUCCESS]]><\/result_code>\n<return_code><![CDATA[SUCCESS]]><\/return_code>\n<sign><![CDATA[957E11E3DD92A65E5B9A0A3389AFAEF6]]><\/sign>\n<time_end><![CDATA[20190506170139]]><\/time_end>\n<total_fee>1<\/total_fee>\n<trade_type><![CDATA[JSAPI]]><\/trade_type>\n<transaction_id><![CDATA[4200000306201905069492218118]]><\/transaction_id>\n<\/xml>"}
[wxPay] 2019-05-06 17:35:45 [message] {"msg":"Invalid request XML.","error_data":"EasyWeChat\\Kernel\\Exceptions\\Exception: Invalid request XML. in \/mnt\/www\/live\/vendor\/overtrue\/wechat\/src\/Payment\/Notify\/Handler.php:141\nStack trace:\n#0 \/mnt\/www\/live\/vendor\/overtrue\/wechat\/src\/Payment\/Notify\/Paid.php(28): EasyWeChat\\Payment\\Notify\\Handler->getMessage()\n#1 \/mnt\/www\/live\/vendor\/overtrue\/wechat\/src\/Payment\/Application.php(115):

**Comment by fenghoer** [comment]
`[wxPay] 2019-05-06 17:35:45 [message] {"error":"wxPayCallback: start!","data":"<xml><appid><![CDATA[wx7aa788c4d12cf3a8]]><\/appid>\n<attach><![CDATA[{\"order_number\":\"txg15571332943298494\"}]]><\/attach>\n<bank_type><![CDATA[CFT]]><\/bank_type>\n<cash_fee><![CDATA[1]]><\/cash_fee>\n<fee_type><![CDATA[CNY]]><\/fee_type>\n<is_subscribe><![CDATA[Y]]><\/is_subscribe>\n<mch_id><![CDATA[1530741181]]><\/mch_id>\n<nonce_str><![CDATA[5ccff7ee52be1]]><\/nonce_str>\n<openid><![CDATA[o7J0X1vaHpr3MS87iZU140xpLTdY]]><\/openid>\n<out_trade_no><![CDATA[txg15571332943298494]]><\/out_trade_no>\n<result_code><![CDATA[SUCCESS]]><\/result_code>\n<return_code><![CDATA[SUCCESS]]><\/return_code>\n<sign><![CDATA[957E11E3DD92A65E5B9A0A3389AFAEF6]]><\/sign>\n<time_end><![CDATA[20190506170139]]><\/time_end>\n<total_fee>1<\/total_fee>\n<trade_type><![CDATA[JSAPI]]><\/trade_type>\n<transaction_id><![CDATA[4200000306201905069492218118]]><\/transaction_id>\n<\/xml>"}
[wxPay] 2019-05-06 17:35:45 [message] {"msg":"Invalid request XML.","error_data":"EasyWeChat\\Kernel\\Exceptions\\Exception: Invalid request XML. in \/mnt\/www\/live\/vendor\/overtrue\/wechat\/src\/Payment\/Notify\/Handler.php:141\nStack trace:\n#0 \/mnt\/www\/live\/vendor\/overtrue\/wechat\/src\/Payment\/Notify\/Paid.php(28): EasyWeChat\\Payment\\Notify\\Handler->getMessage()\n#1 \/mnt\/www\/live\/vendor\/overtrue\/wechat\/src\/Payment\/Application.php(115):
`

**Comment by fenghoer** [comment]
粘了几次，发现用code模式才行，

**Comment by overtrue** [comment]
@fenghoer Swoole 自行解决兼容问题。

**Comment by fenghoer** [comment]
好的，我fork一份

**Comment by s4812785** [comment]
判断一下composer.lock是否有依赖要求的php版本高于你现有的版本，我遇到这样的报错是这个问题

**Comment by s4812785** [comment]
@fenghoer @talentant
