### ISSUE TITLE
微信公众号--返佣商品广告主商品API

### ISSUE THREAD

**Issue by TheNorthMemory** [overtrue/wechat#1474]
文档捋了一串儿，[从这儿阅读格式化版本](https://thenorthmemory.github.io/wechat-swagger/#/%E8%BF%94%E4%BD%A3%E5%95%86%E5%93%81)

涉及4个接口：

- /scan/product/v2/add 导入/更新商品接口
- /scan/product/v2/getinfo 单个商品信息查询接口
- /scan/product/v2/getinfobypage 全量商品信息查询接口
- /scan/product/v2/status 导入或更新结果查询接口

拿锅小伙伴给勒个代码好伐～

**Comment by overtrue** [comment]
👍
