### ISSUE TITLE
微信公众号内唤起支付，会写入一些参数进php_errors.log，如何写进其他地方？

### ISSUE THREAD

**Issue by yadgen** [overtrue/wechat#1482]
## 我用的环境

PHP 版本："php": "^7.1.3",
overtrue/wechat 版本："overtrue/laravel-wechat": "^4.0",
是否使用了框架？框架名称："laravel/framework": "5.7.*",

## 问题及现象
微信公众号内唤起支付，会写入一些参数进php_errors.log。

日志配置：
<img width="615" alt="2019-03-05 8 33 36" src="https://user-images.githubusercontent.com/1206012/53805773-098e5080-3f86-11e9-81a8-baba63a09a88.png">

**Comment by overtrue** [comment]
写的啥啊

**Comment by yadgen** [comment]
> 写的啥啊

呃，debug信息会写进php_errors.log，如何修改？

**Comment by overtrue** [comment]
贴一下样例，谢谢，否则我很难猜测到底是不是 SDK 写入的什么内容。

**Comment by yadgen** [comment]
> 贴一下样例，谢谢，否则我很难猜测到底是不是 SDK 写入的什么内容。
<img width="414" alt="1" src="https://user-images.githubusercontent.com/1206012/53930299-c4743680-40cb-11e9-83df-4c8dfd7562ec.png">
<img width="329" alt="2" src="https://user-images.githubusercontent.com/1206012/53930301-c6d69080-40cb-11e9-8565-fb20301b943d.png">
<img width="699" alt="3" src="https://user-images.githubusercontent.com/1206012/53930305-c807bd80-40cb-11e9-815f-43254278375f.png">

**Comment by overtrue** [comment]
这是 guzzle 写的日志，你是否修改过 guzzle 相关配置

**Comment by yadgen** [comment]
> 这是 guzzle 写的日志，你是否修改过 guzzle 相关配置

微信服务这块，没改过。
使用你的包，安装好，功能使用都没什么问题，就发现这个debug日志会写进php_errors.log，很奇怪。

**Comment by overtrue** [comment]
```
$ composer info overtrue/wechat
```

**Comment by overtrue** [comment]
贴一下结果

**Comment by yadgen** [comment]
> ```
> $ composer info overtrue/wechat
> ```

前两天刚刚更新到最新版本了。
<img width="734" alt="2019-03-07 1 19 19" src="https://user-images.githubusercontent.com/1206012/53933957-b1696280-40db-11e9-96e7-275eb67a5580.png">

**Comment by yadgen** [comment]
<img width="607" alt="2019-03-08 2 13 02" src="https://user-images.githubusercontent.com/1206012/53979075-bebc3680-4147-11e9-8faa-36821f1f2990.png">
初始化的时候，增加log选项即可，默认没读config/wechat.php配置文件。

**Comment by overtrue** [comment]
额，你这样初始化当然不会读配置啊。。。

**Comment by yadgen** [comment]
> 额，你这样初始化当然不会读配置啊。。。

嗯，我再仔细看看文档。
