### ISSUE TITLE
RuntimeException: Failed to cache access token

### ISSUE THREAD

**Issue by talentant** [overtrue/wechat#1483]
## 我用的环境
- PHP 版本：`7.2.10`
- overtrue/wechat 版本：`4.1.19`
- 是否使用了框架？框架名称：`Yii2`

## 问题及现象（操作日志）
1. 前天夜间服务器端更新，运行`composer update --optimize-autoloader --no-dev -vvv`，完成后打开小程序测试了一下，发生错误，查看错误日志为`EasyWeChat\Kernel\Exceptions\RuntimeException: Failed to cache access token. in ...vendor/overtrue/wechat/src/Kernel/AccessToken.php:141`
2. 立即更新`composer.json`，改为：`"overtrue/wechat": "4.1.18"`，错误依然存在
3. 继续更新`composer.json`，改为：`"overtrue/wechat": "4.1.17"`，错误依然存在
4. 继续更新`composer.json`，改为：`"overtrue/wechat": "4.1.16"`，错误依然存在
5. 继续更新`composer.json`，改为：`"overtrue/wechat": "4.1.15"`，一切正常

## 其他说明
1. 本地环境`（Win10+Docker）`正常，上线至服务器后发生以上错误
2. 服务器环境`（Ubuntu16.04+Docker）`一直正常，且近期没有运行调整

第二天查看了一下仓库代码变更 https://github.com/overtrue/wechat/compare/4.1.15...4.1.16 应该是对设置缓存结果的判断导致出现本次异常

**Comment by overtrue** [comment]
确认缓存有真的存进去

**Comment by talentant** [comment]
是的，缓存确实存储成功了

**Comment by talentant** [comment]
```php
        $ok = $this->getCache()->set($this->getCacheKey(), [
            $this->tokenKey => $token,
            'expires_in' => $lifetime,
        ], $lifetime - $this->safeSeconds);

        if (!$ok) {
            throw new RuntimeException('Failed to cache access token.');
        }
```

关于这里的判断方式，我认为用
```php
if ($this->getCache()->get($this->getCacheKey()) === null) {
    throw new RuntimeException('Failed to cache access token.');
}
```
类似的思路更加可靠些。

**Comment by overtrue** [comment]
@talentant `has` 为啥在成功后还是返回 false，有没有看一下：

https://github.com/overtrue/wechat/blob/master/src/Kernel/AccessToken.php#L140

**Comment by talentant** [comment]
@overtrue 我只能在夜间更新服务器，白天可能不太方便测试

**Comment by talentant** [comment]
@overtrue 稍等，我再仔细分析一下错误日志

**Comment by talentant** [comment]
Stack trace 是这样的：
```
EasyWeChat\Kernel\Exceptions\RuntimeException: Failed to cache access token. in ...vendor/overtrue/wechat/src/Kernel/AccessToken.php:141
Stack trace:
#0 ...vendor/overtrue/wechat/src/Kernel/AccessToken.php(119): EasyWeChat\Kernel\AccessToken->setToken('19_920p1O-8gXD-...', 7200)
#1 ...vendor/overtrue/wechat/src/Kernel/AccessToken.php(246): EasyWeChat\Kernel\AccessToken->getToken()
#2 ...vendor/overtrue/wechat/src/Kernel/AccessToken.php(202): EasyWeChat\Kernel\AccessToken->getQuery()
#3 ...vendor/overtrue/wechat/src/Kernel/BaseClient.php(212): EasyWeChat\Kernel\AccessToken->applyToRequest(Object(GuzzleHttp\Psr7\Request), Array)
```

**Comment by bolechen** [comment]
我在之前碰到和你同样的问题，感觉应该是缓存组件在生产环境的问题，我是 Laravel 框架，问题在 #1447 

后来我的解决方法是手动指定 Cache，就正常了，具体原因还未知，超哥可以看看，是否可以把出错信息再详情一下 @overtrue 

```php
    /**
     * EasyWechat init
     *
     * @return EasyWeChat
     **/
    public function getApp(Shop $shop)
    {
        $config = $shop->getConfig();
        $app = \EasyWeChat\Factory::officialAccount($config);

        //下面两句加上就正常了
        $cache = new \Symfony\Component\Cache\Simple\FilesystemCache('', 0, storage_path('framework/cache/data'));
        $app->rebind('cache', $cache);

        return $app;
    }
```

**Comment by talentant** [comment]
> 确认缓存有真的存进去

> 是的，缓存确实存储成功了

更正一下，经手动检查，缓存并没有存储成功。感谢 @bolechen 的提醒

**Comment by overtrue** [comment]
所以我可以关掉这个 issue 了哈？

**Comment by talentant** [comment]
@overtrue 嗯，可以关闭了，我们目前继续使用4.1.15版本，等有空了在想其他办法解决

**Comment by overtrue** [comment]
@talentant 修改一下日志路径就好，或者将 PHP 临时目录权限放开就可以了。

**Comment by bolechen** [comment]
继续使用 4.1.15 会导致 access_token 不缓存，每次都去获取，访问量大的话，要注意配额

talentant <notifications@github.com> 于2019年3月11日周一 下午2:44写道：

**Comment by talentant** [comment]
@overtrue @bolechen 明白，我告诉运维处理一下，感谢你们的帮助
