### ISSUE TITLE
Payment支付模块，日志设置无效

### ISSUE THREAD

**Issue by elim051** [overtrue/wechat#1486]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：4.1.17
是否使用了框架？框架名称：

## 问题及现象
在支付的时候，发现配置log信息，与http.log_template参数时，该配置项都是无效的

**Comment by overtrue** [comment]
贴代码，谢谢

**Comment by elim051** [comment]
配置项代码如下 
`
 'WECHAT_PAY' => [
        'debug'       => false,
        'app_id'      => 'xxxx',
        'mch_id'      => 'xxx',
        'key'         => 'xxx', // API 密钥
        // 如需使用敏感接口（如退款、发送红包等）需要配置 API 证书路径(登录商户平台下载 API 证书)
        'cert_path'   => '/opt/cert.pem',
        'key_path'    => '/opt/key.pem',
        'notify_url'  => '', //默认的订单回调地址
        'log'         => [
            'default' => 'prod',
            'channels' => [
                // 生产环境
                'prod' => [
                    'driver' => 'daily',
                    'path'   => '/data/easywechat.log',
                    'level'  => 'error',
                ],
            ],
        ],
    ],
`
在、data目录下并没有生成日志, 调试代码发现config运行的是
`
EasyWeChat\Kernel\Config Object
(
    [items:protected] => Array
        (
            [http] => Array
                (
                    [timeout] => 30
                    [base_uri] => https://api.mch.weixin.qq.com/
                )

            [app_id] => xxx
            [mch_id] => xxx
            [key] => xxxx
            [cert_path] => /opt/cert.pem
            [key_path] => /opt/key.pem
            [notify_url] =>
            [sub_mch_id] => xxxx
            [sub_appid] =>
            [log] => Array
                (
                    [default] => errorlog
                    [channels] => Array
                        (
                            [errorlog] => Array
                                (
                                    [driver] => errorlog
                                    [level] => debug
                                )

                        )

                )

        )

)
`

**Comment by overtrue** [comment]
贴你的 payment 模块实例的代码
