### ISSUE TITLE
每个请求都会log 到 wechat.log ，如何去掉

### ISSUE THREAD

**Issue by killjin** [overtrue/wechat#1487]
BaseClient 里 会注册
 if (empty($this->middlewares)) {
            $this->registerHttpMiddlewares();
        }

中间件，这时 GuzzleHttp 会注册 info 级别的LOG中间件把响应消息记录 到 wechat.log, 如何去掉这个log信息，否则流量大 wechat.log 会很大。

**Comment by overtrue** [comment]
日志模块注册一个空的处理器 ，或者不配置日志：

参考：

> https://github.com/Seldaek/monolog
> https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/NullHandler.php

**Comment by tianyong90** [comment]
https://www.easywechat.com/docs/master/official-account/configuration
既然都已经翻源码找原因了，是不是也应该仔细看看文档？

**Comment by killjin** [comment]
> https://www.easywechat.com/docs/master/official-account/configuration
> 既然都已经翻源码找原因了，是不是也应该仔细看看文档？

这个配置是控制不到 登录日志中间件的，这里我想的是作者能不能加一下。否则改框架，升级的时候会遇到问题。
