### ISSUE TITLE
请教，Cache::setter中your_custom_set_cache怎么使用

### ISSUE THREAD

**Issue by stonegithubs** [overtrue/wechat#149]
自定义缓存
use Overtrue\Wechat\Cache;

// 写入
Cache::setter(function($key, $value, $lifetime){
    return your_custom_set_cache($key, $value, $lifetime);
});

// 读取
Cache::getter(function($key){
    return your_custom_get_cache($key);
});
请教下，自定义的方法有什么作用？
可以直接这样写吗？
Cache::setter(function(‘abc’, $value, 3600){
    return true;
});
谢谢~~~~

**Comment by overtrue** [comment]
> 自定义的方法有什么作用？

就是自定义缓存写入与读取的方式。

```php
Cache::setter(function(‘abc’, $value, 3600){
return true;
});
```
你的意思是你不想缓存？

**Comment by stonegithubs** [comment]
谢谢，我是这样缓存的
use Overtrue\Wechat\Cache;
$prefix = ‘wx’;
$Cache = new Cache($prefix);
$Cache->set('access_token', $access_token);
$Cache->set('refresh_token', $refresh_token);
$access_token = $Cache->get('access_token');
$refresh_token = $Cache->get('refresh_token');
缓存数据正常，读取也正常
另外请教下setter和getter以及里面的自定义函数有什么用处，要自定义函数，能实现什么更强大的功能？
Cache::setter(function($key, $value, $lifetime){
return your_custom_set_cache($key, $value, $lifetime);
});
Cache::getter(function($key){
return your_custom_get_cache($key);
});

**Comment by overtrue** [comment]
`your_custom_set_cache` 是不存在的，只是 **举例的一个名称**，意思是这里你用自己的方式去 **写** 和 **读** 缓存
