### ISSUE TITLE
希望新增：微信OCR识别接口

### ISSUE THREAD

**Issue by calchen** [overtrue/wechat#1496]
## 我用的环境

PHP 版本：7.2
overtrue/wechat 版本：4.1.20 
是否使用了框架？框架名称：Lumen 5.7

## 问题及现象

本接口提供基于小程序或 H5 的身份证、银行卡、行驶证 OCR 识别 [文档](https://mp.weixin.qq.com/wiki?t=resource/res_main&id=21516712284rHWMX)

**Comment by talentant** [comment]
OCR 识别这个功能不错，期待能在下个版本（4.1.22）中增加

**Comment by overtrue** [comment]
已发布
