### ISSUE TITLE
在pahlcon中使用Factory::miniProgram($this->config);报错

### ISSUE THREAD

**Issue by chanchow** [overtrue/wechat#1499]
## 我用的环境

PHP 版本：7
overtrue/wechat 版本：
是否使用了框架？框架名称：phalcon

## 问题及现象

调用 Factory::miniProgram($this->config); 报错

Fatal error: Uncaught Error: Call to undefined function GuzzleHttp\choose_handler() in E:\55-xampp7.1\1\htdocs\www\vendor\guzzlehttp\guzzle\src\HandlerStack.php:40 Stack trace: #

**Comment by joyeekk** [comment]
你可以根据报错信息，看看相应目录下有没有choose_handler()这个函数
![image](https://user-images.githubusercontent.com/28078593/54796872-089b3580-4c8d-11e9-9253-3311a48f9301.png)

**Comment by chanchow** [comment]
> 你可以根据报错信息，看看相应目录下有没有choose_handler()这个函数
> ![image](https://user-images.githubusercontent.com/28078593/54796872-089b3580-4c8d-11e9-9253-3311a48f9301.png)

有这个函数的，是要加什么特定的命名空间吗，我目前加了这几个

![image](https://user-images.githubusercontent.com/9780914/54797799-a2b0ad00-4c90-11e9-9c4e-9864763bff3a.png)

![image](https://user-images.githubusercontent.com/9780914/54797745-63825c00-4c90-11e9-98f0-0a249ee5bd6d.png)

![image](https://user-images.githubusercontent.com/9780914/54797764-7a28b300-4c90-11e9-8048-d4b01781045c.png)

**Comment by overtrue** [comment]
你就不应该用 ThinkPHP 我觉得

**Comment by overtrue** [comment]
falcon 的 composer 使用是需要人工加命名空间的么？

**Comment by overtrue** [comment]
看配置的写法还以为是 ThinkPHP，哈哈

**Comment by chanchow** [comment]
> 看配置的写法还以为是 ThinkPHP，哈哈

不加命名空间就提示找不到类啊

**Comment by overtrue** [comment]
哈哈，falcon 居然对 Composer 的支持这么差。。。你应该需要将 vendor/class_namespaces.php 中全部引入才行吧。

**Comment by chanchow** [comment]
> 哈哈，falcon 居然对 Composer 的支持这么差。。。你应该需要将 vendor/class_namespaces.php 中全部引入才行吧。

没找到这个　class_namespaces.php　这个文件啊

**Comment by chanchow** [comment]
> 哈哈，falcon 居然对 Composer 的支持这么差。。。你应该需要将 vendor/class_namespaces.php 中全部引入才行吧。

我错了，我的引入方式错了，不要加命名空间，我给phalcon抹黑了

**Comment by overtrue** [comment]
@chanchow 😆 我 13年的时候过用 Phalcon，发现口味不符就放弃了。

**Comment by chanchow** [comment]
> @chanchow  我 13年的时候过用 Phalcon，发现口味不符就放弃了。

谢谢大佬指教了
