### ISSUE TITLE
文档有误，请更新

### ISSUE THREAD

**Issue by wanghj1991** [overtrue/wechat#1501]
## 我用的环境

PHP 版本： 7.3.1
overtrue/wechat 版本：4.1.21
是否使用了框架？框架名称：laravel

## 问题及现象
文档中这块写的有问题，请更新
[https://github.com/overtrue/laravel-wechat#%E6%88%91%E4%BB%AC%E6%9C%89%E4%BB%A5%E4%B8%8B%E6%96%B9%E5%BC%8F%E8%8E%B7%E5%8F%96-sdk-%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%AE%9E%E4%BE%8B](url)
首先这个版本找不到这个EasyWeChat这个门面，改成下面的Factory了
再一个就是使用Factory创建的例如miniProgram  对象，是没有加载默认config的
如果想要获得加载默认config的miniProgram 则需要通过
`$miniProgram = resolve('wechat.mini_program.default');`
这个代码获取。
还有一个publish出来的config文件wechat.php

`'mini_program' => [
         'app_id'  => env('WECHAT_MINI_PROGRAM_APPID', ''),
         'secret'  => env('WECHAT_MINI_PROGRAM_SECRET', ''),
         'token'   => env('WECHAT_MINI_PROGRAM_TOKEN', ''),
         'aes_key' => env('WECHAT_MINI_PROGRAM_AES_KEY', ''),
     ],`
这里需要把default去掉才能加载到

**Comment by wanghj1991** [comment]
> ## 我用的环境
> PHP 版本： 7.3.1
> overtrue/wechat 版本：4.1.21
> 是否使用了框架？框架名称：laravel
> 
> ## 问题及现象
> 文档中这块写的有问题，请更新
> [https://github.com/overtrue/laravel-wechat#%E6%88%91%E4%BB%AC%E6%9C%89%E4%BB%A5%E4%B8%8B%E6%96%B9%E5%BC%8F%E8%8E%B7%E5%8F%96-sdk-%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%AE%9E%E4%BE%8B](url)
> 首先这个版本找不到这个EasyWeChat这个门面，改成下面的Factory了
> 再一个就是使用Factory创建的例如miniProgram 对象，是没有加载默认config的
> 如果想要获得加载默认config的miniProgram 则需要通过
> `$miniProgram = resolve('wechat.mini_program.default');`
> 这个代码获取。
> 还有一个publish出来的config文件wechat.php
> 
> `'mini_program' => [ 'app_id' => env('WECHAT_MINI_PROGRAM_APPID', ''), 'secret' => env('WECHAT_MINI_PROGRAM_SECRET', ''), 'token' => env('WECHAT_MINI_PROGRAM_TOKEN', ''), 'aes_key' => env('WECHAT_MINI_PROGRAM_AES_KEY', ''), ],`
> 这里需要把default去掉才能加载到

链接的地址忽略吧。就是这个库laravel-wechat 
文档内容里面

> 关于我们有以下方式获取SDK的服务实例 
这部分内容 。

**Comment by overtrue** [comment]
1. 找不到门面，请检查你的安装过程是否有问题（Laravel 5.5+)：https://github.com/overtrue/laravel-wechat/blob/master/composer.json#L27
2. 另外你说的现象我无法重现，请确认的 Laravel 版本，并且安装的 laravel-wechat 为最新版（5.0 或者 4.0.23）

**Comment by wanghj1991** [comment]
作者辛苦，主要是注册的别名和项目里面有相同的类名，所以没想到是别名，后面才看到有别名可以使用，使用项目里的那个类有问题，使用别名就不会有问题了。

**Comment by wanghj1991** [comment]
EasyWeChat 这个确实有这个类，误认为使用这个类去了。没注意到注册了别名 EasyWeChat 直接可以使用
