### ISSUE TITLE
使用officialAccount获取用户access_token时，origin中没有refresh_token、expires_in信息

### ISSUE THREAD

**Issue by luxin88** [overtrue/wechat#1502]
使用officialAccount获取用户access_token时，origin中没有refresh_token、expires_in信息

按理说origin中应该包含微信接口返回的所有的信息呀

![image](https://user-images.githubusercontent.com/874056/54879693-e402b180-4e76-11e9-871a-791c58fa3f7d.png)

**Comment by overtrue** [comment]
1. 你的操作并不是在获取 AccessToken，而是 OAuth 的用户授权。
2. 微信的 AccessToken 分为两个：通用接口 Access Token 与 OAuth Access Token 它们不是同一个东西。

**Comment by luxin88** [comment]
我刚看了下代码，在scope为snsapi_userinfo 的时候，会自动再获取一道用户信息，然后把用户信息数据丢出来，而不是第二步获取到的接口原始信息。
在微信接口说明里面，access_token接口不管scope是snsapi_userinfo还是snsapi_base，都返回相同的信息。
scope为userinfo和base的情况下，获取到的token权限是不一样的，具体的用户头像等信息是不是可以让开发者再手工获取一次而不是把access_token接口里面的信息跳过（隐藏起来），这个操作在微信文档里面本身也是分两次来进行的，所以我感觉合并起来似乎不太合适

**Comment by overtrue** [comment]
1. access_token 并没有限制获取次数，所以你不用关心，也不用存起来
2. access_token 已经放到上面截图的 token 里面，你要存也 OK
3. 这个包的目的就是让整个流程更简化，如果你需要自己去一步步的走的话其实你完全可以自己写，就3个方法而已，不到50行代码的事情，分开调用的话用这个包就显得非常多余了。
4. 如果你一定要用这个包，并且喜欢分步手动实现，包里其实也预留了方法：
> 1. 获取 AccessToken https://github.com/overtrue/socialite/blob/master/src/Providers/WeChatProvider.php#L95
> 2. 使用自定义的 Token 获取用户：https://github.com/overtrue/socialite/blob/master/src/Providers/AbstractProvider.php#L186

**Comment by luxin88** [comment]
我刚才也是想用getAccessToken方法获取来着，结果发现code参数无法直接获取，因为getCode是protected的。

我想保存token 还有refresh_token还有expires_in是因为如果每次调用需要token的接口都获取一遍的话，会有不必要的资源开销，直接去数据库取或者去缓存取不是更快，另外，每个需要token的功能都去重新获取一次的话，也比较容易造成并发获取token时，较早获取的token失效的问题。

因此我建议将getAccessToken函数进行修改，如下
![image](https://user-images.githubusercontent.com/874056/54893945-49948380-4ef3-11e9-90bd-283a57b9e000.png)

**Comment by luxin88** [comment]
另外 access_token的有效期只有7200秒，refresh_token的有效期时30天，如果隐藏refresh_token的话，每次刷新token都要走 redirect->getcode->gettoken这个流程，如果客户端卡一下的话，对用户体验也不是很好，而直接从服务端使用refresh_token刷新的话，对用户是无感知的，并且速度也更快

**Comment by overtrue** [comment]
1. code 是在你的 URL 上的，getCode 也是从 URL 里取的。
2. 刷新 token 这个确实目前没有支持，如果你有更好的建议可以 PR，这个只能后面排期来优化了。

**Comment by shenadmin** [comment]
> 另外 access_token的有效期只有7200秒，refresh_token的有效期时30天，如果隐藏refresh_token的话，每次刷新token都要走 redirect->getcode->gettoken这个流程，如果客户端卡一下的话，对用户体验也不是很好，而直接从服务端使用refresh_token刷新的话，对用户是无感知的，并且速度也更快
我也遇到这种问题, 后来采用什么方式解决自动刷新的呢,可以参考下么

**Comment by shenadmin** [comment]
@luxin88

**Comment by shenadmin** [comment]
@luxin88  请问后来你怎么解决,可以参考下么

**Comment by luxin88** [comment]
> @luxin88 请问后来你怎么解决,可以参考下么

我是把refresh token存储在数据库里面了，并且一并存储了一个refresh token的过期时间，在过期时间之前就直接去接口取token，如果refresh token过期了，则重新授权，因为用到了数据库，所以没办法提pr，不然涉及到的内容太多了

**Comment by shenadmin** [comment]
> > @luxin88 请问后来你怎么解决,可以参考下么
> 
> 我是把refresh token存储在数据库里面了，并且一并存储了一个refresh token的过期时间，在过期时间之前就直接去接口取token，如果refresh token过期了，则重新授权，因为用到了数据库，所以没办法提pr，不然涉及到的内容太多了

谢谢回复,我本来也想按照你上面的那种修改getAccessToken这个方法去获取refresh_token,但是这样改包很不好.你后来是怎么获取refresh_token的呢,自己写一个方法使用code去获取微信原本的数据么

**Comment by luxin88** [comment]
> > > @luxin88 请问后来你怎么解决,可以参考下么
> > 
> > 
> > 我是把refresh token存储在数据库里面了，并且一并存储了一个refresh token的过期时间，在过期时间之前就直接去接口取token，如果refresh token过期了，则重新授权，因为用到了数据库，所以没办法提pr，不然涉及到的内容太多了
> 
> 谢谢回复,我本来也想按照你上面的那种修改getAccessToken这个方法去获取refresh_token,但是这样改包很不好.你后来是怎么获取refresh_token的呢,自己写一个方法使用code去获取微信原本的数据么

我的开发原则是尽量不要去修改第三方的库，可以在之上按照自己的业务逻辑再进行一次封装

**Comment by sn01615** [comment]
$app->oauth->getAccessToken()这个接口怎么回事 我无法获取到完整信息？
```
{ 
"access_token":"ACCESS_TOKEN", 
"expires_in":7200, 
"refresh_token":"REFRESH_TOKEN",
"openid":"OPENID", 
"scope":"SCOPE",
"unionid": "o6_bmasdasdsad6_2sgVt7hMZOPfL"
}
```
好像只能获取到access_token？？？

**Comment by sn01615** [comment]
这个项目这么多星星难道还有这种低级的问题？

**Comment by overtrue** [comment]
@sn01615 你还想获取什么信息？

**Comment by sn01615** [comment]
> @sn01615 你还想获取什么信息？

openid + unionid

**Comment by overtrue** [comment]
你贴的 json 里不是已经有了？

**Comment by sn01615** [comment]
> 你贴的 json 里不是已经有了？

我看了源码只有__toString和getToken方法

**Comment by overtrue** [comment]
@sn01615 `$app->oauth->getAccessToken()->toArray()`

**Comment by sn01615** [comment]
> @sn01615 `$app->oauth->getAccessToken()->toArray()`

可以了谢谢大佬

**Comment by sn01615** [comment]
![image](https://user-images.githubusercontent.com/7794149/61861829-5526a400-aeff-11e9-8929-3466168a093e.png)

**Comment by shenadmin** [comment]
我估计你没有认真看文档, 目前就是不能获取  refresh token

**Comment by overtrue** [comment]
@shenadmin refresh token 也能用这样的方法拿

**Comment by nongzhenli** [comment]
请问 网页授权 获取到的用户信息，token 字段是干啥的？这个并非 公众号的 access_token  吧？
