### ISSUE TITLE
 长链接转短链接接口有效期

### ISSUE THREAD

**Issue by helloweb314** [overtrue/wechat#1510]
## 我用的环境

PHP 版本：PHP 7.2.15 
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：YII2

## 问题及现象

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

hi, 查看官方文档, 已经easywecaht的文档中  长链接转短链接接口 没有说明短链接有效期, 使用过程中观察到同一个域名 请求多吃均返回不同的短链接.

看了下easywechat文档最近更新也是几个月以前, 短链接还可用,想确认下

官方接口地址
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1443433600
easywechat文档地址
https://www.easywechat.com/docs/4.0/basic-services/url

因为接口单位请求限制 日100000次,  想着能减少请求最好, 想确认下

麻烦大家了, 谢谢

如果你不提供相关的代码，我不会做任何应答，直接 close，感谢！
$shortUrl = $app->url->shorten('http://www.baidu.com');

**Comment by mingyoung** [comment]
官方也没提到有效期，不过我个人**猜测**应该是永久的
