### ISSUE TITLE
企业微信授权登录callback中出错

### ISSUE THREAD

**Issue by terry8650** [overtrue/wechat#1513]
## 我用的环境

PHP 版本：7.2
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：tp5.1

## 问题及现象
我在callback url中使用$user = $this->qy ->oauth->user();出现错误如下
致命错误: Call to a member function get() on null
`protected function hasInvalidState()
    {
        if ($this->isStateless()) {
            return false;
        }

        $state = $this->request->getSession()->get('state');//这个地方getsession是null

        return !(strlen($state) > 0 && $this->request->get('state') === $state);
    }`
还有我测试makestates那里的getsession也是null
`protected function makeState()
    {
        $state = sha1(uniqid(mt_rand(1, 1000000), true));
        $session = $this->request->getSession();

        if (is_callable([$session, 'put'])) {
            $session->put('state', $state);
        } elseif (is_callable([$session, 'set'])) {
            $session->set('state', $state);
        } else {
            return false;
        }

        return $state;
    }`

**Comment by terry8650** [comment]
stateless.........有点意思。。。。不知道是不是故意的

**Comment by overtrue** [comment]
> stateless.........有点意思。。。。不知道是不是故意的

stateless 用于无法正常使用 session 的情况下使用。

**Comment by terry8650** [comment]
> > stateless.........有点意思。。。。不知道是不是故意的
> 
> stateless 用于无法正常使用 session 的情况下使用。

授权登录我看都是默认不用state的，我觉得文档里应该写个使用session使用state的例子比较好

**Comment by overtrue** [comment]
“授权登录我看都是默认不用state的” 这句是指哪里？

**Comment by terry8650** [comment]
> “授权登录我看都是默认不用state的” 这句是指哪里？

比如wechatprovider就有默认 protected $stateless = true;

**Comment by overtrue** [comment]
是的，因为微信的浏览器老是丢 cookie 的 sessionid ...

**Comment by terry8650** [comment]
> 是的，因为微信的浏览器老是丢 cookie 的 sessionid ...

好的

**Comment by terry8650** [comment]
> 是的，因为微信的浏览器老是丢 cookie 的 sessionid ...

看到有哥们和我一样的问题，就是tp5.1中企业微信授权登录getsession为null的问题：看到你是
`
protected function isStateless()
	    {
	        return $this->stateless;
	        return !$this->request->hasSession() || $this->stateless;
	    }
`
在这个方法里加了个判断 !$this->request->hasSession() 解决的，如果tp5.1想用session想用state验证怎么办呢？

**Comment by zymeli** [comment]
@overtrue ，微信浏览器里，用户授权登录，即公众号的OAuth2的$app->oauth->user()时，由于你这个$stateless = true;，造成可以CSRF攻击了，比如我的/wechat/login?code=xxx&state=yyy，被别人也可以多次试用，虽然多半微信服务器会报code已经被使用，但还是老是让服务器500异常了，不好～
