### ISSUE TITLE
微信支付里面统一下openid如何获得

### ISSUE THREAD

**Issue by hare2011** [overtrue/wechat#1520]
## 我看文档统一支付例子
$result = $app->order->unify([
    'body' => '腾讯充值中心-QQ会员充值',
    'out_trade_no' => '20150806125346',
    'total_fee' => 88,
    'spbill_create_ip' => '123.12.12.123', // 可选，如不传该参数，SDK 将会自动获取相应 IP 地址
    'notify_url' => 'https://pay.weixin.qq.com/wxpay/pay.action', // 支付结果通知网址，如果不设置则会使用配置里的默认地址
    'trade_type' => 'JSAPI',
    'openid' => 'oUpF8uMuAJO_M2pxb1Q9zNjWeS6o',
]);

我找了很久没发现openid是那个接口获得
openid这个值是那个接口获呢？

**Comment by overtrue** [comment]
请先熟读微信官方文档后再使用此 SDK：
> https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140842
> https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140453
> https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140839

**Comment by hare2011** [comment]
@~@
