### ISSUE TITLE
4.1版本的微信支付 jsapi 支付发起问题

### ISSUE THREAD

**Issue by richerdyoung** [overtrue/wechat#1521]
## 我用的环境
lnmp
PHP 版本：7.1
overtrue/wechat 版本： 4.1
是否使用了框架？框架名称：
thinkphp5.1
## 问题及现象
在使用公众号，微信支付 功能时候，遇到 支付参数 $prepayId ，没看到从哪来的，网上查找资料。要引入
`use EasyWeChat\Foundation\Application;
use EasyWeChat\Payment\Order; 
`
我引入之后，报错不存在，

文档代码：
`use EasyWeChat\Factory;

$config = [
    // 前面的appid什么的也得保留哦
    'app_id'             => 'xxxx',
    'mch_id'             => 'your-mch-id',
    'key'                => 'key-for-signature',
    'cert_path'          => 'path/to/your/cert.pem', // XXX: 绝对路径！！！！
    'key_path'           => 'path/to/your/key',      // XXX: 绝对路径！！！！
    'notify_url'         => '默认的订单回调地址',     // 你也可以在下单时单独设置来想覆盖它
    // 'device_info'     => '013467007045764',
    // 'sub_app_id'      => '',
    // 'sub_merchant_id' => '',
    // ...
];

$payment = Factory::payment($config);

$jssdk = $payment->jssdk;
`
jssdk
`$config = $jssdk->sdkConfig($prepayId); // 返回数组`

这个 $prepayId 从哪来的，我记得直接用微信demo，生成预支付订单信息，里边有这个值，
jsapi 也需要这个吗？

**Comment by overtrue** [comment]
1. 请先把[文档首页的说明](https://www.easywechat.com/docs/4.1/overview#heading-h3-2)读完再使用，尤其是加粗的部分：“仔细阅读并看懂微信官方文档”
2. 微信文档上写得非常清楚：
     > https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421141115
3. prepay_id 从哪里来：https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_1


PS. 我给懒得看文档的人准备了视频教程的，如果你懒得去读文档又懒得去尝试，请购买视频教程：https://www.easywechat.com/tutorials

**Comment by richerdyoung** [comment]
这是我第一次看文档的感受，并非新手，老哥抱歉

第一次使用easywechat..之前都是使用自己封装的库，，

prepay_id 这个我知道，刚才我已经描述了，原生微信demo 要请求统一下单接口 获取 prepay_id  ，
现在的问题是如果我用了easywechat库，，我看文档上写的有点不清楚
我在使用 扫码支付时候有这一段
` $wx_pay_config = config::get("config_wechat.payment.default");
            $app = Factory::payment($wx_pay_config);

            $wx_pay_config_native = config::get("config_wechat.payment.native");
            
            $wxOrder_result = $app->order->unify([
                'trade_type' => 'NATIVE',
                'product_id' => time(), // product_id 则为生成二维码时的产品 ID
                'body'=>'test',
                'attach'=>'订单支付',
                'out_trade_no'=>$order_mes['order_no'],
                'total_fee'=>$order_mes['order_money'] * 100,
                'time_start'=>date("YmdHis"),
                'time_expire'=>date("YmdHis", time() + 600),
                'goods_tag'=>'订单',
                'notify_url'=>$wx_pay_config_native['notify_url_order'],
            ]);`
返回结果是有这个 prepay_id
`Array
(
    [return_code] => SUCCESS
    [return_msg] => OK
    [appid] => wxccc0e9ff31f9e433
    [mch_id] => 1530680821
    [nonce_str] => SUDzQC4MjScQDFdZ
    [sign] => BAA891F108AB5604CC3C19C211BA57F9
    [result_code] => SUCCESS
    [prepay_id] => wx1013295391637713efdf03bd1668778665
    [trade_type] => NATIVE
    [code_url] => weixin://wxpay/bizpayurl?pr=VQS3exk
)
`

在使用jssdk  处理支付时候  文档上就没写了。
我把把上边的类型改为jsapi 请求，多加了openid 参数。请求可以获取到了 prepay_id ， 

文档缺失了这一块，  在使用过程中，是一边看文档，一边看微信文档，在一边网上搜资料。。才完成的功能，，如果文档能完善一点，，估计能节省一点时间，，
以上所述如有说错的地方，还望老哥见谅

**Comment by overtrue** [comment]
因为就我的理解来讲，如果认真看过微信的文档，就不会问 prepay_id 哪里来的，官方文档已经写清楚了，看完 jssdk 部分的文档，package 参数里已经说明了使用 prepay_id 所以，我的 SDK 文档没有必须去复制官方已经说明的内容，如果每个人都不看文档来问的话，我基本没有时间来工作了，所以我的回应会非常简单直接，按文档首页说明做到后基本就不会有这些问题了，或者说至少是尝试过后再问会比较科学一些。

**Comment by richerdyoung** [comment]
咱俩的理解有出入， prepay_id 这个不纠结了。我一开始就知道，，
我的意思是 如果easywechat官方文档上。把这个使用的完整例子放上去，衔接上   就好了

**jssdk**

```php
           $wx_pay_config_jsapi = config::get("config_wechat.payment.jsapi");
            $app = Factory::payment($wx_pay_config_jsapi);

            $jssdk = $app->jssdk;

            $wxOrder_result = $app->order->unify([
                'trade_type' => 'JSAPI',
                'product_id' => time(), // product_id 则为生成二维码时的产品 ID
                'body'=>'test',
                'attach'=>'订单支付',
                'out_trade_no'=>time(),
                'total_fee'=>$order_mes['order_money'] * 100,
                'time_start'=>date("YmdHis"),
                'time_expire'=>date("YmdHis", time() + 600),
                'goods_tag'=>'订单',
                'notify_url'=>$wx_pay_config_jsapi['notify_url'],
                'openid'=>$user_mes['openid'],
            ]);

            if($wxOrder_result['return_code'] == 'SUCCESS' && $wxOrder_result['result_code'] =='SUCCESS'){
                $prepayId = $wxOrder_result['prepay_id'];
                $jsapi_config = $jssdk->sdkConfig($prepayId); // 返回数组
                print_r($jsapi_config);exit;

            }else{
                echo 'fail';
                print_r($wxOrder_result);exit;
            }    

```

**Comment by overtrue** [comment]
抱歉不会写这种例子上去的哈

**Comment by richerdyoung** [comment]
那我慢慢摸索下。回头把例子放上去。供其他猿看看，希望有帮助，早点休息老哥
