### ISSUE TITLE
微信公众号&微信支付跨城冗灾公告

### ISSUE THREAD

**Issue by TheNorthMemory** [overtrue/wechat#1526]
- 公告地址 [here](https://developers.weixin.qq.com/community/pay/doc/000446a3894140d38858c10dc5bc01)
- 方案地址 [here](https://pay.weixin.qq.com/wiki/doc/api/micropay_sl.php?chapter=23_6&index=4)

| - | 商户侧要求 | 微信支付
|---|---|---|
|机房和运营商| - | 商户侧DNS就近解析，微信支付提供六个接入点：上海电信、深圳电信、天津电信 上海联通、深圳联通、天津联通
|容灾规则 | 要求：双活，发生故障能主备切换，恢复后能回切<br>1、主域名是主通道， 备用域名（跨城解析域名）可以采用1%以内的流量做验证<br>2、遇到主域名异常要能将主要通道自动切换到备用域名（跨城解析域名）访问<br>3、当主域名恢复正常后，主要通道要从备用域名（跨城解析域名）回切访问 | 主域名：同运营商就近解析；<br>备域名：同运营商跨城解析；<br>网络延时对比：主域名小于备域名<br>微信支付主备域名列表：<br>api.mch.weixin.qq.com（主域名） <br>api2.mch.weixin.qq.com（跨城解析域名） <br>公众平台：<br>api.weixin.qq.com（主域名） <br>api2.weixin.qq.com（跨城解析域名） <br>资源： <br>res.wx.qq.com（主域名）  <br>res2.wx.qq.com（跨城解析域名） 

一言以概之就是，服务端调用的域名，会是 api or api2, ew给做个规划兼容之吧。

**Comment by trockxi** [comment]
看了一头雾水，哪位大佬指点下具体实现步骤，谢谢！

**Comment by Birjemin** [comment]
楼主的意思是想要package支持域名自定义配置吧？？？默认是兼容配置的

文档地址：[https://www.easywechat.com/docs/4.1/official-account/configuration](https://www.easywechat.com/docs/4.1/official-account/configuration)
代码位置：代码替换的位置参见package包的`EasyWeChat\Kernel\ServiceContainer`类的`getConfig`方法、每一个`Application`类的$defaultConfig属性

```php
use EasyWeChat\Factory;

$config = [
    'app_id' => 'wx3cf0f39249eb0exx',
    'secret' => 'f1c242f4f28f735d4687abb469072axx',

    // 指定 API 调用返回结果的类型：array(default)/collection/object/raw/自定义类名
    'response_type' => 'array',

    // 覆盖原有的域名！！！
    'http' => [
            'base_uri' => 'https://qyapi.weixin.qq.com/',
     ],
];
$app = Factory::officialAccount($config);
```

**Comment by overtrue** [comment]
默认就支持，按 @Birjemin 的做法即可。

**Comment by TheNorthMemory** [comment]
俺的意思是，增加多活配置，即主域挂逑了，failover 到 `api2.*.qq.com` 上。配置可以换域名很赞，应用层即可自主搭个反向代理服务器，代理服务器去做死逑切换也是个简单粗暴的方法。

**Comment by overtrue** [comment]
@TheNorthMemory 哈哈，那我根据 curl 报错来切换？
