### ISSUE TITLE
请问在 easyWeChat中该如何获取 unionid

### ISSUE THREAD

**Issue by javaLx** [overtrue/wechat#1529]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：4.x
是否使用了框架？框架名称：laravel 

## 问题及现象

请问在 easyWeChat中该如何获取 unionid

**Comment by almas1992** [comment]
先仔细看看微信官方文档，什么情况下回返回unionid，在调用哪个api时返回，弄清楚这些再看easy-wechat文档就会知道怎么获取unionid

**Comment by javaLx** [comment]
> 先仔细看看微信官方文档，什么情况下回返回蚌，在调用哪个API时返回，弄清楚这些再看易于微信文档就会知道怎么获取蚌

我是pc扫码的场景下  没看可以获取unionid的

**Comment by mingyoung** [comment]
那你知道什么情况下才会返回 unionid 吗？

**Comment by javaLx** [comment]
> 那你知道什么情况下才会返回 unionid 吗？

用户关注了公众号啊 然后拿access_token 和openid换

**Comment by almas1992** [comment]
> > 那你知道什么情况下才会返回 unionid 吗？
> 
> 用户关注了公众号啊 然后拿access_token 和openid换

公众号绑定了微信开放平台才有unionid啊大兄弟

**Comment by javaLx** [comment]
> > > 那你知道什么情况下才会返回 unionid 吗？
> > 
> > 
> > 用户关注了公众号啊 然后拿access_token 和openid换
> 
> 公众号绑定了微信开放平台才有unionid啊大兄弟

绑定的

> > > 那你知道什么情况下才会返回 unionid 吗？
> > 
> > 
> > 用户关注了公众号啊 然后拿access_token 和openid换
> 
> 公众号绑定了微信开放平台才有unionid啊大兄弟

绑定了开放平台的

**Comment by javaLx** [comment]
> > > 那你知道什么情况下才会返回 unionid 吗？
> > 
> > 
> > 用户关注了公众号啊 然后拿access_token 和openid换
> 
> 公众号绑定了微信开放平台才有unionid啊大兄弟

绑定了开放平台的

**Comment by javaLx** [comment]
> > > 那你知道什么情况下才会返回 unionid 吗？
> > 
> > 
> > 用户关注了公众号啊 然后拿access_token 和openid换
> 
> 公众号绑定了微信开放平台才有unionid啊大兄弟

解决了 在关注的时候 可以拿到用户信息 里面有

**Comment by almas1992** [comment]
> > > > 那你知道什么情况下才会返回 unionid 吗？
> > > 
> > > 
> > > 用户关注了公众号啊 然后拿access_token 和openid换
> > 
> > 
> > 公众号绑定了微信开放平台才有unionid啊大兄弟
> 
> 解决了 在关注的时候 可以拿到用户信息 里面有

微信网页授权 了解一下
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140842

网页授权 了解一下
https://www.easywechat.com/docs/4.1/official-account/oauth
