### ISSUE TITLE
企业微信服务商小程序登录接口不支持

### ISSUE THREAD

**Issue by jingpg** [overtrue/wechat#1535]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：
是否使用了框架？框架名称：

## 问题及现象

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

如果你不提供相关的代码，我不会做任何应答，直接 close，感谢！

namespace EasyWeChat\Work\MiniProgram\Auth

添加如下方法
```
public function serviceSession(string $suite_access_token, string $code)
{
        $params = [
            'suite_access_token' => $suite_access_token,
            'js_code' => $code,
            'grant_type' => 'authorization_code',
        ];

        return $this->httpGet('cgi-bin/service/miniprogram/jscode2session', $params);
}
```

**Comment by keacefull** [comment]
企业微信服务商的接口已经大幅升级，正在调整和加入新的接口，超哥也在计划5.0所以看是5.0一起加入还是空了直接加入 @overtrue @jingpg

**Comment by overtrue** [comment]
@keacefull 服务商 3.0 API 我应该是最先知道的吧（如果没猜错），已经计划在 5.0 加入啦！

**Comment by jingpg** [comment]
> 企业微信服务商的接口已经大幅升级，正在调整和加入新的接口，超哥也在计划5.0所以看是5.0一起加入还是空了直接加入 @overtrue @jingpg

感谢

**Comment by yaqianghan** [comment]
企业微信登陆   
现在支持吗？

**Comment by keacefull** [comment]
@yaqianghan 5.0会支持

**Comment by yaqianghan** [comment]
好的！谢谢

**Comment by yaqianghan** [comment]
@keacefull 好的，🙏
