### ISSUE TITLE
小程序场景值scene的问题

### ISSUE THREAD

**Issue by hglaravel** [overtrue/wechat#1537]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：Laravel5.7

## 问题及现象
小程序的场景值scene传递为空

**Comment by hglaravel** [comment]
![111](https://user-images.githubusercontent.com/44674495/57193760-5c2dbe00-6f71-11e9-80fd-c5404ed6dcc3.png)

**Comment by hglaravel** [comment]
![2222](https://user-images.githubusercontent.com/44674495/57193766-664fbc80-6f71-11e9-9821-11c43dffe060.png)

**Comment by overtrue** [comment]
怎么证明场景值传递为空的呢？
