### ISSUE TITLE
3.x企业支付功能是不是没有实现？

### ISSUE THREAD

**Issue by houguang** [overtrue/wechat#1538]
## 我用的环境
PHP 版本：5.5
overtrue/wechat 版本：3.x

## 问题及现象
3.x企业支付功能是不是没有实现？
![image](https://user-images.githubusercontent.com/1720347/57287452-206a3400-70ea-11e9-9e35-b951b51827bc.png)

执行后查询订单显示不存在
![image](https://user-images.githubusercontent.com/1720347/57287532-50b1d280-70ea-11e9-9de5-6cb923b357a1.png)

根据文档的示例，这里也没有返回数据
![image](https://user-images.githubusercontent.com/1720347/57288016-417f5480-70eb-11e9-8c03-d668f23237be.png)

查看send方法是空的
![image](https://user-images.githubusercontent.com/1720347/57287498-3c6dd580-70ea-11e9-9663-f7e6343be302.png)

**Comment by houguang** [comment]
已使用此方法实现功能。
![image](https://user-images.githubusercontent.com/1720347/57353628-ae522780-719b-11e9-99d8-1637eb1cada2.png)

**Comment by almas1992** [comment]
> 已使用此方法实现功能。
> ![image](https://user-images.githubusercontent.com/1720347/57353628-ae522780-719b-11e9-99d8-1637eb1cada2.png)
```php
3.x 不是有封装了 `merchant_pay` 麽
 app( 'wechat' )->merchant_pay->send( $merchantPayData );
 app( 'wechat' )->merchant_pay->query( $partnerTradeNo );
```
这两个方法可以正常使用~我在项目中用过
