### ISSUE TITLE
3.x文档中有一个页面打不开，已找到原因

### ISSUE THREAD

**Issue by houguang** [overtrue/wechat#1539]
overtrue/wechat 版本：3.x

此页面打开右侧空白，查看源码发现是标签错误
https://www.easywechat.com/docs/3.x/notice
![image](https://user-images.githubusercontent.com/1720347/57418747-f7a38500-7236-11e9-93a9-0e766d6e3fea.png)

此处使用了·body·标签，经测试改成·div·可正常显示
![image](https://user-images.githubusercontent.com/1720347/57419853-494c0f80-7237-11e9-8d8a-984d3875f633.png)

**Comment by xiepeixing** [comment]
作者不修复下么

**Comment by overtrue** [comment]
已修复
