### ISSUE TITLE
是否支持礼品卡货架功能

### ISSUE THREAD

**Issue by jasonjiang123** [overtrue/wechat#1543]
## 我用的环境

PHP 版本：7.1.2
overtrue/wechat 版本：4.1
是否使用了框架？框架名称：lumen 5.5

## 问题及现象

目前想通过接口实现礼品卡功能，支持建立货架。

**Comment by overtrue** [comment]
非常抱歉，目前没时间来加这块哦，你可以参考现有的写法做完后 PR。
