### ISSUE TITLE
laravel5.8下缓存过期时间问题

### ISSUE THREAD

**Issue by keller31** [overtrue/wechat#1545]
## 我用的环境

PHP 版本：7.2
overtrue/wechat 版本：4.*
是否使用了框架？框架名称：laravel5.8

## 问题及现象

```
public function setTicket(string $ticket)
    {
        $this->getCache()->set($this->getCacheKey(), $ticket, 3600);

        if (!$this->getCache()->has($this->getCacheKey())) {
            throw new RuntimeException('Failed to cache verify ticket.');
        }

        return $this;
    }
```

laravel5.8下 setTicket 的缓存时间实际只有60秒，造成 验证ticket时报

`Credential "component_verify_ticket" does not exist in cache.`

手动写了一段调试代码 发现设置ttl为3600 但是实际写入的缓存还是只有60s
```
$this->app = app('wechat.open_platform.default');
$dd = $this->getCache()->set('test_cache','666',3600);
```

此问题是否与 《[Laravel 5.8 中缓存的 TTL 单位变更](https://learnku.com/laravel/t/24088)》 有关

**Comment by iszmxw** [comment]
![image](https://user-images.githubusercontent.com/31272102/57604523-eb049100-7596-11e9-9f81-cb7f0b7717d4.png)
我的laravel5.5.45也是包同样的错误
我安装的是这个版本"overtrue/laravel-wechat": "~4.0"

**Comment by keller31** [comment]
此问题可以关闭了，
laravel5.8 使用 "overtrue/laravel-wechat": "~5.0", 即可
