### ISSUE TITLE
第三方平台接口获取预授权码接口，缺少component_access_token参数

### ISSUE THREAD

**Issue by jianzi0307** [overtrue/wechat#1548]
最近在写第三方平台nodejs的sdk，参考easywechat一下；

获取预授权码接口，跟官网接口文档不大一样，缺少一个`component_access_token`参数，不知道这里是不是一个bug。

https://github.com/overtrue/wechat/blob/e1047d0fa847df46046d2a631f4ffadc7f440c3f/src/OpenPlatform/Base/Client.php#L127

![image](https://user-images.githubusercontent.com/2997173/57773399-82f6ac00-774a-11e9-9894-fcb5305ae65d.png)

https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1453779503&token=&lang=

**Comment by mingyoung** [comment]
`component_access_token` 会在请求的时候自动加到 query 上的。
