### ISSUE TITLE
没有找到cgi-bin/media/uploadnews接口

### ISSUE THREAD

**Issue by Guxinpei** [overtrue/wechat#1549]
## Centos 6

PHP 版本：php 7.2
overtrue/wechat 版本：4.1.23
是否使用了框架？框架名称：没有使用

##问题及现象
没有找到微信高级群发接口部分中图文上传的接口支持，并不是永久素材中的图文上传接口，接口地址如下 https://api.weixin.qq.com/cgi-bin/media/uploadnews?access_token=ACCESS_TOKEN。

我在 \EasyWeChat\BasicService\Media\Client 与 EasyWeChat\OfficialAccount\Material\Client 中均没有找到。

业务逻辑上，如果调用 EasyWeChat\OfficialAccount\Material\Client 的 uploadArticle 会占用永久素材5000上限,所以不打算使用该接口。

微信官方文档（上传图文消息素材部分）：https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1481187827_i0l21

请问我们是否对该接口做了支持？
十分感谢

**Comment by overtrue** [comment]
将这段代码：https://github.com/overtrue/wechat/blob/master/src/OfficialAccount/Material/Client.php#L108-L123

复制到：`https://github.com/overtrue/wechat/blob/master/src/BasicService/Media/Client.php` 中作测试，修改 httpPostJson 部分中的 api 地址，测试完成后提个 PR？

**Comment by Guxinpei** [comment]
我完成测试之后会立刻提: )其实我已经copy该代码到我的业务里了2333
感谢！

**Comment by Guxinpei** [comment]
@overtrue 尽管该接口文档在官网写明，但是我在测试过程中发现此接口一直提示该URL不存在，所以测试一直未通过，并没有提交PR，特此反馈。在我工作的业务环境中，也没有停止考虑使用该接口，后续我会继续关注这个接口，如果测试通过我会提交PR。感谢！

**Comment by overtrue** [comment]
好的，谢谢

Guxinpei <notifications@github.com>于2019年5月23日 周四下午1:35写道：
