### ISSUE TITLE
Payment/UnifiedOrder does not support serialize or create by array

### ISSUE THREAD

**Issue by acabin** [overtrue/wechat#155]
In some cases, we will use the same out_trade_no for different scene, but wechat forbid reuse a same out_trade_no to make a new UnifiedOrder.

**Comment by overtrue** [comment]
@0i

**Comment by 0i** [comment]
“out_trade_no” and “transaction_id”, as are the unique ID, so, out_trade_no not have the same, if you have the demand, please consider doing a correspondence between the database table.

**Comment by overtrue** [comment]
@acabin 是否能看明白中文？
