### ISSUE TITLE
  Symfony\Component\Cache\Simple\RedisCache 无法获取缓存

### ISSUE THREAD

**Issue by MaymayJay** [overtrue/wechat#1550]
## 我用的环境

PHP 版本：PHP 7.2.3 
overtrue/wechat 版本：4.0
框架名称：lumen 5.7

## 问题及现象

替换缓存之后，
![image](https://user-images.githubusercontent.com/24680551/57914663-ad1eaa00-78c1-11e9-90ba-22d1ca970697.png)

生成的缓存信息如下：
![image](https://user-images.githubusercontent.com/24680551/57926168-2a0b4d00-78dd-11e9-884a-eef4d7b98af2.png)
但是在 vendor/overtrue/wechat/src/Kernel/AccessToken.php 中却无法获取到值：

![image](https://user-images.githubusercontent.com/24680551/57926279-73f43300-78dd-11e9-9567-4b7e6ef513c8.png)

导致刷新api请求失败

**Comment by overtrue** [comment]
请更新到最新的 4.1.29 即可解决。
