### ISSUE TITLE
Fatal error: Interface 'Psr\SimpleCache\CacheInterface' not found in   /vendor/symfony/cache/Simple/AbstractCache.php on line 28

### ISSUE THREAD

**Issue by taojuntjpp** [overtrue/wechat#1551]
## 我用的环境

PHP 版本：PHP 7.2.14
overtrue/wechat 版本：4.1.23
是否使用了框架？框架名称： yaf

## 问题及现象
EasyWeChat\Kernel\Traits\InteractsWithCache.php 下使用了 `use Psr\SimpleCache\CacheInterface;` 
具体看下图，会导致报错

![image](https://user-images.githubusercontent.com/1578430/58679109-b2392a00-8394-11e9-82d5-307732fad87b.png)

**Comment by afuka** [comment]
去composer 下来 psr/simple-cache 即可，邮件回复了

**Comment by taojuntjpp** [comment]
> 去composer 下来 psr/simple-cache 即可，邮件回复了

谢谢 ，已解决
刚好 composer require psr/simple-cache 完，回来准备回复解决方法，就看到楼上的热心回复了 💯
