### ISSUE TITLE
 "The \"Symfony\\Component\\Cache\\Simple\\FilesystemCache\" class is deprecated since Symfony 4.3, use \"Symfony\\Component\\Cache\\Adapter\\FilesystemAdapter\" and type-hint for \"Symfony\\Contracts\\Cache\\CacheInterface\" instead."

### ISSUE THREAD

**Issue by weijer** [overtrue/wechat#1552]
## 我用的环境

PHP 版本：php 7.2
overtrue/wechat 版本：4.1.23
是否使用了框架？框架名称：sd

## 问题及现象

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

如果你不提供相关的代码，我不会做任何应答，直接 close，感谢！

**Comment by weijer** [comment]
symfony/cache 4.3 版本有问题

**Comment by weijer** [comment]
解决版本在composer.json 里面加入  "symfony/cache": "v4.2.*", 限制版本

**Comment by superong1024** [comment]
@weijer 这个办法有用"symfony/cache": "v4.2.*"， composer update

**Comment by superong1024** [comment]
> 解决版本在composer.json 里面加入 "symfony/cache": "v4.2.*", 限制版本

这个办法有用"symfony/cache": "v4.2.*"， composer update
