### ISSUE TITLE
关于升级Cache部份支持symfony 4.3 的建议

### ISSUE THREAD

**Issue by StartMoney** [overtrue/wechat#1560]
## 我用的环境

PHP 版本：7.2
overtrue/wechat 版本：4.1
是否使用了框架？框架名称：easyswoole 

## 问题及现象
因为项目中也用到symfony，在更新项目中 symfony 升到 4.3后，easywechat中的缓存无法正常使用。我的项目中替换了easywechat 的 cache为redis，而 symfony 4.3已经对simple-cache做了改动:
 * removed `psr/simple-cache` dependency, run `composer require psr/simple-cache` if you need it
 * deprecated all PSR-16 adapters, use `Psr16Cache` or `Symfony\Contracts\Cache\CacheInterface` implementations instead
 * deprecated `SimpleCacheAdapter`, use `Psr16Adapter` instead
所有simple目录的代码中已经加入了不建议使用的提示：
> @trigger_error(sprintf('The "%s" class is deprecated since Symfony 4.3, use "%s" and type-hint for "%s" instead.', RedisCache::class, RedisAdapter::class, CacheInterface::class), E_USER_DEPRECATED);

而easywechat核心库做了强制判断：
wechat/src/Kernel/Traits/InteractsWithCache.php

> public function getCache()
    {
        if ($this->cache) {
            return $this->cache;
        }
        if (property_exists($this, 'app') && $this->app instanceof ServiceContainer
            && isset($this->app['cache']) && $this->app['cache'] instanceof CacheInterface) {
            return $this->cache = $this->app['cache'];
        }
        return $this->cache = $this->createDefaultCache();
    }

> $this->app['cache'] instanceof CacheInterface 

这段代码强制判断了传入的cache是否为 Psr\SimpleCache\CacheInterface 的实例。

> setCache(CacheInterface $cache)
代码也强制指定了。
包括
> protected function createDefaultCache()
也是强制指定的 Simple 相关的实例。

所以导致无论如何替换都会一直notice：

> [The "Symfony\Component\Cache\Simple\FilesystemCache" class is deprecated since Symfony 4.3, use "Symfony\Component\Cache\Adapter\FilesystemAdapter" and type-hint for "Symfony\Contracts\Cache\CacheInterface" instead. at file:/var/www/code/vendor/symfony/cache/Simple/FilesystemCache.php line:21]

目前我只能修改：
wechat/src/Kernel/Traits/InteractsWithCache.php 
为调用 symfony 建议的class。

建议easywechat也做相应适配，或者升级，或者两者都支持。
感谢easywechat项目~~

**Comment by overtrue** [comment]
我可能要换一个缓存驱动了。

**Comment by terry8650** [comment]
> 我可能要换一个缓存驱动了。

那就换。。。我更新后也出现这问题了

**Comment by reatang** [comment]
冷静，兼容为主~

**Comment by terry8650** [comment]
> 冷静，兼容为主~

那也得解决这个问题。。。

**Comment by reatang** [comment]
> > 冷静，兼容为主~
> 
> 那也得解决这个问题。。。

正在商讨

**Comment by overtrue** [comment]
@terry8650 @StartMoney 麻烦帮忙试一下 dev-master 版本是否可以正常使用，如果没问题我就发版了。

**Comment by terry8650** [comment]
> @terry8650 @StartMoney 麻烦帮忙试一下 dev-master 版本是否可以正常使用，如果没问题我就发版了。
刚才用master测试了下没有再报错，应该可以了

**Comment by StartMoney** [comment]
> @terry8650 @StartMoney 麻烦帮忙试一下 dev-master 版本是否可以正常使用，如果没问题我就发版了。

测过了，dev-master没有报notice了

**Comment by overtrue** [comment]
OK 已经发版了。
