### ISSUE TITLE
component_verify_ticket 自定义处理的问题

### ISSUE THREAD

**Issue by cevin** [overtrue/wechat#1562]
## 我用的环境

PHP 版本：php7.3.4
overtrue/wechat 版本：4.1.8
是否使用了框架？框架名称：laravel/5.8

## 问题及现象

能否自定义component_verify_ticket的处理方式我需要和其他系统共享该值  且我自己的另外系统来接收component_verify_ticket并且存在数据库中的。代码中如何手动指component_verify_ticket咧？

**Comment by mingyoung** [comment]
`$app->verify_ticket->setTicket('TICKET');`

**Comment by bolechen** [comment]
> $app->verify_ticket->setTicket('TICKET');

请问这个方法目前还有效吗？

**Comment by overtrue** [comment]
@bolechen https://github.com/w7corp/easywechat/blob/develop/src/OpenWork/SuiteAuth/SuiteTicket.php#L51 有效

**Comment by bolechen** [comment]
> @bolechen https://github.com/w7corp/easywechat/blob/develop/src/OpenWork/SuiteAuth/SuiteTicket.php#L51 有效

收到，谢谢超哥，问题已解决，也给后来的同学提个醒：

component_verify_ticket 的有效期为 12 小时，长期有效，缓存默认只有 3600 秒，为避免有时缓存失效，导致请求 access_token 失败的情况，可以通过下面的方式自己维护 component_verify_ticket

我用的是 `overtrue/laravel-wechat`，通过 VerifyTicketRefreshedListener 可以自己记录最近的 component_verify_ticket，再通过以下 setTicket 在每次实例化前，手动设置。

```php
// 确认当前 component_verify_ticket
app('wechat.open_platform')->verify_ticket->getTicket();
// 自定义设置 component_verify_ticket
app('wechat.open_platform')->verify_ticket->setTicket('xxx');
```

**Comment by overtrue** [comment]
@bolechen 感谢老板！
