### ISSUE TITLE
Failed to cache access token.

### ISSUE THREAD

**Issue by php403** [overtrue/wechat#1567]
## 我用的环境

PHP 版本：7.1.3
overtrue/wechat 版本：
是否使用了框架？框架名称：tp6

## 问题及现象

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**
报错信息　Failed to cache access token.
代码截图　![image](https://user-images.githubusercontent.com/32252481/59812612-30a83c80-9341-11e9-97c4-56c8c09d449f.png)
尝试方法　1 设置目录读写权限　
![image](https://user-images.githubusercontent.com/32252481/59812656-59303680-9341-11e9-93c5-5fde27c226d7.png)
后
![image](https://user-images.githubusercontent.com/32252481/59812995-83362880-9342-11e9-9798-38c54222d095.png)
尝试修改成redis驱动,还是会抛出同样异常

**Comment by overtrue** [comment]
RedisAdapter 是哪里来的？什么版本？

**Comment by php403** [comment]
![image](https://user-images.githubusercontent.com/32252481/59813224-56364580-9343-11e9-9022-caf32f9e837a.png)
看Symfony4.3好像不能用这个了。主要问题还是缓存写不进。

**Comment by php403** [comment]
![image](https://user-images.githubusercontent.com/32252481/59814301-6819e780-9347-11e9-8f8f-f98443292ebb.png)
![image](https://user-images.githubusercontent.com/32252481/59814312-6f40f580-9347-11e9-987b-2b1c794afbab.png)

**Comment by php403** [comment]
暂时修改成了捕获该异常，等作者修改后,重写下缓存驱动
