### ISSUE TITLE
extension is null when calling `download video` in wechat.media

### ISSUE THREAD

**Issue by gabrieltong** [overtrue/wechat#157]
when downloading media , wechat try to guess the extension , and add the right extension .

when downloading a video media , the `guess` failed , and the extension is null . so the downloaded file name will be added a extra '.'

for example, if $MediaId(video) is `abcd`, the final url will be `abcd.`

if we can't get the extension , can we `not add the ext` ?

if the filename param contains a `ext` , can we trust it and  `not add the ext` ?

**Comment by gabrieltong** [comment]
`overtrue/wechat/src/Wechat/Media.php` , line `280`

**Comment by gabrieltong** [comment]
I test video by `mediainfo`, and video by `weixin` is mp4

![1f91e852-b92c-4412-9f40-823079fd4dc8](https://cloud.githubusercontent.com/assets/97657/11216816/3eb63268-8d88-11e5-9aec-77540d03034c.png)

**Comment by overtrue** [comment]
哈哈，下回用中文吧，我能看懂 :laughing:

**Comment by gabrieltong** [comment]
哈哈 ， 反正就是download视频多个 .

**Comment by gabrieltong** [comment]
微信现在这么牛 ，你的文档都是中英文 ，得跟上潮流啊
