### ISSUE TITLE
其他渠道生成的access_token怎么设置到easywechat？

### ISSUE THREAD

**Issue by cos800** [overtrue/wechat#1578]
## 我用的环境

PHP 版本：7.1.23
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：thinkphp

## 问题及现象

我们服务号的`access_token`保存在另一台服务器上，  
是另一个团队开发的一个服务，  
得从他们的接口去获取这个`access_token`，  
我这边并没有密钥，因为我这边直接去微信接口获取`access_token`就会导致他们的`access_token`失效。  
请问我要怎么把这个`access_token`传给`easywechat`？
原码里有看到
```
    /**
     * @param \EasyWeChat\Kernel\Contracts\AccessTokenInterface $accessToken
     *
     * @return $this
     */
    public function setAccessToken(AccessTokenInterface $accessToken)
    {
        $this->accessToken = $accessToken;

        return $this;
    }
```
但是没有文档实在不知道怎么用，
看起来不是简单的传入一个字符串，
而是得先继承一个接口。。。

**Comment by overtrue** [comment]
> 但是没有文档实在不知道怎么用
是你自己没认真看，不是没有文档哈：https://www.easywechat.com/docs/4.1/customize/access_token

**Comment by sn01615** [comment]
> > 但是没有文档实在不知道怎么用
> 
> 是你自己没认真看，不是没有文档哈：https://www.easywechat.com/docs/4.1/customize/access_token
> 
> > **[Access Token | EasyWeChat](https://www.easywechat.com/docs/4.1/customize/access_token)**Documentation for EasyWeChat.

这个在守护进程里 access_token 过期后就会自己去刷新，这是不被允许的，能否禁用自动刷新token？
或者刷新时使用自定义函数之类的？
