### ISSUE TITLE
两处代码php5.4才能运行

### ISSUE THREAD

**Issue by mickelfeng** [overtrue/wechat#158]
我使用的php版本是5.3.10 调用文件出错
1、
Wechat/Utils/SignGenerator.php
      public function onSortAfter(callable $callback) 中callable

解决办法：去掉 callable
2、
Wechat/Payment/UnifiedOrder.php 中$this 变量范围, 使用use的话也会报错的
Fatal error: Cannot use $this as lexical variable in 

        $signGenerator->onSortAfter(function(SignGenerator $that) {
            $that->key = $this->business->mch_key;
        });

解决办法：
  $tmp=$this;
        $signGenerator->onSortAfter(function(SignGenerator $that) use($tmp) {
            $that->key = $tmp->business->mch_key;
        });

**Comment by overtrue** [comment]
@mickelfeng 感谢反馈！https://github.com/overtrue/wechat/commit/5db4708f8410ca922dd02f4c2d31af225f360459

**Comment by phpyii** [comment]
php版本必须是 >= 5.5.9吗？5.4可以用吧？

**Comment by overtrue** [comment]
@phpyii 3.0 要求 >= 5.5.9, 2.1 >=5.3就好
