### ISSUE TITLE
ticket失效问题 不更新

### ISSUE THREAD

**Issue by chahualao** [overtrue/wechat#1580]
## 我用的环境

PHP 版本：7.32
overtrue/wechat 版本：4.1
是否使用了框架？框架名称：thinkphp5.1

## 问题及现象

使用JSSDK分享功能，定期分享失败，经调试 为ticket失效。
进入系统
`rm -rf easywechat/`
立马成功。期间并未在其他地方请求过ticket
猜测为本框架判断缓存时效的代码失效。

**Comment by zhangpf41** [comment]
我也出现同样的问题，

**Comment by hqweiyu** [comment]
> PHP version: 7.1
> Laravel: 5.5
> overtrue/wechat : 4.1
> 我也出现同样的问题，调用jssdk时出现invalid signature,跟踪代码，发现是ticket过期，暂时解决办法在调用buildConfig之前使用，$app->jssdk->getTicket(true)强制重新生成ticket。

亲测有效！

**Comment by overtrue** [comment]
更新到 4.1.27 了么

**Comment by chahualao** [comment]
composer下来的最新包

**Comment by zhangpf41** [comment]
是最新的4.1.27
![image](https://user-images.githubusercontent.com/10841391/60405352-28be8700-9be2-11e9-9349-c12472afbc24.png)

**Comment by overtrue** [comment]
@zhangpf41 麻烦测一下写入后的缓存 key 有效期是多少？

**Comment by zhangpf41** [comment]
我目前测试已过去2个小时了，得到的ticket还上相同的
![image](https://user-images.githubusercontent.com/10841391/60423821-92aa5100-9c21-11e9-8795-36a0d0df98d1.png)

**Comment by overtrue** [comment]
@zhangpf41 你是否有自定义缓存驱动，如果没有，请检查这里：https://github.com/overtrue/wechat/blob/master/src/BasicService/Jssdk/Client.php#L104

这行设置缓存时用的是官方返回的过期时间 - 500秒。

**Comment by zhangpf41** [comment]
我没有自定义缓存驱动，这是今天9：10刚测试，jssdk无法正常调用，提示“config:fail,Error: invalid signature”，ticket和昨天一样没有变化。如下图：
![image](https://user-images.githubusercontent.com/10841391/60475430-dea0d880-9ca9-11e9-865f-5265e9a928a5.png)

**Comment by overtrue** [comment]
@zhangpf41 加我  Q 44294631

**Comment by humengcn** [comment]
composer 包更新到最新版，出现了同样的问题

**Comment by overtrue** [comment]
@humengcn 多少版本号？

**Comment by humengcn** [comment]
4.1.27

**Comment by terry8650** [comment]
> @humengcn 多少版本号？

嗯，我也发现这问题了，就是上次更新缓存问题之后，日志确实没错误了，但ticket缓存这有问题

**Comment by overtrue** [comment]
@humengcn 更新到 4.1.28

**Comment by terry8650** [comment]
> @humengcn 更新到 4.1.28

现在没有4.1.28啊

**Comment by overtrue** [comment]
@terry8650 https://github.com/overtrue/wechat/releases 看完再说啊。。。你自己的 composer 镜像有延迟。。。

**Comment by zhangbaodong** [comment]
我已经用了最新的包，还是有问题
