### ISSUE TITLE
圖文消息報錯 : {"errcode":45162,"errmsg":"invalid type hint: [BjXa6a06523950]"}

### ISSUE THREAD

**Issue by polinwei** [overtrue/wechat#1582]
## 我用的环境

PHP 版本：7.3.6
overtrue/wechat 版本：4.0
是否使用了框架？ 沒有 框架名称：

## 问题及现象

easywechat.log:

<<<<<<<<
HTTP/1.1 200 OK
Connection: keep-alive
Content-Type: application/json; encoding=utf-8
Date: Sun, 30 Jun 2019 07:10:52 GMT
Content-Length: 64

{"errcode":45162,"errmsg":"invalid type hint: [BjXa6a06523950]"}
--------
NULL  
[2019-06-30 07:10:53] NULL.INFO: >>>>>>>>
GET /cgi-bin/user/get?access_token=23_e8x-OFLl3CZS2Oc-RezEwgT-tb2s52eMIQpELkszK6CojLxJ8hQOK4seJN3QzjMHDfdZSBivbYqL1NXlBPm0fSISAM2K8irb6OBR6uDelUWTOjQkidfaCP3xDUkM-tg_A4eBrz0rUVLTRgwHNTEcADAEKV HTTP/1.1
Host: api.weixin.qq.com
User-Agent: GuzzleHttp/6.3.3 curl/7.29.0 PHP/7.3.6

**Comment by overtrue** [comment]
光凭这个恐怕没有人能帮到你，请正确提问。

**Comment by polinwei** [comment]
謝謝您的提醒. 我的程式碼如下: 在 微信公众平台-公众平台测试账号系统 中是正常的, 可是在正式的公眾號時, 就報錯 {"errcode":45162,"errmsg":"invalid type hint: [BjXa6a06523950]"}

`// Include 微信外掛API
require_once WPWX_PLUGIN_DIR . '/vendor/autoload.php';
use EasyWeChat\Factory;
$ewcConfig= (include WPWX_PLUGIN_DIR . '/includes/EasyWeChat-config.php');
$app= Factory::officialAccount($ewcConfig);
$openid='ab9Ek1V2nZrK8V123489XQgrCvvE';

    $items = [
        new NewsItem([
            'title'       => 'Hi!! Easy Wechat！',
            'description' => '歡迎使用 Easy Wechat！',
            'url'         => 'http://wx.com/2019/06/19/hello-world/',
            'image'       => 'http://wx.com/wp-content/uploads/2019/06/city-street-1246870_640.jpg',
        ]),
    ];
    $news = new News($items);
    $result = $app->customer_service->message($news)->to($openid)->send();
`

**Comment by overtrue** [comment]
@polinwei 这个是不是因为 #1583 这个？
