### ISSUE TITLE
可否出NodeJS SDK呢，还是有这需求

### ISSUE THREAD

**Issue by Adgeros** [overtrue/wechat#1591]

**Comment by overtrue** [comment]
哈哈，精力有限哦兄弟，我可以提供模块设计指导，但是写这个东西我还真的抽不出时间来做哦。

**Comment by overtrue** [comment]
还有一点是我自己在 Node 方面水平也有限，所以没有这个能力把它做得很好。

**Comment by Adgeros** [comment]
> 还有一点是我自己在 Node 方面水平也有限，所以没有这个能力把它做得很好。

了解，我抽时间写一下
