### ISSUE TITLE
小微商户获取证书异常

### ISSUE THREAD

**Issue by lixiaolong2** [overtrue/wechat#1592]
## 我用的环境

PHP 版本：7.2
overtrue/wechat 版本：4.1.30
是否使用了框架？框架名称：thinkphp5.0.24

## 问题及现象

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

如果你不提供相关的代码，我不会做任何应答，直接 close，感谢！

调用获取平台证书接口之前，请前往微信支付商户平台升级API证书，升级后才可成功调用本接口。

// 获取到证书后可以做缓存处理，无需每次重新获取
$response = $app->certficates->get($returnRaw = false);
调用这句的时候就出现以下错误了。api证书已经升级。

[64] ErrorException in BaseClient.php line 26
EasyWeChat\Payment\Kernel\BaseClient and EasyWeChat\Kernel\Traits\HasHttpRequests define the same property ($defaults) in the composition of EasyWeChat\MicroMerchant\Kernel\BaseClient. However, the definition differs and is considered incompatible. Class was composed

**Comment by lixiaolong2** [comment]
`    protected static $app_xw;

    // 小微商户
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //var_dump(config('payxw'));
        self::$app_xw = Factory::microMerchant(config('payxw'));
    }
    
    public function index(){
        // 获取到证书后可以做缓存处理，无需每次重新获取
        $response = self::$app_xw->certficates->get( $returnRaw = false);
    }`

**Comment by lixiaolong2** [comment]
sodium扩展7.2和7.3都安装完毕。
但是7.2还是报错，升级到7.3没问题。但是项目又必须使用7.2

**Comment by overtrue** [comment]
@wannanbigpig 帮忙看一下？

**Comment by wannanbigpig** [comment]
@overtrue 收到

**Comment by wannanbigpig** [comment]
@lixiaolong2 问题已经修复，你拉下最新的版本就行

**Comment by lixiaolong2** [comment]
> @ lixiaolong2问题已经修复，你拉下最新的版本就行

测试没问题，谢谢
