### ISSUE TITLE
企业微信

### ISSUE THREAD

**Issue by yaqianghan** [overtrue/wechat#1595]
## 我用的环境

PHP 版本：7.2.*
overtrue/wechat 版本：4.1
是否使用了框架？框架名称：Laravel5.7

## 问题及现象

请问是否支持企业微信相关的接口？

**Comment by yaqianghan** [comment]
比如企业微信登陆

**Comment by her-cat** [comment]
https://www.easywechat.com/docs/4.1/wework/index
