### ISSUE TITLE
一直有个疑问，oauth. scopes配置为什么是个数组？

### ISSUE THREAD

**Issue by cos800** [overtrue/wechat#1598]
当`scopes`为`['snsapi_base']`时是获取openid；
当`scopes`为`['snsapi_userinfo']`时是获取用户信息；

当`scopes`为`['snsapi_base', 'snsapi_userinfo']`是什么作用？

我这边测试，好像第一次跳转会获取用户信息，再次跳转就变成获取openid？

但是在微信官方文档里好像没有讲到这种用法。

**Comment by overtrue** [comment]
oauth 协议里 scopes 就是支持多个的

**Comment by WenkeChen** [comment]
> oauth 协议里 scopes 就是支持多个的

+1啊，我觉得这个问题非常好。
oauth协议支持多个，但是能不能结合微信授权讲一讲传一个和多个有啥区别呢？毕竟snsapi_userinfo需要用户主动授权。
