### ISSUE TITLE
jssdk返回json timestamp的s大小写有问题

### ISSUE THREAD

**Issue by mi-autumn** [overtrue/wechat#1599]
![image](https://user-images.githubusercontent.com/38519056/61032615-5f6f7b00-a3f4-11e9-889e-c6c9c7ccc711.png)
```
console.log(data.timeStamp);
console.log(data.timetamp);
undefined
(index):77 1562831652
```
前端页面要求的timeStamp参数

**Comment by mingyoung** [comment]
调用 `bridgeConfig()` 方法即可
