### ISSUE TITLE
微信公众号绑定的一点问题，请教。

### ISSUE THREAD

**Issue by lyongde** [overtrue/wechat#16]
hi ,overtrue，成功使用wechat框架在微信内绑定H5系统内的用户后(用户表存放openid)，现在需要在微信内判断如果用户已经绑定过openid，则自动登陆。现在的情况是，H5使用Ajax取值时，初次调用$auth->authorize()会服务端会重定向，导致H5端无法取值，这种情况要怎么处理呢？

**Comment by overtrue** [comment]
@lyongde Ajax 请求的时候，你应该要判断当前用户是否登录，Ajax是会带sessionid的，所以你可以用sessionid来跳过这个授权过程：

```php
$user = Session::get('logged_user');
        
        if (empty($user)) {
            $user = $auth->authorize();
            Session::set('logged_user', $user);
        }

        // xxx
```

**Comment by lyongde** [comment]
嗯，感谢回复。
在微信H5内，只要用户已经使用微信绑定过H5用户名，就让用户自动登陆。但是用户第N次进入微信是没有会话保持的，服务端要取到用户的openid(snsapi_base授权)还是需要重新获得1次授权，这样才能判定拿openid和数据库对比判定用户是否已经绑定，才能接下来的操作，不知道我理解得对不对呢？

**Comment by zsj1029** [comment]
同问，snsapi_base直接是得不到openid的，至于是否跳转授权页面不太清

**Comment by overtrue** [comment]
> 只要用户已经使用微信绑定过H5用户名，就让用户自动登陆。但是用户第N次进入微信是没有会话保持的

对，确实是这样，但是你不可能在用户没进页面之前就ajax对不，肯定是先进入一个你的页面，你的页面里才可能有ajax操作，那么就是说，ajax操作肯定是不会发生在第一次请求，第一次请求绝对是打开你的页面，那么在打开页面之前你就应该做授权。

这里的授权，可能用户感觉不到，因为如果你只是 `snsapi_base ` 的方式授权的话，第二次是静默授权，就是说不向用户显示绿色的授权页面直接跳一下就过去了，但是完成了授权的动作，所以你就获取到了 `openid` , 写入 `session`, 完成了登录，所以不会出现你说的情况的。

**Comment by overtrue** [comment]
@zsj1029 任何一种授权都会有openid, http://mp.weixin.qq.com/wiki/17/c0f37d5704f0b64713d5d2c37b468d75.html

> 1、以snsapi_base为scope发起的网页授权，是用来获取进入页面的用户的openid的，并且是静默授权并自动跳转到回调页的。用户感知的就是直接进入了回调页（往往是业务页面）
> 2、以snsapi_userinfo为scope发起的网页授权，是用来获取用户的基本信息的。但这种授权需要用户手动同意，并且由于用户同意过，所以无须关注，就可在授权后获取该用户的基本信息。
> 3、用户管理类接口中的“获取用户基本信息接口”，是在用户和公众号产生消息交互或关注后事件推送后，才能根据用户OpenID来获取用户基本信息。这个接口，包括其他微信接口，都是需要该用户（即openid）关注了公众号后，才能调用成功的。

**Comment by overtrue** [comment]
@lyongde @zsj1029 还有什么问题没?

**Comment by zsj1029** [comment]
snsapi_base直接是得不到openid的
我的意思，微信跳过来的时候不给你openid的
必须再用微信给的code去查询openid

如果需要更多用户信息，必须用snsapi_userinfo发起授权
然后用code获取access_token，然后再去作进一步查询
不知道我这样理解对不对

**Comment by overtrue** [comment]
@zsj1029 snsapi_base 与 snsapi_userinfo 的区别就是:

- snsapi_base 用 code 得到 access_token 的时候就同时得到 openid;
- snsapi_userinfo 用 code 得到 access_token 的时候同时也会得到openid，只不过你要拿用户信息还需要多一步用 access_token 去取用户信息而已。

也就是说不管用哪种方式，都会在用 code 得到 access_token 的时候就同时得到 openid。

**Comment by caodixy** [comment]
想请教下，如果用户 进入页面，授权后，停留太久了，session失效了，后续是可能出现 ajax 是第一次请求的情形，有什么好的处理建议吗
