### ISSUE TITLE
官网是不是挂了， 没开代理，不能访问

### ISSUE THREAD

**Issue by wang199296** [overtrue/wechat#1600]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：
是否使用了框架？框架名称：

## 问题及现象

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

如果你不提供相关的代码，我不会做任何应答，直接 close，感谢！

**Comment by wang199296** [comment]
https://www.easywechat.com/

**Comment by overtrue** [comment]
服务器到期了，已经搬完家了哈。
