### ISSUE TITLE
建议access_token存入时加入过期时间戳数据

### ISSUE THREAD

**Issue by anyforever** [overtrue/wechat#1603]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：5.0
是否使用了框架？框架名称：Laravel 5.8

## 问题及现象

```
    /**
     * @param string $token
     * @param int    $lifetime
     *
     * @return \EasyWeChat\Kernel\Contracts\AccessTokenInterface
     *
     * @throws \Psr\SimpleCache\InvalidArgumentException
     */
    public function setToken(string $token, int $lifetime = 7200): AccessTokenInterface
    {
        $result = $this->getCache()->set($this->getCacheKey(), [
            $this->tokenKey => $token,
            'expires_in' => $lifetime,
            **'expires_timestamp' => time() + $lifetime,**  //建议增加数据过期时间数据
        ], $lifetime - $this->safeSeconds);
        
        if (!$result) {
            throw new RuntimeException('Save access_token to cache failed');
        }

        return $this;
    }

```
由于微信token每天的请求次数限制，以及不能多端各自发起请求，需要自己所有的服务有一个统一管理此token的中控服务，加入此过期时间戳之后，非中控服务，可以自己从中控取得token之后，按照中控的过期时间，自己缓存起来，这样就不用频繁的访问中控服务了，方便数据的使用。
上面存储的expires_in，只能知道缓存了多少秒，并不知道什么时候存的，什么时候到期，所以感觉并没有什么实际使用意义。
另外个人感觉safeSeconds这个安全秒数设定的有些过大，120s足矣。昨天测试中由于拿不到token的过期时间，所以在非主服务中设定的过期时间比较短，一直报“Save access_token to cache failed”错误，后来发现是这里又减去了个安全秒数500导致的

**Comment by overtrue** [comment]
请使用模块替换功能自己定义缓存写入逻辑即可:

https://www.easywechat.com/docs/4.1/customize/cache
