### ISSUE TITLE
不同微信获得的code取换取的openid相同?

### ISSUE THREAD

**Issue by aoeng** [overtrue/wechat#1609]
## 我用的环境

PHP 版本：7.2
overtrue/wechat 版本：4.1
是否使用了框架？框架名称：
Laravel
## 问题及现象
1. 本地环境内网穿透
2. 小程序,两个微信账号两台电脑
```
$code = $request->input('code');
 $response = $this->app->auth->session($code);
info('登录信息', $response['openid']);
```
两个微信通过开发者工具和真机测试获得的openid相同!
一脸懵逼不知道怎么回事...

**Comment by overtrue** [comment]
绝对不可能。

**Comment by aoeng** [comment]
@overtrue  可是我遇到了啊,我不知道怎么办啊,很急啊,懵逼啊,这可如何解决啊???

**Comment by almas1992** [comment]
> @overtrue 可是我遇到了啊,我不知道怎么办啊,很急啊,懵逼啊,这可如何解决啊???

一步步查，从自己的代码开始到框架源码一步步查，急懵没用的
