### ISSUE TITLE
array_filter导致的接口请求失败

### ISSUE THREAD

**Issue by graypants** [overtrue/wechat#1610]
## 我用的环境

PHP 版本：7.2.12
overtrue/wechat 版本：4.0
是否使用了框架？框架名称：Laravel5.7

## 问题及现象

EasyWeChat\Payment\Kernel\BaseClient 80行
array_filter会过滤掉$params中值为0的项，导致微信免押租借完结订单接口调用失败

**Comment by mingyoung** [comment]
https://github.com/overtrue/wechat/pull/1611/files
@garveen 试试这样改能不能用？
