### ISSUE TITLE
前后端分离的系统，微信支付，`spbill_create_ip `值的自动获取函数无法获取前端的 ip 地址。

### ISSUE THREAD

**Issue by balloontmz** [overtrue/wechat#1613]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：5.0
是否使用了框架？框架名称：laravel

## 问题及现象

前后端分离的系统，微信支付，`spbill_create_ip `值的自动获取函数无法获取前端的 ip 地址。
网上找了个代替函数才解决。。。

**Comment by ljyljy0211** [comment]
你自己服务器获取的方式要改一下

**Comment by overtrue** [comment]
前后端分离请自己获取并传参。
