### ISSUE TITLE
退款接口不支持自定义notify_url参数

### ISSUE THREAD

**Issue by ybchenjie** [overtrue/wechat#1614]
## 我用的环境

PHP 版本：5.6.40
overtrue/wechat 版本：3.1.10
是否使用了框架？框架名称：laravel 5.2

## 问题及现象

退款接口不支持自定义notify_url参数。

微信接口是支持自定义通知url参数的，麻烦添加该参数
https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_4

微信接口现在支持该参数
![image](https://user-images.githubusercontent.com/9395358/61946549-7bb70e80-afd5-11e9-8c4b-eee304b57287.png)

项目里不支持该参数，
// 参数列表写死了不支持
![image](https://user-images.githubusercontent.com/9395358/61946460-3b579080-afd5-11e9-9261-268a59ecc841.png)

// 也没有了
![image](https://user-images.githubusercontent.com/9395358/61946506-532f1480-afd5-11e9-867f-42b095c5cb61.png)

**Comment by ybchenjie** [comment]
临时用了解决办法，还望大佬官方修复啊

自定义API子类，然后 override refund方法
![image](https://user-images.githubusercontent.com/9395358/61989398-5243c480-b061-11e9-8c3f-65a62953a914.png)

然后在初始化 Application的时候，载入自己的 API 类
![image](https://user-images.githubusercontent.com/9395358/61989418-8b7c3480-b061-11e9-9bac-655de6fa4c53.png)

然后正常调用就好了
![image](https://user-images.githubusercontent.com/9395358/61989430-ac448a00-b061-11e9-8a4a-6e75d603dfb1.png)

**Comment by mingyoung** [comment]
版本过于遥远，不再维护，自行自定义实现哈
