### ISSUE TITLE
素材管理接口出错

### ISSUE THREAD

**Issue by Devin001** [overtrue/wechat#162]
素材管理接口，在上传图片的时候，出现

array(2) {
  ["errcode"]=>
  int(47001)
  ["errmsg"]=>
  string(40) "data format error hint: [mlCGka0203ent1]"
}

**Comment by overtrue** [comment]
这么提问谁能帮忙你解答，基本的上下文都不提供，你的调用方式、传的什么图片、多大，这些基本信息你都不提供我怎么知道你这是为啥报错哇。:sweat:

**Comment by yedong0839** [comment]
当使用$media->forever()->image($imagePath);就会返回 解析JSON/XML内容错误；
但使用$media->image($imagePath);一切正常；
请问这是何解？
