### ISSUE TITLE
AccessToken Expired Error Code

### ISSUE THREAD

**Issue by palmtale** [overtrue/wechat#163]
Could you please update the AccessToken Expired  ErrorCode from 40001 to 42001.
Check the global return code here: http://mp.weixin.qq.com/wiki/17/fa4e1434e57290788bde25603fa2fcbd.html
As the doc said, 40001 is for error appSecret, so, it would make nothing better after retring.

**Comment by palmtale** [comment]
In overtrue/wechat/src/Wechat/Http.php

**Comment by overtrue** [comment]
@palmtale 我是中国人，可以用中文。

> 40001：获取access_token时AppSecret错误，或者access_token无效。请开发者认真比对AppSecret的正确性，或查看是否正在为恰当的公众号调用接口
> 42001：不合法的凭证类型

这俩其实不一样，第一个是token无效，第二个是appid与appsecret不正确的意思吧（我的理解）

**Comment by palmtale** [comment]
我知道你是中国人呀。咱这不用老外的破玩儿意儿么。 不过，安正超像是韩国名儿。
那请看我下文的两句log（发生的情景就是：本来是有效的，过长时间后抛这个错啊）:
[2015-11-16 12:13:14] local.ERROR: Push job crashed. {0} ["[object] (Overtrue\\Wechat\\Exception(code: 42001): [Wechat]access_token超时，请检查access_token的有效期，
请参考基础支持-获取access_token中，对access_token的详细机制说明 at /home/urbem/sites/vendor/overtrue/wechat/src/Wechat/Http.php:115)"]
[2015-11-16 12:13:17] local.ERROR: Push job crashed. {0} ["[object] (Overtrue\\Wechat\\Exception(code: 42001): [Wechat]access_token超时，请检查access_token的有效期，
请参考基础支持-获取access_token中，对access_token的详细机制说明 at /home/urbem/sites/vendor/overtrue/wechat/src/Wechat/Http.php:115)"]

**Comment by overtrue** [comment]
哈哈，你的报错没提供任何有效的信息哦

**Comment by palmtale** [comment]
再看下，是github对 中括号有转译。  上文双引号和左括号间是有个  中括号括着object的

**Comment by palmtale** [comment]
@overtrue 上面你贴出来的两个code的解释和微信当前的不同，点进去看一下。说明他们有了更新。

**Comment by overtrue** [comment]
@palmtale 我是从他们的文档贴过来的，证明他们的代码里报的与文档不一样

**Comment by palmtale** [comment]
@overtrue 哦，看来得实测确定下。

**Comment by overtrue** [comment]
@palmtale https://github.com/overtrue/wechat/releases/tag/2.1.25
请更新

**Comment by palmtale** [comment]
谢谢。
其实已经自己先改后发布，但毕竟改第三方库我得自己维护，所以还是来这给你提bug了。

**Comment by overtrue** [comment]
@palmtale 感谢！
