### ISSUE TITLE
小程序统一消息发送接口跳转到网页失效

### ISSUE THREAD

**Issue by zhongjq** [overtrue/wechat#1634]
## 我用的环境

* PHP 版本：
* overtrue/wechat 版本：
* 是否使用了框架？框架名称：
laravel 
## 问题及现象
EasyWeChat\MiniProgram\UniformMessage\Client  统一消息发送接口，内部自动加上小程序的app_id，导致我想调用接口跳转到网页失效，我注释了这行代码就可以跳转到网页，这里的逻辑可以优化一下，如果设置了小程序路径又未设置app_id，才自动加上app_id

![image](https://user-images.githubusercontent.com/1228323/62860844-192f7380-bd34-11e9-98f3-9bc5ee29f0cc.png)

**Comment by zhongjq** [comment]
```php
if (empty($params['miniprogram']['appid']) && !empty($params['miniprogram']['pagepath'])) {
            $params['miniprogram']['appid'] = $this->app['config']['app_id'];
}
```
建议代码修改成这样，兼容性好点

**Comment by overtrue** [comment]
https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/uniform-message/uniformMessage.send.html

官网要求 appid 必传。

**Comment by zhongjq** [comment]
官方文档有点错误，我验证过pagepath设置了appid才必须，只设置url不设置pagepath，appid可以不传，不然url不生效，只会跳转到小程序首页
