### ISSUE TITLE
[Wechat]不合法的oauth_code' in /src/Wechat/Http.php:124

### ISSUE THREAD

**Issue by tyronewo** [overtrue/wechat#164]
时不时的会报一个这样的错，用的是默认的授权逻辑，调authorize(); 感觉像是前一次获得的code 还没有用就有请求获得后一个code，然后导致前一个失效，不知道有没有人遇到过？一般都怎么处理啊？

**Comment by tyronewo** [comment]
已解决。

**Comment by motionlife** [comment]
@tyronewo 请问您如何解决的 我一直都是40029 不合法的oauth_code
