### ISSUE TITLE
微信授权，页面上会显示很长的英文redirecting  to http：// xxxx，很影响用户体验，有没有什么方法可以去掉，保留空白页，或者允许自定义显示内容

### ISSUE THREAD

**Issue by 1919141018** [overtrue/wechat#1649]
## 我用的环境

* PHP 版本：7.3
* overtrue/wechat 版本：最新
* 是否使用了框架？框架名称：thinkphp

**Comment by overtrue** [comment]
把你的 return $response 改成 `$response->send(); exit;` 就好了

**Comment by 1919141018** [comment]
解决了

**Comment by terry8650** [comment]
> 把你的 return $response 改成 `$response->send(); exit;` 就好了

这样是能解决不出那个页面了，但在tp6最新版中，跳转到callback后会导致之前设置的session丢失
