### ISSUE TITLE
composer 安装后，调用公众号发送消息提示 'Psr\SimpleCache\CacheInterface' not found

### ISSUE THREAD

**Issue by cc2415** [overtrue/wechat#1651]
## 我用的环境

* PHP 版本：7.2
* overtrue/wechat 版本：4.0
* 是否使用了框架？框架名称：thinkphp5

## 问题及现象
composer 安装 后
调用公众号发送模板消息 ，报 'Psr\SimpleCache\CacheInterface' not found
不知道是我composer出了问题还是咋的
我的调用方式是：
$config = $this->config;
        $app = Factory::officialAccount($config);
        $shortId = $this->WC_SHORT_ID;
        $app->template_message->addTemplate($shortId);
        $now = date('Y-m-d H:i:s');
        $res=$app->template_message->send([
            'touser' => $openid,
            'template_id' => $shortId,
            'url' => 'http://'.$_SERVER['HTTP_HOST'].'/wxgzh/index.html',
            'data' => [
                'first' => '您的文章被转发了',
                'Good' => "被转发标题",
                'contentType' => "您的文章在被转发了",
                'remark' => '',
            ]
        ]);

最后我自己重新compser安装了psr/simple-cache才可以

**Comment by mingyoung** [comment]
原因是 `symfony/cache` 的某个版本修改导致的。


> 最后我自己重新compser安装了psr/simple-cache才可以

或者升级 EasyWeChat 到最新版本即可
