### ISSUE TITLE
【消息】数据库查询无法返回结果

### ISSUE THREAD

**Issue by Moodyqiqi** [overtrue/wechat#1653]
## 我用的环境

* PHP 版本：7.1.30
* overtrue/wechat 版本：4.4
* 是否使用了框架？框架名称：否
原本的目的是利用用户在公众号留言，返回在数据库中匹配的内容组合成【图文消息】，
**如果单独使用文件进行库查询可以正常返回结果，**但是如果放在消息控制里面会报错，微信不会返回任何内容，不会提示如：‘该公众号提供的服务出现故障，请稍后再试’
**不使用继承，创建新的数据库实例，微信也无法返回结果**
**另外，我如果把数据库连接放在查询操作的方法里面，却可以正常返回结果，**
**所有操作，如果单独使用，可以正常返回结果**
日志记录的错误信息：
`NULL.ERROR: 3D000: SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected {"code":"3D000","message":"SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected"`
消息控制：
`$app->server->push(function ($message) {
	switch ($message['MsgType']) {
		case 'text':
			$mes = new \controller\wechat\MessageController;
			return $mes->main($message['Content']);
			break;
		default:
			return ;
			break;
	}
});
`
数据查询
`namespace controller\wechat;
use EasyWeChat\Kernel\Messages\News;
use EasyWeChat\Kernel\Messages\NewsItem;
class MessageController extends \controller\PDOController
{
	public function main($text=null)
	{
		switch ($text) {
			case strpos($text, '@') !== false:
				$news = new NewsItem($this->getQuery(mb_substr($text, 1)));
				return new News([$news]);
				break;
			default:
				return $this->default();
				break;
		}
	}

	public function getQuery($title=null)
	{
		if ( !isset($title) ) {
			return ["title"=>"title","url"=>"url","image"=>"image","description"=>"description"];
		}
		$sql = "SELECT title, url, image, description FROM article WHERE title LIKE :title LIMIT 1";
		$db = new \controller\common\DBController;
		$title = ["title"=>"%".$title."%"];
		$res = $db->query($sql, $title);
		$res = reset($res);
	}
}
/*$a = new MessageController;
$title = $_GET['title'];
$test = $a->main($title);
var_dump($test);*/
`
数据库连接配置：
`namespace controller;
class PDOController
{
	protected $dbpdo;
	public function __construct(){
		// 直接链接数据库
		$this->dbpdo = pdo_connect();
	}
	public function query($query, $args = []){
		$query = trim($query);
		try {
			if (strpos( strtoupper($query), "SELECT" ) === 0 ) {
				$stmt = $this->dbpdo->prepare($query);
				$stmt->execute($args);
				$this->rowCount = $stmt->rowCount();
				$rows = $stmt->fetchAll(\PDO::FETCH_CLASS);
				$collection = [];
				foreach ($rows as $key => $row) {
					$collection[$key] = (array) $row;
				}
				return $collection;
			} else {
				$stmt = $this->dbpdo->prepare($query);
				$stmt->execute($args);
				return $stmt->rowCount();
			}
		} catch (PDOException $e) {
			return $e->getMessage();
		}
	}
}
`

**Comment by overtrue** [comment]
这和 SDK 无关，是你的数据库连接逻辑的问题
