### ISSUE TITLE
The directory "C:\Windows\TEMP" is not writable.

### ISSUE THREAD

**Issue by miaotiao** [overtrue/wechat#1658]
## 我用的环境

* PHP 版本：5.6.30
* overtrue/wechat 版本：3.3.33
* 是否使用了框架？框架名称：thinkphp 3.2.3
* 其他：IIS 7.5 window2008 R2

## 问题及现象

报错： The directory "C:\Windows\TEMP" is not writable.
![image](https://user-images.githubusercontent.com/28383349/63422346-c4c77a80-c43c-11e9-913a-51f8ef659823.png)

是调用 Application->js;报错的

**Comment by almas1992** [comment]
`not writable` 这么明显错误提示，去看看文件夹属性是不是"只读"；
然后 [百度](https://baidu.com)，[必应](https://cn.bing.com)，[谷歌](https://google.com) 都值得你用一用

**Comment by miaotiao** [comment]
嗯，谢谢回复。我搜过这个问题，网上给了两种答案：1.是修改该目录的权限。但是由于该目录在C盘以及还是一个系统目录，我担心修改其权限，会有其他未知问题，所以没敢修改。2.有人建议直接修改 vendor\overtrue\wechat\src\Foundation\Application.php 里面的 registerBase() 方法，但是这样的做法治标不治本。所以故有此提问，还望您有所指点。

**Comment by almas1992** [comment]
> 嗯，谢谢回复。我搜过这个问题，网上给了两种答案：1.是修改该目录的权限。但是由于该目录在C盘以及还是一个系统目录，我担心修改其权限，会有其他未知问题，所以没敢修改。2.有人建议直接修改 vendor\overtrue\wechat\src\Foundation\Application.php 里面的 registerBase() 方法，但是这样的做法治标不治本。所以故有此提问，还望您有所指点。

TEMP目录一般是缓存目录，改权限只要不改成不可写应该是不会出问题的

**Comment by overtrue** [comment]
https://www.easywechat.com/docs/4.1/customize/cache

你的缓存目录不可写，那么你可能需要自己配置缓存实现。

**Comment by miaotiao** [comment]
不知道是不是只有我的缓存目录出了这个不可写的问题？如果不是的话，是不是增加一个配置缓存目录这样更好一点呢？

**Comment by miaotiao** [comment]
嗯，正准备动手实现😁
