### ISSUE TITLE
第三方平台获取授权方实例时需传refreshToken，请问在哪里获得？

### ISSUE THREAD

**Issue by tomener** [overtrue/wechat#1661]
## 我用的环境

* PHP 版本：7.3
* overtrue/wechat 版本：4.2.2
* 是否使用了框架？框架名称：否

## 问题及现象

获取授权方实例
```// 代公众号实现业务
$officialAccount = $openPlatform->officialAccount(string $appId, string $refreshToken);
// 代小程序实现业务
$miniProgram = $openPlatform->miniProgram(string $appId, string $refreshToken);
```

**Comment by chengxiansheng** [comment]
授权的时候拿到自己保存好呀！
![image](https://user-images.githubusercontent.com/13652575/63572576-c49eba80-c5b5-11e9-98ca-feb596b885a9.png)

**Comment by mingyoung** [comment]
![image](https://user-images.githubusercontent.com/6228858/64113081-e5d48780-cdbb-11e9-9457-ab0fddad01ee.png)

授权过程中需要自己保存下来，参考链接：

- https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1453779503&token=&lang=

- https://www.easywechat.com/docs/4.1/open-platform/index
