### ISSUE TITLE
小程序客服 图文消息 errcode":45162,"errmsg":"invalid type hint

### ISSUE THREAD

**Issue by hoseadevops** [overtrue/wechat#1671]
## 我用的环境

* PHP 版本："php": "^7.1.3",
* overtrue/wechat 版本："overtrue/laravel-wechat": "~5.0",
* 是否使用了框架？框架名称： "laravel/framework": "5.8.*",

## 问题及现象

  小程序客服回复文本消息正常回复
  代码

`$app->server->push(function($message){

            \Log::info(__METHOD__,[1, $message]);

            $defaultMessage = new Text("感谢您使用~ \n\n 免分享通道回复 1 \n\n 欢迎您在这里提出意见~");
            $app = \EasyWeChat::miniProgram();

            if($message['Content'] == 1)
            {
                $url = "https://www.xxxxxxxxxxx.com/wechat/pay";
                $image = "https://www.xxxxxxxxxxx.com/wechat.png";
                $items = [
                    new NewsItem([
                        'title'       => '免分享通道',
                        'description' => '测试是测试',
                        'url'         => $url,
                        'image'       => $image,
                    ]),
                ];
                $defaultMessage = new News($items);
            }

            $result = $app->customer_service->message($defaultMessage)->to($message['FromUserName'])->send();

            \Log::info(__METHOD__,[2, $result]);

            return true;
        });`

回复图文消息报错日志：

==> /home/www.xxxxxxxxxxx.com/storage/logs/hosea-2019-08-29.log <==
[2019-08-29 08:23:19] production.INFO: App\Http\Controllers\{closure} [1,{"ToUserName":"gh_5877004ffa33","FromUserName":"oYluB4um2fgS0UV_n6KmgBtPZRaa","CreateTime":"1567066998","MsgType":"text","Content":"1","MsgId":"22435004367861595"}] []

==> /home/www.xxxxxxxxxxx.com/storage/logs/wechat.log <==
[2019-08-29 08:23:19] NULL.DEBUG: >>>>>>>>
POST /cgi-bin/message/custom/send?access_token=22_FqhOEu6zW_HVkpwC73HXFvDP_ALzjdLDWruhR8Y_D5SNiFn0jHVhWCUwzPYIgmxjAn3mMMkb_RPN77bP9ffZ0lct08YKTalUtddH4nAHcwwlfsP4Y8rXhvbS1lpk8YuhFsxcRxyrXtz_ouOGOCHjAHAGUZ HTTP/1.1
Host: api.weixin.qq.com
Content-Length: 261
User-Agent: GuzzleHttp/6.3.3 curl/7.29.0 PHP/7.3.5
Content-Type: application/json

{"msgtype":"news","touser":"oYluB4um2fgS0UV_n6KmgBtPZRYs","news":{"articles":[{"title":"免分享通道","description":"测试测试","url":"https:\/\/www.xxxxxxxxxxx.com\/wechat\/pay","picurl":"https:\/\/www.xxxxxxxxxxx.com\/wechat.png"}]}}
<<<<<<<<
HTTP/1.1 200 OK
Connection: keep-alive
Content-Type: application/json; encoding=utf-8
Date: Thu, 29 Aug 2019 08:23:19 GMT
Content-Length: 64

{"errcode":45162,"errmsg":"invalid type hint: [z_3REa09994100]"}
--------
NULL

==> /home/www.xxxxxxxxxxx.com/storage/logs/hosea-2019-08-29.log <==
[2019-08-29 08:23:19] production.INFO: App\Http\Controllers\{closure} [2,{"errcode":45162,"errmsg":"invalid type hint: [z_3REa09994100]"}] []

**Comment by hoseadevops** [comment]
无论海外账号还是国内账号 小程序客服 貌似 只能回复文本 用第三方 芝麻小客服 可以实现 其他类型回复

**Comment by overtrue** [comment]
https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/customer-message/customerServiceMessage.send.html

小程序客服消息根本没有 news 这种类型啊

**Comment by hoseadevops** [comment]
> https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/customer-message/customerServiceMessage.send.html
> 
> 小程序客服消息根本没有 news 这种类型啊
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/babc525f57941f447a01ce01ac2530f8a641d986/68747470733a2f2f7265732e77782e71712e636f6d2f612f77785f6665642f6173736574732f7265732f4e5449344d5755352e69636f">**[customerServiceMessage.send | 微信开放文档](https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/customer-message/customerServiceMessage.send.html)**微信开发者平台文档

有 link 类型 貌似 sdk没有封装~

**Comment by hoseadevops** [comment]
> https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/customer-message/customerServiceMessage.send.html
> 
> 小程序客服消息根本没有 news 这种类型啊
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/babc525f57941f447a01ce01ac2530f8a641d986/68747470733a2f2f7265732e77782e71712e636f6d2f612f77785f6665642f6173736574732f7265732f4e5449344d5755352e69636f">**[customerServiceMessage.send | 微信开放文档](https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/customer-message/customerServiceMessage.send.html)**微信开发者平台文档

有 link 类型 貌似 sdk没有封装~
