### ISSUE TITLE
公众号jssdk获取签名错误bug

### ISSUE THREAD

**Issue by ljyljy0211** [overtrue/wechat#1674]
## 我用的环境

* PHP 版本：php 7.2
* overtrue/wechat 版本：4.0
* 是否使用了框架？框架名称：lumen

## 问题及现象
我们是前后端分离的，前端用vue写的，后端用lumen写的，获取jssdk配置信息是服务器端传给vue端，我们要调用微信的扫一扫接口，但是怎么测试签名都是失败的，最后经过调试是发现，前后端分离的情况下，你们给jssdk生成配置信息的时候调用的是 
文件 vendor/overtrue/wechat/src/BasicService/Jssdk/Client.php
方法
` public function getUrl(): string
    {
        if ($this->url) {
            return $this->url;
        }
        return Support\current_url();
    }`
这个不能获取的原始地址，所以我只能在业务代码中
`$app->jssdk->setUrl($request->server('HTTP_REFERER'))`
来获取真正的请求地址

**Comment by overtrue** [comment]
所以你的意思是我用上 AI 来判断你是什么模式？

ljyljy0211 <notifications@github.com>于2019年9月1日 周日下午2:35写道：

**Comment by ljyljy0211** [comment]
我只是跟你们说一下，你们改不改无所谓

**Comment by ljyljy0211** [comment]
还有你说话不要这种嘲讽的语气，我们都是在用你们产品，也很喜欢你们的产品

**Comment by mingyoung** [comment]
这不是 bug 吧…… 另外 SDK 也提供了 `setUrl` 等 API 给开发者来按照自己场景/模式去适配

**Comment by qq861229715** [comment]
的确不是bug，哈哈。
