### ISSUE TITLE
3.x版本小程序支付问题

### ISSUE THREAD

**Issue by liuming9157** [overtrue/wechat#1675]
## 我用的环境

* PHP 版本：php 5.6
* overtrue/wechat 版本：3.x
* 是否使用了框架？框架名称：ThinkPHP 5.0.24

## 问题及现象
请教：如果采用如下配置
```
$options=[
'mini_program'=>[],
];
```
那么小程序支付是不是应该写作：
```
$app=new Applications($options);
$miniProgram=$app->mini_program;
$order= new Order($attributes);
$payment=$miniProgram->payment;(这行写的对吗?)
$result=$payment->prepare($order);
```
想问倒数第二行写的对吗?    
因为文档里$payment=$app->payment

**Comment by mingyoung** [comment]
https://www.easywechat.com/docs/3.x/payment

你不需要关心是不是小程序支付，直接这样实例化就可以：

![image](https://user-images.githubusercontent.com/6228858/64112898-529b5200-cdbb-11e9-8202-f0f41ccd8706.png)

**Comment by liuming9157** [comment]
你这样写是没错的。但是在实际操作中，小程序支付是要获取openid的，那么在配置数列中，难道要写成如下形式：
```
$options=[
'app_id'            =>'xxx',
'mini_program'=>[
                   'app_id'   =>'xxx'，//在这里再写一遍小程序的appid,岂不是很很傻的写法？？？？
                           ]，
‘payment’       =>[]

]
```
上述代码是因为获取openid要用到$app->mini_program的写法

**Comment by mingyoung** [comment]
3.x 版本那时候小程序还没出来，所以就这样了…

**Comment by mingyoung** [comment]
所以推荐你升级版本，以减轻各种痛苦
