### ISSUE TITLE
企业微信关联小程序没有解密的方法可以调用

### ISSUE THREAD

**Issue by phper666** [overtrue/wechat#1679]
## 我用的环境 linux

* PHP 版本：php7.1
* overtrue/wechat 版本：4.2
* 是否使用了框架？框架名称：laravel 5.8

## 问题及现象
我们开发企业微信的小程序遇到了一个问题，Factory::Work($config)得到的对象里面没有小程序数据解密的方法。
目前我们的做法是直接把小程序解密的方法重写写成一个类引入再解密~

**Comment by ezsky** [comment]
也是遇到这个问题了。
如果是企业微信开放平台，是传suite_id还是appid呢？

**Comment by phper666** [comment]
@ezsky 4.2版本里面有解密的接口可以调用了
