### ISSUE TITLE
素材管理添加永久素材返回JSON/XML内容错误

### ISSUE THREAD

**Issue by yedong0839** [overtrue/wechat#169]
当使用$media->forever()->image($imagePath);就会返回 解析JSON/XML内容错误；
但使用$media->image($imagePath);一切正常；
thumb 亦是如此；
请问这是为何？

**Comment by overtrue** [comment]
@yedong0839 看看返回的内容是啥，在Http.php内记日志看看

**Comment by yedong0839** [comment]
返回信息：Array
(
    [errcode] => 47001
    [errmsg] => data format error hint: [YoF8vA0104e297]
)

**Comment by yedong0839** [comment]
已解决，原因如下：
素材路径中不能有 ..
如此路径就会有返回错误：$imagePath = __DIR__.'/../img.png';

**Comment by overtrue** [comment]
@yedong0839 DIR 是啥？你自己定义的常量么？

**Comment by yedong0839** [comment]
显示错了，本来是 `_DIR_`;
