### ISSUE TITLE
sowft2.0.5 服务端验证微信token, serve 后怎么返回

### ISSUE THREAD

**Issue by webff** [overtrue/wechat#1695]
## 我用的环境 

* PHP 版本：7.2
* overtrue/wechat 版本：4.1
* 是否使用了框架？框架名称： swoft2.0.5 

## 问题及现象
`swoft` 框架不能使用 `exit` ,文档中说  `$response->send()` 直接输出（echo）了，请问用`swoft` 的方式怎么去做

```
$app = Factory::officialAccount($config);

$response = $app->server->serve();

// 将响应输出
$response->send(); 
//后面应该怎么写
```

**Comment by overtrue** [comment]
非 PHP 官方环境请自行解决。

Zhurf <notifications@github.com>于2019年9月26日 周四下午12:59写道：
