### ISSUE TITLE
请问怎样关闭日志

### ISSUE THREAD

**Issue by tomener** [overtrue/wechat#1699]
## 我用的环境

* PHP 版本：7.3
* overtrue/wechat 版本：4.2
* 是否使用了框架？框架名称：否

## 问题及现象

配置里面没有配置log项，日志就会记录到php错误日志文件里面

**Comment by overtrue** [comment]
日志不应该关掉，出问题你都没办法查，所以建议配置好日志，将 level 调高即可：

> level: 日志级别, 可选为： `debug/info/notice/warning/error/critical/alert/emergency`

**Comment by tomener** [comment]
好的，感谢！
