### ISSUE TITLE
微信回调URL回调不到

### ISSUE THREAD

**Issue by zhoujia123** [overtrue/wechat#170]
http://www.xxxx.com/wx/notify   这类的URL不能回调到？

**Comment by overtrue** [comment]
@zhoujia123 肯定能啊

**Comment by zhoujia123** [comment]
我发起扫码支付URL  为http://www.xxxx.com/wx/webchat   设置回调URL:http://www.xxxx.com/wx/notify

Route::group(['namespace' => 'Webchat','prefix' => 'wx'],function(){
	
        Route::get('webchat','WebchatController@webPayOrder');

	Route::any('notify','NotifyController@notify');

});

去掉了VerifyCsrfToken.php 中间件   为什么微信就是调用不过来？

**Comment by tianyong90** [comment]
1、直接在浏览器里用这个url访问下看能不能到。
2、然后就是订单中参数确认无误。
3、最后就是支付成功了才有回调。

**Comment by overtrue** [comment]
1. 域名需要在微信后台填写安全域名
2. 只能调用同域
3. 域名不能为本地如localhost等

**Comment by zhoujia123** [comment]
域名已经在微信开发中心填写安全域名，支付能正常支付，域名是正常的一级域名，设置的也是同域地址

**Comment by zhoujia123** [comment]
浏览器访问也能正常返回xml格式数据  
<xml><return_code><![CDATA[FAIL]]></return_code><return_msg><![CDATA[verify transaction error]]></return_msg></xml>

**Comment by tianyong90** [comment]
记日志吧……

**Comment by zhoujia123** [comment]
通过记录详细的日志发现，数据解析出错了，现在正在排查，谢谢各位大神的指导！
