### ISSUE TITLE
能否增加微信APP支付相关方法

### ISSUE THREAD

**Issue by wailovet** [overtrue/wechat#171]
即APP支付业务流程中的
[步骤3：统一下单接口返回正常的prepay_id，再按签名规范重新生成签名后，将数据传输给APP。参与签名的字段名为appId，partnerId，prepayId，nonceStr，timeStamp，package。注意：package的值格式为Sign=WXPay]
APP支付流程https://pay.weixin.qq.com/wiki/doc/api/app.php?chapter=8_3

**Comment by overtrue** [comment]
@wailovet 2.0 目前只接受PR，不添加新功能，因为在着力开发3.0

**Comment by wailovet** [comment]
谢谢

**Comment by overtrue** [comment]
@wailovet 3.0 已经有了，请参阅文档
