### ISSUE TITLE
关于4.0企业付款到用户零钱问题

### ISSUE THREAD

**Issue by liererer** [overtrue/wechat#1713]
## 我用的环境

* PHP 版本：7.2
* overtrue/wechat 版本：4.0
* 是否使用了框架？框架名称：laravel5

## 问题及现象

对接微信红包能够正常发送，但是使用企业零钱就会报签名错误，如果说签名问题的话是不是红包也不应该能发送，但是现在红包能发，支付也正常，就企业付款到用户零钱报签名错误
![image](https://user-images.githubusercontent.com/34019269/67755157-997f8e00-fa72-11e9-9cc6-4f4ebfd7bea4.png)
![image](https://user-images.githubusercontent.com/34019269/67755216-b5832f80-fa72-11e9-83e3-c2039784ff06.png)
## 返回值
```json
{"return_code":"SUCCESS",
"return_msg":"SIGN_ERROR",
"mch_appid":"我的ID",
"mchid":"我的商户号",
"result_code":"FAIL",
"err_code":"SIGN_ERROR",
"err_code_des":"\u7b7e\u540d\u9519\u8bef"}
```

**Comment by liererer** [comment]
找到原因了

**Comment by RJustice** [comment]
我也有这个问题, 请问是什么原因
