### ISSUE TITLE
关于素材获取的一个建议

### ISSUE THREAD

**Issue by iam993** [overtrue/wechat#172]
既然media类中的download获取文件同时能够附加扩展名，那为什么就只支持那几个呢？

我建议要不然就补齐一下其他类型（类似mp4等的文件），要不然扩展名就由开发者来做，我更喜欢前者。

另外，我获取媒体时，有些是json，有些是array，最后是二进制。所以代码写的都很死。是微信故意这样做的吗？还是跟php的环境有关？

**Comment by overtrue** [comment]
@iam993 微信的API设计就是这样的，太SB了，各种难用，同一个API返回不同类型...

**Comment by overtrue** [comment]
@iam993 3.0里面已经支持获取流内容，直接把原内容给你，这样你想怎么处理都方便。

**Comment by iam993** [comment]
真搞不懂这种大公司的想法
