### ISSUE TITLE
laravel-s每天都会报错component ticket is expired hint，要手动重启才正常

### ISSUE THREAD

**Issue by Double-Jin** [overtrue/wechat#1721]
## 我用的环境

* PHP 版本：7.2.22
* overtrue/wechat 版本：4.1
* 是否使用了框架？框架名称：laravel-s

## 问题及现象
项目是第三方平台，需要接收绑定商户ticket，查看日志是有接收到授权事件url的，当laravel-s启动后接收到授权事件url是正常的，第当第二天后就会报60015 component ticket is expired hint，需要重启laravel-s第下一次接收才正常，有没有解决方法

**Comment by overtrue** [comment]
laravel s 不在标准 FPM 环境下，这边不负责解答哈。

**Comment by Double-Jin** [comment]
> laravel小号不在标准FPM环境下，这边不负责解答哈。

怎么样在最底层设置用redis做缓存，不走文件系统，我看文档上写的是对第个方法的改造

**Comment by overtrue** [comment]
https://www.easywechat.com/docs/4.1/customize/cache
