### ISSUE TITLE
群发消息加第三个参数依然报错：clientmsgid exist

### ISSUE THREAD

**Issue by oknixus** [overtrue/wechat#1726]
## 我用的环境

* PHP 版本：7.2.22
* overtrue/wechat 版本：^4.1
* 是否使用了框架？框架名称：Laravel 5.7

## 问题及现象
使用微信公众号的群发功能，由于发送人数超过一万，所以需要发送多次，于是在发送的时候将 openid进行了分组，但是一直报错:
`{"errcode":45065,"errmsg":"clientmsgid exist","msg_id    ":3147483730}`
怀疑是自己传参数的方式有问题，查看了源码
`vendor/overtrue/wechat/src/OfficialAccount/Broadcasting/Client.php`
`vendor/overtrue/wechat/src/OfficialAccount/Broadcasting/MessageBuilder.php`
也在`Client.php`中的`sendMessage`方法中加了`return $message->build();`想查看最终 build 的消息体是怎样的，但是都失败了。尝试了很多次，都是上面那个错误，所以只好发个 issue 来求助了

麻烦您了！谢谢！

#### 尝试一
```
foreach ($open_groups as $open_group) {
     $resp = $officialAccount->broadcasting->$sender($broadcast->media_id, $open_group, ['clientmsgid' => Carbon::now()->timestamp]);
}
```

#### 尝试二
```
foreach ($open_groups as $open_group) {
     $resp = $officialAccount->broadcasting->$sender($broadcast->media_id, $open_group, ['clientmsgid' => Carbon::now()->timestamp+mt_rand(0,100)]);
}
```

#### 尝试三
```
foreach ($open_groups as $open_group) {
     $resp = $officialAccount->broadcasting->$sender($broadcast->media_id, $open_group, ['clientmsgid' => uniqid()]);
}
```

#### 尝试四
```
foreach ($open_groups as $open_group) {
     $resp = $officialAccount->broadcasting->$sender($broadcast->media_id, $open_group, [['clientmsgid' => uniqid()]]);
}
```

**Comment by overtrue** [comment]
1. 在 foreach 当中使用 `Carbon::now()->timestamp` 必然会重复啊，你输出一下看看就知道了，1万个以内几乎不变啊。。。
2. `Carbon::now()->timestamp+mt_rand(0,100)` 1到100，可是你的消息是1万条啊，当前秒数 + 1-100 肯定是大量重复啊。。。
3. 至于第4个肯定是参数写法错误吧
4. 你的 `$sender` 是啥值？

**Comment by oknixus** [comment]
老哥，不好意思，我没说明白；
超过 1 万的，会用 array_chunk 按照 8000 个一组，foreach 遍历的时候，每次最多发 8000 个；
$sender是通过消息类型组装的方法名；

**Comment by oknixus** [comment]
验证过了`$message->build();`，数据格式是 OK 的，同时在微信开发者社区发现有用户遇到[同样的问题](https://developers.weixin.qq.com/community/develop/doc/0002eead8b4ff0837d3930ea956c00?highLine=clientmsgid%2520exist)，等待微信官方的反馈；
