### ISSUE TITLE
日志中的StreamHandler类后三个参数没有进行设置，我需要将日志文件权限进行更改

### ISSUE THREAD

**Issue by idler8** [overtrue/wechat#1727]
## 我用的环境

* PHP 版本：7.2
* overtrue/wechat 版本：4.0
* 是否使用了框架？框架名称：Laravel

## 问题及现象

![image](https://user-images.githubusercontent.com/50684820/68818264-6ae2f380-06bf-11ea-8113-06d81f07afea.png)

**Comment by idler8** [comment]
这是Laravel最新的写法
![image](https://user-images.githubusercontent.com/50684820/68818614-813d7f00-06c0-11ea-8e1c-6133f909f06f.png)

这是easywechat的写法
![image](https://user-images.githubusercontent.com/50684820/68818621-869ac980-06c0-11ea-9d8a-7d56d360d7f5.png)

**Comment by idler8** [comment]
@overtrue 果然还是要AT一下么，大佬，我可以通过rebind来直接调用laravel的Log类么，具体该如何使用

**Comment by her-cat** [comment]
可以，参考：
- [https://www.easywechat.com/docs/4.1/customize/replace-service](https://www.easywechat.com/docs/4.1/customize/replace-service)
- [https://www.easywechat.com/docs/4.1/customize/cache](https://www.easywechat.com/docs/4.1/customize/cache)
