### ISSUE TITLE
生成临时二维码时，返回EventKey不是传递的值

### ISSUE THREAD

**Issue by Someker** [overtrue/wechat#173]
当我传递的$sceneId 长度大于10位时，就会出现接受的EventKey莫名其妙的值
其中发现一处bug。应去掉intval，否则永远都不会超过10位。
虽然我尝试去除这个转换，去除后依然不能得到我想要的参数
```php
// 临时二维码时为32位非0整型
        $scene = array('scene_id' => intval($sceneId));
```

**Comment by overtrue** [comment]
@Someker 建议不要大于10位，有朋友试过，官方并没有像文档说的一样支持32位
