### ISSUE TITLE
EasyWechat 世界上最好的微信开发 SDK？？？？

### ISSUE THREAD

**Issue by BinFinn** [overtrue/wechat#1730]
不知道EasyWechat管理人员是否清楚你们的宣传语触犯了国家广告法规定呢？（本人没有恶意、只是提醒EasyWechat官方，以免有些人钻空子，损害到个人利益。）

以下由百度百科整理而来。

《中华人民共和国广告法》中规定的极限词有：

1、国家级、世界级、最高级、顶级

国家级、世界级、最高级、顶级、顶尖、高级、高档、世界领先、遥遥领先、一马当先；
国家示范、全国领先、行业顶尖、行业领先、领衔、问鼎、开创之举、填补国内空白。

2、第一、唯一、首个

第一、唯一、首个、先进、前卫、进步、率先；推荐首选、优选、优质、首家、独家、全力、致力、全新、第一人、首席；

独一无二、独家、绝无仅有、前无古人、100% 百分百、史上、非常一流、优异。

3、金牌、名牌
![image](https://user-images.githubusercontent.com/28726122/68829707-86142a00-06e4-11ea-8833-d580c4e71f17.png)

**Comment by almas1992** [comment]
你在哪儿看到 “EasyWechat 世界上最好的微信开发 SDK” 的广告？
我的理解中，广告法是针对的是面向公众宣传的广告内容的，可github中的标题，说明不算是广告吧？

**Comment by BinFinn** [comment]
我在这个网站里看到的：https://www.easywechat.com
友好的提醒，不用怼我哦！我也是easywechat使用者。
