### ISSUE TITLE
测试环境下是否有办法 mock access_token?

### ISSUE THREAD

**Issue by bolechen** [overtrue/wechat#1734]
## 我用的环境

* PHP 版本：7.2
* overtrue/wechat 版本：最新版
* 是否使用了框架？框架名称：Laravel 6.5.0

## 问题及现象

项目 CI 过程中 unittest 用的是测试号，每天请求数量有限制，有时候测多了，老是提示

```bash
EasyWeChat\Kernel\Exceptions\HttpException: Request access_token fail: {"errcode":45009,"errmsg":"reach max api daily quota limit hint: [sFAFgA01194731]"}
21
```

导致测试过不了，项目自动部署失败。

我尝试着在代码中判断如果是测试环境，就手动设置 access token，代码如下

```php
        if (\App::environment(['local', 'testing'])) {
            $official_account_client->access_token->setToken('access_token_test', 5000);
        }
```

貌似不好使，请超哥帮忙指点一下，感谢~

**Comment by mingyoung** [comment]
```php
$app['access_token'] = Mockery::mock(AccessToken::class, function ($mock) {
    $mock->shouldReceived('getToken')->andReturn(['access_token' => 'nah']);
});
```

**Comment by mingyoung** [comment]
个人感觉不需要 Mock access_token，Mock 你具体要用到的模块就行。比如你用到 `user->list()` 就 Mock `user` 模块，并不需要关心（Mock）更底层的东西。

**Comment by bolechen** [comment]
> 个人感觉不需要 Mock access_token，Mock 你具体要用到的模块就行。比如你用到 `user->list()` 就 Mock `user` 模块，并不需要关心（Mock）更底层的东西。

非常感谢，一语点醒梦中人
