### ISSUE TITLE
请求支付接口，nginx 错误日志就会记录一条 error 信息

### ISSUE THREAD

**Issue by PHPming** [overtrue/wechat#1735]
## 我用的环境

* PHP 版本：7.2.24
* overtrue/wechat 版本：~4.1
* 框架名称：laravel 5.5

## 问题及现象
请求支付接口，nginx 错误日志就会记录一条 error 信息。但是支付和回调没有任何问题
## nginx 日志
2019/11/19 15:31:42 [error] 1042#1042: *20 FastCGI sent in stderr: "PHP message: [2019-11-19 15:31:42] EasyWeChat.INFO: >>>>>>>> POST /pay/unifiedorder HTTP/1.1 Content-Length: 593 User-Agent: GuzzleHttp/6.3.3 curl/7.58.0 PHP/7.2.24-0ubuntu0.18.04.1 Host: api.mch.weixin.qq.com  <xml><mch_id>4545454545</mch_id><nonce_str><![CDATA[5dd39a5df4121]]></nonce_str><body><![CDATA[充值]]></body><out_trade_no><![CDATA[CHARGEDIA201911191531419445606]]></out_trade_no><total_fee>100</total_fee><notify_url><![CDATA[http://play.com/finance/notify/wx/charge]]></notify_url><trade_type><![CDATA[APP]]></trade_type><product_id><![CDATA[f0056d6fa355d63d2af35e3d981b1267]]></product_id><spbill_create_ip><![CDATA[127.0.0.1]]></spbill_create_ip><appid><![CDATA[wx37fb4595fd6e8997]]></appid><sign><![CDATA[9FEF6A1ED839F52984EA530F3CA55FB3]]></sign></xml> <<<<<<<< HTTP/1.1 200 OK Server: nginx Date: Tue, 19 Nov 2019 07:31:42 GMT Content-Type: text/plain Content-Length: 454 Connection: keep-alive Keep-Alive: timeout=8  <xml><return_code><![CDATA[SUCCESS]]></return_cod" while reading response header from upstream, client: 127.0.0.1, server: play.com, request: "POST /finance/charge/establish HTTP/1.1", upstream: "fastcgi://127.0.0.1:9002", host: "play.com", referrer: "http://play.com/develop/system/web?url=api%2Ffinance%2Fcharge%2Festablish&method=post"

**Comment by overtrue** [comment]
#1699

**Comment by PHPming** [comment]
已解决，谢谢！
