### ISSUE TITLE
PR #983  请问一下 可否测试一下这个接口是否还能正常使用么

### ISSUE THREAD

**Issue by shoaly** [overtrue/wechat#1737]
PR #983

```php
// 新增收款个人用户资料
$app->merchant->addSubMerchant([
    'merchant_name' => '店铺名称',
    'merchant_shortname' => '简称',
    'recipient_name' => '姓名',
    'recipient_idcardno' => '111111111111111111', // 身份证
    'recipient_wechatid' => 'wechat-id',
    // ...
]);

// 查询收款个人用户资料
$app->merchant->querySubMerchantByMerchantId('xxx'); // 根据收款识别码查询
$app->merchant->querySubMerchantByWeChatId('xxx'); // 根据收款人微信号查询
```

_Originally posted by @mingyoung in https://github.com/overtrue/wechat/issues/970#issuecomment-339199494_

**Comment by shoaly** [comment]
现在无脑返回下面的, 签名方法应该是对的, 因为查询接口还能用, 但是新增的接口就无脑提示签名系统错误
[
    "return_code" => "FAIL"
    "return_msg" => "签名系统错误，请联系后重试"
 ]

**Comment by overtrue** [comment]
请联系客服💁……

shoaly <notifications@github.com>于2019年11月23日 周六上午12:54写道：

**Comment by shoaly** [comment]
联系过客服的, 官方那个论坛的客服说可以用,  但是官方群里面 又引导直接用小微, 所以就想来这边接口提交PR的朋友 问问试试, 看看接口是否已经过时了

**Comment by overtrue** [comment]
抱歉不清楚哦
