### ISSUE TITLE
Throw Exception的时候 Intel server status 设置为200是不是好一些

### ISSUE THREAD

**Issue by sphenginx** [overtrue/wechat#174]
最近在做微信登陆的接口， lumen集成了这个 package，很好用~ 

但是当传入错误的 auth code的时候， 扔异常的时候，服务器状态也是500了~  

感觉这么是不是体验不大好，是不是设置为200好一些~  

个人浅见。

**Comment by overtrue** [comment]
明明都是错了难道还要错误你没错？这种情况你应该去try catch
