### ISSUE TITLE
发送链接类消息错误

### ISSUE THREAD

**Issue by ycj652901** [overtrue/wechat#175]
return Message::make('link')->title("连接测试")->description('你说呢')->url("http://www.baidu.cn");

回复链接类的消息..但是不成功...普通类的没问题..还是我用错了?

**Comment by overtrue** [comment]
@ycj652901 http://mp.weixin.qq.com/wiki/14/89b871b5466b19b3efa4ada8e577d45e.html

官方没说支持链接类型回复啊，这个类只是预备用的
