### ISSUE TITLE
求大佬对接微信支付分账接口

### ISSUE THREAD

**Issue by NiZerin** [overtrue/wechat#1751]
求大佬对接微信支付分账接口

**Comment by almas1992** [comment]
> https://github.com/overtrue/wechat/pull/1457 不是这个么？

**Comment by NiZerin** [comment]
> > #1457 不是这个么？

看到了，谢谢，文档没有体现，特意跑过来问。

**Comment by almas1992** [comment]
> > > #1457 不是这个么？
> 
> 看到了，谢谢，文档没有体现，特意跑过来问。

遇到问题先看看 别人的踩坑（Issue）填坑（Pull request） 记录
