### ISSUE TITLE
关于Failed to cache access token的解决方法之一

### ISSUE THREAD

**Issue by loyipsing** [overtrue/wechat#1761]
如果遇到Failed to cache access token，除了检查文件目录权限外，还有一种情况👇

如果调用了setToken方法，且设置的超时时间小于500秒，会报错 “Failed to cache access token”
例子：
`$app->access_token->setToken($token, 10);`

因为框架内部在setCache的时候会减掉500秒，导致本次cache能成功set进去，但是在get的时候会get不到，抛出异常。

解决方法：
`$app->access_token->setToken($token, 501);`

👇👇👇👇解析👇👇👇👇

    public function setToken(string $token, int $lifetime = 7200): AccessTokenInterface
    {
        $this->getCache()->set($this->getCacheKey(), [
            $this->tokenKey => $token,
            'expires_in' => $lifetime,
        ], $lifetime - $this->safeSeconds);👉liftime为负数，导致set了后马上失效👈

        if (!$this->getCache()->has($this->getCacheKey())) {
       👉作者为了检查是否setcache成功，会用一次getcache来检测，但是上一步set的已经失效，所以下面抛出异常👈
            throw new RuntimeException('Failed to cache access token.');
        }

        return $this;
    }

**Comment by overtrue** [comment]
666

loyipsing <notifications@github.com>于2019年12月12日 周四下午7:55写道：

**Comment by charescape** [comment]
🐂🍺
