### ISSUE TITLE
QQ小程序没有？

### ISSUE THREAD

**Issue by shulinqian** [overtrue/wechat#1772]
QQ小程序没有？

**Comment by overtrue** [comment]
🈚️

summer <notifications@github.com>于2019年12月26日 周四下午3:16写道：

**Comment by shulinqian** [comment]
加否？

**Comment by overtrue** [comment]
不加哈，看一下包名就不可能在这里加吧

summer <notifications@github.com>于2019年12月26日 周四下午5:09写道：

**Comment by almas1992** [comment]
> 不加哈，看一下包名就不可能在这里加吧 summer <notifications@github.com>于2019年12月26日 

下一个问题 ：有没有 **overtrue/qq**  :stuck_out_tongue_winking_eye: :stuck_out_tongue_winking_eye:
