### ISSUE TITLE
图片上传问题(敏感图接口)

### ISSUE THREAD

**Issue by caihaibin1991** [overtrue/wechat#1783]
## 我用的环境

* PHP 版本：7.2
* WIN: 开发环境
* overtrue/wechat 版本：
* 是否使用了框架？框架名称：thinkphp

## 问题及现象
EasyWeChat\BasicService\ContentSecurity\Client
return $this->httpUpload('img_sec_check', ['@media' => $path]);
@media 没有补充@导致图片上传,win下出现超时的错误,报错内容
{"errcode":87015,"errmsg":"query timeout, try a content with less size hint: [o4gTIA0553b464]"}

**Comment by overtrue** [comment]
不考虑 windows 谢谢。

**Comment by xw43230855** [comment]
EasyWeChat\BasicService\ContentSecurity\Client
return $this->httpUpload('img_sec_check', ['@media' => $path]);
返回下面错误:
Client error: `POST https://api.weixin.qq.com/wxa/img_sec_check` resulted in a `412 Precondition Failed` response
