### ISSUE TITLE
3.x升级4.0是否有方案或建议？

### ISSUE THREAD

**Issue by snaill** [overtrue/wechat#1791]
## 我用的环境

* PHP 版本：7.2/7.4
* overtrue/wechat 版本：3.3.33
* 是否使用了框架？框架名称：yii2

## 问题及现象
3.x使用doctrine/cache 1.4.x，其中有些如impode的用法在php7.4已经失效，导致执行异常。因为只是开发机，暂时直接修改doctrine/cache代码解决，考虑以后的更新升级，希望能更新到4.x版本。

目前看到的4.x改动还是比较大的，请问是否有推荐的升级方案。

或者起码把doctrine/cache升级到1.5.x。

**Comment by overtrue** [comment]
推荐将用到的地方按新版修改代码

snaill <notifications@github.com>于2020年2月6日 周四下午6:38写道：

**Comment by aogg** [comment]
@snaill 亲最后升级了吗？写个升级注意事项的 博客吧
