### ISSUE TITLE
无法发送企业微信群机器人消息

### ISSUE THREAD

**Issue by 2898117012** [overtrue/wechat#1794]
## 我用的环境

* PHP 版本：
* overtrue/wechat 版本：
* 是否使用了框架？框架名称：laravel

## 问题及现象

发送群机器人消息出现access token错误. 实际上官方文档不需要access token。如果没有创建应用无法获取access token.

**Comment by her-cat** [comment]
感谢反馈，已提交修复问题的 PR  ❤️
