### ISSUE TITLE
群发功能

### ISSUE THREAD

**Issue by Comver** [overtrue/wechat#18]
个人觉得还是有作用的，有没有点tip，提示一下：如何在已有的SDK基础上修改开发

**Comment by overtrue** [comment]
@Comver 要添加很多东西才能实现，当然你可以先了解一下 `src/Wechat/Http.php` 然后在src/Wechat下建立一个Broadcast.php 模仿我的其它类实现这个群发功能，如果用得不错你还可以PR过来我合并

**Comment by overtrue** [comment]
http://easywechat.org/docs/zh-cn/broadcast.html
