### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by yao3060** [overtrue/wechat#1804]
文档页面： https://www.easywechat.com/docs/4.1/mini-program/app_code

```
$response = $app->app_code->getUnlimit('scene-value', [
    'page'  => 'path/to/page',
    'width' => 600,
]);
```
在生成小程序码的这儿，`page` 应该是 `path`

**Comment by overtrue** [comment]
https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/qr-code/wxacode.getUnlimited.html#HTTPS%20%E8%B0%83%E7%94%A8

![image](https://user-images.githubusercontent.com/1472352/75424323-5e875b80-597b-11ea-8726-26c5d238928e.png)

**Comment by yao3060** [comment]
不好意思，是我搞错了，谢谢

**Comment by yao3060** [comment]
> https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/qr-code/wxacode.getUnlimited.html#HTTPS%20%E8%B0%83%E7%94%A8
> 
> ![image](https://user-images.githubusercontent.com/1472352/75424323-5e875b80-597b-11ea-8726-26c5d238928e.png)
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/babc525f57941f447a01ce01ac2530f8a641d986/68747470733a2f2f7265732e77782e71712e636f6d2f612f77785f6665642f6173736574732f7265732f4e5449344d5755352e69636f">**[wxacode.getUnlimited | 微信开放文档](https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/qr-code/wxacode.getUnlimited.html#HTTPS%20%E8%B0%83%E7%94%A8)**微信开发者平台文档

-----

不好意思，是我搞错了，谢谢
