### ISSUE TITLE
开放平台网站应用如何实现扫码授权登录呢？

### ISSUE THREAD

**Issue by flycj** [overtrue/wechat#1805]
## 我用的环境

* PHP 版本：
* overtrue/wechat 版本：
* 是否使用了框架？框架名称：laravel

## 问题及现象
我查了文档关于“开放平台”部分没有发现网站应用扫码授权登录的功能说明
查了源码 关于 openPlatform 部分也没有发现集成 socialite 的登录功能

我也看了文档中 公众号-网页授权部分，说的明白，但是如果我使用official_account 调用 oauth 的话，发起授权请求时的app_id就是 公众号的app_id ，而不是 开放平台-网站应用对应的app_id ，导致最后微信返回code 无效。。

我现在纠结的是如果我直接使用socialite 来实现这个功能，我就需要在代码直接配置app_id和 app_secret 而不能够很优雅的调用 config/wechat.app 中 open_paltform 下的配置信息

我只能直接使用 socialite 开发吗？很头疼

没有这个功能吗？还是是我的理解有问题吗？
求指点

**Comment by AlemAblat** [comment]
其实这个很简单，你要先了解好OAuth2.0然后是永久秒懂

**Comment by flycj** [comment]
> 其实这个很简单，你要先了解好OAuth2.0然后是永久秒懂

我最后把 open_platform 下 网站应用配置放在了  official_account 配置下，并配置为web ，然后用下面的方法实现获取用户
```
$app = app('wechat.official_account.web');
$oauth = $app->oauth->scopes(['snsapi_login']);
$oauth->setRequest($request);
$this->wechatUser = $oauth->user();
```
不知道对不对？
我看了 OAuth2.0 啊， 依旧搞不懂这个库怎么用

**Comment by uptutu** [comment]
$app->oauth->scopes(['snsapi_login']);

$app->oauth 返回的是一个 socialite 实例

而 socialite 中通过修改 ->scopes(['snsapi_login']) 设置 snsapi_login 可以实现网页跳转到 QR 扫码登录。文档的缺失。

**Comment by AlemAblat** [comment]
> > 其实这个很简单，你要先了解好OAuth2.0然后是永久秒懂
> 
> 我最后把 open_platform 下 网站应用配置放在了 official_account 配置下，并配置为web ，然后用下面的方法实现获取用户
> 
> ```
> $app = app('wechat.official_account.web');
> $oauth = $app->oauth->scopes(['snsapi_login']);
> $oauth->setRequest($request);
> $this->wechatUser = $oauth->user();
> ```
> 
> 不知道对不对？
> 我看了 OAuth2.0 啊， 依旧搞不懂这个库怎么用

> ```
 我的意思你真的懂了 OAuth 2.0 不需要开放平台的appid来扫码登陆，可以自己模拟扫码登陆，不过又一个问题是，公众号获取的openid和小程序获取的openid不一样所以会导致扫码登陆小程序不成功（或者openid验证用户不靠谱）所以最好是让用户关注操作获取unionId然后在开发扫码登陆功能
```
>

**Comment by uchqur** [comment]
> > > 其实这个很简单，你要先了解好OAuth2.0然后是永久秒懂
> > 
> > 
> > 我最后把 open_platform 下 网站应用配置放在了 official_account 配置下，并配置为web ，然后用下面的方法实现获取用户
> > ```
> > $app = app('wechat.official_account.web');
> > $oauth = $app->oauth->scopes(['snsapi_login']);
> > $oauth->setRequest($request);
> > $this->wechatUser = $oauth->user();
> > ```
> > 
> > 
> > 不知道对不对？
> > 我看了 OAuth2.0 啊， 依旧搞不懂这个库怎么用
> 
> ```
> 我的意思你真的懂了 OAuth 2.0 不需要开放平台的appid来扫码登陆，可以自己模拟扫码登陆，
> 不过又一个问题是，公众号获取的openid和小程序获取的openid不一样
> 所以会导致扫码登陆小程序不成功（或者openid验证用户不靠谱）
> 所以最好是让用户关注操作获取unionId然后在开发扫码登陆功能
> 这个过程 EW 也帮你做很多事情
> ```

> 你要获取unionId可以避免这个问题

**Comment by greedying** [comment]
> 

现在遇到同样的问题，头痛。
问题很简单，就是不想裸用 `socialite`，或者不想一个配置写到两个地方。
