### ISSUE TITLE
如何在服务端获取用户nickname？

### ISSUE THREAD

**Issue by chaopi** [overtrue/wechat#1809]
## 我用的环境

* PHP 版本：7.0.27
* overtrue/wechat 版本：4.1.32
* 是否使用了框架？框架名称：laravel 5.5.48

## 问题及现象

服务端接收公众号用户互动消息中获取用户nickname后，公众号对用户提示故障，return文本未正确向用户展示。

$app = Factory::officialAccount($config);
$app->server->push(function($message){
            $openid = $message['FromUserName'];
            $app2 = Factory::officialAccount($config);
            $nickname = 'unknow';
            //尝试获取用户信息
            $user = $app2->user->get($openid);
            $nickname = $user['nickname'];
            //尝试获取用户信息 end
            return new Text($nickname);
});

上面代码段运行后，用户给公众号发文字会收到微信返回公众号故障提醒；屏蔽“尝试获取用户信息”
2行代码后，能正确返回文字信息“unknow”给用户。

请问如何在服务端获取用户nickname？

**Comment by overtrue** [comment]
看一下 $user 得到的是啥

**Comment by chaopi** [comment]
$user json_encode后 {"subscribe":1,"openid":"oWz-3vxXg1ZWDbzbu2-8F1TIsDEI","nickname":"\u76d6","sex":1,"language":"zh_CN","city":"\u5e7f\u5dde","province":"\u5e7f\u4e1c","country":"\u4e2d\u56fd","headimgurl":"http:\/\/thirdwx.qlogo.cn\/mmopen\/60QgmKtia6204dL7HMfFibTx89dUrfvnwQ0VjDVKM3kx4WGIwEjbV91p76fg2EMHJWgRWwo8QMrYqP1OD4nFLIDr90nXibpqAq\/132","subscribe_time":1548657951,"unionid":"oTcbTuzC6EQkspE9RYBIYm6L-A6U","remark":"","groupid":0,"tagid_list":[],"subscribe_scene":"ADD_SCENE_QR_CODE","qr_scene":0,"qr_scene_str":"id-rGu5ub9"}

**Comment by chaopi** [comment]
对 server->push(){} 内加try catch也没有捕捉到异常

**Comment by chaopi** [comment]
抱歉，和开发沟通后，少了一个细节：中return之前还发送了一次模板消息

$app = Factory::officialAccount($config);
$app->server->push(function($message){
$openid = $message['FromUserName'];
$app2 = Factory::officialAccount($config);
$nickname = 'unknow';
//尝试获取用户信息
$user = $app2->user->get($openid);
$nickname = $user['nickname'];
//尝试获取用户信息 end
//这里还发送了一次模板消息：
$app2->template_message->send([ ... ]);
return new Text($nickname);
});

已知该模板消息正常发送，接送方正常收到。
但注视掉消息模板发送这行代码后，就出现了微信向用户返回服务出现故障的提示。
