### ISSUE TITLE
请问easyWeChat目前支持 付款码支付 吗？

### ISSUE THREAD

**Issue by oknixus** [overtrue/wechat#1810]
想了好久，又翻了一下源码，觉得还是在这里问一下，确认一下比较好；

> 付款码支付
> 
> 付款码支付是用户展示微信钱包内的“刷卡条码/二维码”给商户系统扫描后直接完成支付的模式。主要> 应用线下面对面收银的场景。

https://pay.weixin.qq.com/wiki/doc/api/micropay.php?chapter=5_1

**Comment by overtrue** [comment]
支持的，不过忘记写文档，你要是搞定可以贡献一下文档，下单接口：https://github.com/overtrue/wechat/blob/590a1407ef966d55527366858fe697e102f42a34/src/Payment/Base/Client.php#L29

**Comment by oknixus** [comment]
嗯，是的，我发了issue后，觉得可能只能用这个了
谢谢老哥！

**Comment by zouyan198429** [comment]
可以的，对象直接调 pay方法 
参数：
 $params = [
                        'body' => '面授课--微信收款码支付费用',
                        'out_trade_no' => $resultPay['pay_order_no'],
                        'total_fee' => ceil($createOrder['total_price_goods'] * 100),
                        'auth_code' => $auth_code, // $message['product_id'] 则为生成二维码时的产品 ID

                    ];
 $apiResult = $app->pay($unifyParams);
