### ISSUE TITLE
开放平台使用过程中偶尔会出现获取缓存中的 Access Token 无法解析

### ISSUE THREAD

**Issue by hetengji** [overtrue/wechat#1815]
## 我用的环境

* PHP 版本：7.2
* overtrue/wechat 版本：4.0
* 是否使用了框架？框架名称：laravel 5.5

## 问题及现象
开放平台使用过程中偶尔会出现获取缓存中的 Access Token 无法解析 
直接上图吧 
![微信图片_20200311171146_看图王](https://user-images.githubusercontent.com/30951653/76401187-78ce2a00-63bc-11ea-86d7-a5f85aab3917.png)

**Comment by hetengji** [comment]
缓存中的 数据不正常 例如：\x00\x00\x00\x02\x14\x02\x11\x17authorizer_access_token\x11\x9D28_r4nnEgzn2w2q2PF6Y_v01x4FCg7T1xiiXC1EXcnrzLlQ8tWzp9VJ4kISVItE_KCw7T-U16rkHA5XQ7f4oN6L9GPRMTnhG9kJWZi3Jcl2-XQP1jy3BvtvO3lxmEDfNO9VT3jJp4YU6acjOLhtQMZjAFDDZM\x11\x0Aexpires_in\x08\x1C

**Comment by overtrue** [comment]
@hetengji “正常” 的定义是什么？

**Comment by hetengji** [comment]
@overtrue  正常是这种的 
a:2{s:22:"component_access_token";s:157:"31_yLUVzVvYbhT__ttKYZFCcrQQjN3SrQADD0_3mlkGCeB5toDp-jcHNrURLA27BOLp5x_BgUSqgxFArP97wYdCK2Fki1mR7wMjAtPGhripgvCdzvs_4LQBM2TsL-Amk9WbPadSDZ2-EYZ1gb7KCTKjAJAJAR";s:10:"expires_in";i:7200;}

这种序列化的可以先解析

**Comment by hetengji** [comment]
这个问题是间歇性的

**Comment by overtrue** [comment]
@hetengji 你有其他服务在写入这个 key 吧

**Comment by hetengji** [comment]
没有

**Comment by hetengji** [comment]
其他人有没有遇到类似的问题呢，我在排查一下我们redis 缓存的之类的问题吧

**Comment by mingyoung** [comment]
![C677666E-0769-45EE-A705-533FDBFA508A](https://user-images.githubusercontent.com/6228858/76485361-50473e00-6457-11ea-8fd1-f2f89158c5e9.png)

貌似是 redis 的 ”feature”？有没有出现报错？

**Comment by MaymayJay** [comment]
@

> 其他人有没有遇到类似的问题呢，我在排查一下我们redis 缓存的之类的问题吧

有啊 找到解决方法了么

**Comment by dividez** [comment]
我这里也遇到了同样的问题:
- PHP 版本：7.2
- overtrue/wechat 版本：4.0
- 是否使用了框架？框架名称：laravel 5.5

问题和现象是一模一样的 , 目前还没找到何时的解决办法!

**Comment by MaymayJay** [comment]
安装 igbinary试试

**Comment by sandersyao** [comment]
> 安装 igbinary试试

安装了，问题还存在，目前在 symfony 的 DefaultMarshaller 中复现该问题，Laravel 的 Cache 还在观察中。

**Comment by laraveler** [comment]
你这个问题是自定义了使用symfony的redis缓存，在symfony 的 DefaultMarshaller 中，会根据情况判断当前环境有没有安装igbinary，如果安装了会使用igbinary_serialize序列化数据，而igbinary_serialize序列化的数据就是你说的“缓存数组不正常”，你可以new RedisAdapter()的时候把第4个构造函数参数使用 new DefaultMarshaller(false)，关掉igbinary_serialize，使用php的serialize()，或者可以实现MarshallerInterface接口，然后实现里面的方法，自定义序列化方案，比如json。

**Comment by dividez** [comment]
> 你这个问题是自定义了使用symfony的redis缓存，在symfony 的 DefaultMarshaller 中，会根据情况判断当前环境有没有安装igbinary，如果安装了会使用igbinary_serialize序列化数据，而igbinary_serialize序列化的数据就是你说的“缓存数组不正常”，你可以new RedisAdapter()的时候把第4个构造函数参数使用 new DefaultMarshaller(false)，关掉igbinary_serialize，使用php的serialize()，或者可以实现MarshallerInterface接口，然后实现里面的方法，自定义序列化方案，比如json。

通过安装 php 的 igbinary 扩展 也可以解决这个问题,
![image](https://user-images.githubusercontent.com/19829513/101330451-924dc500-38ad-11eb-92f8-85c30d650202.png)
