### ISSUE TITLE
$app->server->push中$message的沒反應

### ISSUE THREAD

**Issue by EthanHung** [overtrue/wechat#1819]
## 我用的环境

* PHP 版本：7.3.1
* overtrue/wechat 版本："overtrue/wechat": "~4.1"
* 是否使用了框架？框架名称：laravel: 6.18.0

## 问题及现象
![Question code](https://github.com/EthanHung/test/blob/master/Screenshot%202020-03-15%20at%201.32.44%20AM.png?raw=true)

跟著範例去做還是做不了，是不是還有config要加上去？

順便再問
照理解是用戶發訊息去公眾號後微信會回傳資料去這個api。不知有沒有用錯api

**Comment by overtrue** [comment]
1. 先确认你的回调通知到达了截图部分。
2. 检查 nginx 日志情况

多半是请求没到你的逻辑代码，可能被中间件拦截了。

> PS: 不要在非 `config/*.php` 外使用 `env` 函数，正式环境它是读不到任何值的。

**Comment by EthanHung** [comment]
**回调通知到达了截图部分**: 是不是指去到 `function ($message) {  return "您好！欢迎使用 EasyWeChat";}` 內？
如果是的話：可以到達；也能在這回調內 `echo print_r($message, true); ` 但回傳  `Array( [0] => )`
**检查 nginx 日志情况**: 很奇怪，無論用nginx/apache都沒有log

另外以下是easywechat log
![log](https://github.com/EthanHung/test/blob/master/log.png?raw=true)

以下是log內的xml data
![log data](https://github.com/EthanHung/test/blob/master/xml%20data.png?raw=true)

**Comment by overtrue** [comment]
您怎么调试的？

**Comment by EthanHung** [comment]
有試過直接用localhost試也有試過用微信的debug才測試

![debug](https://github.com/EthanHung/test/blob/master/Screenshot%202020-03-18%20at%2011.01.53%20AM.png?raw=true)

**Comment by overtrue** [comment]
看上面的 XML 结构中没有 FromUserName 和 ToUserName, 所以我担心是请求被修改过了，或者你请求时就没传递，测试工具的响应值（response）正常吗？如果正常的话，确保你没有使用 laravel-debugbar 之类的工具，因为他们会 append 内容到 response。

**Comment by EthanHung** [comment]
测试工具的响应值：請求是失敗的
我沒用laravel-debugbar

**Comment by overtrue** [comment]
但是服务器有日志记录对吧？状态码是多少？

EthanHung <notifications@github.com>于2020年3月18日 周三下午12:21写道：

**Comment by EthanHung** [comment]
剛剛發現不用artisan的時侯才會有access log
再看log才知道我看漏了response是用post回調我的伺服器難怪一直收不到response
最終收到了response但我發現還是沒有東西從微信發給用戶
![res](https://github.com/EthanHung/test/blob/master/resp.png?raw=true)

**Comment by overtrue** [comment]
为啥 response 是两个一样的 xml...

**Comment by EthanHung** [comment]
加了$response->send();就有兩個一樣的xml

**Comment by overtrue** [comment]
感觉你的环境会有点问题，你需要仔细查一下为啥会输出两个 XML

**Comment by EthanHung** [comment]
剛再測試而回傳已經是一個xml不是兩個
而且返回是200, ok
但還是沒有回覆用戶

**Comment by EthanHung** [comment]
@overtrue 
今日再多做一次還是請求成功但用戶沒有收到任何的回覆
感謝
[is url correct?](https://github.com/EthanHung/test/blob/master/Screenshot%202020-03-27%20at%2012.59.59%20AM.png)

[response correct](https://github.com/EthanHung/test/blob/master/Screenshot%202020-03-27%20at%201.00.29%20AM.png)

**Comment by idler8** [comment]
This is a personal use problem, not a failure of the plug-in, it is recommended to self-check.
@EthanHung

**Comment by overtrue** [comment]
> @overtrue
> 今日再多做一次還是請求成功但用戶沒有收到任何的回覆
> 感謝
> ![is url correct](https://github.com/EthanHung/test/blob/master/Screenshot%202020-03-27%20at%2012.59.59%20AM.png?raw=true)
> 
> ![response correct](https://github.com/EthanHung/test/blob/master/Screenshot%202020-03-27%20at%201.00.29%20AM.png?raw=true)
> 
> ![testing code](https://github.com/EthanHung/test/blob/master/Screenshot%202020-03-27%20at%201.07.16%20AM.png?raw=true)

如果您使用调试工具已经成功的话，那问题可能出在外部的其它地方，建议自行排查一下。

**Comment by EthanHung** [comment]
感謝兩位
我再找找

**Comment by EthanHung** [comment]
找到原因了
我配置錯了接口
