### ISSUE TITLE
laravel4.2安装不成功

### ISSUE THREAD

**Issue by xugege** [overtrue/wechat#182]
我使用laravel4.2，但是通过composer安装的时候不能成功
 [RuntimeException]
 Could not load package intervention/image in http://packagist.phpcomposer.c
 om: [UnexpectedValueException] Could not parse version constraint 4.x.x: In
 valid version string "4.x.x"

Could not parse version constraint 4.x.x: Invalid version string "4.x.x"

**Comment by overtrue** [comment]
明明报的是 `intervention/image` 包的版本号写得不对，与我这个包没有任何关系，麻烦报错时读一下错误消息，谢谢。
