### ISSUE TITLE
Failed to cache access token.

### ISSUE THREAD

**Issue by mztlive** [overtrue/wechat#1820]
## 我用的环境

* PHP 版本：7.1
* overtrue/wechat 版本：4.2.11
* 是否使用了框架？框架名称：laravel

## 问题及现象

Failed to cache access token.
项目一直好好的，今天突然抛出这个错误，经确认后这个异常是overtrue/wechat 抛出来的，经过一段时间的百度与排查，未果。

我要如何能解决这个问题？

**Comment by overtrue** [comment]
你提供的信息太少，抱歉无法推断问题可能原因，只知道是缓存 accessToken 失败。

**Comment by Chrisdowson** [comment]
我也遇到了，
我重写了cache组件
`<?php

namespace app\components;

use Psr\SimpleCache\CacheInterface;
use yii\base\Component;
use yii\base\Exception;

class EasyWeChatCache extends Component implements CacheInterface
{
    public function get($key, $default = null):array
    {
        $value = \Yii::$app->cache->get($key);
        if (is_array($value)) {
            return $value;
        }
        return [];
    }

    public function set($key, $value, $ttl = null)
    {
        $flag = \Yii::$app->cache->set($key, $value, $ttl);
        if (!$flag) {
            throw new Exception('设置缓存失败！');
        }
        return $flag;
    }

    public function delete($key)
    {
        // your code
        $flag = \Yii::$app->cache->delete($key);
        if (!$flag) {
            throw new Exception('删除缓存失败！');
        }
        return $flag;
    }

    public function clear()
    {
        // your code
        $flag = \Yii::$app->cache->flush();
        if (!$flag) {
            throw new Exception('全量删除缓存失败！');
        }
        return $flag;
    }

    public function getMultiple($keys, $default = null)
    {
        return \Yii::$app->cache->multiGet($keys);
    }

    public function setMultiple($values, $ttl = null)
    {
        return \Yii::$app->cache->multiSet($values, $ttl);
    }

    public function deleteMultiple($keys)
    {
        foreach ($keys as $key) {
             \Yii::$app->cache->delete($key);
        }
        return true;
    }

    //缓存预热
    public function has($key)
    {
        $value = \Yii::$app->cache->exists($key);
        \Yii::info(__METHOD__.json_encode($value));
        if(empty($value)){
            return false;
        }
        return true;
    }
}`，用的是yii2原生的FileCache,偶现，当很久没用access_token的时候才会报错，而且只会报一次
