### ISSUE TITLE
事件分发报错

### ISSUE THREAD

**Issue by luolaifa000** [overtrue/wechat#1821]
## 我用的环境

* PHP 版本：7.2.19
* overtrue/wechat 版本：4.0
* 是否使用了框架？框架名称：laravel

## 问题及现象
![image](https://user-images.githubusercontent.com/8252640/77382054-478d2b00-6dba-11ea-8ada-0e4748adfb3c.png)
分发事件是一个对象
![image](https://user-images.githubusercontent.com/8252640/77382090-5ffd4580-6dba-11ea-830e-d194482d89a8.png)
这里直接用对象在数组下面取值，报错

**Comment by mingyoung** [comment]
升级下 symfony/event-dispatcher

**Comment by luolaifa000** [comment]
> 升级下 symfony/event-dispatcher

{
        "name": "symfony/event-dispatcher",
        "version": "v4.2.8",
        "version_normalized": "4.2.8.0",
        "source": {
            "type": "git",
            "url": "https://github.com/symfony/event-dispatcher.git",
            "reference": "fbce53cd74ac509cbe74b6f227622650ab759b02"
        },
这个版本还要升吗

**Comment by mingyoung** [comment]
https://github.com/overtrue/wechat/blob/570ba034e522e0a94a8f2e5483f5eaa9939354d4/composer.json#L30

建议升级一下，不然你的 `overtrue/wechat` 也升级不了😅

**Comment by luolaifa000** [comment]
> https://github.com/overtrue/wechat/blob/570ba034e522e0a94a8f2e5483f5eaa9939354d4/composer.json#L30
> 
> 建议升级一下，不然你的 `overtrue/wechat` 也升级不了😅

OK
