### ISSUE TITLE
建议不要写死Http

### ISSUE THREAD

**Issue by tsunamilx** [overtrue/wechat#183]
对于微信api的http请求，你封装在了Http类里，需要的时候直接new了用。

那么问题来了。。。
我现在在做微信第三方平台，问题在于这个Http不能直接用，因为需要不同的access token，于是我自己继承了你的Http来满足需求。

然而你没有使用注入的方式，而是直接new的，导致我的Http没发用了。我只能苦逼的覆盖掉你的所有的类，把Http都换成我的，有些类是有http成员变量的，所以我只要覆盖成员变量就OK，其他类里没有成员变量，我只能覆盖所有用到Http的方法。

我知道你这个SDK仅针对微信公众号的，功能上是很赞的，但作为SDK，应该要有一定的扩展能力，比如这个Http，可以用注入的方式，就可以灵活替换了。

**Comment by overtrue** [comment]
@tsunamilx 这是遗留问题了，请使用 3.0 分支新版：https://github.com/overtrue/wechat/tree/3.0

3.0 支持了第三方授权调用
