### ISSUE TITLE
公众号配置菜单时，不支持小程序类型的菜单码？

### ISSUE THREAD

**Issue by jeffwu2000** [overtrue/wechat#1832]
## 我用的环境

* PHP 版本：7.4
* overtrue/wechat 版本：4.1
* 是否使用了框架？框架名称：TP5.1.39 LTS

**Comment by overtrue** [comment]
自己看文档，谢谢！https://developers.weixin.qq.com/doc/offiaccount/Custom_Menus/Creating_Custom-Defined_Menu.html

**Comment by jeffwu2000** [comment]
哦哦，确实是我没看全……

不好意思，占用您时间了
