### ISSUE TITLE
基础access_token怎么设置保存到redis或者数据库呢

### ISSUE THREAD

**Issue by xiongbenwu** [overtrue/wechat#1841]
## 我用的环境

* PHP 版本：7。1
* overtrue/wechat 版本：4.2
* 是否使用了框架？框架名称：
thinkphp
## 问题及现象
看文档使用的是 symfony/cache缓存，但是我不太了解这个东西，想知道怎么配置他，在哪里配置，
配置文件还是说需要修改源码

**Comment by overtrue** [comment]
### 只是使用自己存储的 access token
https://www.easywechat.com/docs/4.1/customize/access_token

### 缓存替换
https://www.easywechat.com/docs/4.1/customize/cache#heading-h2-6
