### ISSUE TITLE
Laravel如何优雅获取请求错误，例如 access_token 错误

### ISSUE THREAD

**Issue by hihuangwei** [overtrue/wechat#1849]
## 我用的环境

* PHP 版本：7.4.6
* overtrue/wechat 版本：4.2.19
* 是否使用了框架？框架名称：Laravel 7

## 问题及现象

如何优雅获取请求错误，例如 access_token secret 错误微信徐错误代码等

**Comment by overtrue** [comment]
try...catch...

黄威 <notifications@github.com>于2020年5月24日 周日下午3:31写道：

**Comment by hihuangwei** [comment]
@overtrue 
````
use EasyWeChat\Kernel\Exceptions\Exception;

try {
      $contacts = Factory::work($config);
      return $contacts->user->get('100001');
} catch (Exception $e) {
      return $e->getMessage();
}
````

`Request access_token fail: {"errcode":40001,"errmsg":"invalid credential, hint: [1590306111_47_182cd83eef8a93e587e6fb9faca94428], from ip: 110.83.153.114, more info at https:\/\/open.work.weixin.qq.com\/devtool\/query?e=40001"}`

如何得到原始的返回消息

**Comment by mingyoung** [comment]
```php
try {
    //
} catch (EasyWeChat\Kernel\Exceptions\HttpException $e) {
    (string) $e->response->getBody();
}
```

当然你也可以在 `App\Exceptions\Handler` 中捕获异常

**Comment by hihuangwei** [comment]
@overtrue @mingyoung 搞定了 谢谢

**Comment by sky8652** [comment]
EasyWeChat\Kernel\Exceptions\RuntimeException: Failed to cache access token. in file /mnt/e/work/jpworldoa/vendor/overtrue/wechat/src/Kernel/AccessToken.php on line 140

PHP 版本：7.2.5
overtrue/wechat 版本：5.0.12
