### ISSUE TITLE
好像没有『代小程序实现业务』方面的接口？

### ISSUE THREAD

**Issue by cos800** [overtrue/wechat#1852]
比如这个『上传小程序代码』

https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/Mini_Programs/code/commit.html

**Comment by fplun** [comment]
有的$mini->code->commit()

**Comment by cos800** [comment]
文档完全跟不上啊，
感觉上了贼船，
微信官方文档写得倒是详尽，
但是用了 easywechat 反而无从下手了，

**Comment by cos800** [comment]
我好像看懂了 源码。。。

**Comment by yadgen** [comment]
> 有的$mini->code->commit()

这个对象实例怎么操作的？

我现在做上传代码和获取体验版二维码，遇见这个使用问题了。
https://github.com/w7corp/easywechat/issues/2066

**Comment by yadgen** [comment]
> 我好像看懂了 源码。。。

兄弟，你怎么操作的？
