### ISSUE TITLE
使用授权登录 授权过程中 网页出现跳转链接 体验不太好 怎么处理可以优化

### ISSUE THREAD

**Issue by jartins** [overtrue/wechat#1854]
## 我用的环境

* PHP 版本：7.2
* overtrue/wechat 版本：4.0
* 是否使用了框架？框架名称：是 thinkphp5.1

## 问题及现象
 授权登录出现重定向的页面 体验不好

![4441590641203_ pic](https://user-images.githubusercontent.com/38277424/83099959-4d1c2f80-a0e1-11ea-9b92-139e3ea057a7.jpg)

**Comment by jartins** [comment]
已经解决

**Comment by almas1992** [comment]
> 已经解决

分享一下解决方案呗~~方便有需要的人参考

**Comment by overtrue** [comment]
@almas1992 返回值是一个 response 对象，不能直接 echo 啊大哥，echo 当然就能看到哪些文字啊。。。

**Comment by overtrue** [comment]
```php
$response->send();
exit;
```

**Comment by jartins** [comment]
$response->send();
exit;

这个代码是哪的 源码里没找到

**Comment by jartins** [comment]
> > 已经解决
> 
> 分享一下解决方案呗~~方便有需要的人参考

我的解决方案是 https://blog.csdn.net/jartins/article/details/106402709 直接隐藏了

**Comment by mingyoung** [comment]
可以用 `$response->getTargetUrl();` 获得需要跳转的 URL。然后根据自己框架的跳转方式去跳转。

```php
// 例如 ThinkPHP 5:
return redirect($response->getTargetUrl());
```
