### ISSUE TITLE
接口更新-新增临时素材接口变动

### ISSUE THREAD

**Issue by cenxun** [overtrue/wechat#186]
![新增临时素材-微信](!http://mp.weixin.qq.com/wiki/15/2d353966323806a202cd2deaafe8e557.html)
>本接口即为原“上传多媒体文件”接口。

>接口调用请求说明

>http请求方式: POST/FORM,需使用https
https://api.weixin.qq.com/cgi-bin/media/upload?access_token=ACCESS_TOKEN&type=TYPE
调用示例（使用curl命令，用FORM表单方式上传一个多媒体文件）：
curl -F media=@test.jpg "https://api.weixin.qq.com/cgi-bin/media/upload?access_token=ACCESS_TOKEN&type=TYPE"

## sdk api 
>  const API_UPLOAD = 'https://file.api.weixin.qq.com/cgi-bin/media/uploadimg';

## new api 
https://api.weixin.qq.com/cgi-bin/media/upload?access_token=ACCESS_TOKEN&type=TYPE

**Comment by overtrue** [comment]
@cenxun 谢谢！
