### ISSUE TITLE
小程序直播这块的 api 有提供吗？

### ISSUE THREAD

**Issue by luotianzhu** [overtrue/wechat#1869]
## 我用的环境

* PHP 版本：7.x
* overtrue/wechat 版本：4.x
* 框架名称：laravel

**Comment by overtrue** [comment]
https://github.com/overtrue/wechat/blob/master/src/MiniProgram/Broadcast/Client.php

**Comment by overtrue** [comment]
欢迎贡献文档！

**Comment by mayunf** [comment]
> 欢迎贡献文档！

这个是不是还没合并
