### ISSUE TITLE
官方文档服务器500了

### ISSUE THREAD

**Issue by jiawei666** [overtrue/wechat#1877]
## 我用的环境

* PHP 版本：
* overtrue/wechat 版本：
* 是否使用了框架？框架名称：

**Comment by overtrue** [comment]
哪个 URL？

**Comment by jiawei666** [comment]
![image](https://user-images.githubusercontent.com/24775116/85983139-8d8d0700-ba19-11ea-8502-0e6635e38fa1.png)

https://www.easywechat.com/，这个。奇怪的是，同事可以访问

**Comment by overtrue** [comment]
同事可以的话，可能是你的设备情况了。

**Comment by jiawei666** [comment]
谢谢超哥，我把本地cookie清掉就可以了
