### ISSUE TITLE
StreamResponse的saveAs方法无法写入

### ISSUE THREAD

**Issue by bblmj** [overtrue/wechat#1878]
## 我用的环境

* PHP 版本：7.2.16
* overtrue/wechat 版本：4.2.20
* 框架名称：ThinkPHP 5.0
* 操作系统：Windows Server 2008 R2 Enterprise x64

## 问题及现象

\EasyWeChat\Kernel\Http\StreamResponse的saveAs方法无法写入，提示：is not writable.
```php
if ($res instanceof \EasyWeChat\Kernel\Http\StreamResponse) {
    $filename = "room_{$room->room_id}.jpg";
    $res->saveAs(SITE_DIR . DS . 'qrcode', $filename); 
}
```
替换为以下代码可正常写入：
```php
file_put_contents(SITE_DIR . DS . 'qrcode' . DS . $filename, $res->getBody()->getContents());
```

## 原因分析
wechat/src/Kernel/Http/StreamResponse.php 第45行 is_writable 在windows下对文件夹进行写判断工作不正常。
参考：https://www.php.net/manual/zh/function.is-writable.php 下 User Contributed Notes

**Comment by overtrue** [comment]
windows服务器？
