### ISSUE TITLE
monolog 版本升级2.0

### ISSUE THREAD

**Issue by 247759589** [overtrue/wechat#1882]
依赖的monolog 现在已经2.0版本了，composer.json 强制了主版本号1.0 。导致项目无法安装monolog2.0

composer 安装信息
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - overtrue/wechat 3.3.33 requires monolog/monolog ^1.17 -> satisfiable by monolog/monolog[1.17.0, 1.17.1, 1.17.2, 1.18.0, 1.18.1, 1.18.2, 1.19.0, 1.20.0, 1.21.0, 1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.25.0, 1.25.1, 1.25.2, 1.25.3, 1.25.4, 1.x-dev] but these conflict with your requirements or minimum-stability.
    - overtrue/wechat 3.3.33 requires monolog/monolog ^1.17 -> satisfiable by monolog/monolog[1.17.0, 1.17.1, 1.17.2, 1.18.0, 1.18.1, 1.18.2, 1.19.0, 1.20.0, 1.21.0, 1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.25.0, 1.25.1, 1.25.2, 1.25.3, 1.25.4, 1.x-dev] but these conflict with your requirements or minimum-stability.
    - overtrue/wechat 3.3.33 requires monolog/monolog ^1.17 -> satisfiable by monolog/monolog[1.17.0, 1.17.1, 1.17.2, 1.18.0, 1.18.1, 1.18.2, 1.19.0, 1.20.0, 1.21.0, 1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.25.0, 1.25.1, 1.25.2, 1.25.3, 1.25.4, 1.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for overtrue/wechat (locked at 3.3.33, required as ^3.3) -> satisfiable by overtrue/wechat[3.3.33].

**Comment by overtrue** [comment]
3.x 系列的时候 Monolog 没有 2.0 哈，如果需要升级可以考虑 4.0 版本，3.x 只做安全修复
