### ISSUE TITLE
openapi回调地址请求不通过

### ISSUE THREAD

**Issue by jiandongw** [overtrue/wechat#1883]
## 我用的环境

* PHP 版本：7.2.27
* overtrue/wechat 版本：4.0
* 是否使用了框架？框架名称：否

## 问题及现象
      使用企业微信，根据文档配置了server.php的各项配置后，却显示openapi回调地址请求不通过，请问这是什么原因造成的

**Comment by jiandongw** [comment]
<?php


use EasyWeChat\Factory;

$config = [
    'corp_id'=>'ww28c5f5eeedb4b6f7',
    'agent_id' => 1000006,
  // 'app_id' => 'wx0e2f54001bc6ea40',
    'secret' => '2Ylvyg4kokYJ8_efh350aVuPWeM7ijh89IT3EjrMTLk',
    'token' => 'weixinceshi',
    'ase_key' => '2maZL5Q2xKJkAYU4K2FrfsYCSWOFUaqLYHTd4qhzC6t',




//...
];

$app = Factory::work($config);

$app->server->push(function(){
    return 'Hello easywechat.';
});

$response = $app->server->serve();

// 将响应输出
$response->send(); // Laravel 里请使用：return $response;

**Comment by overtrue** [comment]
把你的 secret 删掉哦，暴露了……
