### ISSUE TITLE
openapi回调地址未通过

### ISSUE THREAD

**Issue by jiandongw** [overtrue/wechat#1885]
## 我用的环境

* PHP 版本：7.2.27
* overtrue/wechat 版本：4.0
* 是否使用了框架？框架名称：否

**Comment by overtrue** [comment]
搞啥啊，不停的干嘛呢？

jiandongw <notifications@github.com>于2020年7月3日 周五下午6:32写道：

**Comment by jiandongw** [comment]
抱歉啊，不太会弄。
