### ISSUE TITLE
cookie失效过快

### ISSUE THREAD

**Issue by whycomeing** [overtrue/wechat#1887]
## 我用的环境

* PHP 版本：7.2
* overtrue/wechat 版本：4.0
* 是否使用了框架？框架名称：laravel

## 问题及现象

公众号网页授权完之后，重定向回来的的页面的cookie过期时间为2小时
有办法更改吗

**Comment by overtrue** [comment]
抱歉，这个 SDK 没用到 cookie 哈

wanglijun <notifications@github.com>于2020年7月4日 周六上午10:07写道：

**Comment by whycomeing** [comment]
好的，找到问题了，感谢超哥
