### ISSUE TITLE
使用小程序->订阅信息时会提示Identifier "subscribe_message" is not defined.

### ISSUE THREAD

**Issue by plamYuan** [overtrue/wechat#1888]
## 我用的环境

* PHP 版本：7.2
* overtrue/wechat 版本：4.1
* 是否使用了框架？框架名称：thinkphp5.1

## 问题及现象
使用小程序->订阅信息时会提示Identifier "subscribe_message" is not defined.请问应该怎么解决

#### 相关代码：

` public function templateMsg()
    {
        $easyWeChat = Factory::miniProgram(config('other.easywechat'));
        $list = $easyWeChat->subscribe_message->getCategory();
        dump($list);
        die();

    }`

#### 报错截图
![image](http://mutouyun-test.oss-cn-shenzhen.aliyuncs.com/upload/banner/20200709/t8mS2YNp5H.png)

**Comment by overtrue** [comment]
升级包版本到4.2
