### ISSUE TITLE
按照说明里面:基本使用（以服务端为例），总是错误

### ISSUE THREAD

**Issue by hulang** [overtrue/wechat#1893]
## 我用的环境

* PHP 版本：7.2
* overtrue/wechat 版本：4.2
* 是否使用了框架？框架名称：thinkphp 6.0

## 问题及现象
按照README.md 以服务端为例那段，报错
This page contains the following errors:
error on line 1 at column 1: Document is empty
Below is a rendering of the page up to the first error.

目前代码：
        $app = Factory::officialAccount($config);
        // 用户API
        $user = $app->user;
        //
        $app->server->push(function ($message) use ($user) {
            // 用户openid
            $openid = $message['FromUserName'];
            switch ($message['MsgType']) {
                case 'event':
                    $user = $user->get($openid);
                    return json_encode($user) . " 您好！欢迎关注 XXXX网络科技有限公司!";
                    break;

关注后：
{"errcode":48001,"errmsg":"api unauthorized hints: [lkid3Cqge-2_ZvTa!]"} 您好！欢迎关注 XXXX网络科技有限公司!

**Comment by overtrue** [comment]
你为何要用浏览器去访问这个地址？微信文档教你的？还是你自己发明的？麻烦弄清楚这个服务端是用来干嘛的，谢谢。

快乐浪子哥 <notifications@github.com>于2020年7月17日 周五下午9:24写道：

**Comment by hulang** [comment]
@overtrue 哦。。。
{"errcode":48001,"errmsg":"api unauthorized hints: [lkid3Cqge-2_ZvTa!]"} 您好！欢迎关注 XXXX网络科技有限公司!
这个不能获取用户的数据！！咋处理。。

**Comment by overtrue** [comment]
这两单词不认识谷歌翻译啊大哥，实在不行百度翻译也就10秒钟的事儿……

**Comment by hulang** [comment]
@overtrue 照着README.md那段代码，搬的。。。我去看文档吧。。
