### ISSUE TITLE
guzzlehttp/guzzle ^7.0 的支持问题

### ISSUE THREAD

**Issue by ginnerpeace** [overtrue/wechat#1894]
## 我用的环境

* PHP 版本：7.4.6
* overtrue/wechat 版本：^4.2
* 是否使用了框架？框架名称：Laravel 6

## 问题及现象

- overtrue/wechat: ^4.2 对 guzzlehttp/guzzle 的依赖是 ^6.2 || ^7.0
- 安装了 guzzlehttp/guzzle 7.0.1 之后再安装 overtrue/wechat，提示版本冲突。
- 单独安装 overtrue/wechat，最终会使用 6.5
  排查后是因为 `overtrue/socialite: dev-develop` 的依赖仍然是 `guzzlehttp/guzzle: ~6.0`

> 第一步安装报错
![image](https://user-images.githubusercontent.com/15716336/87899572-33192080-ca84-11ea-84a0-ae09d9b63241.png)

> remove guzzle 之后再次安装 wechat
![image](https://user-images.githubusercontent.com/15716336/87899929-598b8b80-ca85-11ea-8da6-78e4ba2b0199.png)

> 查看 composer.lock
![image](https://user-images.githubusercontent.com/15716336/87899946-64deb700-ca85-11ea-8d95-b6f1b0b56ba5.png)

**Comment by overtrue** [comment]
一会儿我来升级一下
