### ISSUE TITLE
ocr client 调用 身份查询时 方法错误

### ISSUE THREAD

**Issue by supersonicgeng** [overtrue/wechat#1895]
## 我用的环境

* PHP 版本：7.2
* overtrue/wechat 版本： "overtrue/wechat": "^4.2",
* 是否使用了框架？框架名称： laravel 5.8

## 问题及现象
调用 ocr 身份证查询时 底层代码为 httpGet 请求 
实际现在 微信 的请求方式为 post 
使用自带的 $app->ocr->idCard() 方法 微信会报错 43002 自己修改源码 请求方式为 httpPost 成功返回
下面是源码 请求方式
```
public function idCard(string $path, string $type = 'photo')
    {
        if (!\in_array($type, $this->allowTypes, true)) {
            throw new InvalidArgumentException(sprintf("Unsupported type: '%s'", $type));
        }

        return $this->httpGet('cv/ocr/idcard', [
            'type' => $type,
            'img_url' => $path,
        ]);
    }
```
此处为微信小程序 接口文档
![image](https://user-images.githubusercontent.com/36435756/88021746-a1cbac00-cb60-11ea-9a5f-73bb6e443f82.png)

**Comment by overtrue** [comment]
帮忙试试另外两个接口吧？银行卡和驾照，我一起发版

**Comment by liuyuno** [comment]
@overtrue 
![image](https://user-images.githubusercontent.com/28513143/88502372-d62be600-d000-11ea-848b-a45f04a94a2d.png)

还有这里之前写的 \EasyWeChat\MiniProgram\OCR\Client  IDE无法提示
