### ISSUE TITLE
lumen 7 下与 guzzlehttp/guzzle 版本冲突

### ISSUE THREAD

**Issue by shdiablo** [overtrue/wechat#1896]
## 我用的环境

* PHP 版本：7.4.7
* overtrue/wechat 版本：^4.2
* 是否使用了框架？框架名称：lumen 7.0

## 问题及现象

安装 overtrue/wechat  之后再安装guzzlehttp/guzzle ，提示版本冲突。

![err](https://user-images.githubusercontent.com/68626732/88131312-44426880-cc0f-11ea-8838-25e266a01470.png)

**Comment by overtrue** [comment]
https://github.com/overtrue/wechat/releases/tag/4.2.24

**Comment by shdiablo** [comment]
谢谢，解决了，指定版本装才行
