### ISSUE TITLE
不能依赖 overtrue/socialite:dev-develop

### ISSUE THREAD

**Issue by ys1119** [overtrue/wechat#1897]
## 我用的环境

* PHP 版本：7.4.6
* overtrue/wechat tag:4.2.24：
* 是否使用了框架？框架名称：laravel

## 问题及现象
无：SocialiteManager::driver
不能依赖 overtrue/socialite:dev-develop  修改依赖为2.0.16 
 
$socialite = (new Socialite($wechat))->driver('wechat');

**Comment by overtrue** [comment]
请更新到 4.0.25
