### ISSUE TITLE
为什么从 4.2.24 开始，socialite依赖的是dev-develop这个分支的呢？

### ISSUE THREAD

**Issue by mogody** [overtrue/wechat#1899]
## 我用的环境

* PHP 版本：7.4.8
* overtrue/wechat 版本：4.2.25
* 是否使用了框架？框架名称：Hyperf

## 问题及现象

从 4.2.24 开始，发现 socialite 这个包的版本变成了 dev-develop，而 socialite的dev-develop 分支里面是没有 drive() 这个方法的，导致了从4.2.24开始，微信登录的时候会报 drive() method not found

**Comment by overtrue** [comment]
已经在 4.2.25 修复

**Comment by mogody** [comment]
这里还有几个疑问：
1. 4.2.24 之后依赖 socialite的dev-develop 分支代码，这个稳定性怎么样？是否可以用在生产环境？
2. 分布式环境下还需要设置请求吗？以下是easywechat文档中例子：
```php
$app->oauth->scopes(['snsapi_userinfo'])
                          ->setRequest($request)
                          ->redirect();
```
3. 简单看了源码，很多api变化了，并且不向下兼容，那么easywechat的文档是否要更新呢？

谢谢了

**Comment by overtrue** [comment]
确实不向下兼容，但是会在 wechat 内部消化这个差异，如果有遗漏还请帮忙指出

**Comment by mogody** [comment]
我们这几天业务上也在做升级，如果有问题会继续请教，万分感谢

**Comment by overtrue** [comment]
嗯啦，欢迎随时讨论
