### ISSUE TITLE
关于获取（接收）用户发送消息

### ISSUE THREAD

**Issue by zsj1029** [overtrue/wechat#19]
$this->wxServer->on('message', function($message) {
            return Message::make('text')->content('您好！');
 });
如何获取用户发来的信息呢？
比如我记录用户的信息日志
根据信息查询订单数据返回，类似智能回复
$message 这个？
如何能更好的扩展智能回复方案

**Comment by zsj1029** [comment]
貌似是的谢谢，输出了看了一下
把服务器所有信息都以json返回了
很好用的sdk，非常棒谢谢

**Comment by overtrue** [comment]
@zsj1029 是的。用户发来的信息在 `$message` 里, 同理，事件也是一样，需要注意的是，这里的 `$message` 它本身是一个对象([Bag](https://github.com/overtrue/wechat/blob/master/src/Wechat/Utils/Bag.php)), 而不是一个简单的数组，这样做的目的是为了让你可以使用 `$message-> FromUserName ` 或者 `$message['FromUserName']` 都可以得到数据。

如果你想到得到干净的数组，可以：`$message->toArray();` 或者想得到 json: `$message->toJson()` 

如果在使用过程中遇到任何问题请再向我反馈。
