### ISSUE TITLE
https://www.easywechat.com/docs/4.1/official-account/oauth这页 的代码错的

### ISSUE THREAD

**Issue by shijunti19** [overtrue/wechat#1902]
## 我用的环境

* PHP 版本：7.4
* overtrue/wechat 版本：4.1
* 是否使用了框架？框架名称：laravel

## 问题及现象

"message": "Call to undefined method Overtrue\\Socialite\\Providers\\WeChat::user()",

$app = Factory::officialAccount($config);
$oauth = $app->oauth;

// 获取 OAuth 授权结果用户信息
$user = $oauth->user();这个根本就不存在的，他弄到其他同名类里去了

**Comment by overtrue** [comment]
已经修复，请更新至 4.2.28
