### ISSUE TITLE
获取 jssdk 配置的时候，报数组越界错误

### ISSUE THREAD

**Issue by mogody** [overtrue/wechat#1908]
## 我用的环境

* PHP 版本：PHP7.4.8
* overtrue/wechat 版本：V4.2.25
* 是否使用了框架？框架名称：Hyperf

## 问题及现象

在获取 jssdk 配置的时候，报数组越界异常：
![image](https://user-images.githubusercontent.com/10496478/89035999-7c178180-d36e-11ea-8e42-4f97dea85156.png)

个人感觉像这向下不兼容的API更新，并不应该用小版本号。从 4.2.24 之后api已经是不向下兼容了(比如获取用户信息等等)，根据语义化的版本规范，这样其实是不行的。而且文档还没有来得及相应更新，导致假如安装的时候没有固定死版本，安装下来的和文档中是对不上的

**Comment by overtrue** [comment]
更新到新版，已经解决这个问题

翁航 <notifications@github.com>于2020年7月31日 周五下午8:48写道：
