### ISSUE TITLE
Composer依赖扩展版本不一致

### ISSUE THREAD

**Issue by dtshy** [overtrue/wechat#1910]
## 我用的环境

* PHP 版本：7.3.6
* overtrue/wechat 版本：5.0.1
* 是否使用了框架？框架名称：tp6.0

## 问题及现象

composer require overtrue/wechat 依赖php版本7.2、和overtrue/socialite: ^3.0

overtrue/socialite: ^3.0又依赖php7.4

造成7.3版本无法安装依赖

**Comment by overtrue** [comment]
我发个新版 https://github.com/overtrue/wechat/blob/master/composer.json#L19

**Comment by dtshy** [comment]
这样改5.0.1版本的还是用不了，之前5.0.1依赖的overtrue/socialite是2.0版本的，正常在用，今天composer update了下就挂啦，能不能还保持5.0.1对socialite2.0的依赖，新开发版的话在依赖3.0

**Comment by overtrue** [comment]
要用 socialite2.0 的话用 4.x 版本就好了啊，5.0 的发布就是因为用了 3.0 啊，而且，我确认过了，5.0.1 是依赖的 3.0：https://github.com/overtrue/wechat/commit/29c711a6b5b0322aee7ca610494991ea8522d484

**Comment by dtshy** [comment]
好的， 不确定4.0到5.0的用法上有没有很大的变化

**Comment by overtrue** [comment]
@dtshy 目前就变了 socialite 3.0

**Comment by dtshy** [comment]
好的，感谢！！！
