### ISSUE TITLE
支付成功后回调方法一直重复通知

### ISSUE THREAD

**Issue by dongshiguo** [overtrue/wechat#1911]
## 我用的环境

* PHP 版本：7.4
* overtrue/wechat 版本：overtrue/wechat: v4.2.23
* 是否使用了框架？框架名称："laravel/framework": v7.9.2

## 问题及现象

请问支付成功之后， 回调一直通知，代码里面已经return true; 并没有效果。希望能指定一下什么原因导致的。感谢！

回调代码如下：

public function notify($request)
{
        $response = $this->payment->handlePaidNotify(function ($message, $fail) {
            \Log::info('进入回调');

            return true;
        });

        return $response;
 }

**Comment by Jayin** [comment]
重复通知时正常的现象，不是你的锅，是微信的锅。你的业务逻辑处理好，重复支付通知不做处理就好了

**Comment by dongshiguo** [comment]
感谢您的回复，我这边今天做了一个修改，结果只通知一次了。

解决方法是：

把 return $response;  替换成 下面代码就解决了
 
$str = '<xml><return_code><![CDATA[SUCCESS]]></return_code><return_msg><![CDATA[OK]]></return_msg></xml>';
exit($str);
