### ISSUE TITLE
未来是否还会继续出现小版本号升级，API不兼容的情况？

### ISSUE THREAD

**Issue by mogody** [overtrue/wechat#1912]
## 我用的环境

* PHP 版本：7.4.8
* overtrue/wechat 版本：4.2.30
* 是否使用了框架？框架名称：Hyperf 2.0.3

## 问题及现象
目前发现，小版本号升级出现了明显的 API 不兼容的问题。目前发现这几个API不兼容：
1. 获取授权跳转地址，目前版本是这样(4.2.30)：
```php
$redirectUrl = $officialAccount->oauth->scopes([$scope])
            ->withRedirectUrl($data['redirect_url'])
            ->redirect()
            ->getTargetUrl();
```

但是之前的某一个版本(4.2.25-4.2.29之间)，确是这样的：
```php
$redirectUrl = $officialAccount->oauth->scopes([$scope])
            ->withRedirectUrl($data['redirect_url'])
            ->redirect()；
```
这个问题导致线上用户登录功能挂了

2. 获取授权登录信息，目前版本是这样(4.2.30)：
```php
$redirectUrl = $officialAccount->oauth->scopes([$scope])
            ->withRedirectUrl($data['redirect_url'])
            ->redirect()
            ->getTargetUrl();
```

但是之前的某一个版本(4.2.25-4.2.29之间)，确是这样的：
```php
$officialAccount = EasyWechat::officialAccount();
$user = $officialAccount->oauth->userFromCode($data['code']);
```
这个不兼容导致获取用户信息出问题了

所以这边想问一下就是，未来的开发计划中，是否还会出现这种，小版本号升级 API 不兼容的情况？

**Comment by overtrue** [comment]
这确实是我的锅 😭 原本是计划在 SDK 内去兼容 socialite 的升级，后来改到后面发现很多地方没法搞，所以就回滚了这个模块的版本到2.x并将破坏性变更的版本改为 5.0 发布，对不起，给你造成麻烦了，后面我们绝对不再小版本做破坏性变更。 🙏

**Comment by mogody** [comment]
没事，我们这边也是没考虑好compose.lock的问题，下次尽量避免一下就好了，谢谢了~

**Comment by overtrue** [comment]
@mogody "没考虑好compose.lock的问题" 是指是否纳入版本控制吗？

**Comment by mogody** [comment]
对，我们这边没有把lock文件加入版本控制，然后composer.json文件版本写了^4.2版本，所以每次线上打包镜像默认都是打最新版的，才出现了这个问题

**Comment by overtrue** [comment]
@mogody 一般没有特殊原因的话，应用的 composer.lock 是需要放到版本控制的（library 除外），这样才能确保每个开发者的版本一致并且发版是有保证的
