### ISSUE TITLE
能否新增http代理功能？

### ISSUE THREAD

**Issue by lzj500** [overtrue/wechat#1915]
## 我用的环境

* PHP 版本：7.2
* overtrue/wechat 版本：4
* 是否使用了框架？框架名称：thinkphp

## 问题及现象

由于我们本地开发，或者使用内网穿透开发，我们本地是没有固定IP的，但是微信获取access_token需要IP在白名单里。如果能提供代理这个配置，GuzzleHttp是提供代理配置的。只要把这个配置开放出来即可。这样更加便于我们本地调试。希望开发者考虑一下我这个建议，谢谢。辛苦了。

**Comment by overtrue** [comment]
麻烦仔细阅读完文档哈：https://www.easywechat.com/docs/4.1/official-account/configuration

![image](https://user-images.githubusercontent.com/1472352/90087314-07b9e680-dd4f-11ea-834b-ffbfd6b0ae82.png)

**Comment by lzj500** [comment]
明白了。谢谢提醒
