### ISSUE TITLE
Request access_token fail: {"errcode":41002,"errmsg":"appid missing rid: 5f368647-37f5f5fd-763fff09"}

### ISSUE THREAD

**Issue by MrCPF** [overtrue/wechat#1918]
## 我用的环境

* PHP 版本：7.3
* overtrue/wechat 版本：4.2
* 是否使用了框架？框架名称：phalcon

## 问题及现象
在所有使用easywechat的地方均报错：Request access_token fail: {"errcode":41002,"errmsg":"appid missing rid: 5f368647-37f5f5fd-763fff09"}

**Comment by xjdata** [comment]
不要升级 4.2.31 用4.2.30 即可 .
