### ISSUE TITLE
有没有验证查询订单返回数据签名签名的方法

### ISSUE THREAD

**Issue by pandelix** [overtrue/wechat#1921]
## 我用的环境

* PHP 版本：
* overtrue/wechat 版本：4.1
* 是否使用了框架？框架名称：ThinkPHP5

## 问题及现象
异步回调处理方法中有验证签名合法性我看到了
可是调用各个方法后返回的数据(如查询订单),需要我自己校验签名合法性么?

**Comment by overtrue** [comment]
一般不用，除非你的服务器环境都被 DNS 劫持了
