### ISSUE TITLE
redis缓存里的access_token出现大量非法字符

### ISSUE THREAD

**Issue by Double-Jin** [overtrue/wechat#1936]
## 我用的环境

* PHP 版本7.2：
* overtrue/wechat 版本4.2.16：
* 是否使用了框架？框架名称： laravel.v5.7 + laravel-s.3.5.17

## 问题及现象

我们的系统是第三方平台，当出现这处情况事全部商家都不能开卡

![企业微信截图_b2afb89b-6f12-42e4-a5b2-3d9c07247ded](https://user-images.githubusercontent.com/48013971/94112149-9e61e300-fe77-11ea-8209-a9311b2c270c.png)

正常是这样的
![企业微信截图_9e51a1a3-b719-42ad-929d-2d780589fe7b](https://user-images.githubusercontent.com/48013971/94112178-a588f100-fe77-11ea-80e6-ce5b738b6cac.png)

**Comment by Double-Jin** [comment]
这种现象出现过很多次了，每次都说需要15-60分钟才好

**Comment by overtrue** [comment]
1. 检查是否有其它系统同时写入这个 redis 实例。
2. 在写入的时候埋钩子，确实是否写入前就已经乱码。
