### ISSUE TITLE
Call to undefined method GuzzleHttp\Utils::chooseHandler()

### ISSUE THREAD

**Issue by xiaoshangmin** [overtrue/wechat#1943]
## 我用的环境

* PHP 版本：7.4.9
* overtrue/wechat 版本：^4.2
* 是否使用了框架？框架名称：tp6

## 问题及现象

调用此api会报：Call to undefined method GuzzleHttp\Utils::chooseHandler()

`
$app = Factory::miniProgram($config);   
$wxuser = $app->auth->session($code);
`  

![image](https://user-images.githubusercontent.com/6623100/94996380-fd8dc900-05d6-11eb-9ff9-531c6604cf08.png)

 composer require overtrue/wechat   安装的guzzlehttp/guzzle 是7.xx版本 替换成6.xx就不会有这个报错

**Comment by mingyoung** [comment]
`composer dump-autoload`
