### ISSUE TITLE
公众号，安全模式下，怎么得到解密之后的信息

### ISSUE THREAD

**Issue by ruikc** [overtrue/wechat#1946]
## 我用的环境

* PHP 版本：php7.3
* overtrue/wechat 版本：4.3.1
* 是否使用了框架？框架名称：Yii2

## 问题及现象
公众号，安全模式下，怎么得到解密之后的信息。
![image](https://user-images.githubusercontent.com/7445875/95728430-16207200-0cae-11eb-91c5-7e5fcf1c12d6.png)

![image](https://user-images.githubusercontent.com/7445875/95731656-613c8400-0cb2-11eb-86bf-b90823fed52f.png)

这个地方，为什么要添加个$this->isSafeMode()？

**Comment by overtrue** [comment]
https://github.com/overtrue/wechat/blob/master/src/Kernel/ServerGuard.php#L157

**Comment by overtrue** [comment]
>为什么要添加个$this->isSafeMode()？ 

非安全模式不需要解密啊

**Comment by ruikc** [comment]
我知道我这什么问题了。
