### ISSUE TITLE
自定义缓存报错

### ISSUE THREAD

**Issue by jackwangshukai** [overtrue/wechat#1947]
## 我用的环境

* PHP 版本：7.3.19
* overtrue/wechat 版本：~4.0
* 是否使用了框架？框架名称：tp5

## 问题及现象

`          
use Symfony\Component\Cache\Simple\RedisCache;

     $host =$redis['host'];
            $port =$redis['port'];
            $select = $redis['select'];
            $password = $redis['password'];
            $timeout = $redis['timeout'];
            $redis = new \Redis();
            $redis->connect($host, $port, $timeout);
            if ('' != $password) {
                $redis->auth($password);
            }
            if (0 != $select) $redis->select($select);
            $cache = new RedisCache($redis);
            self::$app->rebind('cache', $cache);
`

 使用redis 作为缓存驱动，我看有报错

[ error ] [16384]The "Symfony\Component\Cache\Simple\RedisCache" class is deprecated since Symfony 4.3, use "Symfony\Component\Cache\Adapter\RedisAdapter" and type-hint for "Symfony\Contracts\Cache\CacheInterface" instead.[/code/vendor/symfony/cache/Simple/RedisCache.php:19]
[ error ] [16384]The "Symfony\Component\Cache\Simple\AbstractCache" class is deprecated since Symfony 4.3, use "Symfony\Component\Cache\Adapter\AbstractAdapter" and type-hint for "Symfony\Contracts\Cache\CacheInterface" instead.[/code/vendor/symfony/cache/Simple/AbstractCache.php:23]

**Comment by overtrue** [comment]
这不是错误哈，这只是警告，下一个版本将会抛弃的 API。

**Comment by jackwangshukai** [comment]
> 这不是错误哈，这只是警告，下一个版本将会抛弃的 API。

恩是个警告。我按咱们 官方文档里的 直接用predis 算了。因为我这边 Symfony已经升级到4.3了
