### ISSUE TITLE
您好,现在composer2已经发布，请问该扩展包是否支持

### ISSUE THREAD

**Issue by ouyangfangyuan** [overtrue/wechat#1951]
## 我用的环境

* PHP 版本：
* overtrue/wechat 版本：
* 是否使用了框架？框架名称：

**Comment by overtrue** [comment]
试过了么？

**Comment by ouyangfangyuan** [comment]
暂时没有试过,composer官方的提示“升级后有些 Composer 1.0 版本的插件可能还没有支持 Composer 2.0，以及新的平台检测机制会检测运行时 PHP 版本和扩展包版本是否匹配，这些都有可能导致之前本来正常的扩展包依赖解析出现问题“,所以自己的就问了一下

**Comment by overtrue** [comment]
composer 是一个包管理器，他不会影响被安装的内容，你安装一个包的时候本身就检测过环境依赖，不会有问题。
