### ISSUE TITLE
在thinkphp5.0 中报错

### ISSUE THREAD

**Issue by gytai** [overtrue/wechat#1956]
## 我用的环境

* PHP 版本：7.2.13
* overtrue/wechat 版本：4.2
* 是否使用了框架？框架名称：thinkphp5.0.24

## 问题及现象
致命错误: Cannot use object of type EasyWeChat\Work\OAuth\AccessTokenDelegate as array

**Comment by Abbotton** [comment]
请检查自己的代码，和扩展包没有关系。

**Comment by overtrue** [comment]
提问请提供上下文代码，仅凭这一行神仙也难知道问题再哪里。

**Comment by gytai** [comment]
`
/**
     * Set the token on the user.
     *
     * @param \Overtrue\Socialite\AccessTokenInterface $token
     *
     * @return $this
     */
    public function setToken(AccessTokenInterface $token)
    {
        $this->setAttribute('token', $token->getToken());
        $this->setAttribute('access_token', $token->getToken());

        if (!empty($token['refresh_token'])) {
            $this->setAttribute('refresh_token', $token['refresh_token']);
        }

        return $this;
    }
`

这里的$token 是一个对象。而代码中使用数组形式访问变量。所以报错。我看了一下老版本的代码是这样的。所以没有报错。


`
    /**
     * Set the token on the user.
     *
     * @param \Overtrue\Socialite\AccessTokenInterface $token
     *
     * @return $this
     */
    public function setToken(AccessTokenInterface $token)
    {
        $this->setAttribute('token', $token);

        return $this;
    }
`

**Comment by gytai** [comment]
https://github.com/overtrue/socialite/issues/197#issuecomment-715880948

和这里的问题一样。

**Comment by overtrue** [comment]
升级 overtrue/socialite 到 2.0.22
