### ISSUE TITLE
接口好像没有集成 uniformMessage.send

### ISSUE THREAD

**Issue by ShiqiangZhao** [overtrue/wechat#1958]
## 我用的环境

* PHP 版本：7.26
* overtrue/wechat 版本：4.1
* 是否使用了框架？框架名称：phalcon

## 问题及现象

这个接口好像没有集成
[统一消息发送 uniformMessage.send
](https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/uniform-message/uniformMessage.send.html)

**Comment by overtrue** [comment]
https://github.com/overtrue/wechat/blob/master/src/MiniProgram/UniformMessage/Client.php
