### ISSUE TITLE
authorize snsapi_base 下可以获取unionid

### ISSUE THREAD

**Issue by sayiwen** [overtrue/wechat#198]
snsapi_base 授权之后会返回这些
```
{
   "access_token":"ACCESS_TOKEN",
   "expires_in":7200,
   "refresh_token":"REFRESH_TOKEN",
   "openid":"OPENID",
   "scope":"SCOPE",
   "unionid": "o6_bmasdasdsad6_2sgVt7hMZOPfL"
}
```
所以理论上snsapi_base 下可以获取unionid。希望加一下。

**Comment by zzpwestlife** [comment]
貌似并没有 unionid

**Comment by overtrue** [comment]
有没有 unionid 请确认你加到了开放平台，SDK 并不对返回值做处理。

**Comment by overtrue** [comment]
@zzpwestlife

**Comment by zzpwestlife** [comment]
公众号已绑定开放平台，snsapi_userinfo 可以获取 unionid，没有问题。

但是 snsapi_base 没有 unionid， 还需要做什么设置么？

**Comment by overtrue** [comment]
@zzpwestlife 人家本来就没说在 snsapi_base 时会返回 Unionid 啊：

> https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140842
> https://developers.weixin.qq.com/blogdetail?action=get_post_info&lang=zh_CN&token=&docid=70ea209ea2f0c70719467d692f0d4e34

![image](https://user-images.githubusercontent.com/1472352/39617643-0d07f270-4fb3-11e8-9016-f5c0d89e158d.png)

**Comment by zzpwestlife** [comment]
之前可以，后来删除了。了解了， 非常感谢。
