### ISSUE TITLE
access token 重复添加的问题

### ISSUE THREAD

**Issue by alpha1130** [overtrue/wechat#201]
version: 2.1
Wechat/Http.php

line 81:
        if ($this->token) {
            // clear repeat token
            $url = preg_replace('/[?&]access_token\=[^&]*/i', '', $url);
            $url .= (stripos($url, '?') ? '&' : '?').'access_token='. $this->token->getToken();

**Comment by overtrue** [comment]
为啥会有重复添加的问题，在其它地方都没有设置过access token 呢

**Comment by overtrue** [comment]
@alpha1130 找到问题所在了，是重试机制导致的，多谢！
