### ISSUE TITLE
网页授权 跳转

### ISSUE THREAD

**Issue by cutexin** [overtrue/wechat#202]
// 未登录
if (empty($_SESSION['wechat_user'])) {
  return $oauth->with(['target_url' => 'user/profile'])->redirect();
  // 这里不一定是rturn，如果你的框架action不是返回内容的话你就得使用
  // $oauth->with(['target_url' => 'user/profile'])->redirect()->send();
}

使用官网文档测试，获取授权后不能跳转到target_url, 在授权页面打印GET变量 没有target_url

**Comment by overtrue** [comment]
这个问题我修复一下，谢谢！
