### ISSUE TITLE
微信支付里有一个收货地址共享 ,超哥你这里没有,可以加一下不?

### ISSUE THREAD

**Issue by laione001** [overtrue/wechat#204]
已经跪等https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=7_8&index=7

**Comment by overtrue** [comment]
http://easywechat.org/docs/zh-cn/payment.html#u751F_u6210_u5171_u4EAB_u6536_u8D27_u5730_u5740_JS__u914D_u7F6E
