### ISSUE TITLE
模板消息notice

### ISSUE THREAD

**Issue by zsj1029** [overtrue/wechat#21]
建议
将send的返回值，返回全部，不要只是msgid
    {
           "errcode":0,
           "errmsg":"ok",
           "msgid":200228332
       }
回头方便调用者处理发送过程的结果（不是微信告知用户是否收到）

**Comment by overtrue** [comment]
@zsj1029 失败的话返回的是 `false` 而不是 `msgid`

**Comment by overtrue** [comment]
@zsj1029 以下代码在请求的时候，如果发送失败就会异常了：

https://github.com/overtrue/wechat/blob/master/src/Wechat/Notice.php#L215-L217

**Comment by zsj1029** [comment]
正常传递，基本不会失败对吧
代码处理了异常吗？
我要做个接口给其他系统发送信息用的
我意思假如发送失败，微信不会返回类似
{
"errcode":1,
"errmsg":"sorry sth is wrong"
}
我就把这部分错误信息直接返回给调用我接口的系统

**Comment by overtrue** [comment]
整个SDK 都是统一用异常形式报错的，你可以用try catch 
或者全局定义一个错误处理，只捕获本SDK的
