### ISSUE TITLE
发送模板消息 CRUL 错误

### ISSUE THREAD

**Issue by cutexin** [overtrue/wechat#223]
发送模板消息时提示CURL 56错误 CURLE_RECV_ERROR
easywechat.ERROR: 0: cURL error 56:  CP connection reset by peer (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 187.

**Comment by overtrue** [comment]
@cutexin 正在跟进这个问题

**Comment by overtrue** [comment]
https://github.com/overtrue/wechat/commit/b78be546eccb63b4cf62ca861d4afa02dba6420c
