### ISSUE TITLE
[3.0][payment] 两个可能的bug

### ISSUE THREAD

**Issue by sunmingyang** [overtrue/wechat#235]
根据官网文档使用，发现两个可能存在的bug

第一个
文档：http://easywechat.org/docs/payment.html#u7EDF_u4E00_u4E0B_u5355

统一下单，提交之后微信返回的错误是post不得为空，然后一路找到

https://github.com/overtrue/wechat/blob/develop/src/Core/Http.php#L78

把 “ form_options” 改成 “body”解决；

第二个

支付签名在 微信公众平台支付接口调试工具上，验证签名不通过

https://github.com/overtrue/wechat/blob/develop/src/Payment/helpers.php#L38

改成 
return strtoupper ( call_user_func_array ( $encryptMethod, [ urldecode ( http_build_query ( $attributes ) ) ] ) );

就可以了

**Comment by overtrue** [comment]
@sunmingyang 下次直接PR吧
