### ISSUE TITLE
The implementation class of ServerServiceProvider missing an important 

### ISSUE THREAD

**Issue by motionlife** [overtrue/wechat#244]
In the Guard class, line #324, it seems that you forgot to declare the property of messageFilter, which caused the dysfunction of  received message type-filtering.

protected function handleMessage($message)
    {
        $handler = $this->messageHandler;

        if (!is_callable($handler)) {
            Log::debug('No handler enabled.');

            return;
        }

        Log::debug('Message detail:', $message);

        $message = new Collection($message);

        $type = $this->messageTypeMapping[$message->get('MsgType')];

        $response = null;
        
        // forgot to declare the property of messageFilter?
        if ($this->messageFilter & $type) {
            $response = call_user_func_array($handler, [$message]);
        }

        return $response;
    }

**Comment by overtrue** [comment]
@motionlife Thanks.
