### ISSUE TITLE
typo of variable

### ISSUE THREAD

**Issue by lichunqiang** [overtrue/wechat#245]
[Here](https://github.com/overtrue/wechat/blob/master/src%2FSupport%2FFile.php#L91,)

It should be `$stream`.

Now the master branch is the main branch for develop 3.0?

**Comment by motionlife** [comment]
谢谢

**Comment by overtrue** [comment]
@lichunqiang `master` 与 `develop` 都是3.0，`master` 是稳定版，`develop` 是开发版可能包含一些未完成的feature，这样
