### ISSUE TITLE
为什么所有的子模块在自己的库都是develop分支

### ISSUE THREAD

**Issue by lichunqiang** [overtrue/wechat#247]
导致现在不能单独使用某个模块，例如 `payment`

在 `composer` 中依赖的是 ` "easywechat/core" : "dev-master"`

而这个会导致在安装 `payment` 模块的时候安装不成功。

需要帮助改下吗？需要的话，我可以提交个pr吧依赖改下，改成  `dev-develop`

**Comment by lichunqiang** [comment]
还是目前如果使用3.0的话，只能安装  `overtrue/wechat`

**Comment by overtrue** [comment]
@lichunqiang 不需要修改，现在3.0本来就是开发版，而且那个自己的包不是强依赖，只是一个分发用的而已
