### ISSUE TITLE
下载素材的一个小问题

### ISSUE THREAD

**Issue by Liu-xu-dong** [overtrue/wechat#263]
我使用jssdk接口上传文件，获取到mediaId，然后下载文件的时候，返不到文件的后缀。我也不知道问题原因，大神告诉我Overtrue\Wechat\Utils\File.php 92行改成
$finfo = new finfo(FILEINFO_MIME_TYPE);就好使了。版本2.1。一样的问题可以试试。

**Comment by greedying** [comment]
帅哥，这个问题最后怎么解决的呢

**Comment by Liu-xu-dong** [comment]
好早了把，现在都出来4了，你还看2.0的啊。
