### ISSUE TITLE
40029不合法的oauth_code

### ISSUE THREAD

**Issue by motionlife** [overtrue/wechat#264]
总是出这个 请问大家有没遇到过 怎么解决的 我用的是Laravel 5.2

**Comment by overtrue** [comment]
@motionlife 要不你用3.0吧，我大概知道你的问题应该是把业务逻辑与授权写在一个页面的原因。

**Comment by motionlife** [comment]
@overtrue 谢谢解答。我用的是3.0刚刚发现了问题：我在middleware中写了 
return $oauth->redirect();
这可能最终导致了对微信服务器做了2次请求，我把改成
$oauth->redirect()->send();
问题解决了。希望大家遇到类似的也可以检查一下是不是这个问题。

**Comment by overtrue** [comment]
Laravel?
