### ISSUE TITLE
关于模板消息换行的问题

### ISSUE THREAD

**Issue by BelinChung** [overtrue/wechat#266]
按照官方的文档，建议使用 `\n` 来进行换行
不过，我使用过程中，好像被转义了，直接显示了出来？

```
$data = array(
    "first"    => array("\n恭喜你购买成功！\n", '#555555'),
);
```

**Comment by overtrue** [comment]
@BelinChung 刚刚试了一下：

```php
$data = [
     "first"    => "恭喜你\n购买成功！",
     "name" => "巧克力",
     "price" => "39.8元",
     "remark"   => "欢迎再次购买！",
];
```

没啥问题：

![qq20160125-0 2x](https://cloud.githubusercontent.com/assets/1472352/12551137/55a6453e-c3a3-11e5-8951-eb7eb34df1cb.png)

**Comment by BelinChung** [comment]
So  so sorry.我是前端工程师，这几天私人项目里自己写PHP..以前项目规范字符串都必须是单引号的，写PHP的时候写顺手了，不知道是不是这个原因。
            在2016年01月25日 20:37，安正超 写道:@BelinChung 刚刚试了一下：

$data = [
     "first"    => "恭喜你\n购买成功！",
     "name" => "巧克力",
     "price" => "39.8元",
     "remark"   => "欢迎再次购买！",
];

没啥问题：

**Comment by overtrue** [comment]
@BelinChung PHP里双引号才会解析转义符
