### ISSUE TITLE
2.1： Link 消息类型没有实现

### ISSUE THREAD

**Issue by chanpunlap** [overtrue/wechat#269]
wechat/src/Wechat/Message.php

没有link， 缺少const LINK = 'link'; ，报Error Message Type 'link'

回复消息为link会报， Overtrue\Wechat\Messages\BaseMessage未实现此方法：toReply()

**Comment by overtrue** [comment]
你先回去微信官方文档看看，啥时候说支持回复link类型消息了？
punlap <notifications@github.com>于2016年1月26日 周二16:45写道：

**Comment by chanpunlap** [comment]
https://github.com/overtrue/wechat/wiki/消息的使用

Wiki上写了有link的类型，源码message下也有link.php

**Comment by overtrue** [comment]
@chanpunlap 表格下面的说明没看吧

**Comment by chanpunlap** [comment]
@overtrue sorry，看漏了
