### ISSUE TITLE
wechat3.0中 有2个地方的js调用参数不一样，超哥没有提供

### ISSUE THREAD

**Issue by laione001** [overtrue/wechat#272]
1.微信支付的时候 调用js的时候配置并不能直接从js方法获取 ，需要单独提供的 2.1有的 3.0没有了
2.调用送货地址共享js的时候 也是配置需要单独生成的 。2.1和3.0里面都没有

**Comment by zhang19960118** [comment]
安抚

**Comment by overtrue** [comment]
@laione001 @zhang19960118 已经有了
