### ISSUE TITLE
3.0网页授权时scope为snsapi_base得不到openid

### ISSUE THREAD

**Issue by krissss** [overtrue/wechat#276]
而且还会报48001错误

**Comment by overtrue** [comment]
@krissss 请贴你的用法，以及是否为 `overtrue/socialite` 最新版本

**Comment by krissss** [comment]
是最新版本
$options = array_merge(self::$_weixin_options,[
            'oauth' => [
                'scopes'   => ['snsapi_base'],
                'callback' => Url::to(['/we-chat/oauth-callback']),
            ],
        ]);
这是配置信息
然后在oauth-callback下使用
$oauthUser = $oauth->user();
1. $wxOpenId = $oauthUser->getId(); // 这个获取得到的是null，并且报48001错误
2. $wxOpenId = $oauthUser['token']['openid']; // 这个方式可以获取到

**Comment by overtrue** [comment]
@krissss 请扫描一下这个二维码，然后输入内容：oauth 把得到的结果截屏发我一下：

![](http://mmbiz.qpic.cn/mmbiz/l77NfczuBicqgHOxr7Inb9rG4cia40ljF6ZHgwwiaicwh4dSajXiadpTWttXHpIiazoBJFLZfv3wZ1SkIzUQz7SfMrLg/0)

**Comment by terranc** [comment]
同样遇到这个问题，是怎么解决的呀？

**Comment by scqrzdt** [comment]
5x也遇到这个问题
