### ISSUE TITLE
[3.0]Message/Article类的$properties内的source_url没有正常转换为content_source_url.

### ISSUE THREAD

**Issue by yanqing6628780** [overtrue/wechat#281]
要改成以下才能正常提交原文链接
`class Article extends AbstractMessage
{
    /**
     * Properties.
     *
     * @var array
     */
    protected $properties = [
                                'thumb_media_id',
                                'author',
                                'title',
                                'content',
                                'digest',
                                'content_source_url',
                                // 'source_url',
                                'show_cover',
                            ];

    /**
     * Aliases of attribute.
     *
     * @var array
     */
    protected $aliases = [
        // 'source_url' => 'content_source_url',
        'show_cover' => 'show_cover_pic',
    ];
}`

我在new时使用source_url构造.看日志,post到微信那边的字段还是source_url.
`$article = new Article([`
`            'title'   => $item['title'],`
`            'author'  => $item['author'],`
`            'content' => $item['content'],`
`            'digest' => $item['digest'],`
`            'source_url' => $item['content_source_url'],`
`]);`

**Comment by overtrue** [comment]
fixed
