### ISSUE TITLE
[3.0] 无法获取用户分组信息

### ISSUE THREAD

**Issue by chao** [overtrue/wechat#285]
按照文档里的

`$userGroupId = $userService->group($openId);
`

去获取某个指定OpenID用户的分组信息失败。

按照微信的官方文档获取用户分组信息应该是用POST方法，我看了一下EasyWeChat\User\User里的getGroup方法用的是GET。

修改为json后通过POST可正确获得结果。
`   return $this->parseJSON('json', [self::API_GROUP, $params]);
`

**Comment by overtrue** [comment]
@chao 为啥不直接PR嘛 :octocat:

**Comment by chao** [comment]
懒了，下次直接PR。

**Comment by overtrue** [comment]
@chao :laughing:
