### ISSUE TITLE
[3.0] 下载永久素材时，微信返回的Content-Type不正确，导致出错。

### ISSUE THREAD

**Issue by chao** [overtrue/wechat#290]
刚发现微信接口在下载永久素材时（素材类型为video, image, voice）的，用get($mediaId)方法下载时服务器返回的Content-Type居然是`Content-Type: text/plain`。

这样导致Material.php里的get($mediaId)方法无法返回整个request body。而是开始parseJSON。而parseJSON返回的结果是`false`，所以在checkAndThrow就出错了。

不知道这个获取永久素材时的content-type不正确是我的个别现象还是普遍现象。

**Comment by overtrue** [comment]
在我发布新版之前你可以先按我的代码变更修改用着

**Comment by hareluya** [comment]
而且下载下来的音频是压缩过的，完全不能放。
视频则是下不来的。。。

**Comment by overtrue** [comment]
@hareluya 这...

**Comment by chao** [comment]
微信确实太操蛋，不仅不给文件名，还连正确content type 都不给。

@hareluya 视频给链接其实是一个页面，真要下载只有自己解析内容，抓取了。。。。
