### ISSUE TITLE
[3.0] 永久素材上传视频无法上传问题

### ISSUE THREAD

**Issue by yanqing6628780** [overtrue/wechat#304]
![qq 20160229123603](https://cloud.githubusercontent.com/assets/8479740/13385886/ea77ff24-dee0-11e5-9bc2-b92114846713.png)
Http.php这个类的upload函数.要在$this->request的options参数加上'stream' => true才能上传成功
不过,这样会造成两个问题.
1.就是视频标题和视频描述的中文会转成unicode
2.微信那边没有返回media_id.虽然没有media_id但是素材是上传成功的
![qq 20160229124002](https://cloud.githubusercontent.com/assets/8479740/13385937/94232a6c-dee1-11e5-9ebb-692846035786.png)

从微信提供的调用示例看:
`curl "https://api.weixin.qq.com/cgi-bin/material/add_material?access_token=ACCESS_TOKEN" -F media=@media.file -F  description='{"title":VIDEO_TITLE, "introduction":INTRODUCTION}'`
造成这个原因可能是因为那个@字符?
这条命令提交视频文件是能正确返回的media_id的.

**Comment by overtrue** [comment]
请尝试在 `stream=true` 的情况下，修改这部分代码：

https://github.com/overtrue/wechat/blob/master/src/Material/Material.php#L95-L102

为：

```php
 $params = [
            'description' => json_encode(
                [
                    'title' => $title,
                    'introduction' => $description,
                ]
            , JSON_UNESCAPED_UNICODE),
        ];
```

再看看结果。

**Comment by yanqing6628780** [comment]
@overtrue 这样中文没问题了.
至于第2个问题.
虽然,我能处理这个异常.但是,由于微信那边不返回media_id,你的checkAndThrow会报下面的
`0-Argument 1 passed to EasyWeChat\Core\AbstractAPI::checkAndThrow() must be of the type array, boolean given`
我也明白是啥原因造成的...就是不知道怎样告诉写微信接口那班操蛋的人

**Comment by overtrue** [comment]
@yanqing6628780 OK，就是说这样还是不返回  `media_id` 了嘛。

我再想想是否有其它原因。

**Comment by stan415** [comment]
请问这个问题现在解决了吗？

**Comment by stan415** [comment]
请问这个问题解决了吗？

**Comment by overtrue** [comment]
@stan415 你遇到啥问题了

**Comment by stan415** [comment]
@overtrue 跟上面一样的，上传视频素材微信那边不返回media_id,checkAndThrow会报这个错
Argument 1 passed to EasyWeChat\Core\AbstractAPI::checkAndThrow() must be of the type array, boolean given

**Comment by overtrue** [comment]
@stan415 超时了吧？
