### ISSUE TITLE
关于Util\HTTP::encode()中的urlencode()/urldecode()成组操作的疑问

### ISSUE THREAD

**Issue by acgrid** [overtrue/wechat#31]
其实并不明白加这段代码的作用
https://github.com/overtrue/wechat/blob/master/src/Wechat/Utils/Http.php#L267-276

从结果上说，这使得双引号在Util\JSON::encode()执行期间躲起来了。
一个情景是图文信息是可以使用HTML的，content中的双引号就杯具了QAQ
```php
$src = '""';
var_dump(urlencode($src)); // string '%22%22' (length=6)
var_dump(urldecode(urlencode($src))); // string '""' (length=2)
```

**Comment by overtrue** [comment]
@acgrid 这段代码的作用是解决 < 5.4 版本的php 不支持json_encode的第二个参数：JSON_UNESCAPED_UNICODE 

http://php.net/manual/zh/function.json-encode.php
