### ISSUE TITLE
使用sendNormal(),sendGroup()发送红包时，报Undefined index: HTTP_CLIENT_IP

### ISSUE THREAD

**Issue by chechao** [overtrue/wechat#316]
## 我用的环境

PHP 版本：5.6
overtrue/wechat 版本：3.0
Nginx： 1.9

## 问题及现象

使用`sendNormal($params);sendGroup($params)`发送红包时，报`Undefined index: HTTP_CLIENT_IP `
当填写`$params['client_ip']='127.0.0.1'`时，报签名错误!
不填写client_ip，报报Undefined index: HTTP_CLIENT_IP 

用`send($params, API::TYPE_TYPE_NORMAL);`暂时解决!

**Comment by overtrue** [comment]
@tianyong90

**Comment by tianyong90** [comment]
sendGroup时也报？不应该啊，前几天这个方法里设置IP的部分已经删除了。

**Comment by overtrue** [comment]
@tianyong90 https://github.com/overtrue/wechat/blob/master/src/Payment/LuckyMoney/API.php#L132

**Comment by tianyong90** [comment]
@chechao 请加 SDK  交流群并在群中@田较瘦
