### ISSUE TITLE
临时素材接口无法使用

### ISSUE THREAD

**Issue by zxz054321** [overtrue/wechat#319]
## 我用的环境

PHP 版本：5.6
overtrue/wechat 版本：3.0
Laravel 5.1

## 问题及现象

按照文档：
```
<?php
use EasyWeChat\Foundation\Application;

$app = new Application($options);

// 临时素材
$temporary = $app->material_temporary;
$temporary->uploadImage($pathToFile);
```
永远提示：

> EasyWeChat\Core\Exceptions\HttpException: invalid media type hint: [_GDbeA0855ure1]
> 
> E:\xampp\htdocs\LuckyQuestion\vendor\overtrue\wechat\src\Core\AbstractAPI.php:235
> E:\xampp\htdocs\LuckyQuestion\vendor\overtrue\wechat\src\Core\AbstractAPI.php:135
> E:\xampp\htdocs\LuckyQuestion\vendor\overtrue\wechat\src\Material\Temporary.php:106
> E:\xampp\htdocs\LuckyQuestion\vendor\overtrue\wechat\src\Material\Temporary.php:162

**PS：改成永久素材接口上传一切正常！**

**Comment by overtrue** [comment]
@zxz054321 https://github.com/overtrue/wechat/commit/6c78b40e95d40f6fc67b1453a80c5c8b75f176d7
