### ISSUE TITLE
订单相关接口bug

### ISSUE THREAD

**Issue by sxpd7788** [overtrue/wechat#327]
## 我用的环境

PHP 版本：5.5.9
overtrue/wechat 版本：3.0.3

## 问题及现象

调用 查询订单接口时候返回
￼
![12 pic](https://cloud.githubusercontent.com/assets/3759571/13566409/6ff30b6c-e490-11e5-8fa1-34398620ea99.jpg)
￼
{
return_code: "FAIL",
return_msg: "不识别的参数time_stamp"
}

**Comment by overtrue** [comment]
@sxpd7788 请按我的修改改一下代码测试一下告诉我结果我来发版

https://github.com/overtrue/wechat/commit/06d78513f0d8f574541d4f21e170d6b99408b66a
