### ISSUE TITLE
laravel 5.1引入包报错

### ISSUE THREAD

**Issue by alwaystrong** [overtrue/wechat#331]
在引入框架时，报下面的错：
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - overtrue/wechat 3.0.4 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - overtrue/wechat 3.0.3 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - overtrue/wechat 3.0.2 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - overtrue/wechat 3.0.1 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - overtrue/wechat 3.0 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - Installation request for overtrue/wechat ^3.0 -> satisfiable by overtrue/wechat[3.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4].

我也参考一些解决的方法，在composer.json里添加了下面一句，发现也不行
    "minimum-stability" : "dev",

**Comment by overtrue** [comment]
请稍微抽出2秒的时候看一下报错信息再提问，明明写着：

```shell
requires ext-mcrypt
```
