### ISSUE TITLE
服务器配置https 并且 通过阿里云 https cdn之后, 会出现 https 判断语句失效

### ISSUE THREAD

**Issue by shoaly** [overtrue/wechat#338]
## 我用的环境
centos
PHP 版本：
php 5.7
overtrue/wechat 版本：2.x

## 问题及现象
 $protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off' || $_SERVER['SERVER_PORT'] === 443) ? 'https://' : 'http://';  

代码中判断 当前 是https 和 http 的代码 会在服务器 上https 并且 挂 阿里云 https cnd的时候失效, 阿里云要通过判断:
if(Request::server('HTTP_X_CLIENT_SCHEME') == 'https') 去判断 才正常
描述你的问题现象，报错贴截图粘贴或者贴具体信息

**Comment by zeasly** [comment]
为什么把问题关闭了呢 我也遇到了

**Comment by shoaly** [comment]
@zeasly  因为api 已经升级到3.0了吧, 好像马上就要变成4.0...
我现在在用3.0 , 为了避免同样的问题, 我都取消 阿里云的https了, 一方面是兼容性, 另一方面我现在用的是letsencrypt 的证书3个月就过期, 还得往阿里云上同步 太麻烦
