### ISSUE TITLE
文本类型的通知消息

### ISSUE THREAD

**Issue by zhangv** [overtrue/wechat#341]
## 我用的环境
3.0
PHP 版本：
5.5

## 问题及现象
在有赞中经常见到的文本类型的通知消息是如何实现的？#不是被动消息# 就是通知消息，但是是纯文本格式的。谢谢！

**Comment by overtrue** [comment]
通知消息没有纯文本的，所以应该是客服消息

**Comment by hareluya** [comment]
也有可能是模板信息。。
