### ISSUE TITLE
请使用openssl 而不是不安全的mcrypt来加密

### ISSUE THREAD

**Issue by hye** [overtrue/wechat#342]
你的composer.json openssl , mcrypt 里require了，但 `mcrypt` 已经很久不更新了 (2008-11-22)

REF：
https://paragonie.com/blog/2015/05/if-you-re-typing-word-mcrypt-into-your-code-you-re-doing-it-wrong
https://github.com/laravel/framework/pull/9041
https://github.com/laravel/framework/issues/9020

**Comment by overtrue** [comment]
感谢，已经更换了。
