### ISSUE TITLE
js sdk config 建议增加 beta 字段

### ISSUE THREAD

**Issue by nosun** [overtrue/wechat#35]
public function config(array $APIs, $debug = false, $json = true,$beta = false)
    {
        $signPackage = $this->getSignaturePackage();

        $config = array_merge(array('debug' => $debug),array('beta' => $beta), $signPackage, array('jsApiList' => $APIs));

        return $json ? JSON::encode($config) : $config;
    }

针对设备的 api 中有 beta 这个属性……

**Comment by overtrue** [comment]
@nosun 请把微信相关的文档链接发一下

**Comment by nosun** [comment]
是设备相关的，beta版本，文档已经qq传给你了

**Comment by overtrue** [comment]
@nosun 你给的文档里没有找到 `beta` 相关字眼
