### ISSUE TITLE
无法获取 $message->ScanCodeInfo->ScanType 对象

### ISSUE THREAD

**Issue by vangogogo** [overtrue/wechat#358]
无法获取扫描值。提示找不到对应的对象 “exception 'yii\base\ErrorException' with message 'Trying to get property of non-object' in frontend/controllers/WechatController.php:48” 
![6fa02d1c-e613-4e4b-8e37-b4a690a619f5](https://cloud.githubusercontent.com/assets/5194254/14009443/e6161c38-f1c6-11e5-8253-dd7625032355.png)

**Comment by vangogogo** [comment]
jsonzhuan转换一下就可以了，好奇怪，哪里姿势不对吗？
![38b30662-6ce5-45d9-9e97-6dc958ed3ac5](https://cloud.githubusercontent.com/assets/5194254/14009798/73056538-f1ca-11e5-88af-0b1387a1db2c.png)

**Comment by overtrue** [comment]
`$message->ScanCode` 本来得到的就已经是数组了，你再去数组当成对象用肯定是不行啊。

```php
$message->ScanCodeInfo['ScanType']; 
```
