### ISSUE TITLE
[BUG] 微信收货地址无法成功

### ISSUE THREAD

**Issue by Jamlee** [overtrue/wechat#359]
## 问题及现象

官方文文档上说收货地址的access_token 是 通过静默授权来得到的，
```
注意，用网页授权接口，获取accessToken的scope是snsapi_base（和前端网页JavaScript API传入的scope不同）。因为使用了网页授权接口，url是经过微信回调后打开的，所以参与签名使用的url必须带上微信服务器返回的code和state参数。
```

但是  wechat 库里面 确是 通过直接获取的。这应该不是一个概念吧。

**Comment by overtrue** [comment]
`但是 wechat 库里面 确是 通过直接获取的` 代码呢？

**Comment by ancon** [comment]
微信的收货地址的签名错误,花了许多时间看了您写的源码,无论是getToken还是微信用户的access_token都不能获取.其二,url的值不对.

**Comment by ancon** [comment]
最终还是放弃治疗了,用了官方的SDK,不帮忙调bug了

**Comment by ancon** [comment]
希望大神尽快解决,谢谢~

**Comment by ancon** [comment]
代码在Payment.php
$accessToken = $accessToken->getToken();
这个值用来签名是不对的~
不知道改成这样对不对
            $app = app('EasyWeChat\\Foundation\\Application');
            $accessToken2 = $app->access_token;
            $token = $accessToken2->getToken(true);
但是,url的值怎么拼接就不知道了

**Comment by overtrue** [comment]
@ancon 加我QQ？44294631

**Comment by alwaystrong** [comment]
今天也遇到了这个问题。签名的地址需要拼接oauth过程code和state，否则会有错误：eidt_ address：fail或者eidtAddress：fail_auth_error

**Comment by JellyBool** [comment]
本来也想提个issue的，（用户反映，我看了一下源码）好像遇到了一样的问题,貌似是由于
```
 $signParams = [
            'appid' => $params['appId'],
            'url' => UrlHelper::current(),
            'timestamp' => $params['timeStamp'],
            'noncestr' => $params['nonceStr'],
            'accesstoken' => $accessToken,
        ];
```

这个 'UrlHelper::current()'引起的，根据微信的文档，我们应该还是要CODE和STATE这两个参数，最后的url会是类似下面这个样子：

```
url=http://open.weixin.qq.com/?code=CODE&state=STATE 
//所以在这里基本上解决的问题是：UrlHelper::current()带上CODE和STATE
```

文档地址： https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=7_8&index=7
