### ISSUE TITLE
关于Access——toekn

### ISSUE THREAD

**Issue by 104260033** [overtrue/wechat#368]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：

## 问题及现象

描述你的问题现象，报错贴截图粘贴或者贴具体信息

**Comment by 104260033** [comment]
access_token 过期问题，现在是access_toekn过期不会自动去请求刷新，需要认为的删除session

**Comment by overtrue** [comment]
@104260033 请证明它没有去自动刷新。我在 SDK 里有这个逻辑。

**Comment by 104260033** [comment]
能告诉我下在哪里嘛，我现在发现会这样

**Comment by overtrue** [comment]
https://github.com/overtrue/wechat/blob/master/src/Core/AbstractAPI.php#L158-L174

**Comment by 104260033** [comment]
谢谢，我查看下

**Comment by 104260033** [comment]
if (!$this->accessToken) {
                    return $handler($request, $options);
                }看到这里就是从新注册的对嘛
但是有个问题，现在accessToken  过期，$this->accessToken 也能获取到，所以就不会进去更新

**Comment by overtrue** [comment]
@104260033 https://github.com/overtrue/wechat/blob/master/src/Core/AbstractAPI.php#L204
