### ISSUE TITLE
laravel 下session问题

### ISSUE THREAD

**Issue by deathkel** [overtrue/wechat#369]
## 我用的环境

PHP 版本：5.6
overtrue/wechat 版本：3.0
laravel版本：5.2
## 问题及现象

laravel下面使用3.0版本的授权
我在返回的cookie中得到了2个session，laravel-session与PHPSESSID
PHPSESSION是一个php-fpm的session
怎么样能让他不创建，似乎是因为你的依赖socialite

**Comment by overtrue** [comment]
没用 [overtrue/laravel-wechat](/overtrue/laravel-wechat) 吧？

**Comment by deathkel** [comment]
laravel我看了下，就是一个中间件吧，我自己实现了那个功能。跟原生的session没关系吧

**Comment by overtrue** [comment]
@deathkel 那你参考：https://github.com/overtrue/socialite#set-custom-session-manager

把 Laravel 的 Session 放进去看看

**Comment by deathkel** [comment]
我试试
