### ISSUE TITLE
建议支持开发模式下禁用验证

### ISSUE THREAD

**Issue by zxz054321** [overtrue/wechat#373]
建议允许在开发模式下，禁用微信请求验证。不然在本地没法调试，只能放上公网接入微信MP来调

**Comment by overtrue** [comment]
@zxz054321 目前没有验证啊

**Comment by zxz054321** [comment]
感谢，问题已定位
是因swoole服务器下file_get_contents('php://input')取不到值导致
[https://github.com/zxz054321/aurora/blob/master/app/Foundation/Server.php#L79](https://github.com/zxz054321/aurora/blob/master/app/Foundation/Server.php#L79)

**Comment by overtrue** [comment]
OK
