### ISSUE TITLE
overture/wechat 2.1.36(客服消息转发错误)

### ISSUE THREAD

**Issue by caolixiang** [overtrue/wechat#374]
## 我用的环境
Laravel 5.2
PHP 版本：7.0.
overtrue/wechat 版本：2.1.36

## 问题及现象

描述你的问题现象，报错贴截图粘贴或者贴具体信息
```php

$server->on('message', function ($message) {


            return Message::make('transfer');
         
});
```
微信返回该公众号暂时无法提供服务。

**Comment by overtrue** [comment]
@caolixiang 请查看 你的web服务器错误日志，不一定问题出在这里。而且，建议贴代码多上几行，如果你知道问题出在这3行那估计你都已经改好了。对吧
