### ISSUE TITLE
自定义缓存

### ISSUE THREAD

**Issue by xifat** [overtrue/wechat#379]
怎么把accesstoken 写入redis呢？

**Comment by overtrue** [comment]
https://easywechat.org/docs/zh-cn/cache.html

**Comment by xifat** [comment]
是在构造函数里面设置么？

**Comment by xifat** [comment]
我想要把js ticket 和accesstoken 写入redis 怎么操作呢 @overtrue

**Comment by xifat** [comment]
app('redis')->connection('redis'); 怎么返回时null 呢？

**Comment by xifat** [comment]
use Doctrine\Common\Cache\PredisCache;

$predis = app('redis')->connection();// connection($name), $name 默认为 `default`
$cacheDriver = new PredisCache($predis);

_**$app->cache = $cacheDriver;  **_// 这句$app 是不是写错了？？

报错message: "Creating default object from empty value",
@overtrue

**Comment by overtrue** [comment]
@xifat 一样，只要在调用前，任何地方设置都行。
