### ISSUE TITLE
网页授权过不了

### ISSUE THREAD

**Issue by alwaystrong** [overtrue/wechat#392]
laravel 5.2
微信iOS版本

PHP 版本：5.6
overtrue/wechat 版本：3.0

问题及现象:
我在使用easy wechat的网页授权时：
开始用一个测试公众号开发的，一切都正常。
现在配置到另外一个公众号，网页授权就过不了：http://test.com/wechat/test?_url=%2Fwechat%2Ftest&code=04187031b66895077a59f5856d87dd5S&state=bf12031d4aa8c419e6e0946555f228eaca6eb6ff。感觉多拼了?_url=%2Fwechat%2Ftest这个。
我这个网页授权使用的是这个中间件'middleware' => 'wechat.oauth'。

是不是哪里的配置不对呢？

**Comment by overtrue** [comment]
test.com?

**Comment by alwaystrong** [comment]
只是示例。xxx.com

**Comment by alwaystrong** [comment]
我试了一个上午，非常困惑。
使用下面这种方式授权是可以的。
`if (empty($_GET['code'])) {
            $currentUrl = UrlHelper::current(); // 获取当前页 URL
            $response = $this->wechat->oauth->scopes(['snsapi_userinfo'])->redirect($currentUrl);
            return $response; // or echo $response;
        }`

**Comment by overtrue** [comment]
@alwaystrong 你现在的写法是在哪儿得到上面的url的？

**Comment by alwaystrong** [comment]
@overtrue 是用的你上面的 UrlHelper::current()。
我现在怀疑是我正式的服务器缺少ssl 证书，导致使用中间件session时出现了问题。
原因如下：
1. 因为我使用中间件每次进入都要走授权，说明session没起作用。
2. 现在忽然会报一个CA证书的错
![27 pic](https://cloud.githubusercontent.com/assets/12870849/14596072/8239b5d0-0576-11e6-9174-0e03635ecf13.jpg)

**Comment by alwaystrong** [comment]
@overtrue 安神，谢了。那个时ca证书问题，这台服务器是别的兄弟配的，没证书。装了一个就好了。多谢了

**Comment by overtrue** [comment]
@alwaystrong OK。

**Comment by lideshun123** [comment]
@alwaystrong  能不能把下载证书的地址 发给我一下 我也遇上这个问题 在什么地方下载证书呢

**Comment by overtrue** [comment]
@lideshun123 https://easywechat.org/docs/zh-cn/troubleshooting.html

**Comment by alwaystrong** [comment]
@lideshun123 apt-get install ca-certificates
