### ISSUE TITLE
查询支付的地址多了一个空格，导致查询失败，去掉最后的那个空格后就好了

### ISSUE THREAD

**Issue by wuhong1986** [overtrue/wechat#393]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：

## 问题及现象

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

./vendor/overtrue/wechat/src/Payment/MerchantPay/API.php:    const API_QUERY = 'https://api.mch.weixin.qq.com/mmpaymkttransfers/gettransferinfo ';

**Comment by overtrue** [comment]
@wuhong1986 Thanks.
