### ISSUE TITLE
payment里没有configForJSSDKPayment方法

### ISSUE THREAD

**Issue by zyj007** [overtrue/wechat#401]
## 我用的环境

PHP 版本：5.6.20
overtrue/wechat 版本：3.0

## 问题及现象

payment 里好像并没有文档里面的configForJSSDKPayment方法，查看源代码也没有发现有configForJSSDKPayment的定义。

**Comment by overtrue** [comment]
更新版本了么？这是昨天发版的 3.0.13

**Comment by fathoo** [comment]
在最新版中的 configForJSSDKPayment中,这两句 $config['timestamp'] = $config['timeStamp'];
unset($config['timeStamp']);应该注释掉吧,因为微信支付文档上是timeStamp大写的

**Comment by overtrue** [comment]
@fathoo JSSDK 是小写：

```js
wx.chooseWXPay({...});
```

下面的写法才是大写：

```js
WeixinJSBridge.invoke(
      'getBrandWCPayRequest',
      ...
    );
```
