### ISSUE TITLE
支付统一下单接口签名错误

### ISSUE THREAD

**Issue by icedeng** [overtrue/wechat#402]
## 我用的环境

PHP 版本：5.6
overtrue/wechat 版本：最新版

解决方法：EasyWeChat\Payment\API类方法request，385行，增加如下过滤：
```
foreach($params as $k=>$v) {
            if(empty($v)) {
                unset($params[$k]);
            }
        }
```

**Comment by overtrue** [comment]
@icedeng 试试：$params = array_filter($params);
