### ISSUE TITLE
Class 'GuzzleHttp\Middleware' not found

### ISSUE THREAD

**Issue by xiejianxuan5** [overtrue/wechat#404]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：3.0

## 问题及现象

composer 下来的代码。
$userinfoService = Yii::$app->wechat->getService('user');
$userinfo = $userinfoService->get($openid); 

Class 'GuzzleHttp\Middleware' not found、再整个vendor中也没有找到这个命名空间下的Middleware文件。是不是版本跟GuzzleHttp的版本不一样了

**Comment by overtrue** [comment]
`composer info guzzlehttp/guzzle` 把结果粘贴到这里我看看。

**Comment by xiejianxuan5** [comment]
@overtrue 多谢回复。已经解决！多个包中都用到了它。每个里面的版本都一样。我更新了。

**Comment by overtrue** [comment]
好的
