### ISSUE TITLE
通过unionid发送信息。

### ISSUE THREAD

**Issue by kelvinblood** [overtrue/wechat#411]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：
## 问题及现象

如何通过unionid给用户发信息呢？

或者换一个说方法，如何通过unionid获得用户的openid呢？

**Comment by ac1982** [comment]
unionid 就是一种特别的openid， 他跨应用不变化。微信官方文档，最后一段：https://mp.weixin.qq.com/wiki/8/f9a0b8382e0b77d87b3bcc1ce6fbc104.html
