### ISSUE TITLE
[help want]Is hard to change default configuration of GuzzleHttp

### ISSUE THREAD

**Issue by lichunqiang** [overtrue/wechat#415]
现在想要修改GuzzleHttp的请求超时时间，由默认的设置为10S超时时间，不是很容易。。。

**Comment by overtrue** [comment]
https://github.com/EasyWeChat/docs/commit/9083a30831481de5d7a41a4ece1b6a167f4fe901

**Comment by lichunqiang** [comment]
版本3.0.16，这样配置没有效果。没有在代码里面找到有提取guzzle配置的地方

**Comment by overtrue** [comment]
3.0.17

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.11.24&pv=9.3.1&source=email_footer_2]
On 周二, 5月 17, 2016 at 6:41 下午, LightOfHeaveN <notifications@github.com> wrote:
版本3.0.16，这样配置没有效果。没有在代码里面找到有提取guzzle配置的地方
