### ISSUE TITLE
下载二维码, $qrcode->download($ticket,$paths);  目录参数不可加入 中文

### ISSUE THREAD

**Issue by s81415157** [overtrue/wechat#420]
## 我用的环境

PHP 版本：5.6.13
overtrue/wechat 版本：2 

## 问题及现象

 $qrcode->download($ticket,$paths); 目录参数不可加入 中文

报错 为Illuminate\Foundation\Bootstrap\HandleExceptions">HandleExceptions</abbr>->handleError('2', 'file_put_contents(D:\xampp\htdocs\weixin\public/2016/0519/孙永权.jpg): failed to open stream: Invalid argument', 'D:\xampp\htdocs\weixin\vendor\overtrue\wechat\src\Wechat\QRCode.php', '167',

**Comment by overtrue** [comment]
你的调用代码呢？
