### ISSUE TITLE
获取 refresh_token，access_token

### ISSUE THREAD

**Issue by hubs** [overtrue/wechat#43]
<pre>
 public function user()
    {
        if ($this->authorizedUser
            || !$this->input->has('state')
            || (!$code = $this->input->get('code')) && $this->input->has('state')) {
            return $this->authorizedUser;
        }
        $permission = $this->getAccessPermission($code);
        if ($permission['scope'] !== 'snsapi_userinfo') {
            $user = new Bag(array('openid' => $permission['openid']));
        } else {
            $user = $this->getUser($permission['openid'], $permission['access_token']);
        }
        return $this->authorizedUser = $user;
    }
</pre>

您好，当access_token过期时使用accessTokenIsValid时需要access_token和刷新使用refresh_token，而<pre>
$user = new Bag(array('openid' => $permission['openid']));
</pre>
只返回了openid

**Comment by overtrue** [comment]
@hubs 谢谢，这块会在3.0里重构，目前的写法其实我也不满意

**Comment by hubs** [comment]
哈哈,谢谢，等待你放大招
