### ISSUE TITLE
WeChatProvider下的getAuthUrl个人觉得应该暴露出来

### ISSUE THREAD

**Issue by cnjack** [overtrue/wechat#432]
如题,不然总会出现跳转的链接,太不好了

**Comment by cnjack** [comment]
找到了$oauth->redirect()->getTargetUrl() 直接这样就行了

**Comment by overtrue** [comment]
@cnjack 其实你不需要这样，你的用法肯定错误了，我猜你应该是：

```php
echo $response;
```
或者：

```php
return $response;
```

应该是这样用法所致，在页面出现链接的原因估计是你的框架并不支持返回 Response 对象，这种情况下你应该这样用：

```php
$response->send();
```

**Comment by cnjack** [comment]
应该是的我用的是yaf

**Comment by overtrue** [comment]
@cnjack yaf:

```php
$response->send(); exit;
```

**Comment by cnjack** [comment]
我最终用的$this->redirect($oauth->redirect()->getTargetUrl());
感觉yaf自带的跳转蛮叼的样子,然而只是心理作用

**Comment by overtrue** [comment]
@cnjack 好吧。。。

**Comment by cnjack** [comment]
我看到了,应该不行的,因为在setTargetUrl()   里面设置了$this->setContent里面加了一些html,所以打开很丑,我并不想让用户觉得跳转了,所以还是直接header 或者用框架自带的
用send的话line378 $this->sendContent();这样会输出内容的

**Comment by overtrue** [comment]
```php
$oauth->redirect()->send(); exit;
```
这样肯定是行的

**Comment by cnjack** [comment]
实验了一下,确实可以~~哈哈,瞬间打脸

**Comment by overtrue** [comment]
@cnjack 没事，不疼。:laughing:
