### ISSUE TITLE
用户标签接口无法使用

### ISSUE THREAD

**Issue by Jasonwdt** [overtrue/wechat#433]
## 我用的环境

PHP 版本：7.0.6
overtrue/wechat 版本：3.0

## 问题及现象
  $app = new Application($useConfig);
  $tag = $app->user_tag;

在这里会报错

![qq 20160601100027](https://cloud.githubusercontent.com/assets/13548062/15696091/ec7f6742-27df-11e6-9d60-5d30490b6acf.png)

请大神有时间帮忙看一下

**Comment by overtrue** [comment]
`composer info overtrue/wechat` 然后贴结果上来

**Comment by Jasonwdt** [comment]
不好意思，给你添麻烦了，找到原因了

**Comment by overtrue** [comment]
@Jasonwdt 我就知道应该是版本太旧。。。

**Comment by Jasonwdt** [comment]
但是更新版本tag类没有更新下来

**Comment by Jasonwdt** [comment]
"overtrue/wechat": "~3.0",

**Comment by overtrue** [comment]
`composer update overtrue/wechat`

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.11.24&pv=9.3.1&source=email_footer_2]
On 周三, 6月 1, 2016 at 11:07 上午, Jasonwdt <notifications@github.com> wrote:
"overtrue/wechat": "~3.0",

**Comment by Jasonwdt** [comment]
可以了，非常感谢，大神
