### ISSUE TITLE
scan出现公众号暂时无法服务的消息

### ISSUE THREAD

**Issue by dxywx** [overtrue/wechat#436]
## 我用的环境

PHP 版本：7
overtrue/wechat 版本：当前版本

## 问题及现象

处理scan事件时候会先出一行公众号暂时无法服务，之后能正常处理事件逻辑，通过event分支判断scan，查看log也没发现错误。必要时回复的也是空字符串，不知道哪里问题。

**Comment by overtrue** [comment]
@dxywx 代码呢？

**Comment by dxywx** [comment]
`$app->server->setMessageHandler(function ($message) {
            //if (!isset($message->MsgType)) return null;

            switch ($message->MsgType) {
                case 'event':
                    return $this->eventHandler($message);
                    break;
                case 'text':
                    return $this->textHandler($message);
                    break;
                case 'image':
                    # 图片消息...
                    return null;
                    break;
                case 'voice':
                    # 语音消息...
                    return null;
                    break;
                case 'video':
                    # 视频消息...
                    return null;
                    break;
                case 'location':
                    # 坐标消息...
                    return null;
                    break;
                case 'link':
                    # 链接消息...
                    return null;
                    break;
                // ... 其它消息
                default:
                    return null;
                    break;
            }
        });`



`/*
     * 事件处理
     * */
    public function eventHandler($message){
        switch ($message->Event) {
            case 'subscribe':
            case 'SCAN':
                if (isset($message->EventKey)){
                    $qrcode_id = str_replace('qrscene_' , '' , $message->EventKey);
                    //具体业务代码
                    
                }else{
                    return null;
                }
                break;
            default:
                break;
        }
        return null;
    }`

**Comment by dxywx** [comment]
![snip20160602_4](https://cloud.githubusercontent.com/assets/7811125/15740245/a640a694-28e6-11e6-8f0d-4391cdf24b40.png)

![snip20160602_5](https://cloud.githubusercontent.com/assets/7811125/15740253/b27a64b8-28e6-11e6-9a88-60d2172c8c44.png)

**Comment by dxywx** [comment]
@overtrue 代码如上

**Comment by overtrue** [comment]
@dxywx 日志里的：`Server response created: 这里如果有XML结构` 如果有正常的XML结构，你看看从请求到达一直到这条日志出现花了多久（日志前面有时间，对比一下就知道）如果大于 `5s`, 则可能是你的业务逻辑太复杂导致超时所致。

**Comment by dxywx** [comment]
我刚刚看了一下，从接受消息到返回只需1s时间，对于scan事件直接返回null或者‘success’或者空字符串仍然有问题，但是text消息接收和回复就不存在问题。

![snip20160602_7](https://cloud.githubusercontent.com/assets/7811125/15741106/af1d499e-28ea-11e6-81d4-7ae5d1d82e7f.png)

**Comment by overtrue** [comment]
@dxywx 不需要你返回任何东西。。。 SDK 自己处理，除非你要回复消息。

**Comment by dxywx** [comment]
我排查了很久，发现微信在推送scan事件时候之前可能会调用一下服务器url，我这个url在浏览器get直接访问的时候会报错（图如下）。通过微信给我反馈的错误通知，服务器响应了一个错误页面。我觉得是不是这个状态码造成了这个“暂时无法服务”的提示？

直接访问错误如下:

![snip20160616_8](https://cloud.githubusercontent.com/assets/7811125/16105482/6ec8c390-33bd-11e6-8196-abe4968bebd3.png)

请问这个controller配置之后直接访问就是会报错吗？

controller配置如下：

```
public function development(){
        $app = app('wechat');
        $app->server->setMessageHandler(function ($message) {
            switch ($message->MsgType) {
                case 'event':
                    return $this->eventHandler($message);
                    break;
                case 'text':
                    return $this->textHandler($message);
                    break;
                case 'image':
                    # 图片消息...
                    return null;
                    break;
                case 'voice':
                    # 语音消息...
                    return null;
                    break;
                case 'video':
                    # 视频消息...
                    return null;
                    break;
                case 'location':
                    # 坐标消息...
                    return null;
                    break;
                case 'link':
                    # 链接消息...
                    return null;
                    break;
                // ... 其它消息
                default:
                    return null;
                    break;
            }
        });
        return $app->server->serve();
    }
```

**Comment by samplecms** [comment]
遇到同样的问题。
      
     function index(){
		$options = [
		    
		    'app_id'    => $this->config['app_id'],
		    'secret'    => $this->config['secret'],
		    'token'     => $this->config['token'],
		    'debug'     => true,
		    'log' => [
		        'level' => 'debug',
		        'file'  => RUNTIME_PATH.'/easywechat.log',
		    ],
		    
		];


		$app = new Application($options);
		$server = $app->server;

		$server->setMessageHandler(function ($message) {
		    return "您好！欢迎关注我!";
		});


		$server->serve()->send();


	}



日志里面没有显示错误 


        [2016-06-16 19:03:43] easywechat.DEBUG: Current config: {"app_id":"***2e3f7","secret":"***d436f","token":"wstaichi","debug":true,"log":{"level":"debug","file":"/www/mm.wstaichi.com/public/../runtime//easywechat.log"}} []
[2016-06-16 19:03:43] easywechat.DEBUG: Request received: {"Method":"POST","URI":"/weichat/index/index.html?signature=bb69bad62240a69b1228a4287b3e310e1650e32c&timestamp=1466075023&nonce=1695624170&openid=orohDuFZmnFKHPandDiXJv4H7yeo&encrypt_type=aes&msg_signature=f3230820166883ed86127b82dede670cc1dab202","Query":"encrypt_type=aes&msg_signature=f3230820166883ed86127b82dede670cc1dab202&nonce=1695624170&openid=orohDuFZmnFKHPandDiXJv4H7yeo&signature=bb69bad62240a69b1228a4287b3e310e1650e32c&timestamp=1466075023","Protocal":"HTTP/1.0","Content":"<xml>\n    <ToUserName><![CDATA[gh_51c13d9e2c0d]]></ToUserName>\n    <FromUserName><![CDATA[orohDuFZmnFKHPandDiXJv4H7yeo]]></FromUserName>\n    <CreateTime>1466075023</CreateTime>\n    <MsgType><![CDATA[text]]></MsgType>\n    <Content><![CDATA[t]]></Content>\n    <MsgId>6296744277679679315</MsgId>\n    <Encrypt><![CDATA[BHPJXAOW9Fh8PI1bMDqokdA/02V8G14x4ReuilMNwIWk5K9ARnGy9n49qtQVL+YwsVFWyMXLQGtjaB6RcJX5+mPGPknEHO+0R2gjMfZUl0Xly/yjii42Lr4Lmybk+saMh2atna7FjmeJv4AutAOIk2CcN9TQxRyXPC5I67Kph2z/CDNfud9Tyt9qHfw1U074MyMq2/L+MEpxVkfXyQLUmvlK3kotZM9xdINvqitV5bvE9jThyIDyCbpSUV8YPISG4mqRMV2kkhusvrYTuZD0R+tCg7sNqlgQNoj+BpcEvlsN7M+hq/SMFKTW3l5mUL5aRDj4VTVJbs4CvHsgatGE6NkLN0mLqPeLXwhUOzdP7ni8Mf8RlZUpXTfVdiEU3KRVjMN6KtAyx40RJ3U5SZ4IySqEzdM9Smkn7jfr08+um3Q=]]></Encrypt>\n</xml>\n"} []

**Comment by samplecms** [comment]
直接按手册写出现这样的提示。是哪里写错了吗？

**Comment by overtrue** [comment]
@samplecms 安全模式下 AES_KEY 你填写在哪儿了？

**Comment by samplecms** [comment]
要加个['aes'] 建议手册里面加一下

**Comment by overtrue** [comment]
@samplecms https://easywechat.org/zh-cn/docs/configuration.html 一直就写着的好吧？

**Comment by dxywx** [comment]
@overtrue controller直接get访问出错这个问题是不是一个正常情况？

**Comment by overtrue** [comment]
@dxywx server 端是给微信服务器访问的，不是让你用浏览器访问的。
