### ISSUE TITLE
请问 SDK 是否支持授权接入的公众号接口调用？

### ISSUE THREAD

**Issue by chenghaojun** [overtrue/wechat#438]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：~3.0
## 问题及现象

公众号是授权接入的，不一定有 token 等

**Comment by overtrue** [comment]
目前不支持

via CloudMagic for Mac [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=7.12.46&pv=10.11.5&source=email_footer_2]
On 周四, 6月 16, 2016 at 10:23 上午, chenghaojun <notifications@github.com> wrote:
我用的环境
PHP 版本：
overtrue/wechat 版本：~3.0

问题及现象
公众号是授权接入的，不一定有 token 等
