### ISSUE TITLE
安装出错

### ISSUE THREAD

**Issue by lazyou** [overtrue/wechat#450]
## 我用的环境

PHP 版本：5.5.9
overtrue/wechat 版本：3.1
laravel版本是5.0.*

## 问题及现象

执行`composer require overtrue/wechat:~3.1 -vvv`后报错如下。
我的laravel版本是5.0.*
![2016-07-07 10 51 03](https://cloud.githubusercontent.com/assets/2617574/16641238/2bb9af54-4431-11e6-9d43-8365cdea4acf.png)

**Comment by overtrue** [comment]
因为你的 Laravel 依赖的是 symfony/http-foundation 2.6.13, 而我的包依赖的是 2.7/2.8/3.0

**Comment by gentcys** [comment]
@overtrue 你的包是否可以依赖2.6版本

**Comment by overtrue** [comment]
@gentcys 再试一下

**Comment by gentcys** [comment]
@overtrue nice done! 用的是Laravel5.0.
