### ISSUE TITLE
素材管理中，上传图文下的上传图片，关于返回内容的差异

### ISSUE THREAD

**Issue by dingdayu** [overtrue/wechat#466]
## 我用的环境

**非环境问题**

## 问题及现象

官方文档中：提示`上传图文消息内的图片获取URL `返回的是图片的Url；
接口地址：`https://api.weixin.qq.com/cgi-bin/media/uploadimg?access_token=ACCESS_TOKEN`

咱们文档中：提示说明返回的是`media_id`;
文档地址：`https://easywechat.org/zh-cn/docs/material.html#上传永久文章内容图片`

相关截图

![qq 20160721143010](https://cloud.githubusercontent.com/assets/2040348/17013460/4b70924c-4f51-11e6-81c6-02c5fca87ca3.png)
![qq 20160721142929](https://cloud.githubusercontent.com/assets/2040348/17013468/53d69ff8-4f51-11e6-869a-61a20d60ff61.png)

**Comment by overtrue** [comment]
@dingdayu 感谢提醒，已经修复。
