### ISSUE TITLE
Overtrue\Wechat\Http识别JSON的问题

### ISSUE THREAD

**Issue by gera2ld** [overtrue/wechat#47]
Overtrue\Wechat\Http对JSON的识别存在问题，不能识别`text/json`，我觉得可以用
``` php
textMIME = '~/json|text/plain~i'
```

**Comment by gera2ld** [comment]
算了，其实也无所谓，直接用`Overtrue\Wechat\Utils\Http`就好了。

**Comment by overtrue** [comment]
@gera2ld 多谢，我会在下一版本中更新此问题

**Comment by overtrue** [comment]
@TheNorthMemory :+1:

**Comment by TheNorthMemory** [comment]
超超在尝试解决另外个问题 https://github.com/overtrue/wechat/commit/4222187d7cb8ed57a71fd23c32a50633e740a356 

这只能说WX 服务端屎逼很，返回的header区域贼拉不规范，SDK只能是见到一处兼容一次，屎逼。
