### ISSUE TITLE
用户授权登录问题

### ISSUE THREAD

**Issue by tomhaoye** [overtrue/wechat#481]
## 我用的环境

PHP 版本：5.6
overtrue/wechat 版本：3.0

## 问题及现象

用户授权登录回调时获取用户信息有时候会抛出invalidstateexception，有时候获取到的用户信息为null，错误日志中发现该问题，多次尝试不能复现，暂不清楚是用户操作流程问题还是其他问题。

**Comment by tomhaoye** [comment]
貌似有时候获取access_token也失败
```
The key "access_token" could not be empty.
```

**Comment by overtrue** [comment]
@tomhaoye oauth 协议是不能在失败页面刷新的，刷新就必然是 "The key "access_token" could not be empty."

第一个问题应该是你的 sessionid 丢失造成的。

**Comment by tomhaoye** [comment]
Invalid state exception是获取code的时候抛的异常吧，这个也跟我的sessionid有关吗？

**Comment by overtrue** [comment]
@tomhaoye state 使用 session 存储

**Comment by tomhaoye** [comment]
@overtrue 噢看到了，谢谢，我先再看看吧😄。

**Comment by tomhaoye** [comment]
我感觉除了过了时间回收，服务器的session丢了几率没多大，更像是微信浏览器的cookie丢了，暂时我只能捕获异常再去处理了。

**Comment by overtrue** [comment]
@tomhaoye 嗯，我也同意，大部分可能是微信浏览器的问题。

**Comment by tomhaoye** [comment]
@overtrue 回复真快，棒棒的
另外有时候会有某些时候会出现
```
cURL error 28: Operation timed out after 0 milliseconds with 0 out of 0 bytes
```
对应我找到的一个issue不知道是不是有关: https://github.com/curl/curl/issues/619

**Comment by overtrue** [comment]
应该是你的服务器请求微信 API 的时候网络抖动吧。

**Comment by tomhaoye** [comment]
嗯，出现几率很低，感觉也跟网络问题有关，谢谢啦😄

**Comment by overtrue** [comment]
不客气

On 周五, 8月 5, 2016 at 11:10 上午, yiweiq <notifications@github.com> wrote:
嗯，出现几率很低，感觉也跟网络问题有关，谢谢啦😄

**Comment by Hexor** [comment]
php7.08 laravel 5.2

网络条件不好的时候 服务器请求微信API的时候 就会报

ConnectException in CurlFactory.php line 186:
cURL error 28: Operation timed out after 0 milliseconds with 0 out of 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by overtrue** [comment]
@Hexor 那你的意思是？
