### ISSUE TITLE
微信的消息回复的FromUserName和ToUserName是不是对调了

### ISSUE THREAD

**Issue by xifat** [overtrue/wechat#484]
## 我用的环境

PHP 版本：
overtrue/wechat 版本： "overtrue/wechat": "~3.1"

## 微信的消息回复的FromUserName和ToUserName是不是对调了

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

`
$server = $this->app->server;

 $server->setMessageHandler(function ($message) {
            return "您好！欢迎关注我!";
   });
$server->serve()->send();

微信debug 
`
<xml>
    <ToUserName>
        <![CDATA[o4aeVxBRVSHGy0mHpXvKHVEHTIPE]]>
    </ToUserName>
    <FromUserName>
        <![CDATA[gd_2123132456]]>
    </FromUserName>
    <CreateTime>1470360550</CreateTime>
    <MsgType>
        <![CDATA[text]]>
    </MsgType>
    <Content>
        <![CDATA[您好！欢迎关注我!]]>
    </Content>
</xml>
`

另外$server->serve()->send();  

Content内容怎么多了<![CDATA[！]]> 是不是格式不对呢？

**Comment by overtrue** [comment]
要不你有空学习一下  XML？

**Comment by xifat** [comment]
好的,
另外FromUserName 和ToUserName 是否对调了呢，要手动指定么？
$server->serve()->send(); 在微信debug调试上回复的是上面的xml ，导致在微信上没收到消息。
是上面那个xml的格式问题么。我对比了一下Content 多了<![CDATA[ !];

**Comment by xifat** [comment]
问题已解决,弄错了！！ @overtrue  感谢这么好的应用扩展
