### ISSUE TITLE
微信支付存在问题

### ISSUE THREAD

**Issue by JKair** [overtrue/wechat#489]
## 我用的环境

PHP 版本：7
overtrue/wechat 版本：~3.0 laravel

## 问题及现象

当我使用`WeixinJSBridge`，直接生成js配置的时候，前端调用支付，提示缺少`timeStamp`
检查源码发现
```
    public function configForJSSDKPayment($prepayId)
    {
        $config = $this->configForPayment($prepayId, false);

        $config['timestamp'] = $config['timeStamp'];
        unset($config['timeStamp']);

        return $config;
    }
```
中，对timestamp进行了转换？把转换去掉之后，可以正常调用组件，是否这里是否存在问题呢，还是我调用本身就有问题？

**Comment by overtrue** [comment]
@JKair 请认真阅读文档：https://easywechat.org/zh-cn/docs/payment.html#生成支付-JS-配置

**Comment by tianyong90** [comment]
JSBridge 却用生成的 JSSDK 配置，不错才怪。

**Comment by JKair** [comment]
老眼昏花，哈哈哈，抱歉 @overtrue  @tianyong90
