### ISSUE TITLE
今天开始，授权时候一直报40029，invalid  code的错误

### ISSUE THREAD

**Issue by zhyq132** [overtrue/wechat#5]
今天开始，授权时候一直报40029，invalid  code的错误，是我配置错误还是使用错误？？？之前一直很好的在使用，没有问题。。。BTW，谢谢楼主分享这个包

**Comment by zhyq132** [comment]
应该是我们项目的个例。。。授权时，要下载头像，引入阿里云的OSS类，就报错，删除阿里云的OSS代码，就无错

**Comment by overtrue** [comment]
@zhyq132 是不是url上的参数冲突了之类的？
