### ISSUE TITLE
如何加入QQ群

### ISSUE THREAD

**Issue by kuoyehs** [overtrue/wechat#501]
在加入QQ交流群 ID: 319502940 時,
QQ會要求我回答：該框架文檔官網域名
我填寫easywechat.org仍無法進去
謝謝

**Comment by overtrue** [comment]
抱歉，其它管理员设置的问题，我已经修改了。

On 周四, 9月 8, 2016 at 3:39 下午, kuoyehs <notifications@github.com> wrote:
在加入QQ交流群 ID: 319502940 時,
QQ會要求我回答：該框架文檔官網域名
我填寫easywechat.org仍無法進去
謝謝

**Comment by aszx0413** [comment]
为什么拒绝加入了

**Comment by overtrue** [comment]
@aszx0413 没有啊

**Comment by aszx0413** [comment]
@overtrue 提示 该群群主拒绝添加任何新成员

**Comment by overtrue** [comment]
你用的什么版本在加？Mac?你用手机加一下试试
