### ISSUE TITLE
V3.1 JSSDK使用疑惑

### ISSUE THREAD

**Issue by stoensin** [overtrue/wechat#503]
## 我用的环境 phalcon3.0 php7  in macos

PHP 版本：
overtrue/wechat 版本： "overtrue/wechat": "~3.1",
## 问题及现象

 Error: Class 'EasyWeChat\Js\Js' not found in /Code/API/lib/vendor/overtrue/wechat/src/Foundation/ServiceProviders/JsServiceProvider.php on line 44

![image](https://cloud.githubusercontent.com/assets/8474954/18437310/eb93f492-792e-11e6-827a-31e2fa83e5ab.png)
![image](https://cloud.githubusercontent.com/assets/8474954/18437327/03ae66ac-792f-11e6-9fce-248f1848fcfe.png)

**Comment by stoensin** [comment]
检查了目录 发现src 下  没有 js 目录存在，安装后就没有这个目录，使用 composer require 安装的

**Comment by overtrue** [comment]
检查你的安装情况，谢谢。
