### ISSUE TITLE
支付重复回调问题

### ISSUE THREAD

**Issue by tomhaoye** [overtrue/wechat#504]
#### 说明环境情况

 - 平台:linux 
 - 软件与版本：nginx 1.9\ PHP 5.6\ easywechat 3.0

---

#### 回调部分的代码

```
$response = $app->payment->handleNotify(function($notify, $successful){
    return 具体业务流程返回值；
});
$response->send();
```

#### 问题
测试环境回调没有问题。。。而生产环境下业务能顺利完成并且return true，微信还是会重复回调。测试和生产环境下日志都记录返回包含:

```
<xml><return_code><![CDATA[SUCCESS]]></return_code><return_msg><![CDATA[OK]]></return_msg></xml>
```

因为做了判断，即使重复回调也没有影响业务，但总不能一直这样吧。。。
但是具体是哪的问题，请大神们给点意见。

**Comment by overtrue** [comment]
@tomhaoye 打个电话给微信，不要再回调了，也许会解决。

**Comment by tianyong90** [comment]
部分框架最后在最后 exit 下，比如那啥 ThinkPHP ……

**Comment by tomhaoye** [comment]
额，但是测试环境没有问题。。。
