### ISSUE TITLE
卡券核销、查询建议

### ISSUE THREAD

**Issue by loktarjugg** [overtrue/wechat#506]
## 我用的环境
mac os
PHP 版本：
overtrue/wechat 版本：3.1

## 问题及现象

卡券核销、查询接口的code码应该是非必填,而easywechat是必填项
`$card->consume('', $code);`
这样写感觉不舒服...

**Comment by tianye** [comment]
code是必填的
cardid 是可以选填的
如果 code 是自定义创建的 cardid 是必填的

cardid 默认微信生成现在 是 28位的
默认code微信生成现在是 12位纯数字 可自定义
