### ISSUE TITLE
[4.0] 微信支付 sandbox模式

### ISSUE THREAD

**Issue by ChitaGideon** [overtrue/wechat#507]
## 我用的环境

PHP 版本：5.6
overtrue/wechat 版本：3.0
## 问题及现象

https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=21_2

怎样对接沙箱模式 进行调试

**Comment by vic-volk** [comment]
Hi!

I have tried price 1.01 for sandbox.
It works for me.

**Comment by overtrue** [comment]
@vic-volk So?

**Comment by overtrue** [comment]
@vic-volk This package is not an official SDK.

**Comment by vic-volk** [comment]
Ok,

I have mistaken with the issue translation.

If I use: https://api.mch.weixin.qq.com/sandboxnew/pay/unifiedorder
from: https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=23_1
for qr-code generation, I receive bad answer:
```
沙箱支付金额(100)无效，请检查需要验收的case
```
But I solved it.

**Comment by overtrue** [comment]
@vic-volk Good Job. 👍

**Comment by skyred** [comment]
沙盒的支持已经被merge到master, 如果谁感兴趣，请测试。使用方法：

```
$app = new Application($options);
$wechat_pay = $app->payment;
$wechat_pay->enableSandbox(true);
```

**Comment by overtrue** [comment]
@skyred 

```php
$app = new Application($options);
$payment = $app->payment->sandboxMode(true);
```
