### ISSUE TITLE
2.1.40命名空间巨变引发的重大问题(疑似提错版本了)

### ISSUE THREAD

**Issue by yurenzhen** [overtrue/wechat#508]
## 我用的环境
(略)
PHP 版本：7.0n
overtrue/wechat 版本：
2.1.*
## 问题及现象
使用composer对wechat 2.1.*规则进行版本升级时, 
升级到2.1.40后提示一些wechat的类找不到, 
查看vender目录总更新后的wechat源代码, 
    1.发现目录结构发生巨大变化(变成了easywechat 3.*的目录结构)
    2.**# 发现源码的命名空间由Overtrue\Wechat\*** 变成了 EasyWechat\*** **

目测是提交错版本号了!

**Comment by overtrue** [comment]
@yurenzhen sorry, 我的失误，已经重新发版了。
