### ISSUE TITLE
php 5.6版本下出现错误（5.6以下版本正常）

### ISSUE THREAD

**Issue by fangd123** [overtrue/wechat#51]
错误提示如下：
`PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0`

`PHP Warning:  Cannot modify header information - headers already sent in Unknown on line 0`

我换成了php5.5版本后错误消失

**Comment by overtrue** [comment]
@fangd123 这只是说不再建议使用这个了。我改一下吧
