### ISSUE TITLE
$_SERVER['SERVER_ADDR'] 在mac php7中获取不到

### ISSUE THREAD

**Issue by dongm2ez** [overtrue/wechat#520]
使用支付报错，报错是

```
"return_code" => "FAIL"
"return_msg" => "spbill_create_ip参数长度有误"
```

查找源码 在获取这个值的地方扫码支付使用的是
function get_server_ip()
{
    // for php-cli(phpunit etc.)
    if (empty($_SERVER['SERVER_ADDR'])) {
        return gethostbyname(gethostname());
    }

```
return $_SERVER['SERVER_ADDR'];
```

}

但是 $_SERVER['SERVER_ADDR'] 是空的，而获取的gethostbyname(gethostname()) 为本机的机器名不是IP地址

**Comment by jinchun** [comment]
我的测试环境`phpversion()`打印的结果是 `7.0.8-2+deb.sury.org~xenial+1`，没重现你说的问题。
另外 `gethostbyname()` 如果获取的是本机的机器名而不是IP地址，通常是因为你的机器名没指向`127.0.0.1` 。（这个之前是为了解决 phpunit 等 cli 命令而作的）

**Comment by dongm2ez** [comment]
ok,已经解决了，谢谢你
