### ISSUE TITLE
[4.0] 自定义 endpoint

### ISSUE THREAD

**Issue by jefferycn** [overtrue/wechat#521]
## 我用的环境

PHP 版本：PHP 7.0.11
overtrue/wechat 版本：3.1.5
## 问题及现象

我们的业务逻辑是需要从微信上传图片，然后使用  Temporary 接口把上传到微信的临时图片取回服务器永久保存。

如果系统部署在国内的服务器，是没有问题的。但是我们的最终用户是面向海外用户。因此，EasyWeChat\Material\Temporary line 39 默认的 API_GET 地址并不适合。

我们在阿里云美西的服务器，解析`api.weixin.qq.com`这个endpoint，会得到上海联通的IP地址，速度非常慢。如果使用`file.api.wechat.com`可以解析到香港的IP，速度会快很多。

目前我的解决方法是：
- 继承 EasyWeChat\Foundation\Application，自定义 MaterialServiceProvider::class
- 使用自定义的 MaterialServiceProvider::class 以使用 自定义的 Temporary
- 使用自定义的 Temporary 继承 EasyWeChat\Material\Temporary，以修改 API_GET endpoint

目前工作正常，但是考虑到overtrue可能会升级，这个hack就会使整个sdk系统不工作。

期望：
- 是否有其他办法可以自定义 endpoint？
- 如果没有，希望在将来的版本，能够支持自定义 endpoint。

**Comment by overtrue** [comment]
@jefferycn OK, 我明白了，我会考虑这个事情
