### ISSUE TITLE
SCAN 事件会出现无法提供服务

### ISSUE THREAD

**Issue by nigelvon** [overtrue/wechat#525]
## 我用的环境

PHP 版本：7.0.12
overtrue/wechat 版本：3.1.2

## 问题及现象

SCAN 事件自动回复的时候，除了正常回复的内容，总是会同时带上“该公众号暂时无法提供服务，请稍候再试”
为了调试代码已经精简到最简

```PHP
$server = $wechat->server;
$server->setMessageHandler(function ($message) {
    return 'test';
});
return $server->serve()->send();
```

![overtrue wechat](https://cloud.githubusercontent.com/assets/909257/20094644/2ea1c9d2-a5dd-11e6-92c0-1f7047346a95.png)

**Comment by overtrue** [comment]
查看出错日志

**Comment by nigelvon** [comment]
@overtrue 
日志没出错

[2016-11-08 18:04:20] easywechat.DEBUG: Message detail: {"ToUserName":"xxx","FromUserName":"xxx","CreateTime":"1478599460","MsgType":"event","Event":"SCAN","EventKey":"event1","Ticket":"xxxx=="} []
[2016-11-08 18:04:20] easywechat.DEBUG: Server response created: {"response":"<xml><ToUserName><![CDATA[xxx]]></ToUserName><FromUserName><![CDATA[xxx]]></FromUserName><CreateTime>1478599460</CreateTime><MsgType><![CDATA[text]]></MsgType><Content><![CDATA[test]]></Content></xml>"} []

**Comment by overtrue** [comment]
你的服务器地址是多少

**Comment by overtrue** [comment]
Url

**Comment by nigelvon** [comment]
@overtrue http://wx.youwo360.com/api/main

**Comment by overtrue** [comment]
![image](https://cloud.githubusercontent.com/assets/1472352/20095194/7e0dfa2a-a5df-11e6-9977-28cadd75cb28.png)

**Comment by overtrue** [comment]
返回的内容是 no access 啊，用的微信开发者在线调试

**Comment by nigelvon** [comment]
不对吧。PHP 版本都不对啊。我随便访问一下是这个头

``
Cache-Control:no-store, no-cache, must-revalidate
Connection:keep-alive
Content-Type:text/html;charset=UTF-8
Date:Tue, 08 Nov 2016 10:20:31 GMT
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Pragma:no-cache
Server:nginx/1.10.2
Transfer-Encoding:chunked
X-Powered-By:PHP/7.0.12
``

**Comment by overtrue** [comment]
![image](https://cloud.githubusercontent.com/assets/1472352/20095368/2d766b46-a5e0-11e6-8c3a-87c191616e55.png)

**Comment by overtrue** [comment]
所以你自己看看给的 url ?

**Comment by nigelvon** [comment]
你刷新一下，我回复的时候给错了，马上改了。URL。

**Comment by overtrue** [comment]
好吧，测试内容正常，你过一段时间再看看吧，这个与 SDK 应该没有关系

**Comment by nigelvon** [comment]
好吧。好诡异我准备把所有的输入都打出来看看微信是不是请求了两次。

**Comment by nigelvon** [comment]
搞定了。原因是授权了第三方帐号服务权限。结果他们代码没写好，返回了不规范的结果。导致出来俩结果。多谢

**Comment by overtrue** [comment]
@nigelvon 好的

**Comment by nigelvon** [comment]
能不能麻烦把上面带链接的图给编辑掉谢谢啦。毕竟生产环境。还发错了

**Comment by overtrue** [comment]
已经删除所有图片
