### ISSUE TITLE
Scope 参数错误或没有 Scope 权限

### ISSUE THREAD

**Issue by zacksleo** [overtrue/wechat#528]
## Centos 7 PHP7-fpm Yii2 

PHP 版本：
overtrue/wechat 版本：

## 问题及现象

调用用户授权登录方法时, 出现**Scope 参数错误或没有 Scope 权限**,
```
https://open.weixin.qq.com/connect/qrconnect?appid={appid}&redirect_uri={domain}&response_type=code&scope=snsapi_login&state=STATE#wechat_redirect
```

**Comment by overtrue** [comment]
这是微信报的错，我解决不了。

**Comment by zacksleo** [comment]
这个会是什么原因引起的呢?

**Comment by overtrue** [comment]
@zacksleo 
1. 你的 appid 不正确
2. 用了其它账号的 appid
3. 你用错了平台权限类型：公众平台与开放平台

**Comment by zacksleo** [comment]
@overtrue 谢谢 , 我会仔细检查确认

**Comment by zacksleo** [comment]
在登录授权的时候, 我在代码中发现 位于 `socialite/src/Providers/WechatProvider`中59行:

如果scrop是`snsapi_login`, 会把`oauth2/authorize`替换为`qrconnect`, 这是为什么?

如何把这个取掉, 微信登录授权可以通过

## 使用qrconnect
![qrconnect](http://7s1rjx.com1.z0.glb.clouddn.com/QQ20161123-1.png)
## 使用oauth2/authorize
![authorize](http://7s1rjx.com1.z0.glb.clouddn.com/QQ20161123-0.png)

**Comment by overtrue** [comment]
@zacksleo 公众平台的权限里没有 snsapi_login 吧？那么你为啥要用它呢？

**Comment by overtrue** [comment]
如果没弄清楚这俩平台的区别建议不要乱用哦，开放平台 https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419316505&token=&lang=zh_CN

**Comment by overtrue** [comment]
- 公众平台只有：snsapi_base 与 snsapi_userinfo
- 开放平台：snsapi_login

😞

**Comment by zacksleo** [comment]
ok, 已经搞明白了, scope需要在Application的config里配置 😃
