### ISSUE TITLE
网页授权$auth->authorize() 后还需要保存access_token吗？

### ISSUE THREAD

**Issue by iScript** [overtrue/wechat#53]
如果 Session 中没有登录信息，则跳转到授权页并获取用户信息（$auth->authorize() 一个方法全搞定）

文档上写着一个方法全搞定，这样自己还需要保存access_token或session吗？

**Comment by overtrue** [comment]
@iScript 请看wiki页的标题：https://github.com/overtrue/wechat/wiki/%E7%BD%91%E9%A1%B5%E6%8E%88%E6%9D%83

**Comment by iScript** [comment]
不是， 我的意思是用户信息我保存了，但wiki上说不保存assess_token.  当独立用户访问大于2000的时候，是不是也会出错。  尽管用户信息保存在session了。

**Comment by overtrue** [comment]
我是说我没有保存，你需要保存(assess_token)啊。。。

**Comment by iScript** [comment]
自己保存token， $auth->authorize() 这个方法是不是不好用了。因为该方法没有token参数。
需要自己将token保存在缓存中，然后用这个方法？$auth->getUser($openId, $accessToken);

**Comment by overtrue** [comment]
“ $auth->authorize() 这个方法是不是不好用了” 不是不好用了，这只是一个简写方法。。。
