### ISSUE TITLE
服务端Server模块回复音乐消息出错

### ISSUE THREAD

**Issue by bzp2010** [overtrue/wechat#533]
## 我用的环境
overtrue/wechat 版本：3.1

## 问题及现象
该问题与Bug无关
经过流程跟踪
应在Server\Transformer类中加入音乐消息XML转换方法

下例：
`public function transformMusic(AbstractMessage $message)
    {
        $response = [
            'Music' => [
                'Title' => $message->get('title'),
                'Description' => $message->get('description'),
                'MusicUrl' => $message->get('url'),
                'HQMusicUrl' => $message->get('hq_url'),
                'ThumbMediaId' => $message->get('thumb_media_id'),
            ],
        ];
        return $response;
    }`

**Comment by overtrue** [comment]
抱歉没看到哪里有报错

**Comment by bzp2010** [comment]
抱歉是我描述出了一些问题
框架的消息回复模块无法正确拼装音乐消息，这个可以通过log看出来
因为在Transformer类中没有xml的拼装方法

**Comment by overtrue** [comment]
如果你不明白我的 issue 模板里说的：“报错截图” 与 “报错日志” 是什么的话，一定要用你自己的描述来说明问题，其实我觉得你已经具备解决问题的能力了，就不应该需要来这里提问啊。反正我说的让贴错误日志与截图你都觉得没必要。
