### ISSUE TITLE
[4.0]黑名单管理

### ISSUE THREAD

**Issue by ww380459000** [overtrue/wechat#538]
增加黑名单管理？

**Comment by mingyoung** [comment]
不是在[用户组管理](https://easywechat.org/zh-cn/docs/user-group.html#获取所有分组)里面能获取吗？

**Comment by acgrid** [comment]
应该是说的这个 https://mp.weixin.qq.com/wiki?action=doc&id=mp1471422259_pJMWA
是冗余设计？
