### ISSUE TITLE
是否有接入小程序的计划

### ISSUE THREAD

**Issue by leo108** [overtrue/wechat#543]
小程序登录接口文档 https://mp.weixin.qq.com/debug/wxadoc/dev/api/api-login.html?t=20161122

**Comment by overtrue** [comment]
抱歉，没有这个计划，而且，它是 js 玩法，不需要 PHP 的封装。

**Comment by leo108** [comment]
并不是纯JS的，用户登录是**可以有**后端部分的，可以仔细看下文档
