### ISSUE TITLE
HttpException with uploadArticle API

### ISSUE THREAD

**Issue by djade007** [overtrue/wechat#544]
## 我用的环境

PHP 版本：7.0
overtrue/wechat 版本：3.1

## 问题及现象

I'm unable to use Material::uploadArticle(). I keep getting empty content error Exception.

##wechat logs
media_id gotten from Material::uploadThumb();

`easywechat.DEBUG: Client Request: {"url":"https://api.weixin.qq.com/cgi-bin/material/add_news","method":"POST","options":{"timeout":5,"body":"{"articles":[{"thumb_media_id":"media_id","author":"TEST","digest":"This is the summary","show_cover_pic":1,"content":"This is a test content","content_source_url":"http://example.com"}]}","headers":{"content-type":"application/json"}}} []`

`[2016-12-13 22:52:46] easywechat.DEBUG: API response decoded: {"contents":{"errcode":44004,"errmsg":"empty content hint: [tlL0965e541]"}} []`

**Comment by overtrue** [comment]
plz post your code.

**Comment by djade007** [comment]
@overtrue 
` $m = app('wechat')->material->uploadThumb($path);
$article = new \EasyWeChat\Message\Article([
                'thumb_media_id' => $m->media_id,
                'author' => 'TEST',
                'tittle' => 'Test Tittle',
                'content' => "This is a test content",
                'digest' => 'description',
                'content_source_url' => 'http://example.com',
                'show_cover_pic' => 1
            ]);

           $r = app('wechat')->material->uploadArticle($articles);`

**Comment by overtrue** [comment]
`'thumb_media_id' => $m->media_id`   

> media_id gotten from Material::uploadThumb(); ??? 

get media id:

```php
$result = $material->uploadThumb("/path/to/your/thumb.jpg"); 
$mediaId = $result->media_id;
// {
//    "media_id":MEDIA_ID,
// }
```
and upload article:

```php
use EasyWeChat\Message\Article;
// 上传单篇图文
$article = new Article([
    'title' => 'xxx',
    'thumb_media_id' => $mediaId,
    //...
  ]);
$material->uploadArticle($article);

```

**Comment by djade007** [comment]
Yes media Id gotten from Material::uploadThumb().

$m = app('wechat')->material->uploadThumb($path);

**Comment by overtrue** [comment]
@djade007 it seems like that you missing the `title` key of `Article `, plz take a check.

**Comment by djade007** [comment]
The title is there.

**Comment by overtrue** [comment]
@djade007 I'm sorry, I've tried my best.

**Comment by djade007** [comment]
@overtrue, please can you try to test the Material::uploadArticle() from your end?

**Comment by overtrue** [comment]
yes, I've tried.

**Comment by djade007** [comment]
You are right, there was a typo in the title, I was using 'tittle'.

**Comment by overtrue** [comment]
@djade007 💔💔💔💔💔💔💔

**Comment by djade007** [comment]
I would blame the wechat api, the error message wasn't helpful. I kept thinking it was the content field that was missing. 

Thanks for taking your time to help.

**Comment by overtrue** [comment]
@djade007 you are welcome.
