### ISSUE TITLE
How to get authorize url?

### ISSUE THREAD

**Issue by yanpeipan** [overtrue/wechat#555]
https://mp.weixin.qq.com/wiki

I want to get authorize urls when i create menu

**Comment by mingyoung** [comment]
这类问题应该到[论坛](https://forum.easywechat.org/)提问

**Comment by yanpeipan** [comment]
看了下源码， 自行解决了

`$app->oauth->withRedirectUrl('user/center.html')->redirect()->getTargetUrl();`
