### ISSUE TITLE
卡券的 attachExtension 方法 

### ISSUE THREAD

**Issue by hubs** [overtrue/wechat#56]
<pre>
    public function attachExtension($cardId, array $extension = array())
    {
        $timestamp = time();

        $ext = array(
            'code'      => Arr::get($extension, 'code',''),
            'openid'    => Arr::get($extension, 'openid', Arr::get($extension, 'open_id','')),
            'timestamp' => $timestamp,
            'outer_id'  => Arr::get($extension, 'outer_id',''),
        );

        $ext['signature'] = $this->getSignature(
            $this->getTicket(),
            $timestamp,
            $cardId,
            $ext['code'],
            $ext['openid']
        );

        return array(
            "cardId"  => $cardId,
            "cardExt" => JSON::encode($ext),
        );
    }
</pre>

之前返回的是 card_id,card_ext 界面显示不出卡券信息,改成cardId,cardExt就可以了

**Comment by overtrue** [comment]
OK,多谢！
