### ISSUE TITLE
文档里的自定义菜单中，group_id是否为tag_id的误写？

### ISSUE THREAD

**Issue by greedying** [overtrue/wechat#561]
rt。

微信官方文档，可以设置自定义菜单的时候，可以传入具体tag_id。
easywechat文档中，为group_id

**Comment by overtrue** [comment]
@greedying 也不是写错啦，而是微信修改了，最开始是有用户组的，后来官方放弃了这个设计，改成了用户标签。。。，哈哈，感谢提醒！
