### ISSUE TITLE
支付签名错误

### ISSUE THREAD

**Issue by liuyami** [overtrue/wechat#563]
## 开发口令红包 ，纯 composer 模式

PHP 版本：7.09
overtrue/wechat 版本：3.1

## 发送普通现金红包一直返回签名错误，把发送出去的 XML 放在 https://pay.weixin.qq.com/wiki/tools/signverify/ 中验证生成的签名也是一致的。

debug 信息：

`easywechat.DEBUG: Client Request: {"url":"https://api.mch.weixin.qq.com/mmpaymkttransfers/sendredpack","method":"POST","options":{"timeout":5,"body":"<xml><mch_billno>201701075651429092</mch_billno><send_name><![CDATA[Lucky Money]]></send_name><re_openid><![CDATA[oCQj_wkvh-3_PLrnNz4BCIHJNorc]]></re_openid><total_amount>166</total_amount><wishing><![CDATA[Chinese new year]]></wishing><act_name><![CDATA[redpack test]]></act_name><remark><![CDATA[记得还钱]]></remark><total_num>1</total_num><client_ip><![CDATA[121.40.125.246]]></client_ip><wxappid><![CDATA[wxa10ac71a8741474e]]></wxappid><mch_id>1405516602</mch_id><nonce_str><![CDATA[587087f431ebc]]></nonce_str><sign><![CDATA[FEB8085F70467FC4C3ED94DAAF7371EF]]></sign></xml>","cert":"/var/www/datas/ca/apiclient_cert.pem","ssl_key":"/var/www/datas/ca/apiclient_key.pem"}} []`

`
<xml>
	<mch_billno>201701075651429092</mch_billno>
	<send_name><![CDATA[Lucky Money]]></send_name>
	<re_openid><![CDATA[oCQj_wkvh-3_PLrnNz4BCIHJNorc]]></re_openid>
	<total_amount>166</total_amount>
	<wishing><![CDATA[Chinese new year]]></wishing>
	<act_name><![CDATA[redpack test]]></act_name>
	<remark><![CDATA[记得还钱]]></remark>
	<total_num>1</total_num>
	<client_ip><![CDATA[121.40.125.246]]></client_ip>
	<wxappid><![CDATA[wxa10ac71a8741474e]]></wxappid>
	<mch_id>1405516602</mch_id>
	<nonce_str><![CDATA[587087f431ebc]]></nonce_str>
	<sign><![CDATA[FEB8085F70467FC4C3ED94DAAF7371EF]]></sign>
</xml>
`

![2](https://cloud.githubusercontent.com/assets/1524158/21740003/27e5ef00-d4e6-11e6-82da-347b38bbf84e.png)

非常感谢。

**Comment by overtrue** [comment]
@liuyami 用抓包工具看一下最终网络发出去的结果是否包含其它异常内容在里面，比如前置或者后置了其它内容

**Comment by liuyami** [comment]
@overtrue 非常感谢，打电话给微信解决了，是我账户有点非安全方面异常，现在没有问题了，真是给你添麻烦了。
