### ISSUE TITLE
Cannot use EasyWeChat\OpenPlatform\Traits\VerifyTicket as VerifyTicket because the name is already in use

### ISSUE THREAD

**Issue by wenbinye** [overtrue/wechat#579]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：3.2.3

## 问题及现象

Cannot use EasyWeChat\OpenPlatform\Traits\VerifyTicket as VerifyTicket because the name is already in use in /home/ywb/work/dsp/dsp/vendor/overtrue/wechat/src/OpenPlatform/AccessToken.php on line 31

在 OpenPlatform 名字空间下的 Guard, AccessToken 类中使用  EasyWeChat\OpenPlatform\Traits\VerifyTicket，同时这个名字空间下已有 VerifyTicket 类。建议  EasyWeChat\OpenPlatform\Traits\VerifyTicket 改名为  EasyWeChat\OpenPlatform\Traits\VerifyTicketTrait

**Comment by overtrue** [comment]
CC @mingyoung

**Comment by mingyoung** [comment]
[#580](https://github.com/overtrue/wechat/pull/580)
