### ISSUE TITLE
[4.0] PHP 版本最低要求 7.1

### ISSUE THREAD

**Issue by overtrue** [overtrue/wechat#586]
同时升级各依赖到最新版本

**Comment by greedying** [comment]
啊啊啊啊啊！迅猛

**Comment by justcodingnobb** [comment]
是要升级4.0版本么？ 只支持php7.0以上了？

**Comment by overtrue** [comment]
@justcodingnobb 不是支持 7.0，是要求 7.0 以上

**Comment by justcodingnobb** [comment]
@overtrue 有计划什么时候更新4.0版本吗？ 最近在做开发平台，发现还有很多东西并没有坐进来，另外，为了你这个7.0以上 我又买了个服务器 装LNMP都搞了一天了😂

**Comment by overtrue** [comment]
@justcodingnobb 哈哈，今年上半年完成。另外，装环境这个事情，多搞几遍，熟练就好了

**Comment by justcodingnobb** [comment]
@overtrue 👍期待4.0版本，目前的拓展做单个公众号管理已经足够了，但是开放平台的内容还是不够多，已Star， 环境已经装好了 PM技术控，要求都是最新稳定版本的环境 所以花了些时间😆

**Comment by ishuowang** [comment]
@overtrue 要求 7.0 以上估计不太好吧。
目前PHP各版本市场占有率如下：
PHP 5.6 39.67%
PHP 5.5 29.56%
PHP 7.0 20.24%
PHP 5.4 7.64%
PHP 5.3 2.43%

现在停留在5.6的应该居多。

**Comment by overtrue** [comment]
@ishuowang 5.6 升级到 7 基本是无痛的，所以不愿意升级的继续用旧版就好了。

**Comment by openset** [comment]
@overtrue 这个我是知道的，现在扩展都没什么问题。好多公司用的都是云服务器，而那些集成环境镜像，大多是5.6。项目能正常运行，一般都不愿意升级。

**Comment by overtrue** [comment]
@openset 嗯，Laravel 5.5 都 require  php 7.0 + 了，而且 7.0 带来了很多新的语法，写起来也轻松，性能也更好，与 5.6 性能几乎接近翻倍，所以何乐而不为呢，而且 4.0 与 3.0 是不兼容的，相当于要新开发，或者至少要花一些时间来集成，这样的情况下升级一下 PHP 版本也挺好的嘛。
