### ISSUE TITLE
composer update 之后报错

### ISSUE THREAD

**Issue by zhimeiRaomc** [overtrue/wechat#6]
PHP Parse error:  syntax error, unexpected '{' in /home/wwwroot/weixin.xxx.com/vendor/overtrue/laravel-wechat/src/ServiceProvider.php on line 62

**Comment by overtrue** [comment]
这个错误是因为我还在改，这个错已经fix.

这是overtrue/wechat 2.0版本的provider, 2.0 与1.0 相比变化较大
