### ISSUE TITLE
laravel5.3 安装 "overtrue/wechat:~3.1 失败

### ISSUE THREAD

**Issue by yanggg1133** [overtrue/wechat#607]
## 我用的环境

PHP 版本：7
overtrue/wechat 版本：2.1

## 问题及现象
composer require "overtrue/wechat:~3.1" -vvv

Installation failed, reverting ./composer.json to its original content.

**Comment by yanggg1133** [comment]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - overtrue/laravel-wechat 2.1.2 requires overtrue/wechat 2.1.* -> satisfiabl
e by overtrue/wechat[2.1.0, 2.1.38, 2.1.39, 2.1.41, 2.1.x-dev] but these conflic
t with your requirements or minimum-stability.
    - overtrue/laravel-wechat 2.1.2 requires overtrue/wechat 2.1.* -> satisfiabl
e by overtrue/wechat[2.1.0, 2.1.38, 2.1.39, 2.1.41, 2.1.x-dev] but these conflic
t with your requirements or minimum-stability.
    - overtrue/laravel-wechat 2.1.2 requires overtrue/wechat 2.1.* -> satisfiabl
e by overtrue/wechat[2.1.0, 2.1.38, 2.1.39, 2.1.41, 2.1.x-dev] but these conflic
t with your requirements or minimum-stability.
    - Installation request for overtrue/laravel-wechat (locked at 2.1.2, require
d as 2.1.*) -> satisfiable by overtrue/laravel-wechat[2.1.2].


Installation failed, reverting ./composer.json to its original content.

**Comment by overtrue** [comment]
`composer require overtrue/laravel-wechat:~3.1`
