### ISSUE TITLE
是否有 2.1 升级到最新版的方案？

### ISSUE THREAD

**Issue by forecho** [overtrue/wechat#609]
## 我用的环境

PHP 版本：php7
overtrue/wechat 版本：2.1

## 问题及现象

目前项目中使用的是 2.1 的最新版，是否可以直接升级到最新版而不影响以前的使用代码？
如果不行，是否有提供升级方案？
找了文档，没看到有说明，特此询问。

**Comment by overtrue** [comment]
嗯，2.0与3.x差别比较大，由于时间上的原因没有整理，不过有同学实践过了，如果不是太多的应用的话感觉差别不大，建议方式：

1. 先修改基础引入方式 app('wechat')
2. 配置文件更新
3. 找到自己应用里所有与 2.0 相关的代码
4. 逐个对比在 3.0 中的用法，将差别修改过来
5. 集成测试，修复 bug
