### ISSUE TITLE
美国移动网络获取不到accessToken

### ISSUE THREAD

**Issue by lllito** [overtrue/wechat#610]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：

## 问题及现象

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

**Comment by overtrue** [comment]
这。。。我也没有办法啊

**Comment by tianyong90** [comment]
发推特给川普，让他解决这事儿…… 😆

**Comment by motecshine** [comment]
红红火火恍恍惚惚

**Comment by DestinyLuo** [comment]
。。。。
