### ISSUE TITLE
不管哪个公众号，只要填写 这个接口地址，都能配置或应用成功，实际上是不成功的，不到怎么找错。。

### ISSUE THREAD

**Issue by dan381006472** [overtrue/wechat#611]
## 我用的环境

PHP 版本：php7.0
overtrue/wechat 版本：3.1

## 问题及现象

![image](https://cloud.githubusercontent.com/assets/3352450/24077336/d5d12db6-0c84-11e7-9e59-5dc4fe8cb7a5.png)

接口地址 http://wx.kfk.me/wechat

不管哪个公众号，只要填写 这个接口地址，都能配置或应用成功，实际上是不成功的，不到怎么找错..

app_id与token 随便写，都能通过，不明白为什么
```
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use EasyWeChat\Foundation\Application;
class WechatController extends Controller
{
    public function serve(){
	    $options = [
		    'debug'     => true,
		    'app_id'    => '312312',
		    'secret'    => '313123',
		    'token'     => '31231231231',
		    'log' => [
			    'level' => 'debug',
			    'file'  => '/tmp/easywechat.log',
		    ],
		    // ...
	    ];
	    $app = new Application($options);
	    $server = $app->server;
	    $user = $app->user;
	    $server->setMessageHandler(function($message) use ($user) {
		    $fromUser = $user->get($message->FromUserName);
		    return "{$fromUser->nickname} 您好！欢迎关注 123!";
	    });
	    $server->serve()->send();
    }
}
```

**Comment by wilon** [comment]
看文档：https://mp.weixin.qq.com/wiki/8/f9a0b8382e0b77d87b3bcc1ce6fbc104.html

下源码看看就知道了。你可以随便在一个地址上返回`$_GET["echostr"]`就会成功。

实际上微信没有验证你的token，而是要你自己验证。

```php

    public function wechatapi(Request $request)
    {
        Log::info('wechat-api', $_REQUEST);

    $echoStr = $_GET["echostr"] ?: '';

    //valid signature , option
    if($this->checkSignature()){
        echo $echoStr;
        exit;
    }
    }

    private function checkSignature()
    {
        $signature = $_GET["signature"];
        $timestamp = $_GET["timestamp"];
        $nonce = $_GET["nonce"];    

        $token = 'btsjwechat';
        $tmpArr = array($token, $timestamp, $nonce);
        sort($tmpArr, SORT_STRING);
        $tmpStr = implode( $tmpArr );
        $tmpStr = sha1( $tmpStr );

        if( $tmpStr == $signature ){
            return true;
        }else{
            return false;
        }
    }
```

**Comment by overtrue** [comment]
@dan381006472 在 laravel 里的用法我的文档好像单独说过吧？

> $server->serve()->send();
改成:
> return $server->serve();

**Comment by overtrue** [comment]
@dan381006472 https://github.com/overtrue/laravel-wechat

**Comment by dan381006472** [comment]
并没有效果..

**Comment by Lin07ux** [comment]
我追踪了下代码逻辑，发现对于公众号来说，如果没有公众号配置时启用安全模式，那么`src/Kernel/ServerGuard.php`中的`isSafeMode()`方法返回的就总是 false，这就导致`validate()`方法中，并不会对`signature`进行验证，而是直接返回`$this`。

另外，在`isSafeMode()`函数中，虽然使用了`$this->alwaysValidate`来判断，但是对于公众号来说，这个属性的值是 false，所以也并不会走这个逻辑的。

不知道是不是这个原因 @overtrue  @dan381006472

**Comment by overtrue** [comment]
@Lin07ux 这个非安全模式下不校验是因为从这个项目诞生以来，有起码不下于100多次问我为啥验证不通过，然后我就在非安全模式下不校验签名了，这样方便大家使用浏览器网址加 `echostr=test` 这样的方式来调试，而且线上环境我们推荐开启安全模式。

**Comment by Lin07ux** [comment]
感谢你的回复~你这样说我能理解了。

是否有考虑过在`ServerGuard`中增加修改`$alwaysValidate`属性值的接口？这样的话可以控制是否必须进行签名验证。当然，我刚开始使用这个 SDK，并不确定`$alwaysValidate`属性是否必须为预设的值。

**Comment by overtrue** [comment]
https://github.com/overtrue/wechat/releases/tag/4.0.30

**Comment by Lin07ux** [comment]
@overtrue 发现一个问题。公众号没有设置加密模式时，调用`forceValidate()`，在回复信息的时候  SDK 会对回复的信息进行加密，如果配置文件中没有设置加密密钥，则会出现加密失败异常，如下：

```
{"code":-40006,"message":"Key length must be 16, 24, or 32 bytes; got key len (0).","file":"/home/vagrant/code/glasses/vendor/overtrue/wechat/src/Kernel/Encryptor.php","line":114} 
```

如果配置了加密密钥，而因为公众号设置的是明文模式，此时微信服务器接收的消息是密文，而无法解密，从而出现问题。

所以这个`forceValidate()`的功能还是有待商榷。
