### ISSUE TITLE
开放平台接收ComponentVerifyTicket,会出现Undefined index: FromUserName

### ISSUE THREAD

**Issue by cnvcanson** [overtrue/wechat#623]
## 我用的环境

PHP 版本：5.6.25
overtrue/wechat 版本：3.1.8

## 问题及现象
laravel5.3版本，开放平台接收ComponentVerifyTicket,会出现Undefined index: FromUserName

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

开放平台接收ComponentVerifyTicket
2017-03-27 17:45:19] local.INFO: postStr:<xml>
    <AppId><![CDATA[wxb1a0809efc40f6e2]]></AppId>
    <Encrypt><![CDATA[pyOdlKkqjfj+fcuqI5I4+2caSPQGqXFQhAtvgpqnegpPH8bK0PqGlEk/JFaJps3zxXz3EZOv1QaeniOC2IPy6FW1pPufgoAeG2JVGXNjaMRYwj8FV/xOBPQMouEvB11SEsQRBBELXcKU6SDgTvAi29Y8z2leqIy/EErp8LjjkM/R/uFQQn2TgkxRn9gR2/SAwq8bode/EbFLD6eeR9Ao1/xSymz/iRq8hXQtXat5NQYaN27mzhbH3WTuGX9ludqlD/OGxD58c5rru4sm2S1abMAqYI4p4wS69wc//kaO743OQBSEfk9y3ZP1Fjer25IWtOfRgfM+cquwmnM8nq21xXLXs/OSwYn2o8t7AVcEjf/NYORXk1yksZ1bPpOnhHm8QRZHBuLfecIMaXlOgm7Q/hUotB6/VCrUdjhJ6U23mhyheBJH9QaQS80ol7LuMYKN5iiDWnO387dq8y9+8ed+4g==]]></Encrypt>
</xml>
  
[2017-03-27 17:45:19] local.ERROR: exception 'ErrorException' with message 'Undefined index: FromUserName' in /vendor/overtrue/wechat/src/Server/Guard.php:374
Stack trace:
#0 /vendor/overtrue/wechat/src/Server/Guard.php(374): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/www/wwwroot/ca...', 374, Array)
#1 /vendor/overtrue/wechat/src/Server/Guard.php(157): EasyWeChat\Server\Guard->handleRequest()
#2 /Http/Controllers/Modules/Open/TickController.php(46): EasyWeChat\Server\Guard->serve()
#3 [internal function]: App\Http\Controllers\Modules\Open\TickController->ticket(Object(Illuminate\Http\Request))
#4 /vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#5 /vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('ticket', Array)
#6 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(190): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Modules\Open\TickController), 'ticket')
#7 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(144): Illuminate\Routing\Route->runController()
#8 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(653): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))

**Comment by overtrue** [comment]
@mingyoung

**Comment by mingyoung** [comment]
@cnvcanson 拉 master 版本代码试试
`"overtrue/wechat": "dev-master"`
