### ISSUE TITLE
微信开发平台接受消息报Invalid request signature bug

### ISSUE THREAD

**Issue by jekst** [overtrue/wechat#625]
## 我用的环境

PHP 版本：5.6  7
overtrue/wechat 版本：3.2

## 问题及现象
开发平台代码里接受微信服务器推送的ticket或其他信息时报Invalid request signature bug
处理信息代码：
$openPlatform->server->serve();
在
serve方法里有个验证前面的方法validate
    public function validate($token)
    {
        $params = [
            $token,
            $this->request->get('timestamp'),
            $this->request->get('nonce'),
        ];
        if (!$this->debug && $this->request->get('signature') !== $this->signature($params)) {
            throw new FaultException('Invalid request signature.', 400);
        }
    }
参与签名的参数缺少
encrypt_type
msg_signature
正确的是
  public function validate($token)
    {
        $params = [
            $token,
            $this->request->get('timestamp'),
            $this->request->get('nonce'),            
            $this->request->get('encrypt_type'),
            $this->request->get('msg_signature'),
        ];
        if (!$this->debug && $this->request->get('signature') !== $this->signature($params)) {
            throw new FaultException('Invalid request signature.', 400);
        }
    }

**Comment by bolechen** [comment]
请问这个问题后来怎么解决的？我碰到了同样的问题

**Comment by NiZerin** [comment]
请问这个问题后来怎么解决的？我碰到了同样的问题
