### ISSUE TITLE
[4.0]自定义微信API的区域接入点

### ISSUE THREAD

**Issue by hawkefly** [overtrue/wechat#636]
微信提供了如下接入点，建议在配置文件中增加这个配置。

1. 通用域名(api.weixin.qq.com)，使用该域名将访问官方指定就近的接入点；
2. 上海域名(sh.api.weixin.qq.com)，使用该域名将访问上海的接入点；
3. 深圳域名(sz.api.weixin.qq.com)，使用该域名将访问深圳的接入点；
4. 香港域名(hk.api.weixin.qq.com)，使用该域名将访问香港的接入点。

**Comment by mingyoung** [comment]
短链接转换接口地址：

> https://apihk.mch.weixin.qq.com/tools/shorturl    （建议接入点：东南亚）
> https://apius.mch.weixin.qq.com/tools/shorturl    （建议接入点：其它）
> https://api.mch.weixin.qq.com/tools/shorturl        （建议接入点：中国国内）

Doc：[转换短链接](https://pay.weixin.qq.com/wiki/doc/api/external/native.php?chapter=9_9)
