### ISSUE TITLE
微信公众号不能回复接收到的消息，日志无报错

### ISSUE THREAD

**Issue by dm22933** [overtrue/wechat#637]
## 我用的环境 

PHP 版本：5.6
overtrue/wechat 版本：3.1.8

## 问题及现象
服务器已经配置成功，用户发送消息可以接收，日志有提示记录没有报错，问题是用户接收不了消息，微信会提示公众号当前无法提供服务
描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**
![Uploading TIM截图20170406130359.png…]()
`namespace App\Http\Controllers\service;

use Log;
use App\Http\Controllers\Controller;

class WechatController extends Controller
{

    /**
     * 处理微信的请求消息
     *
     * @return string
     */
    public function serve()
    {
        Log::info('request arrived.'); # 注意：Log 为 Laravel 组件，所以它记的日志去 Laravel 日志看，而不是 EasyWeChat 日志
			
        $wechat = app('wechat');
        $wechat->server->setMessageHandler(function($message){
            return "欢迎关注 overtrue！";
        });

        Log::info('return response.');

        return $wechat->server->serve();
    }
}`

**Comment by overtrue** [comment]
`namespace App\Http\Controllers\service` 是什么鬼？

**Comment by dm22933** [comment]
@overtrue  控制器位于 App\Http\Controllers\service\WechatController.php

**Comment by overtrue** [comment]
@dm22933 路由呢？

**Comment by dm22933** [comment]
@overtrue Route::group(['prefix' => 'weixin'],function(){
	Route::any('/','service\WechatController@serve');
});

**Comment by overtrue** [comment]
laravel 版本

**Comment by overtrue** [comment]
在微信填写的地址是？

**Comment by dm22933** [comment]
域名+/weixin  laravel5.1

**Comment by overtrue** [comment]
@dm22933 那就奇怪了，你路由明明是  `Route::any('/',` 怎么突然填写到微信就变成了 `/weixin` ?????

**Comment by dm22933** [comment]
路由器前缀里有Route::group(['prefix' => 'weixin']

**Comment by dm22933** [comment]
@overtrue

**Comment by overtrue** [comment]
https://mp.weixin.qq.com/debug/ 用这个发消息测试看返回啥

**Comment by dm22933** [comment]
@overtrue 请求失败    我在控制器中加入了
` Log::info($wechat->server->serve());`
日志里有
`[2017-04-06 13:46:24] local.INFO: HTTP/1.0 200 OK
Cache-Control: no-cache
Date:          Thu, 06 Apr 2017 05:46:24 GMT

<xml><ToUserName><![CDATA[oxxxxxxxxc]]></ToUserName><FromUserName><![CDATA[gh_xxxxxxxxx]]></FromUserName><CreateTime>1491457584</CreateTime><MsgType><![CDATA[text]]></MsgType><Content><![CDATA[欢迎关注 overtrue！]]></Content></xml>  
`

**Comment by overtrue** [comment]
服务器URL贴出来

**Comment by dm22933** [comment]
weibangxueyuan.com

**Comment by overtrue** [comment]
![image](https://cloud.githubusercontent.com/assets/1472352/24741305/ebc070c6-1ad7-11e7-8141-bf306cc435ab.png)

所以你的服务器没有返回内容。。。

**Comment by dm22933** [comment]
所以我才纳闷  到底哪里的问题  日志显示也没报错。。。。

**Comment by overtrue** [comment]
@dm22933 这个你就得自己去研究你一环境问题了

**Comment by dm22933** [comment]
@overtrue get请求验证echostr成功  post请求能接收  就是返回失败也是属于环境的问题是么

**Comment by overtrue** [comment]
@dm22933 莫非你怀疑一个 9 万多安装量的 SDK 会有这样的基础 bug 存在?

**Comment by dm22933** [comment]
@overtrue 不敢怀疑超哥的SDK   是怀疑自己配错了参数  尴尬

**Comment by overtrue** [comment]
@dm22933 那如果是这样的话你就需要自己去研究了，我就帮不上了

**Comment by dm22933** [comment]
@overtrue  刚才重新新建了一个站点  还是这个bug  希望大神给我指点一下方向  最可能的问题在哪里  已经俩天了  不想自己写    还是想用这个SDK

**Comment by larry-666** [comment]
Laravel 的话看下有没有在CSRF里面排除路由 @dm22933

**Comment by dm22933** [comment]
最后通过微信公众平台接口查询是PHP配置错误解决  谢谢
