### ISSUE TITLE
微信开放平台发起网页授权bug

### ISSUE THREAD

**Issue by jekst** [overtrue/wechat#638]
## 我用的环境

PHP 版本： php5.6
overtrue/wechat 版本：3.2.3

## 问题及现象
微信开放平台发起网页授权，client_id不存在或者client_id错误的问题
OAuthServiceProvider里配置client_id里取的是wechat配置文件里的，
WeChatProvider里应该提供一个设置client_id的方法，可以设置authorizer_app_id；

WeChatProvider里获取开发平台的access_token方法错误，wechat.open_platform.access_token在Application初始化的时候没有初始化
  if ($this->isOpenPlatform()) {
            return array_merge($base, [
                'component_appid' => $this->config->get('wechat.open_platform.app_id'),
                'component_access_token' => $this->config->get('wechat.open_platform.access_token'),
            ]);
        }

另外Application $oauth属性应为
* @property \Overtrue\Socialite\Providers\WeChatProvider        $oauth

**Comment by jekst** [comment]
暂时解决方法：
在Overtrue\Socialite\Providers\WeChatProvider添加了两个方法
`    /**
     * Set app id
     * @param $authorizer_app_id
     * @return $this
     */
    public function setAuthorizerAppId($authorizer_app_id)
    {
        $this->clientId = $authorizer_app_id;
        return $this;
    }

    /**
     * set platform component access token
     * @param $token
     * @return $this
     */
    public function setComponentToken($token)
    {
        $this->config->set('wechat.open_platform.access_token', $token);
        return $this;
    }`

调用：
` $oauth =$app->oauth; 
$token=$app->open_platform->authorizer_token->getToken();
 $oauth->setAuthorizerAppId($this->authorizer_app_id)
            ->setComponentToken($token);`

**Comment by jekst** [comment]
暂时解决方法：
在Overtrue\Socialite\Providers\WeChatProvider添加了两个方法

    /**
     * Set app id
     * @param $authorizer_app_id
     * @return $this
     */
    public function setAuthorizerAppId($authorizer_app_id)
    {
        $this->clientId = $authorizer_app_id;
        return $this;
    }

    /**
     * set platform component access token
     * @param $token
     * @return $this
     */
    public function setComponentToken($token)
    {
        $wechat= $this->config->get('wechat');
        $wechat['open_platform']['access_token'] = $token;
        $this->config->set('wechat', $wechat);
        return $this;
    }
	
	修改getCodeFields方法
	  /**
     * {@inheritdoc}.
     */
    protected function getCodeFields($state = null)
    {
        if ($this->isOpenPlatform()) {
            $this->with(['component_appid' => $this->config->get('wechat.open_platform.app_id')]);
        }
        return array_merge([
            'appid' => $this->clientId,
            'redirect_uri' => $this->redirectUrl,
            'response_type' => 'code',
            'scope' => $this->formatScopes($this->scopes, $this->scopeSeparator),
            'state' => $state ?: md5(time()),
        ], $this->parameters);
    }
	
调用：
	$oauth =$app->oauth; 
	$token = $WxPlatformService->getOpenPlatform()->access_token->getToken();
    $oauth->setAuthorizerAppId($this->authorizer_app_id)
            ->setComponentToken($token)
			->redirect()->send();

**Comment by jekst** [comment]
修改配置竟然不能这么使用$this->config->set('wechat.open_platform.access_token', $token);

**Comment by mingyoung** [comment]
升级 3.3版本解决

⚠️ 3.3版本开放平台部分不兼容之前的版本，请按最新[开放平台文档](https://easywechat.org/zh-cn/docs/open_platform.html)使用
