### ISSUE TITLE
微信素材管理小改版，求跟上~

### ISSUE THREAD

**Issue by hareluya** [overtrue/wechat#64]
目前图片上传后返回的xml已经不仅仅是media_id了，还有url，求加上哟~

**Comment by hareluya** [comment]
在media.php 的122行加上：

        if($type=='image'){
            return $response;
        }

不是很优雅。。仅供参考- -

**Comment by overtrue** [comment]
https://github.com/overtrue/wechat/commit/605c319fdfca1b24a4a2dbb736d7dc28dd6a0fe4

**Comment by overtrue** [comment]
你看看对不对？

**Comment by hareluya** [comment]
我试过，没问题，就是返回是个数组，要在文档里说明下。

**Comment by overtrue** [comment]
@hareluya OK
