### ISSUE TITLE
在获取用户信息是出错

### ISSUE THREAD

**Issue by stevesgit** [overtrue/wechat#643]
## 我用的环境

PHP 版本：7
overtrue/wechat 版本：3.1

## 问题及现象
本来按照这个demo在线上服务器时都ok，但今天用ngrok服务，做了下本地端口映射，在本地开发
按着官方的demo在消息处理时
`   $server->setMessageHandler(function($message) use ($user) {
//            $fromUser = $user->get($message->FromUserName); 加这段代码会出错

            return " 您好！欢迎关注 overtrue!";
        });
`

如果不加这段代码就能发送消息。

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

**Comment by overtrue** [comment]
sorry, 你提供的信息并不足矣让人能分析出问题所在

**Comment by icoder2013** [comment]
一模一样的问题,请教贴主怎么结局的?
