### ISSUE TITLE
微信开放平台authorizer token缓存问题

### ISSUE THREAD

**Issue by greatpie** [overtrue/wechat#644]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：最新的。

## 问题及现象

文档中说SDK内部会缓存authorizer的access_token和refresh_token，授权完成后发现并没有缓存，只缓存了component的token。

**Comment by mingyoung** [comment]
3.3 版本后，SDK 在微信**推送授权事件后不缓存** Authorizer 的 AccessToken 和 RefreshToken。在调用授权方 API 后会缓存并自动刷新 Token 有效期。

⚠️ 3.3版本开放平台部分**不兼容**之前的版本

请按最新[开放平台文档](https://easywechat.org/zh-cn/docs/open_platform.html)使用
