### ISSUE TITLE
微信下的单的默认过期时间是多少啊

### ISSUE THREAD

**Issue by lear2012** [overtrue/wechat#645]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：

## 问题及现象

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

**Comment by overtrue** [comment]
@lear2012 自己去看微信官方文档

**Comment by lear2012** [comment]
额，我查了，它那只有最小关单间隔，没有说单子默认过期时间，参数里是有过期时间，但如果不设置呢?默认是多少啊
