### ISSUE TITLE
[4.0] 返回值类型可配置

### ISSUE THREAD

**Issue by overtrue** [overtrue/wechat#661]
1.  选择：array / collection
2.  自定义函数 / 钩子

**Comment by overtrue** [comment]
- `response_type`
    - `collection`
    - `array`
    - `object`
    - `raw`
    - 自定义类名

**Comment by mingyoung** [comment]
@overtrue 
要不都返回 array？
比如基于 laravel-wechat 再写了一个 Laravel 包，包里面有个： `$app->user->get('xxx')['nickname']`
如果是数组的话这样是没问题的，但是如果用户自定义 `response_type` 为其他的话那就会报错了🤣

**Comment by overtrue** [comment]
@mingyoung 想想办法
