### ISSUE TITLE
小程序解密$encryptedData数据

### ISSUE THREAD

**Issue by zhkzyth** [overtrue/wechat#687]
## 我用的环境
centos7.x

PHP 版本：PHP 5.6.21 (cli)
overtrue/wechat 版本：3.1

## 问题及现象
MiniProgram怎么使用解密api来解密用户的数据？木有看到类似的api调用方法。

**Comment by mingyoung** [comment]
`$miniProgram->encryptor->decryptData($encryptedData);`

**Comment by hareluya** [comment]
不太明白现在这个方法到底是怎么用的？
看到MiniProgram下面有一个Encryptor类，然后从service provider看到却是用了overtrue自带的encryptor，到底应该怎么使用呢？

**Comment by hareluya** [comment]
另外如果用原生的Encryptor类，里面的解密方法似乎和官方说法不一致？

**Comment by mingyoung** [comment]
@hareluya 
已修复：https://github.com/overtrue/wechat/commit/af7ba6aa5282d9fde5cb9fc7b95562d9859837ca

**Comment by hareluya** [comment]
@mingyoung 
神速。。但构造函数个数似乎不对哟- -~

**Comment by mingyoung** [comment]
@hareluya 好，我明天看看再处理一下

**Comment by mingyoung** [comment]
@hareluya 
https://github.com/overtrue/wechat/commit/67dcd98bce308235dda9698f82ecf8fba150ba70
实例化后：`$miniProgram->encryptor->decryptData($sessionKey, $iv, $encryptedData);`

**Comment by hareluya** [comment]
收到~ 已通过~ 感谢~

**Comment by mingyoung** [comment]
good☺
