### ISSUE TITLE
生成AccessToken时，似乎没有调用自定义缓存的delete方法

### ISSUE THREAD

**Issue by Insua** [overtrue/wechat#693]
## 我用的环境

PHP 版本：5.6
overtrue/wechat 版本：3.1

## 问题及现象

我重写了一个mysql的DoctrineCache缓存，调整了过期时间后，读取缓存时，会重新生成很多token，而原有的token并没有被删除  
![](https://cloud.githubusercontent.com/assets/5939744/25936914/415b0cea-365c-11e7-9d67-6d7f6e2c7f67.png)

**Comment by overtrue** [comment]
删除是需要你自己实现的啊，不然过期时间有啥用？

**Comment by Insua** [comment]
```php
<?php
use Doctrine\Common\Cache\Cache as CacheInterface;
class MyCacheDriver implements CacheInterface
{
..............
.............
 public function delete($id)
    {
        // 删除并返回 bool 值
    }   
```

*这里的delete方法我已经重写了啊，业务逻辑就写了一条SQL 语句*  
```sql
DELETE FROM cache WHERE id=$id
```  
**delete方法还需要写其他东西嘛？**

**Comment by overtrue** [comment]
过期清除并不是 Doctrine Cache 这个组件去做的事情，redis, mc 这些都是自带过期清除功能的， mysql 没有过期时间的概念，所以需要定时执行脚本去删除过期的，明白么？

**Comment by Insua** [comment]
好的，谢谢
那我在fetch方法里判断过期后，直接调用
```php
$this->delete($id)
```

**Comment by overtrue** [comment]
可以啊，只要符合该机制就行了

**Comment by Insua** [comment]
谢谢安正超大神，我正在等待你设计的laravel文化衫到货，我close comment了

**Comment by overtrue** [comment]
❤️ 加油！
