### ISSUE TITLE
是否支持H5支付

### ISSUE THREAD

**Issue by almas1992** [overtrue/wechat#694]
## 我用的环境

PHP 版本：7.0.15
overtrue/wechat 版本：3.1

## 问题及现象
需要开发微信内置浏览器调起微信支付，可发现easywechan貌似不支持 trade_type=MWEB 的H5支付功能
https://github.com/overtrue/wechat/blob/b56b7360c48211a11ad2610cbd1d41a7bb13865b/src/Payment/Order.php#L49-L52
源码中只有JSAPI，NATIVE，APP，MICROPAY四种类型交易类型；
微信官方H5支付文档：
https://pay.weixin.qq.com/wiki/doc/api/H5.php?chapter=15_4
描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

**Comment by overtrue** [comment]
@almas1992 建议你先尝试，毕竟下单接口是一样的

**Comment by mingyoung** [comment]
理论上在创建订单时设置 `'trade_type' => 'MWEB'` 就可以了。
文档：[创建订单](https://easywechat.org/zh-cn/docs/payment.html#创建订单)

issue 先关闭了，有问题再回复
