### ISSUE TITLE
mcrypt_module_open error

### ISSUE THREAD

**Issue by samuelzhang** [overtrue/wechat#7]
Call to undefined function Overtrue\Wechat\mcrypt_module_open() in ... vendor/overtrue/wechat/src/Wechat/Crypt.php on line 195
这个好奇怪，怎么namespace会调用到Overtrue\Wechat\

**Comment by overtrue** [comment]
你的环境没有装mcrypt

2015-04-25 16:05 GMT+08:00 Samuel Zhang <notifications@github.com>:
