### ISSUE TITLE
【建议】可以添加微信js的功能吗？

### ISSUE THREAD

**Issue by vickoo** [overtrue/wechat#71]
使用微信公众号进行开发时也常常会用到微信js，是否考虑添加微信js的功能呢？

**Comment by overtrue** [comment]
微信的js用法其实已经相当于是在js框架下使用了，所以再封装是没有必要的

**Comment by vickoo** [comment]
嗯嗯，是我表述不清，我想说的是微信js的授权功能#^_^#

**Comment by overtrue** [comment]
@vickoo js授权？？？

**Comment by vickoo** [comment]
对的，用于获取微信js调用权限，需要在后台获取并进行缓存
http://mp.weixin.qq.com/wiki/11/0e4b294685f817b95cbed85ba5e82b8f.html

**Comment by overtrue** [comment]
@vickoo 本来就有啊 https://github.com/overtrue/wechat/wiki/JSSDK

**Comment by vickoo** [comment]
⊙﹏⊙‖ 没注意看  赞一个
