### ISSUE TITLE
怎样从数据库中调取配置

### ISSUE THREAD

**Issue by xhh110** [overtrue/wechat#711]
## 我用的环境
linux
PHP 版本：php7.1.4
overtrue/wechat 版本：
最新的laravel-wechat
## 问题及现象
现在是做一个手机端，然后别人的服务号上传key等内容，用作生成微信中的底部按钮和设置商户等内容，超哥，如果用easy-wechat。怎样从数据库内取出配置，而不是固定的写一个统一的配置呢。

没有任何bug，希望超哥抽空帮下忙

**Comment by overtrue** [comment]
1. 从数据库读取配置
2. 创建 EasyWeChat 实例：`new Application($config)`

**Comment by xhh110** [comment]
超哥 我是不是需要把包从laravel-wechat 换成这个我用的laravel

**Comment by overtrue** [comment]
嗯，是

**Comment by xhh110** [comment]
谢谢超哥。。。
