### ISSUE TITLE
 使用$server->getMessage();报错

### ISSUE THREAD

**Issue by DukeAnn** [overtrue/wechat#712]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：

## 问题及现象
我打算用事件存储微信发送的消息，把 `new Application($this->options)` 实例传入了事件中，在监听里面打印用户发送的消息
***
 public function handle(WechatMessageEvent $event)
    {
        $server = $event->wechat->server;
        // 获取数组类型的 微信接口发送数据
        $message = $server->getMessage();
        Log::info($message['Content']);
    }
***
`$message = $server->getMessage();`，使用时虽然数据能正常获取到但是会写日志一个error

EasyWeChat\Server\BadRequestException: Invalid request. in /home/wwwroot/wechat_admin/vendor/overtrue/wechat/src/Server/Guard.php:343

#0 /home/wwwroot/wechat_admin/app/Listeners/WechatMessageListener.php(34): EasyWeChat\Server\Guard->getMessage()
#1 [internal function]: App\Listeners\WechatMessageListener->handle(Object(App\Events\WechatMessageEvent))

**Comment by overtrue** [comment]
请不要使用浏览器来访问，这个东西是给微信服务器来调用的。

**Comment by DukeAnn** [comment]
不是浏览器访问的，是我写在微信接口中的一个监听事件里面了，用来存储用户发送的消息时调用的，就报错了

**Comment by overtrue** [comment]
那就是你的 Nginx 配置有问题了，query 部分丢了

**Comment by DukeAnn** [comment]
laravel 的 nginx 文件该怎么配置，能提供一下完整样例嘛，这个虽然报错但是还是可以正常运行的。

**Comment by overtrue** [comment]
```nginx
location / {
    try_files $uri $uri/ /index.php?$query_string;
}
```
