### ISSUE TITLE
网页能授权但无法获取用户信息，代码跟官方文档一样。

### ISSUE THREAD

**Issue by dm22933** [overtrue/wechat#713]
## 我用的环境

PHP 版本：5.6
overtrue/wechat 版本：3.3

## 问题及现象
按照官方文档设置在最后一步获取用户信息中会返回curl信息,复制到浏览器中打开能够获取用户信息。
测试地址：http//meiwu.xxxxx.com/wx/user
描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**
![qq 20170524233152](https://cloud.githubusercontent.com/assets/26136524/26412573/cb81d686-40db-11e7-87bd-5b2cb4625d6b.png)

**Comment by mingyoung** [comment]
在哪里 dd() 了吧

还有你的secret暴露了

**Comment by dm22933** [comment]
@mingyoung 反正secret是要换的  没有dd，代码也贴上去了  就是这个执行这个方法

**Comment by dm22933** [comment]
@mingyoung   果然很快被黑了

**Comment by mingyoung** [comment]
@dm22933 啥。。

**Comment by dm22933** [comment]
![_20170525104750](https://cloud.githubusercontent.com/assets/26136524/26433848/97e007ce-4137-11e7-9021-a7f86d631b4f.png)

**Comment by mingyoung** [comment]
![25888a7fa6d22ea2741049262c60bad2](https://cloud.githubusercontent.com/assets/6228858/26433892/d1f644d2-4137-11e7-8e81-3c1a438d11e8.png)

被群发了吧

**Comment by dm22933** [comment]
高手真会玩，宁愿恶搞也不愿意过来帮我解决问题

**Comment by mingyoung** [comment]
还是检查下在哪里dd()了吧 ，不然也不会显示这个格式

**Comment by overtrue** [comment]
> 在最后一步获取用户信息中会返回curl信息

请问你是如何看到你第二张截图内容的？自己  dd 的还是就你第一张截图产生的？

**Comment by dm22933** [comment]
第一张截图代码产生的  我没有dd

**Comment by overtrue** [comment]
额，不太可能，你还是搜索一下你的代码里，哪里出现了 dd

**Comment by dm22933** [comment]
排查到这一步 ，问题就出现在箭头标记的方法这，return $this->getCode() 值有效，在getAccessToken方法中无论返回什么值都是无效的
![a](https://cloud.githubusercontent.com/assets/26136524/26434649/68aa584c-413c-11e7-961f-11a9e7f849e5.png)


![b](https://cloud.githubusercontent.com/assets/26136524/26434701/d0a81f4c-413c-11e7-8bc8-4a33cdc5378c.png)

**Comment by overtrue** [comment]
这不会导出出现 dd 效果吧？

**Comment by dm22933** [comment]
我也是这样想的呀  这个方法之前return 就不会出现这个效果，然后我又在getAccessToken()里面return 1或者$code; 依然这样，可是这个类中只有这一个getAccessToken()，然后我就没法往下面找了,不然删了重新装？

**Comment by overtrue** [comment]
哈哈，你删除重新装吧，我怀疑你改过 vendor 下的代码

**Comment by dm22933** [comment]
大神我要疯了！！！

**Comment by overtrue** [comment]
@dm22933 你还好么哈哈

**Comment by dm22933** [comment]
大神快快出手相救

**Comment by overtrue** [comment]
重新装的结果呢？

**Comment by dm22933** [comment]
结果一样

**Comment by overtrue** [comment]
Q 多少

**Comment by dm22933** [comment]
229334935
