### ISSUE TITLE
微信网页授权重复请求报code无效

### ISSUE THREAD

**Issue by openset** [overtrue/wechat#714]
## 我用的环境

PHP 版本：5.6.30
overtrue/wechat 版本：3.2.7

## 问题及现象

微信网页授权，如果授权成功后用户点击返回按钮，会报“40029 不合法的oauth_code 错误”，因为code只能用一次，怎么在code无效时自动重新授权，而不是报错。用set_exception_handler不太合适，改源码就更不好了。

![20170526122416](https://cloud.githubusercontent.com/assets/6274967/26480781/e4691d24-420e-11e7-9bad-7aebc9158360.png)

**Comment by overtrue** [comment]
我在文档上说过啊，授权完成后要用 301 跳转到业务页面而不是直接显示页面

**Comment by ishuowang** [comment]
跳转到业务页面了，是正常的，问题在于在业务页面用户点击返回，就到了那个有code参数的链接，就会报code无效。安卓手机更容易出现这个错误。

**Comment by never615** [comment]
我在授权中间件里面处理:保存code到session中,如果发现用过的code就重新请求,没有就继续获取用户信息.

我也是在日志中发现挺多这个错误出现才这么做的.在网络不好的时候,用户刷新当前有code的页面也可能出现这个问题.

**Comment by reason211** [comment]
history.replaceState

**Comment by openset** [comment]
@overtrue 大神，packagist用户头像怎么修改，谢谢~
