### ISSUE TITLE
guzzle curl error28 - 去哪设置默认timeout ？

### ISSUE THREAD

**Issue by Lujidev** [overtrue/wechat#715]
大家好，
我经常会有这个错误跳出来。
经过寻找，我读了论坛上的这个帖子：https://forum.easywechat.org/d/173--
说要改写guzzle默认的timeout。
是要去core里面http.php 那里设置吗？

错误：`Fatal error: Uncaught exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL error 28: Operation timed out after 0 milliseconds with 0 out of 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)'`

**Comment by mingyoung** [comment]
```php
$config = [
    'app_id' => 'your-app-id',
    'secret' => 'your-secret',
    // ...
    'guzzle'=>[
        'timeout' => 30.0
    ],
];

$app = new Application($config);

**Comment by TheSaltwaterRoom** [comment]
我设置了超时时间还是会报错啊

**Comment by ouhaohan8023** [comment]
我也是额。。。这个报错怎么破？
