### ISSUE TITLE
接入多个公众号

### ISSUE THREAD

**Issue by Lujidev** [overtrue/wechat#718]
我想问一下如何接入多个公众号？
需要全新的SDK？在新的地址开始？
好像问题在于access_token(一只存着第一个个账号的？)。
如果我把acess_token存到mysql（比如存3个账号不同的access_token），
option里能强行输入一个access_token吗？

**Comment by overtrue** [comment]
> 好像问题在于access_token(一只存着第一个个账号的？)

咱们搞编程的还是严谨一些比较好哦，不要好像，要确定。
