### ISSUE TITLE
oauth能获取用户信息，再通过access_token与用户openid去获取信息，部分用户的信息为空

### ISSUE THREAD

**Issue by dm22933** [overtrue/wechat#720]
## 我用的环境

PHP 版本：5.6
overtrue/wechat 版本：

## 问题及现象
目前为止好像是iphone正常，安卓不能获取。
access_token不是oauth的，微信接口测试截图如下
描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**
![tim 20170604131832](https://cloud.githubusercontent.com/assets/26136524/26759170/2d184ba0-4929-11e7-903c-76a44122b50c.png)

**Comment by overtrue** [comment]
> access_token不是oauth的

OAuth 肯定只能用 oauth 自己的 token 啊，另外 scope 必须要为 sns_userinfo 才能拿用户资料哦，否则只有 openid

**Comment by dm22933** [comment]
是的   用的userinfo。但是看微信文档openid对公正号不是应该唯一么，并且不是所有的不可获取，部分是可以获取的，目前发现的事iphone可以，安卓的不行

**Comment by overtrue** [comment]
这应该与手机平台无关

**Comment by overtrue** [comment]
1. OAuth 拿用户信息与用户管理中的获取用户信息 API 是两个
2. OAuth 拿用户信息只需要用户同意即可获取，但是并不代表此时你用用户管理接口能拿到资料
3. 用户管理接口能不能拿到资料的条件只有一个：他是否关注，没关注公众号就是拿不到。
