### ISSUE TITLE
$data是数组,title输出不了内容

### ISSUE THREAD

**Issue by YeFatBoy** [overtrue/wechat#73]
$news = Message::make('news')->items(function ()
                    {
                          for ($i = 0; $i < 4; $i++){
                              $list[$i] = Message::make('news_item')->title($data[$i]['title'])
                              ->description('我的太难啊')
                              ->url('http://www.baidu.com')
                              ->picUrl('http://zxpic.gtimg.com/infonew/0/wechat_pics_-711632.jpg/640');
                          }
                          return $list;
                    });

**Comment by overtrue** [comment]
$data 在哪儿？你引入了么？https://github.com/overtrue/wechat/issues/72

**Comment by YeFatBoy** [comment]
@overtrue 引入了,
$article = Factory::CreateArticle();
                    $data = $article->getArticle();
                    $news = Message::make('news')->items(function ()
                    {
                          for ($i = 0; $i < 4; $i++){
                              $list[$i] = Message::make('news_item')->title('玻璃心的人都会喜欢这些东西')
                              ->description('玻璃心的人都会喜欢这些东西')
                              ->url('http://www.zxbird.com')
                              ->picUrl('http://zxpic.gtimg.com/infonew/0/wechat_pics_-711632.jpg/640');
                          }
                          return $list;
                    });
                    return $news;
