### ISSUE TITLE
$temporary->getStream($media_id) 与 file_get_contents() 有区别？？?

### ISSUE THREAD

**Issue by Chooin** [overtrue/wechat#742]
## 我用的环境
Ubuntu
PHP 版本：7.1.4
overtrue/wechat 版本：~3.1

## 问题及现象

`$temporary->getStream($media_id) `与 `file_get_contents()` 有点区别？？?

我现在要将图片上传到阿里云OSS必须得先执行`file_put_contents('/a.jpg', $temporary->getStream($media_id))`保存图片到服务器，再执行 `file_get_contents('/a.jpg')` ，最后才能将图片上传到OSS，这样操作是否有点怪异？？？？？？

**Comment by overtrue** [comment]
没区别啊

**Comment by Chooin** [comment]
`$temporary->getStream($media_id)` 获取的数据流给阿里云 OSS 接口服务端提示 502。`$temporary->getStream($media_id)` 获取的数据流，`file_put_contents ` 保存到服务器，再用 `file_get_contents ` 获取数据流给阿里云 OSS 接口上传成功。

**Comment by Chooin** [comment]
```bash
$temporary = $this->app->material_temporary;
        $fileContents = $temporary->getStream($media_id);
        $filename = date('Ym').'/'.md5($fileContents).'.png';
        try {
            $ossClient = new OssClient(env('ALIYUN_ACCESSKEY_ID'), env('ALIYUN_ACCESSKEY_SECRET'), env('ALIYUN_OSS_ENDPOINT'));
            $ossClient->putObject(env('ALIYUN_OSS_BUCKET'), $path.$filename, $fileContents);
            return [
                'status' => true,
                'filename' => $filename
            ];
        } catch (OssException $e) {
            $error = $e->getMessage();
            return [
                'status' => false,
                'error' => $error
            ];
        }
```
上面是 502 报错代码

**Comment by overtrue** [comment]
1. 502 是哪里报的错，你本地报的还是  $e 里的？
2. 你的 file_get_contents 的代码贴上来看看

**Comment by Chooin** [comment]
``` bash
$temporary = $this->app->material_temporary;
$fileContents = $temporary->getStream($media_id);
$filename = date('Ym').'/'.md5($fileContents).'.png';
file_put_contents('/data/wwwroot/api/storage/'.$filename, $fileContents);
try {
    $ossClient = new OssClient(env('ALIYUN_ACCESSKEY_ID'), env('ALIYUN_ACCESSKEY_SECRET'), env('ALIYUN_OSS_ENDPOINT'));
    $ossClient->putObject(env('ALIYUN_OSS_BUCKET'), $path.$filename, file_get_contents('/data/wwwroot/api/storage/'.$filename));
} catch (OssException $e) {
    $error = $e->getMessage();
}
```
1. 502 报错在 `$ossClient->putObject(env('ALIYUN_OSS_BUCKET'), $path.$filename, $fileContents);`，用 `file_get_contents` 就正常了，但是感觉这个用法很尴尬😓
2. 上面的用法能正常上传到 阿里云OSS

**Comment by Chooin** [comment]
期望是直接能上传到阿里云 OSS，而不是在生产环境服务器再建个图片资源，然后再上传。

**Comment by overtrue** [comment]
@Chooin 按理一样的，不过 502 错误感觉就很奇怪了

>502: 连接超时 我们向服务器发送请求 由于服务器当前链接太多，导致服务器方面无法给于正常的响应，产生此类报错

不过我还是感觉这个 502 是你自己站点报的，如果是对方（阿里云）报的，你应该是在 catch 里能捕获的。

**Comment by Chooin** [comment]
注释掉 `$ossClient->putObject(env('ALIYUN_OSS_BUCKET'), $path.$filename, $fileContents);` 一切正常不会报 502，这就很尴尬了。晚上回去把 overtrue/wechat 版本升到最高看看有没有问题

**Comment by overtrue** [comment]
有进展么？

**Comment by Chooin** [comment]
嗯，升级版本后还是不行

**Comment by overtrue** [comment]
@Chooin 加我 Q 44294631

**Comment by Chooin** [comment]
万分感谢

**Comment by Chooin** [comment]
@overtrue 这个问题在 4.0 又出现了
`
$stream = $this->OfficialAccount->media->get($mediaId);
`
拿到的二进制流不能直接提交到阿里云 OSS
