### ISSUE TITLE
configForJSSDKPayment

### ISSUE THREAD

**Issue by lamzy** [overtrue/wechat#744]
public function configForJSSDKPayment($prepayId)
    {
        $config = $this->configForPayment($prepayId, false);

//        $config['timestamp'] = $config['timeStamp'];
//        unset($config['timeStamp']);

        return $config;
    }

里面的timeStamp参数微信是要求驼峰写法的

**Comment by overtrue** [comment]
> https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421141115

**Comment by lamzy** [comment]
WeixinJSBridge才是驼峰写法，jssdk是全小写，感谢。
ps：微信大坑
