### ISSUE TITLE
微信网页支付配置生成

### ISSUE THREAD

**Issue by daxiong123** [overtrue/wechat#751]
## 我用的环境

PHP 版本：7.0.19
overtrue/wechat 版本：3.3.2

## 问题及现象

![wx20170620-115232](https://user-images.githubusercontent.com/2648157/27315926-28129416-55af-11e7-93bb-84cb70ec6484.png)

微信官网文档时间戳字段名称为 timeStamp

![image](https://user-images.githubusercontent.com/2648157/27315959-600fd360-55af-11e7-9a29-b2aaa2845723.png)

代码里生成配置时使用的是 timeStamp 生成后 将 timeStamp 赋值给 timestamp 然后销毁 timeStamp 导致微信支付签名验证不正确

**Comment by overtrue** [comment]
请使用 `configForPayment`

**Comment by daxiong123** [comment]
好的 文档应该是没有更新

**Comment by overtrue** [comment]
你用的 JSSDK 还是 WeixinJSBridge?

**Comment by daxiong123** [comment]
JSSDK

**Comment by daxiong123** [comment]
![image](https://user-images.githubusercontent.com/2648157/27316107-18e7d388-55b0-11e7-8133-8da21229cb7f.png)

**Comment by overtrue** [comment]
@daxiong123 你改一下我的代码看看：

把 configForJSSDKPayment 里面的改成：

```php
$params = [
            'appId' => $this->merchant->app_id,
            'timestamp' => strval(time()),
            'nonceStr' => uniqid(),
            'package' => "prepay_id=$prepayId",
            'signType' => 'MD5',
        ];

        $params['paySign'] = generate_sign($params, $this->merchant->key, 'md5');

        return $json ? json_encode($params) : $params;
```

**Comment by daxiong123** [comment]
timestamp 这个字段应该还是要使用 timeStamp

**Comment by overtrue** [comment]
1. WeixinJSBridge (timeStamp大写):

https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=7_7&index=6

2. WeixinJSBridge(timestamp 小写):

https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421141115

**Comment by overtrue** [comment]
JSSDK 生成签名时用大写，配置时用小写：

![image](https://user-images.githubusercontent.com/1472352/27316225-eed6409c-55b0-11e7-8fe6-121962fd67c5.png)

所以看起来我的 SDK 的写法是 OK 的

**Comment by overtrue** [comment]
所以不用改源代码了，你检查一下其它选项可能是错了，不应该是这个大小写问题

**Comment by daxiong123** [comment]
额 我把小写的改成大写的问题就解决了

**Comment by daxiong123** [comment]
找到原因了 是因为用SDK之前 前端代码直接使用的timeStamp字段 所以用了这个方法会有问题
