### ISSUE TITLE
扩展门店小程序错误

### ISSUE THREAD

**Issue by ljyljy0211** [overtrue/wechat#762]
## 我用的环境

PHP 版本：7.1.5
overtrue/wechat 版本：最新版本

## 问题及现象

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

这个$application即vendor/overtrue/wechat/src/Foundation/Application.php
 $application->register(new \WechatBundle\Custom\ServicesProviders\XcxServiceProvider);
 $application->addProvider(\WechatBundle\Custom\ServicesProviders\XcxServiceProvider::class);

报错

(1/1) InvalidArgumentException
Identifier "xiaochengxu" is not defined.
in Container.php (line 96)
at Container->offsetGet('xiaochengxu')
in Application.php (line 194)
at Application->__get('xiaochengxu')
in web.php (line 30)
at Closure->{closure}()
at call_user_func_array(object(Closure), array())
in BoundMethod.php (line 29)
at BoundMethod::Illuminate\Container\{closure}()
in BoundMethod.php (line 75)
at BoundMethod::callBoundMethod(object(AppKernel), object(Closure), object(Closure))
in BoundMethod.php (line 31)
at BoundMethod::call(object(AppKernel), object(Closure), array(), null)
in Container.php (line 539)
at Container->call(object(Closure), array())
in RoutesRequests.php (line 654)

**Comment by overtrue** [comment]
你的 provider 怎么写的啊

**Comment by ljyljy0211** [comment]
找到问题了，第三方授权开发授权的失火，需要注册一个新的扩展，这个扩展的注册要写在EasyWeChat\OpenPlatform\createAuthorizerApplication之后，即以下代码顺序，
`$authorizerApplication = $this->getApplication()->open_platform->createAuthorizerApplication($authorizerAppId, $authorizerRefreshToken);
        $authorizerApplication = $authorizerApplication->register(new \WechatBundle\OvertrueWechat\Foundation\ServiceProviders\MenDianServiceProvider);`

**Comment by overtrue** [comment]
哈哈哈哈
