### ISSUE TITLE
网页授权问题，提示scopes类型错误

### ISSUE THREAD

**Issue by xhh110** [overtrue/wechat#764]
## 我用的环境
valet 
PHP 版本：php7.1.5
overtrue/wechat 版本：
"overtrue/wechat": "~3.1",
## 问题及现象
![image](https://user-images.githubusercontent.com/16145443/27536394-85b2e1b0-5aa1-11e7-8c6d-3c8cdc40729e.png)
自己创建的middleware，具体就是测试一下授权页面。。暂时未跳转过授权，不必担心是授权过后，的问题。
![image](https://user-images.githubusercontent.com/16145443/27536377-7767f5d2-5aa1-11e7-94a6-291e21fd1c37.png)
options的内容如下
![image](https://user-images.githubusercontent.com/16145443/27536411-9b8caee4-5aa1-11e7-8ee8-f343d3b7d7b9.png)
报错信息，提示类型不对。。。请求超哥援助
描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

**Comment by overtrue** [comment]
scopes 必须是数组，你的是字符串啊

**Comment by xhh110** [comment]
@overtrue  ok 谢谢超哥

**Comment by overtrue** [comment]
不客气
