### ISSUE TITLE
Call to undefined method EasyWeChat\Server\Guard::setRequest()

### ISSUE THREAD

**Issue by hinet** [overtrue/wechat#765]
guzzlehttp/guzzle 已移除并更换为https://github.com/guzzle/guzzle，造成：Call to undefined method EasyWeChat\Server\Guard::setRequest() 错误。请官方尽快更新版本

**Comment by overtrue** [comment]
@hinet 要不阅读一下：https://github.com/guzzle/guzzle#installing-guzzle
