### ISSUE TITLE
多添加一个$option

### ISSUE THREAD

**Issue by Lujidev** [overtrue/wechat#772]
请问怎么多传一个option到accessToken的请求options里？ （比如accountId）。
这是因为我们不是直接发送请求到微信的api，是要经过另一个api， 所以需要多一个区分方式。

$options = [
'debug'  => true,
'app_id' => '******',
'secret' => '*********',
//'accountId' => '0',
];

core 里面的accessToken 已修改。 后面是要修改foudation/Application ?

**Comment by overtrue** [comment]
sorry, 这种定制型的东西可能需要自己研究了
