### ISSUE TITLE
门店创建API ($poi->create) 建议返回 poi_id / exception

### ISSUE THREAD

**Issue by ryh** [overtrue/wechat#774]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：master

## 问题及现象
微信公众号的API 现在创建时就会返回poi_id https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1444378120 
> 门店poiid体系已做改造，poiid自创建后立刻分配，不再受审核影响发生变化。
> 创建门店接口调用成功后会返回errcode 0、errmsg ok，会实时返回唯一的poiid。

所以建议$poi->create 成功后直接返回`poi_id`方便保存

**Comment by overtrue** [comment]
不能随便修改原有的 API 用法，这样别人已经上线的应用容易出问题，请使用 $poi->createAndGetId($data);
