### ISSUE TITLE
access_token 是否能不内部主动请求微信

### ISSUE THREAD

**Issue by Shoot-tigers-tonight** [overtrue/wechat#778]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：3.1

## 问题及现象

我想是否能通过扩展内部的token类（就好像cache类那样，可以通过实现一个接口来自定。）。
实现只让内部读token。不主动去微信刷新。
现在问题是。之前的有一个服务是定时去刷新token的。
现在我用php这个wechat包。虽然能自定义cache类读缓存。但是不能避免wechat这个包主动是刷新。

我看了这个 [#696](https://github.com/overtrue/wechat/issues/696)，好象目前没有修复。

**Comment by overtrue** [comment]
添加配置项：`max_retries` 为 0 即可

**Comment by Shoot-tigers-tonight** [comment]
你好。能再问下。这个配置在哪里判断了吗？
我查看代码。没看懂。也没找到这个配置在哪读取了呢。
然后我全局搜索也没看出来呢。
能否贴下相关片段的代码呢。我想看看是怎么实现的。
谢谢

**Comment by overtrue** [comment]
我不晓得你是怎么搜索的，反正我一搜就知道了：https://github.com/overtrue/wechat/search?utf8=%E2%9C%93&q=max_retries&type=

> https://github.com/overtrue/wechat/blob/master/src/Foundation/Application.php#L134
> https://github.com/overtrue/wechat/blob/master/src/Core/AbstractAPI.php#L216

**Comment by Shoot-tigers-tonight** [comment]
恩。知道了。谢谢。
我当前用的版本是~3.1。
没有更新。看了max_retries这个参数是在3.3.5加上的。
我升级一下。感谢。

**Comment by overtrue** [comment]
@Shoot-tigers-tonight 嗯，以后还是看最新版吧，一般问题修复在线上搜索比较准确。

**Comment by Shoot-tigers-tonight** [comment]
好的。谢谢。

**Comment by refear99** [comment]
@overtrue 请问4.X版本如果做呢？

**Comment by overtrue** [comment]
@refear99 4.0 不会自动重试。
