### ISSUE TITLE
【新增】支付

### ISSUE THREAD

**Issue by overtrue** [overtrue/wechat#78]

**Comment by liyunfang** [comment]
作者牛叉，希望坚持下去。

**Comment by liyunfang** [comment]
我用composer更新到的版本是2.0.35

**Comment by overtrue** [comment]
改你的composer.json中版本号为：2.1.*

**Comment by caohui123** [comment]
Error 500
[Wechat]系统繁忙，此时请开发者稍候再试 
支付的时候返回这个错误 ，能不能在里面加上调试日志信息啊，这样我知道 我发送的什么出去的 ，现在我都不知道 怎么调试错误

**Comment by manhere** [comment]
微信支付是否会加入商户侧现金红包功能？

**Comment by kinosang** [comment]
个人认为支付或许可以单独分出去，这样包体积会小很多

**Comment by overtrue** [comment]
@kinosang 在3.0的设计当中，所有都模块化了，到时候你可以完全只用其中一个模块 :smile: https://github.com/easywechat
