### ISSUE TITLE
网页授权一刷新页面就出现40029 不合法的oauth_code

### ISSUE THREAD

**Issue by kamwing** [overtrue/wechat#8]
你好 我根据wiki里面的示例 第一次授权可以获得用户信息  但是只要刷新就会出现40029，能帮我分析一下问题吗？

```
if ($auth->authorized() || Session::get('logged_open_id')) {
    $user = $auth->user();// 获取已经登录后用户信息
    Session::set('logged_open_id', $user['open_id']);

    //code 显示授权后的页面，或者跳转到其它授权才能访问的页面
    //...
} else {
    $to = "http://微信授权完成后跳回你的地址，就是当前代码所在的 URL";
    $auth->redirect($to);
}
```

**Comment by sinoon** [comment]
`开发者中心`-->`网页授权获取用户基本信息`-->`授权回调页面域名`  
这里你有设置吗?

**Comment by kamwing** [comment]
@sinoon 有设置呢，很奇怪为什么会不能刷新

**Comment by sinoon** [comment]
看起来似乎是刷新的时候,还带着旧的`code`,一个`code`只能只用一次,不使用的话,5分钟内作废.

对此我不是很确定.

**Comment by kamwing** [comment]
@sinoon 请问你有测试下这个问题嘛？ 不知道是否会出现和我同样的问题.

**Comment by overtrue** [comment]
正在处理，请不要着急，今天会解决，

2015-04-26 16:48 GMT+08:00 Ngai Kam Wing <notifications@github.com>:

**Comment by overtrue** [comment]
@kamwing @sinoon 请更新后再试一下
