### ISSUE TITLE
在微信的接口配置时Token 无效，可任意输入

### ISSUE THREAD

**Issue by MrWangwj** [overtrue/wechat#800]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：

## 问题及现象

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**
服务端Token为  weixin, 配置界面为weixin11111  提示匹配成功。如图所示
![fc2_38nt5lbn bon_ 3al32](https://user-images.githubusercontent.com/21521991/28244329-a12e703e-6a1a-11e7-9a2c-e05c4e2ea2da.png)
![tim 20170716112216](https://user-images.githubusercontent.com/21521991/28244312-642c2da2-6a1a-11e7-9cdb-94ca72fa5bb8.png)
![tim 20170716113105](https://user-images.githubusercontent.com/21521991/28244313-67e76060-6a1a-11e7-8952-f025a9e7be46.png)

**Comment by overtrue** [comment]
为了方便调试，验证时并没加签名验证，消息发送时会验证。
