### ISSUE TITLE
Overtrue\Wechat\Media not found

### ISSUE THREAD

**Issue by sherryt400** [overtrue/wechat#801]
**[Symfony\Component\Debug\Exception\FatalErrorException]
Class 'Overtrue\Wechat\Media' not found**
I don't see either in vendor/overtrue/wechat/src/ folder
How to upload media files now in order to get **$media_id**?

**my code**

```
<?php
use Overtrue\Wechat\Media;
// $appId = xxxx;
// $appSecret = xxxx;
// ...
$media = new Media($appId, $appSecret);
$imageId = $media->image(__DIR__ . '/demo.jpg'); // 上传并返回媒体ID
$message = Message::make('image')->media($imageId);
--
```

i am using code from here: https://easywechat.org/en/docs/messages.html

**Comment by overtrue** [comment]
https://easywechat.org/zh-cn/docs/material.html
