### ISSUE TITLE
微信意图识别接口返回invalid param

### ISSUE THREAD

**Issue by echogqq** [overtrue/wechat#804]
采用python访问微信意图识别接口

def getTest():
    global access_token
    if len(access_token) == 0:
        access_token = getAccessToken()
    TEST_URL = 'https://api.weixin.qq.com/customservice/msgrecord/getmsglist?access_token=' + access_token;
    print(TEST_URL)
    post = {
        "query": "ff",
        "city": "ff",
        "category": "flight,hotel",
        "appid": "wx***********",
        "uid": "oki*****************"
    }
    response = requests.post(TEST_URL, json = post)
    print(response.text)

返回
{"errcode":65416,"errmsg":"param invalid, please check hint: [Vd3cpa0529e563]"}
不明白参数有什么不对，也不知道这个hint去哪里查看

**Comment by mingyoung** [comment]
检查你的 URL 和参数
