### ISSUE TITLE
请教这个项目的支付部分，尤其是签名和结果回调，是否支持小程序？

### ISSUE THREAD

**Issue by greedying** [overtrue/wechat#814]
我看了下小程序的支付，很像。

但是不是很确定是不是完全能无缝衔接。

因为本身小程序还没有支付功能，我这边没法自己试验，所以来问下有没有用过的兄弟姐妹~~谢谢

**Comment by daxiong123** [comment]
可以正常使用

**Comment by daxiong123** [comment]
生成配置时用 **configForPayment** 这个方法

**Comment by greedying** [comment]
谢谢，泪奔。这么快就有人回复！

**Comment by daxiong123** [comment]
恰巧看到 恰巧用了 ：）

**Comment by greedying** [comment]
好的~ 明白~ overtrue本身的使用，我还是很熟的，哈哈。
