### ISSUE TITLE
[意见]作者能否提供getTokenFromServer方法扩展从外部第三方获取access_token

### ISSUE THREAD

**Issue by zhangmazi** [overtrue/wechat#837]
## 我用的环境
ubuntu server

PHP 版本：
overtrue/wechat 版本：3.x

## 问题及现象

有一个背景，核心的东西都是用Java做的， 包括微信access_token（基础）也要从java拿。所以java那边是一个token池。
期望：wechat组件在ACCESS_TOKEN.php的getTokenFromServer方法内，能提供一个调用自定义获取token的扩展， 不用组件自己去换access_token,这样才能避免access_token失效

**Comment by overtrue** [comment]
1. 关掉重试次数：`\EasyWeChat\Core\AbstractAPI :: maxRetries = 0;`
2. https://easywechat.org/zh-cn/docs/access_token.html
