### ISSUE TITLE
不能上传gif格式的图片素材

### ISSUE THREAD

**Issue by linb** [overtrue/wechat#84]
系统返回错误：“不合法的文件类型”

**Comment by overtrue** [comment]
文件名是啥？

**Comment by linb** [comment]
PFNsqmrELwUV2kLNxpQY2nO0l8mhYCdFoppNZ5cWKmoPMvwYoal77gNdKM2-aefO.gif

**Comment by linb** [comment]
试过了，任何的名字都不行！

**Comment by overtrue** [comment]
这是微信平台报的错，所以我也不知道微信为啥不支持gif
