### ISSUE TITLE
[4.0] 功能测试

### ISSUE THREAD

**Issue by overtrue** [overtrue/wechat#849]
## 基础服务
- [x] JSSDK  - @overtrue
- [x] 临时素材  - @overtrue
- [x] 二维码  - @overtrue
- [x] URL  - @overtrue

## 公众号
- [x] 自动回复  - @overtrue
- [x] 群发 - @mingyoung
- [x] 卡券 - @mingyoung
- [x] 评论 - @mingyoung
- [x] 客服  - @overtrue
- [x] 数据统计  - @overtrue
- [x] 设备 `待认领`
- [x] 基础设置  - @overtrue
- [x] 素材  - @overtrue
- [x] 自定义菜单  - @overtrue
- [x] POI  - @overtrue
- [x] 语义识别  - @overtrue
- [x] 服务端  - @overtrue
- [x] 摇一摇周边 `待认领`
- [x] 模板消息  - @overtrue
- [x] 用户与标签  - @overtrue

## 小程序
- [x] 小程序码 - @mingyoung
- [x] 授权 - @mingyoung
- [x] 数据统计 - @mingyoung
- [x] 服务端 - @mingyoung
- [x] SNS - @mingyoung
- [x] 模板消息 - @mingyoung

## 微信支付
- [ ] 优惠券 `待认领`
- [x] JSSDK `待认领`
- [ ] 红包 - @tianyong90
- [ ] 企业转账 `待认领`
- [x] 支付基础 `待认领`

## 企业微信
- [x] 应用 - @overtrue
- [x] 授权 - @overtrue
- [x] 部门 - @overtrue
- [x] 素材 - @overtrue
- [x] 自定义菜单 - @overtrue
- [x] 消息 - @overtrue
- [x] OA - @overtrue
- [x] OAuth - @overtrue
- [x] 通讯录 - @overtrue

## 开放平台
- [x] OAuth - @mingyoung
- [x] 服务端 - @mingyoung

---

请在回复中认领。同时需要完成文档：https://github.com/easywechat/docs

**Comment by tianyong90** [comment]
@overtrue 认领红包部分。

**Comment by rockxsj** [comment]
请问一下4.0的开发目标是什么？  哪里能看到相关的介绍吗？
