### ISSUE TITLE
文档中网页授权实例写的不明确

### ISSUE THREAD

**Issue by stephencode** [overtrue/wechat#850]
## 我用的环境

PHP 版本：
overtrue/wechat 版本："overtrue/laravel-wechat": "~3.0"

## 问题及现象

在文档中 [**网页授权实例**](https://easywechat.org/zh-cn/docs/oauth.html#网页授权实例) 这一小节中的示例代码无法正常运行，需要在声明 `Application` 对象时传入的 `$config` 配置项中包含 `wechat.php` 中的全部配置项（刚开始以为这些会自动从配置文件中读取）。

举例：在 `Laravel` 中使用 `app('wechat')` 的方式是可以的，但是使用示例的方式必须传入 `new Application(config('wechat'))` 才行，否则在授权获取 `code` 和 `token` 时拼接好后的 `url` 中不会拼接上 `appid` 参数，通过调试可以知道 `Config.php` 获取不到 `client_id` 等必要配置项。

```php
$config = [
  // ...
  'oauth' => [
      'scopes'   => ['snsapi_userinfo'],
      'callback' => '/oauth_callback',
  ],
  // ..
];
$app = new Application($config);
```

**Comment by overtrue** [comment]
所以 `// ...` 这个符号还不够明确咯？
