### ISSUE TITLE
退款结果通知

### ISSUE THREAD

**Issue by almas1992** [overtrue/wechat#858]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：
^3.1
## 问题及现象
3.*版本是否支持处理退款结果通知？
文档中有提到支付结果通知处理和退款查询，可没看到有处理退款结果通知的内容。
微信支付退款通知文档链接：
https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_16

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

**Comment by tianyong90** [comment]
@almas1992 可以确定的是 4.0 版本会支持，刚写完这部分的单元测试。 😄

**Comment by almas1992** [comment]
@tianyong90 大赞，期待4.0版本  :smile:

**Comment by leo108** [comment]
已经实现 https://github.com/overtrue/wechat/pull/931

**Comment by overtrue** [comment]
感谢 @leo108！
