### ISSUE TITLE
有关4.0使用文档的问题

### ISSUE THREAD

**Issue by Logan-2017** [overtrue/wechat#883]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：

## 问题及现象

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

您好，请问4.0的文档目前还没有撰写吗？因为我看https://easywechat.org， 这里没有4.0的，而https://easywechat.com/又打不开； 感觉4.0很棒， 想试用，所以想了解一下文档，感谢

**Comment by overtrue** [comment]
https://github.com/easywechat/docs 先看这里吧，网站开发中
