### ISSUE TITLE
如何不下载图片，通过mediaId获取图片存储的URL

### ISSUE THREAD

**Issue by caolixiang** [overtrue/wechat#89]
大大，我想通过mediaId拿到图片然后存在七牛云上。
看了一下API，文件被file_put_contents了，有木有接口可以直接获取URL。

**Comment by overtrue** [comment]
你存到本地再上传到七牛啊，url又不能直接上传到七牛

**Comment by caolixiang** [comment]
http://developer.qiniu.com/docs/v6/api/reference/rs/fetch.html，是可以的。
我觉得返回一个base64对象也可以，写到本地觉得有点麻烦，还有通用性也不好。

**Comment by overtrue** [comment]
@caolixiang 2.x 系列已经不会改了，你最好是直接上传本地文件，上传完后可以删除

**Comment by tanshiqi** [comment]
我也建议加上个查看media地址的方法，七牛的fetch可以直接抓取，不需要在本地绕一圈了，目前自己拼接也不麻烦，Media::API_TEMPORARY_GET ＋access_token ＋mediaId 就可以了

**Comment by overtrue** [comment]
@tanshiqi 

1. 我有获取素材列表的接口，你可以从列表得到mediaid
2. 永久素材，只有视频接口给了链接，其它类型素材直接给的是内容，我哪儿来MediaId给你？http://mp.weixin.qq.com/wiki/4/b3546879f07623cb30df9ca0e420a5d0.html
3. 临时素材也只是直接给内容的，同样没有内容http://mp.weixin.qq.com/wiki/11/07b6b76a6b6e8848e855a435d5e34a5f.html

**Comment by tanshiqi** [comment]
mediaid已经能获取到，其实楼主想要的返回的地址就是素材内容的url：https://api.weixin.qq.com/cgi-bin/media/get?access_token=ACCESS_TOKEN&media_id=MEDIA_ID，而不是直接下载，比如 $media->getDownloadUrl , 这样这个url地址就可以直接给到七牛的fetch接口那里，直接传到七牛空间上去了，目前Media方法里只有download
