### ISSUE TITLE
小程序调用加密数据解密时报错，不存在方法

### ISSUE THREAD

**Issue by cboy868** [overtrue/wechat#890]
## 我用的环境

PHP 版本：5.6
overtrue/wechat 版本：3.1

## Encryptor中无decryptData方法
运行以下方法时
$miniProgram->encryptor->decryptData($sessionKey, $iv, $encrypt);
报错如下
Call to undefined method EasyWeChat\Encryption\Encryptor::decryptData()

**Comment by mingyoung** [comment]
升级一下版本？

**Comment by cboy868** [comment]
嗯  确实  升级版本后，问题解决 多谢
