### ISSUE TITLE
关于缓存，请问为什么key中包含appId * 2，有什么讲究吗？

### ISSUE THREAD

**Issue by waney** [overtrue/wechat#892]
我存入redis之后，key是这样的，如下：
**`easywechat.open_platform.authorizer_refresh_tokenwxa6a1262c0dbd2e2bwxa6a1262c0dbd2e2b`**

这样设计有什么用意吗? 文档中没有提到。

**Comment by overtrue** [comment]
多公众号防止冲突

**Comment by waney** [comment]
wxa6a1262c0dbd2e2b + wxa6a1262c0dbd2e2b ，
谢谢，我是指这里的, appId * 2 并没有提高不重复的概率啊
