### ISSUE TITLE
http://easywechat.org/ 网站访问不了了?

### ISSUE THREAD

**Issue by ustcwxz** [overtrue/wechat#896]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：

## 问题及现象

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

**Comment by foxhunter** [comment]
的确，文档都看不了啦！ 要搞个离线文档看啊

**Comment by mingyoung** [comment]
https://github.com/easywechat/docs
