### ISSUE TITLE
4.0 报错“Your requirements could not be resolved to an installable set of packages.”

### ISSUE THREAD

**Issue by Lujidev** [overtrue/wechat#898]
## 我用的环境

PHP 版本：7.1.5
overtrue/wechat 版本：目前3.1 想升级 4.0

## 问题及现象
composer版本: 1.5.1

无法通过composer下载。好像是4.0版本里面所需的package有冲突。请问如何解决？

描述你的问题现象，报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package overtrue/wechat ~4.0 is satisfiable by overtrue/wechat[4.0.0-alpha.2, 4.0.0-alpha1, 4.0.0-beta.1] but these conflict with your requirements or minimum-stability.

Installation failed, deleting ./composer.json.`

**Comment by NominationP** [comment]
解决了吗

**Comment by Lujidev** [comment]
同过手动json安装可以了。
