### ISSUE TITLE
订单查询

### ISSUE THREAD

**Issue by nurexmet** [overtrue/wechat#90]
你好！ 请问有没有实现订单查询接口

**Comment by jaring** [comment]
<?php
/**
 *
 * Part of Overtrue\Wechat.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author    Frye <frye0423@gmail.com>
 * @copyright 2015 Frye <frye0423@gmail.com>
 * @link      https://github.com/0i
 * @link      https://github.com/thenbsp/Wechat
 */

namespace Overtrue\Wechat\Payment;

use Overtrue\Wechat\Utils\Bag;
use Overtrue\Wechat\Utils\XML;
use Overtrue\Wechat\Utils\SignGenerator;
use Overtrue\Wechat\Http;
use Overtrue\Wechat\AccessToken;

class QueryOrder
{
    /**
     * 查询订单接口
     * https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_2
     */
    const QUERYORDER_URL = 'https://api.mch.weixin.qq.com/pay/orderquery';

    protected $appId;
    protected $appSecret;
    protected $mchId;
    protected $mchKey;

    /**
     * @var Bag
     */
    protected $transaction_info;

    public function __construct($appId, $appSecret, $mchId, $mchKey) {
        $this->appId = $appId;
        $this->appSecret = $appSecret;
        $this->mchId = $mchId;
        $this->mchKey = $mchKey;
    }



    /**
     * 获取订单结果
     *
     * @param bool|false $force 是否忽略缓存强制更新
     *
     * @return array
     * @throws Exception
     * @throws \Overtrue\Wechat\Exception
     */
    public function getTransaction($order_id,$force = false)
    {

        $params['appid']    = $this->appId;
        $params['mch_id']   = $this->mchId;
        $params['out_trade_no']   = $order_id;
        $params['nonce_str']  = md5(uniqid(microtime()));
        $signGenerator = new SignGenerator($params);
        $signGenerator->onSortAfter(function(SignGenerator $that) {
            $that->key = $this->mchKey;
        });
        
        $params['sign'] = $signGenerator->getResult();
        $request = XML::build($params);

        $http = new Http(new AccessToken($this->appId, $this->appSecret));

        $response = $http->request(static::QUERYORDER_URL, Http::POST, $request);
        if(empty($response)) {
            throw new Exception('Get ORDER Failure:');
        }

        $transaction = XML::parse($response);

        if( isset($transaction['result_code']) &&
            ($transaction['result_code'] === 'FAIL') ) {
            throw new Exception($transaction['err_code'].': '.$transaction['err_code_des']);
        }
        
        if( isset($transaction['return_code']) &&
            $transaction['return_code'] === 'FAIL' ) {
            throw new Exception($transaction['return_code'].': '.$transaction['return_msg']);
        }


        //数据校验
        if (empty($transaction) || empty($transaction['sign'])) {
            return false;
        }
        $sign = $transaction['sign'];
        unset($transaction['sign']);
        $signGenerator = new SignGenerator($transaction);
        $signGenerator->onSortAfter(function(SignGenerator $that) {
            $that->key = $this->mchKey;
        });
        if ($sign !== $signGenerator->getResult()) {
            return false;
        }
        //var_dump($transaction);
        return $transaction_info=new Bag($transaction);
}
}

**Comment by jaring** [comment]
依样画葫芦。。

**Comment by jaring** [comment]
$http = new Http(new AccessToken($this->appId, $this->appSecret));
改为$http = new Http();

**Comment by nurexmet** [comment]
如果系统已受到支付结果通知，调用查询借口有必要么？

**Comment by overtrue** [comment]
@nurexmet 有必要
