### ISSUE TITLE
[4.0] Pimple\Exception\UnknownIdentifierException

### ISSUE THREAD

**Issue by edwardaa** [overtrue/wechat#901]
## 我用的环境

PHP 版本：7.0
overtrue/wechat 版本：4.0

## 问题及现象

`$payment->jssdk` 抛异常:

```
Pimple\Exception\UnknownIdentifierException:
Identifier 'access_token' is not defined in Pimple\Container->offsetGet()
```

## 代码段:

```php
use EasyWeChat\Factory;

$payment = Factory::payment([
   // ...
]);

$jssdk= $paymen->jssdk;  // throw exception: UnknownIdentifierException
```

**Comment by edwardaa** [comment]
[\EasyWeChat\Payment\Jssdk\Client](https://github.com/overtrue/wechat/blob/master/src/Payment/Jssdk/Client.php#L23) 只用于生成客户端（js bridge, jssdk, app）请求参数，更像一个简单的工具类，不需要依赖`access_token`。

能否*不*继承`EasyWeChat\BasicService\Jssdk\Client` ，而是作为一个简单类并添加一个` __construct`: 
```php
namespace EasyWeChat\Payment\Jssdk;

class Client
{
   /**
     * Constructor.
     *
     * @param \EasyWeChat\Payment\Application $app
     */
    public function __construct(Application $app)
    {
        $this->app = $app;
    }

    // ...
}
```
这样的话，也可以解决这个`UnknownIdentifierException`。

**Comment by overtrue** [comment]
我也希望不依赖 access_token, 但是其中的签名过程是需要 ticket 的，而 ticket 的请求是需要 access_token 的

**Comment by edwardaa** [comment]
只有“收货地址共享”需要 `access_token`, 而且是通过参数传入的（shareAddressConfig），并不需要 Payment 相关的类做处理

**Comment by overtrue** [comment]
稍等我看一下

**Comment by overtrue** [comment]
刚才看了一下，支付的 jssdk 是继承自基础 jssdk 的，比如  `wx.config` 是需要 ticket 来签名的，而通常支付的 js 也是需要用到 `wx.config` 的，所以这里还是需要 access_token
