### ISSUE TITLE
关于小程序支付的疑问

### ISSUE THREAD

**Issue by greedying** [overtrue/wechat#912]
如题。
一个小程序，我需要支付功能。

于是我先设置了min_app的 appid和secret，然后设置了支付配置。这时候我以为应该就可以支付了。

但是后来发现不行，还是得把以前公众号位置的appid和secret填上，当然填的其实是小程序的appid和secret。

这样就导致我需要填写两遍appid信息，这个有点不合理。

我觉得应该是在支付那儿加个type的选项，或者就在appid不存在的时候，自动探测小程序的appid是否存在

**Comment by mingyoung** [comment]
4.0 已优化配置
