### ISSUE TITLE
模板消息的颜色设置问题

### ISSUE THREAD

**Issue by stephencode** [overtrue/wechat#914]
## 我用的环境

PHP 版本：7.1.2
overtrue/wechat 版本：3.3

## 问题及现象

模板消息中的数据项颜色我通过 `defaultColor($color)` 来统一修改，但是调用该方法后安卓上的微信可以收到颜色正确的模板消息，但是IOS上的微信收到的模板消息数据项内容全变空了。

```php
$this->notice->to($openid)->uses($templateId)->defaultColor($color)->data($body)->send();
```

当我将该方法去掉后就都正常能显示了，然后又尝试了独立设置每个模板项颜色：
```php
$body = array(
    "first"    => array("恭喜你购买成功！", '#555555'),
    // ...
);
```
这样也是正常的。

**Comment by overtrue** [comment]
官方已经不支持了吧，官方文档都去掉颜色相关的部分了

**Comment by stephencode** [comment]
我就是看官方文档这么写才用的呢，官方文档截图如下：

<img width="680" alt="example" src="https://user-images.githubusercontent.com/17685647/30240891-90eb19bc-953e-11e7-9b59-724938d2c579.png">

**Comment by stephencode** [comment]
贴个有锚点的链接吧：[传送门](https://easywechat.org/zh-cn/docs/notice.html#模板数据)

**Comment by overtrue** [comment]
我说的是微信官方。。。

**Comment by stephencode** [comment]
我晕，还以为是easywechat的官方文档咧。。。 🙊 🙊 🙊

**Comment by stephencode** [comment]
微信官方文档上目前还是有颜色设置的描述的，然后我想说的是，既然微信官方仍然提供颜色设置的，并且easywechat提供了批量设置默认颜色的方法，但是使用该方法后出现的问题就和微信官方无关了吧 😢

**Comment by stephencode** [comment]
<img width="612" alt="t" src="https://user-images.githubusercontent.com/17685647/30245205-b6a6e4c0-9597-11e7-9b22-cbe69e25b2cc.png">

[GO](https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1433751277)
