### ISSUE TITLE
条件判断错了，stripos返回的是“返回在字符串 haystack 中 needle 首次出现的数字位置。”，所以不能直接作为条件判断

### ISSUE THREAD

**Issue by blackjune** [overtrue/wechat#915]
https://github.com/overtrue/wechat/blob/1a6eeb26ecc359f0dbfbf331b1986025d2555f05/src/Core/AbstractAPI.php#L218

参见
http://www.php.net/manual/zh/function.stripos.php

**Comment by overtrue** [comment]
感谢！
