### ISSUE TITLE
请教小程序的模板消息是否支持

### ISSUE THREAD

**Issue by greedying** [overtrue/wechat#920]
如题。
看文档上，都是按照服务号的模板消息写的。不知道小程序模板消息是否可以支持

**Comment by mingyoung** [comment]
支持的，不过有些参数和公众号的不同，详看小程序模版消息文档

**Comment by greedying** [comment]
好的。谢谢

**Comment by greedying** [comment]
经过实测，有两个问题。
1、字段不同，导致部分代码不兼容。但这个可以想办法绕过
2、小程序和公众号模板消息的url不同。 这个没法绕过，除非改代码或者自己fork一份

**Comment by mingyoung** [comment]
1、哪里代码不兼容？把代码贴出来
2、
公众号模版消息为：`$app->notice;`
小程序模版消息为：`$app->mini_program->notice;`

**Comment by greedying** [comment]
你这个是新的版本吧，未发布版本？我还说的是3.1

**Comment by greedying** [comment]
额。还真有，谢谢，我试试。  我看文档里没提到，就以为没有

**Comment by mingyoung** [comment]
说的是 3.1
