### ISSUE TITLE
3.3 版本 数据类型不对导致无法运行

### ISSUE THREAD

**Issue by micln** [overtrue/wechat#928]
## 我用的环境

PHP 版本：7.0 7.1
overtrue/wechat 版本：3.3.14
是否使用了框架？框架名称：Laravel 5.3 5.4

## 问题及现象

问题代码：

https://github.com/overtrue/wechat/blob/3.3.14/src/Foundation/ServiceProviders/OAuthServiceProvider.php#L54

$pimple['config'] 是 Collection， 不能作为 in_array  的的参数

错误信息：

```
ErrorException: in_array() expects parameter 2 to be array, object given

vendor/overtrue/wechat/src/Foundation/ServiceProviders/OAuthServiceProvider.php:54
```

**Comment by micln** [comment]
好快

**Comment by overtrue** [comment]
3.3.15
