### ISSUE TITLE
PC端扫描登录的问题

### ISSUE THREAD

**Issue by crisslin** [overtrue/wechat#930]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：最新
是否使用了框架？框架名称：laravel

## 问题及现象

使用easywechat实现PC端扫描微信登录，使用中间件'wechat.oauth:snsapi_login'，显示appid不正确，因为easywechat 默认读取 wechat.php配置文件中appid的值，而不去读取open_platform配置项的值，按道理来说，scope就限定了读取不同的配置方案。
snsapi_login 应该读取第三方平台的值
snsapi_userinfo和snsapi_base 应该读取微信公众号的appid等值

-------------------------

路由中使用中间件
代码:
//pc端微信扫码登录
Route::group(['middleware' => ['web', 'wechat.oauth:snsapi_login']], function () {}

//微信端登录
Route::group(['middleware' => ['web', 'wechat.oauth:snsapi_userinfo']], function () {}

=================================

wechat.php配置文件
/*
     * 账号基本信息，请从微信公众平台/开放平台获取
     */
    'app_id'  => env('WECHAT_APPID', '****已填****'),         // AppID
    'secret'  => env('WECHAT_SECRET', '*****已填*******'),     // AppSecret
    'token'   => env('WECHAT_TOKEN', 'your-token'),          // Token
    'aes_key' => env('WECHAT_AES_KEY', ''),                    // EncodingAESKey

    /**
     * 开放平台第三方平台配置信息
     */
     'open_platform' => [
         'app_id'  => env('WECHAT_OPEN_PLATFORM_APPID', '****已填**'),
         'secret'  => env('WECHAT_OPEN_PLATFORM_SECRET', '*****已填*****'),
         'token'   => env('WECHAT_OPEN_PLATFORM_TOKEN', ''),
         'aes_key' => env('WECHAT_OPEN_PLATFORM_AES_KEY', ''),
     ],
//由于值做登录验证，所以token与aes_key 未配置

**Comment by crisslin** [comment]
//由于目前只做登录验证，所以token与aes_key 未配置

**Comment by mingyoung** [comment]
开放平台第三方平台和开放平台网站应用是不同的

**Comment by mingyoung** [comment]
你要用 PC 扫码登录的直接用 [overtrue/socialite](https://github.com/overtrue/socialite) 即可

**Comment by crisslin** [comment]
如果使用中间件模式
//pc端微信扫码登录
Route::group(['middleware' => ['web', 'wechat.oauth:snsapi_login']], function () {}

//微信端登录
Route::group(['middleware' => ['web', 'wechat.oauth:snsapi_userinfo']], function () {}

怎么修改配置项呢

**Comment by overtrue** [comment]
@crisslin 这个 `wechat.oauth` 中间件不支持 PC 开放平台登录
