### ISSUE TITLE
有多个商户时，订单通知的 $payment 怎么创建

### ISSUE THREAD

**Issue by alwaystrong** [overtrue/wechat#934]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：4.0.0-beta
是否使用了框架？框架名称：laravel

## 问题及现象

创建订单时，我可以根据商户 code 从数据库找到商户的相关配置，根据配置来构造 $payment。
可是订单通知时，$payment 怎么构造？有什么办法获取到商户的配置？

```
$payment->handleNotify(function($notify, $successful){
    return true; 
});
```

下面时创建订单时构造 $payment 的代码：

        $appInfo = DB::table('wxapps')->where('merchant_code', $merchantCode)->first();
      

        $options = [
            // 前面的appid什么的也得保留哦
            'app_id' => $appInfo->app_id,
            'merchant_id' => $appInfo->merchant_id,
            'key' => $appInfo->merchant_key,
            'cert_path' => '', //'path/to/your/cert.pem', // XXX: 绝对路径！！！！
            'key_path' => '', //'path/to/your/key',      // XXX: 绝对路径！！！！
            'notify_url' => 'xxxxxx',
            // 'device_info'     => '013467007045764',
            // 'sub_app_id'      => '',
            // 'sub_merchant_id' => '',
            // ...
        ];

        $payment = Factory::payment($options);

**Comment by overtrue** [comment]
一样的方式创建啊

**Comment by alwaystrong** [comment]
超哥，是这样，我自己发的请求我会把我的商户号信息传过来，我是根据商户号去取对应的配置来生成 payment，而这个是微信的通知，商户号有什么办法知道？

**Comment by overtrue** [comment]
那就得你自己想办法了，比如在通知 URL 上加商户标记等

**Comment by tianyong90** [comment]
@alwaystrong 如果没记错的话，回调时传给你的数据里本来就包含商户号 mch_id。另外统一下单时可以设置一个叫 attach 的参数传其它你想传的附加数据，支付回调通知里会原样传回。微信官方的文档还是多看看吧，虽然写得不咋滴……
