### ISSUE TITLE
微信小程序生成二维码（接口B）微信扫描不出来结果

### ISSUE THREAD

**Issue by Witype** [overtrue/wechat#938]
## 我用的环境

PHP 版本：
overtrue/wechat 版本："overtrue/laravel-wechat": "^3.1",
是否使用了框架？框架名称：laravel

## 问题及现象
~~~
$app = new Application(config('wechat'));
        $qrcode = $app->mini_program->qrcode;
        $appcode = $qrcode->getAppCodeUnlimit('bindId='.$code);
~~~

通过这个方式生成的二维码在小程序内部扫一扫无法获取scene信息，请问有这是微信的限制还是其他什么原因，
谢谢
ps：小程序未上架

**Comment by greedying** [comment]
还有这个函数！赞啊

**Comment by mingyoung** [comment]
估计是微信的坑吧
https://developers.weixin.qq.com/blogdetail?action=get_post_info&lang=zh_CN&token=&docid=51c988399d70914a51f57a085c4c1cf4
