### ISSUE TITLE
微信静默授权的时候，页面上老是会显示一段很长的英文Redirecting to http://xxxx，很影响用户体验，有没有什么方法可以去掉，保留空白页，或者允许自定义显示内容

### ISSUE THREAD

**Issue by birdy0815** [overtrue/wechat#939]

**Comment by shenjr** [comment]
我也想知道这个问题怎么处理,看你关闭了讨论,有解决方法了吗?  难不成去改源码?

**Comment by shwatty** [comment]
找到这个文件
\vendor\symfony\http-foundation\RedirectResponse.php

把body 设置 style 隐藏即可
代码如下
 <body style="display: none">
        Redirecting to <a href="%1$s">%1$s</a>.
    </body>

**Comment by overtrue** [comment]
$response->send();

不要 echo 就没这些事儿了，了解一下 RedirectResponse 的用法...
