### ISSUE TITLE
官网挂了

### ISSUE THREAD

**Issue by kdlz30** [overtrue/wechat#950]
http://easywechat.com/
打不开了,貌似ssl的问题
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

**Comment by Feelop** [comment]
![image](https://user-images.githubusercontent.com/9813956/31474856-ff996a9c-aec2-11e7-8a47-d2043ecb22d7.png)

**Comment by smartymoon** [comment]
waiting for repire

**Comment by yaoshanliang** [comment]
在线等

**Comment by rshinesun** [comment]
在线等+1

**Comment by overtrue** [comment]
维护中，别着急

**Comment by overtrue** [comment]
搞 好了

**Comment by overtrue** [comment]
强制刷新
