### ISSUE TITLE
laravel队列中使用了SDK报Component verify ticket does not exists.

### ISSUE THREAD

**Issue by elinxer** [overtrue/wechat#958]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：^3.1
是否使用了框架？框架名称：laravel5.5

## 问题及现象
做粉丝列表拉取得时候用到了laravel框架的队列，但发现在队列监听和执行中报ticket不存在，调试发现可以读取到ticket的key，但却无法获取ticket内容。
`
/**
     * 获取公众号授权APP句柄
     *
     * @param $authorizerAppId
     * @param $authorizerRefreshToken
     * @return Application
     */
    public function getMpAuthApp($authorizerAppId, $authorizerRefreshToken)
    {
        return $this->openPlatform->createAuthorizerApplication($authorizerAppId, $authorizerRefreshToken);
    }
`
再次调试发现，是php命令行下无法获取微信第三方平台下发的ticket，报Component verify ticket does not exists.

**Comment by elinxer** [comment]
再次调试发现，是php命令行下无法获取微信第三方平台下发的ticket，报Component verify ticket does not exists.

**Comment by elinxer** [comment]
@overtrue

**Comment by mingyoung** [comment]
tinker 下有问题吗

**Comment by elinxer** [comment]
有的，tinker下一样获取不到呢，暂时找不问题所在 @mingyoung

**Comment by mingyoung** [comment]
@elinxer 
原因是因为不同环境下 ```sys_get_temp_dir()``` 获取到的临时目录不同。

可以设置自定义 cache 解决：
```php
use EasyWeChat\Foundation\Application;
use Doctrine\Common\Cache\FilesystemCache; // 示例为 File 缓存

$app = new Application([
    'cache' => new FilesystemCache(storage_path('easywechat')), // storage_path 为 Laravel 函数
    'open_platform' => [
        // ...
    ]
]);
```

**Comment by elinxer** [comment]
重新设置后，ticket使用正常，非常感谢！

**Comment by mingyoung** [comment]
😄
