### ISSUE TITLE
第三方平台 接收消息一直报错 但是能回复消息 也会提示错误

### ISSUE THREAD

**Issue by reprover** [overtrue/wechat#961]
## 我用的环境

PHP 版本：7.1.0
overtrue/wechat 版本：3.3.16
是否使用了框架？框架名称：Laravel 5.5

## 问题及现象

在开放平台接收消息推送回复时，报错如下：

    [2017-10-16 18:25:29] local.ERROR: EasyWeChat\Encryption\EncryptionException: Invalid Signature. in /mnt/webroot/ticketsystem/vendor/overtrue/wechat/src/Encryption/    Encryptor.php:131
    Stack trace:
    #0 /mnt/webroot/ticketsystem/vendor/overtrue/wechat/src/Server/Guard.php(467): EasyWeChat\Encryption\Encryptor->decryptMsg('cb2a5130db88d82...', '325857308', '1508149529', '<    xml>\n    <ToUs...')
    #1 /mnt/webroot/ticketsystem/vendor/overtrue/wechat/src/Server/Guard.php(340): EasyWeChat\Server\Guard->parseMessageFromRequest('<xml>\n    <ToUs...')
    #2 /mnt/webroot/ticketsystem/vendor/overtrue/wechat/src/OpenPlatform/Guard.php(88): EasyWeChat\Server\Guard->getMessage()
    #3 /mnt/webroot/ticketsystem/app/Http/Controllers/Auth/OpenWechatAuthController.php(159): EasyWeChat\OpenPlatform\Guard->serve()
    #4 [internal function]: App\Http\Controllers\Auth\OpenWechatAuthController->pushOrReceive(Object(Illuminate\Http\Request), 'wxde12bc8ad31c2...')
    #5 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
    #6 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('pushOrReceive', Array)
    #7 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Routing/Route.php(189): Illuminate\Routing\ControllerDispatcher->dispatch(Object(    Illuminate\Routing\Route), Object(App\Http\Controllers\Auth\OpenWechatAuthController), 'pushOrReceive')
    #8 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Routing/Route.php(144): Illuminate\Routing\Route->runController()
    #9 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Routing/Router.php(653): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
    #10 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(    Illuminate\Http\Request))
    #11 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(    Object(Illuminate\Http\Request))
    #12 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(    Illuminate\Http\Request), Object(Closure))
    #13 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(    Illuminate\Http\Request))
    #14 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}    (Object(Illuminate\Http\Request))
    #15 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(    Illuminate\Http\Request), Object(Closure))
    #16 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(    Illuminate\Http\Request))
    #17 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object    (Illuminate\Http\Request))
    #18 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Session\Middleware\StartSession->handle(Object(    Illuminate\Http\Request), Object(Closure))
    #19 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(    Illuminate\Http\Request))
    #20 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->    Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
    #21 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(    Illuminate\Http\Request), Object(Closure))
    #22 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(    Illuminate\Http\Request))
    #23 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(    Object(Illuminate\Http\Request))
    #24 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(    Illuminate\Http\Request), Object(Closure))
    #25 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(    Illuminate\Http\Request))
    #26 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(    Illuminate\Http\Request))
    #27 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Routing/Router.php(655): Illuminate\Pipeline\Pipeline->then(Object(Closure))
    #28 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Routing/Router.php(629): Illuminate\Routing\Router->runRouteWithinStack(Object(    Illuminate\Routing\Route), Object(Illuminate\Http\Request))
    #29 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Routing/Router.php(607): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
    #30 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(268): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
    #31 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(    Illuminate\Http\Request))
    #32 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->    Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
    #33 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(    Illuminate\Http\Request), Object(Closure))
    #34 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(    Illuminate\Http\Request))
    #35 /mnt/webroot/ticketsystem/vendor/dingo/api/src/Http/Middleware/Request.php(111): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
    #36 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Dingo\Api\Http\Middleware\Request->handle(Object(Illuminate\Http\Request),     Object(Closure))
    #37 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(    Illuminate\Http\Request))
    #38 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(    Illuminate\Http\Request))
    #39 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(150): Illuminate\Pipeline\Pipeline->then(Object(Closure))
    #40 /mnt/webroot/ticketsystem/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(    Illuminate\Http\Request))
    #41 /mnt/webroot/ticketsystem/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
    #42 {main}

代码如下：

    public function __construct()
    {
        $this->openAppid = \Config::get('wechat.openWechat.AppID');
        $this->openAppSecret = \Config::get('wechat.openWechat.AppSecret');
        $this->openToken = \Config::get('wechat.openWechat.token');
        $this->encodingaeskey = \Config::get('wechat.openWechat.encodingaeskey');

        $this->open_options = [
            'open_platform' => [
                'app_id' => $this->openAppid,
                'secret' => $this->openAppSecret,
                'token' => $this->openToken,
                'aes_key' => $this->encodingaeskey
            ]
        ];
        $this->app = new Application($this->open_options);
        $this->open_platform = $this->app->open_platform;
    }
    /**
     * 开放平台 事件接收
     */
    public function pushOrReceive(Request $request, $appid)
    {
        //处理消息事件
        $openPlarform = $this->open_platform;
        $server = $openPlarform->server;
        $server->setMessageHandler(function ($message) {
            return null;
        });
        return $server->serve();
    }

无论回复是什么都会报错，现在是return null ,打出来的log $server->serve()为

    [2017-10-16 18:02:34] local.INFO: HTTP/1.0 200 OK
    Cache-Control: no-cache

    success

打出来的message为正常的json形式的message

    [2017-10-16 17:58:00] local.INFO: {"ToUserName":"gh_0d287e1992f4","FromUserName":"osDaNv0_Bet20H7T-mHzWG1Cl-os","CreateTime":"1508147879","MsgType":"text","Content":"和","MsgId":"6477445818254983883"}

是我写的有什么问题吗，配置检查过没问题，在授权方法中是没问题的，这个是消息接收的方法

截图如下

![wechatimg4](https://user-images.githubusercontent.com/9566402/31607854-a99913d6-b2a0-11e7-838a-b261c131aee9.jpeg)

**Comment by mingyoung** [comment]
代公众号实现业务，你要创建一个授权方的实例，而不是用开放平台的 server，代码如下：
```php
return $this->open_platform
->createAuthorizerApplication('authorizer-appid', 'refresh-token')
->server
->setMessageHandler(function ($message) {
    return 'hello';
})
->serve();
```

**Comment by reprover** [comment]
@mingyoung 啊。。。对 授权的时候时创建的 这个是最开始写的 一直不记得了 谢谢提醒~我去试一下
