### ISSUE TITLE
请问是否有遇到微信扫码或内部打开外部网站出现请求2次的情况

### ISSUE THREAD

**Issue by AnimalWorld-zhongxiangzhao** [overtrue/wechat#963]
![image](https://user-images.githubusercontent.com/19886578/31646125-9d7b51fc-b2c5-11e7-9a35-6c96ffdcb1e3.png)

117.136.75.231是本机
101.226.233.156是外部请求,IP来至上海.
请指教

**Comment by pal301x** [comment]
是的，我也发现这个问题，是安卓手机下才会出现。第一次基本正常，重复获取openid 很大几率二次访问。

**Comment by pal301x** [comment]
请问下没，改问题是否已经解决了？

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
