### ISSUE TITLE
希望兼容新出的微信H5支付

### ISSUE THREAD

**Issue by weer0026** [overtrue/wechat#966]
微信新出的H5支付，统一下单接口请求部分增加新字段'scene_info'，新的支付类型 'MWEB'，返回增加新字段'mweb_url'，希望官方支持。

**Comment by overtrue** [comment]
@mingyoung 正好你在重构。考虑一下

**Comment by greedying** [comment]
H5支付早就有的。开放了？

**Comment by mingyoung** [comment]
都兼容的，无论哪种支付方式，在调用接口的时候传入支付方式所需要的参数就可以了，同样，SDK 返回的字段都是微信原样返回的。

Example(4.0):
```php
$app->order->unify([
    'body' => '腾讯充值中心-QQ会员充值',
    // ...
    'trade_type' => 'MWEB',
    'scene_info' => '{"h5_info": {"type":"Wap","wap_url": "https://pay.qq.com","wap_name": "腾讯充值"}}',
]);

**Comment by weer0026** [comment]
@mingyoung 我用的版本是3.3.12，我通过重写兼容了，4.0还没关注，麻烦了。
