### ISSUE TITLE
是否可以加入微信收款（个人转账版）服务接口

### ISSUE THREAD

**Issue by chenhaizano** [overtrue/wechat#970]
### 简介

为规范服务商下属个人用户的接入，服务商需将个人用户基本资料提交给微信支付，微信支付返回下属个人用户的收款识别码。因为用户的数量较多，服务商可以直接调用该系列 API 实现高效快捷的录入个人用户的资料。

#### 1. 新增收款个人用户资料 API

'https://api.mch.weixin.qq.com/secapi/mch/submchmanage?action=add'

#### 2. 查询收款个人用户资料 API
'https://api.mch.weixin.qq.com/secapi/mch/submchmanage?action=query'

需要我提供文档么？

**Comment by mingyoung** [comment]
文档看看

**Comment by chenhaizano** [comment]
@mingyoung 

https://gitee.com/chenhaizano/document/tree/master/wechat/%E5%BE%AE%E4%BF%A1%E6%94%B6%E6%AC%BE%E4%B8%AA%E4%BA%BA%E8%BD%AC%E8%B4%A6%E7%89%88

**Comment by mingyoung** [comment]
PR #983

```php
// 新增收款个人用户资料
$app->merchant->addSubMerchant([
    'merchant_name' => '店铺名称',
    'merchant_shortname' => '简称',
    'recipient_name' => '姓名',
    'recipient_idcardno' => '111111111111111111', // 身份证
    'recipient_wechatid' => 'wechat-id',
    // ...
]);

// 查询收款个人用户资料
$app->merchant->querySubMerchantByMerchangId('xxx'); // 根据收款识别码查询
$app->merchant->querySubMerchantByWeChatId('xxx'); // 根据收款人微信号查询
```

**Comment by chenhaizano** [comment]
@mingyoung 

现在发现一个问题，有不存在的字段参与签名，微信会返回错误提示：签名校验失败，请检查后重试

https://github.com/overtrue/wechat/blob/62945e1bada42823becb3ac88520a0a8b6c7ab45/src/Payment/Kernel/BaseClient.php#L64-L96

现在 nonce_str 参数是一直会存在，但现在不需要这个参数
```
'nonce_str' => uniqid() 
```

我尝试注释nonce_str等字段能正常返回数据

这个问题需要解决一下

**Comment by chenhaizano** [comment]
可以改成这样？
```
'nonce_str' => isset($this->app['config']['nonce_str']) ? $this->app['config']['nonce_str'] : uniqid(),
```

配置的时候`nonce_str=''`就过滤掉了

**Comment by chenhaizano** [comment]
能否这样改？

在
https://github.com/overtrue/wechat/blob/62945e1bada42823becb3ac88520a0a8b6c7ab45/src/Payment/Merchant/Client.php#L35-L49

把参数改成这样，覆盖掉之前的？
```
$params = [
    'micro_mch_id' => $id,
    'nonce_str' => '',
    'sub_mch_id' => '',
    'sub_appid' => ''
];
```

其他类似

**Comment by mingyoung** [comment]
@chenhaizano 可以，提个 PR 呗👀

**Comment by chenhaizano** [comment]
https://github.com/overtrue/wechat/pull/986
