### ISSUE TITLE
Curl error 77

### ISSUE THREAD

**Issue by birdol** [overtrue/wechat#982]
## 我用的环境

PHP 版本：7.1.8
overtrue/wechat 版本：4.0 
是否使用了框架？框架名称：原生php

## 问题及现象
```php
$app = Factory::officialAccount($options);
$oauth = $app->oauth;
$user = $oauth->user();
```

最后一行提示 cURL error 77

$options中
```php
    'http' => [
        'retries' => 1,
        'retry_delay' => 500,
        'timeout' => 5.0,
        'base_uri' => 'https://api.weixin.qq.com/',
        'verify' => '/path/cert.pem', //这个路径是正确可以访问的
    ],
```
我尝试把:
```php
'verify' => false; 
```
还是提示这个错误.直到我把wechat/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php
```php
$conf[CURLOPT_SSL_VERIFYHOST] = 2;
$conf[CURLOPT_SSL_VERIFYPEER] = true;
```
改成了
```php
$conf[CURLOPT_SSL_VERIFYHOST] = 0;
$conf[CURLOPT_SSL_VERIFYPEER] = false;
```
问题才得到解决,这个坑要怎么填....? 求指点.

**Comment by overtrue** [comment]
贴一下错误详情

**Comment by birdol** [comment]
cURL error 77: (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) 
wechat/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php 187行

185 | $error = isset($connectionErrors[$easy->errno])
186 | ? new ConnectException($message, $easy->request, null, $ctx)
187 | : new RequestException($message, $easy->request, $easy->response, null, $ctx);

**Comment by overtrue** [comment]
77 报错应该会有一条消息才对吧，说证书问题

**Comment by cute001** [comment]
@birdol 你怎么解决的，我的也报个错

**Comment by TheNorthMemory** [comment]
更新操作系统 CA 证书，详询 [公众平台接口证书更换通知@2018年07月13日](https://mp.weixin.qq.com/cgi-bin/announce?action=getannouncement&announce_id=11531387046zmIME&version=&lang=zh_CN&token=)
