### ISSUE TITLE
有微信退款回调接口吗？

### ISSUE THREAD

**Issue by haibin2017** [overtrue/wechat#985]
overtrue/wechat 版本：3.1
是否使用了框架？框架名称：
laravel
## 问题及现象
有微信退款回调接口吗？

**Comment by mingyoung** [comment]
```php
$payment->handleRefundNotify(callable $callback);
```

使用方法和[支付结果通知](https://easywechat.org/zh-cn/docs/payment.html#支付结果通知)类似
