### ISSUE TITLE
xml解释失败

### ISSUE THREAD

**Issue by elinxer** [overtrue/wechat#989]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：3.1^
是否使用了框架？框架名称：laravel5.5

## 问题及现象

在解释返回的用户信息时，xml解释失败
`往后余生，风雪是你，平淡是你，清� {"exception":"[object] (ErrorException(code: 0): simplexml_load_string(): Entity: line 24: parser error : CData section not finished
往后余生，风雪是你，平淡是你，清� at /data/ops/vendor/overtrue/wechat/src/Support/XML.php:40)`

**Comment by overtrue** [comment]
你返回的内容有问题吧，中文没正确截取？

**Comment by scplay** [comment]
偶而也会遇到这个问题，是否因为XML中有非法字符？导致 simplexml_load_string 报错？

**Comment by TheNorthMemory** [comment]
[XML CDATA](http://www.w3school.com.cn/xml/xml_cdata.asp) 要仔细研读一下。
