### ISSUE TITLE
自动回复多图文素材，错误

### ISSUE THREAD

**Issue by yiyouguisu** [overtrue/wechat#996]
## 我用的环境

PHP 版本：7.1.4
overtrue/wechat 版本：3.3.12
框架名称：thinkphp5

## 问题及现象

return new Material('mpnews', "yNnp6cTPl-nC4c0yYCn9iWl3vywQmv-ziK3Spv8W7OA");

![image](https://user-images.githubusercontent.com/11996269/32315650-e98b97b2-bfe7-11e7-878a-5fa7a7ae88ce.png)

**Comment by yiyouguisu** [comment]
return new Video(['media_id' => $replyinfo['replymediaid']]);
回复视频和语音和图片可以发送

**Comment by overtrue** [comment]
报错请提供错误消息内容，如果该素材不支持发送我们也解决不了。
