### ISSUE TITLE
请教有没有高清素材下载方法？

### ISSUE THREAD

**Issue by greedying** [overtrue/wechat#997]
谢谢，我在文档里没找到高清素材的下载~想问下只是文档没有，还是确实没有~~

**Comment by overtrue** [comment]
官方没有就没有，官方有这里就会有的

**Comment by greedying** [comment]
官方是指的微信官方？ 那官方给是有的

**Comment by overtrue** [comment]
链接

**Comment by overtrue** [comment]
https://github.com/EasyWeChat/docs/commit/1c42a6e0ab57b783d7e746be9bd030d82a05c785
